### ISSUE TITLE
Create a Blitline Account

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#100]
We're using [Blitline](http://blitline.com/) to process thumbmail images for webmaker-android, and are hitting the limits of the free tier (just on staging)

If we're to get this working consistently, we need to set up a real account and get a paid plan in place.

cc/ @jbuck @simonwex @toolness @thisandagain

**Comment by jbuck** [comment]
I've created an account using the Github devops account

**Comment by jbuck** [comment]
Emailed Angela to get CC details on the account

**Comment by cadecairos** [comment]
AFAIK, an account has been set up, and I have an application id.

@jbuck is working on configuring Blitline to write to an S3 Bucket in the mofo AWS account
