### ISSUE TITLE
Grant access to help@webmaker.org for...

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#101]
* Kate
 * Andrew
 * Gavin

/cc @thisandagain anyone else?

**Comment by thisandagain** [comment]
Bobby, Laura, Matthew. Thanks @simonwex !

**Comment by simonwex** [comment]
Google group created as collaborative inbox (webmaker-help@mozillafoundation.org)

Bug filed for forwarding help@webmaker.org -> collaborative inbox
https://bugzilla.mozilla.org/show_bug.cgi?id=1174266

**Comment by thisandagain** [comment]
@simonwex Is this now hooked-up?
