### ISSUE TITLE
Fix cert for https://mozillathimblelivepreview.net

### ISSUE THREAD

**Issue by humphd** [MozillaFoundation/mofo-devops#107]
IE refuses to load Bramble in Thimble because it won't let https://mozillathimblelivepreview.net/bramble/dist/bramble.js load.  If you try to hit that URL in IE, you get:

```
The publisher of bramble.js couldn't be verified. Are you sure you want to run the program?
```

We need files from that domain to be verified/trusted, since this is the domain where we serve all of Bramble.

cc @Pomax, @sedge

**Comment by Pomax** [comment]
this requires someone with a devops touch to not just change the cert, but to at the very least also brief me on how to get this done. @jbuck, want to talk through how to get a cert updated?

**Comment by jbuck** [comment]
Why does the certificate need to be changed?

**Comment by humphd** [comment]
I don't know the fix, tbh.  I just know that IE refuses to load this script, despite the fact that every SSL verification tool I've tried says the cert is good.  Over to you, devops!

**Comment by jbuck** [comment]
Could it be that the SSL certificate is fine and there's some other issue going on with IE? I loaded up https://bramble.mofostaging.net in IE11 on Windows 7 and the text looked incorrectly aligned in the menus due to loading fonts via http but everything else appeared to load correctly. I know you're looking for a fix but I'm certain it's not cert related.

**Comment by Pomax** [comment]
looking at the F12 information, IE throws a "SCRIPT5: Access is denied." on line 1, column 2, which is absolutely useless information. Looking at where things break during the network traffic, the following two network transfer is "pending" when IE hits its "access denied" error:
```
1. https://mozillathimblelivepreview.net/bramble/dist/extensions/default/bramble/stylesheets/lightTheme.less
2. https://mozillathimblelivepreview.net/bramble/dist/extensions/default/JavaScriptCodeHints/tern-worker.js
```
Whether that lets us home in on what's really going wrong, I can't say. There's some brackets deprecation warnings in the console, but those do not seem to contribute to errors.

**Comment by jbuck** [comment]
@humphd There doesn't appear to be anything I can fix here, so I'm closing this issue.

**Comment by humphd** [comment]
Sure.  I still can't get it to load in IE, though.  It's a real mystery.
