### ISSUE TITLE
Debug delays in deployment on bramble.mofostaging.net

### ISSUE THREAD

**Issue by sedge** [MozillaFoundation/mofo-devops#108]
Hi all! 

We need some help figuring out why there's a delay between us deploying to `bramble-staging.herokuapp.com` and being able to see the changes on `bramble.mofostaging.net`. 

We can confirm that the changes are happening, and that it's being deployed to heroku correctly through attaching a `bash` instance and checking the contents of the files.  

We can't seem to predict how long it takes for our changes to show up, and it means that if we need staging to be stable then we can't merge anything that might break it. Likewise, testing on `bramble-staging.herokuapp.com` is impossible since its environment is configured for the `bramble.mofostaging.net` domain.

Are we using a service like cloudflare to improve performance through caching? 

Help!

cc: @jbuck @cadecairos

**Comment by cadecairos** [comment]
Jon may have turned on a Heroku feature that delays deployment of apps by about 3 minutes.

This allows rollbacks within the 3 minute period without having downtime.

**Comment by jbuck** [comment]
Nah, I haven't turned that on for bramble.

**Comment by sedge** [comment]
Things seem to be okay right now - our last breaking merge was backed out successfully. I'll update again when we run into trouble.

**Comment by sedge** [comment]
We haven't run into this problem again - updates seem responsive. Closing for now...
