### ISSUE TITLE
Add sedge as a collaborator for the publish.wm.o heroku app

### ISSUE THREAD

**Issue by sedge** [MozillaFoundation/mofo-devops#109]
Hey all, I need to update our heroku instance of publish.webmaker.org but I don't have permission. Would you mind adding me? I'm not sure what information you need, but the email I used to sign up was kieran.sedgwick@gmail.com

cc: @jbuck

**Comment by sedge** [comment]
The url is: https://damp-anchorage-2948.herokuapp.com/

**Comment by humphd** [comment]
cc @simonwex, @davidascher - we're blocked on this, so if you can help get this done it would help us this week.

**Comment by jbuck** [comment]
@sedge done!

**Comment by humphd** [comment]
merci
