### ISSUE TITLE
Get S3 creds for the CDOT thimble team

### ISSUE THREAD

**Issue by sedge** [MozillaFoundation/mofo-devops#113]
Hey all!

@gideonthomas @humphd and I need S3 creds to test and develop publishing thimble projects with `publish.webmaker.org`. Can we get some?

**Comment by jbuck** [comment]
@sedge Did anyone else get you sorted out while I was away?

**Comment by sedge** [comment]
@cadecairos got us S3 creds for our staging deployment, which was really helpful. Would it be possible to get some for local development? Mox only takes us so far :P

**Comment by cadecairos** [comment]
where does it not become a viable solution for local dev?

**Comment by sedge** [comment]
It isn't a realistic representation of how S3 will behave :S 

When we initially landed our publish work, everything worked locally but broke on deployment. Relying on just mox made it time consuming to debug, since we had to land push and deploy to see our changes.

**Comment by jbuck** [comment]
Yeah, mox is really bare bones. I'd actively discourage using it.

**Comment by sedge** [comment]
Is there a more realistic local alternative?

**Comment by jbuck** [comment]
I haven't found one, I'd just recommend using S3 directly

**Comment by sedge** [comment]
@jbuck Sounds like a plan! Can you give us credentials for our local dev?

**Comment by sedge** [comment]
@jbuck @cadecairos Any update on this?

**Comment by jbuck** [comment]
Okay, I've created a new AWS sandbox account and sent AWS keys to @sedge @humphd and @gideonthomas
