### ISSUE TITLE
Source search returning 500 errors for some queries

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#114]
@ryanpitts emailed me:
> Getting some super weird errors on Source when you run certain searches. These searches throw 500s:
> 
>         https://source.opennews.org/en-US/search/?q=work
>         https://source.opennews.org/en-US/search/?q=journalism
> 
> But this works as expected:
> 
>         https://source.opennews.org/en-US/search/?q=django
> 
> And this empty result set works fine too:
> 
>         https://source.opennews.org/en-US/search/?q=djangofoobarbaz
> 
> So I have no idea what’s triggering the 500s. Any chance you could pull a log so I could start trying to troubleshoot?

**Comment by jbuck** [comment]
@ryanpitts Okay, I am throughly confused here. I can't find any useful logs on the server; is there a way of increasing the log verbosity somehow?

**Comment by ryanpitts** [comment]
@jbuck I just triggered a couple 500s by requesting the searches noted above. I _think_ the standard location for apache error logs on EC2 is `/var/log/httpd/error.log`, and I was figuring that something would show up there. But no?

**Comment by jbuck** [comment]
If I look at `/var/log/apache2/source.error.log` I see references to missing images: `[Thu Jul 30 05:11:19 2015] [error] [client 10.181.108.8] File does not exist: /var/www/source/media/img/uploads/article_images/10_Door_PushPull.jpg, referer: https://source.opennews.org/en-US/learning/design-principles-news-apps-graphics/` but nothing related to searches if I trigger a search.

If I look at `/var/log/apache2/syslog` I see the HTTP 500, but it's only an access log: `[30/Jul/2015:05:19:40 +0000] 69.165.142.168 10.152.132.109 - [500] GET /en-US/search/ 665921 "https://source.opennews.org/en-US/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0"`

Would source store logs somewhere else? I don't see any other files I could look at in https://github.com/mozilla/mofo_system_configurations/blob/master/modules/apps/templates/source/vhost.erb but I'm happy to be wrong!

**Comment by ryanpitts** [comment]
Nope, Source logs the results of some cron jobs it runs, but unfortunately no logs that would capture something like this. Logging can be configured to automatically send emails after a 500 error, so that would probably be the next step here.

Not sure whether to fold this into the code refactor, or to get this into the current codebase right away though.

**Comment by jbuck** [comment]
I see in the source production config that Dan, you, and myself are configured to receive traceback emails... but evidently none of us are.

**Comment by jbuck** [comment]
@ryanpitts I have a log:

```
UndefinedError at /search/

'None' has no attribute 'content_type'

Request Method: 	GET
Request URL: 	https://source.opennews.org/en-US/search/?q=work
Django Version: 	1.4.8
Exception Type: 	UndefinedError
Exception Value: 	

'None' has no attribute 'content_type'

Exception Location: 	/var/www/source/source/base/templates/search/search.html in block "content", line 28
Python Executable: 	/usr/bin/python
Python Version: 	2.7.3
```

Which corresponds to `{% set result_type = result.content_type().split('.')[1] %}`. I guess `result` is `None`?

**Comment by ryanpitts** [comment]
Whoa. Nice find!!! That tells me what to change, at least. Zero idea how `result` even _could_ be `None` in there though, considering that the loop is defining it: `{% for result in page.object_list %}`

**Comment by jbuck** [comment]
If you want to examine what `page.object_list` is, you could set Debug = True in the source production config and re-run the erroring search query.

**Comment by ryanpitts** [comment]
yeahhhhhh, I'm a little wary of flipping debug true on production though ...

Do you happen to know how ElasticSearch is configured on the mofoprod instance? Does it only accept connections from a certain domain? If not, we could also temporarily point the staging server settings at the production ElasticSearch instance, and try the broken searches on staging.

**Comment by jbuck** [comment]
Lets try that!

**Comment by jbuck** [comment]
Okay, same error as on prod: https://source.mofostaging.net/en-US/search/?q=work

**Comment by ryanpitts** [comment]
Sweeeeet. Thanks for tweaking that!

```
'organization_results': [<SearchResult: people.organization (pk=54)>, <SearchResult: people.organization (pk=49)>, <SearchResult: people.organization (pk=56)>, None, None],
'person_results': [<SearchResult: people.person (pk=67)>, <SearchResult: people.person (pk=103)>, <SearchResult: people.person (pk=209)>, <SearchResult: people.person (pk=82)>, <SearchResult: people.person (pk=183)>, <SearchResult: people.person (pk=234)>, <SearchResult: people.person (pk=101)>, <SearchResult: people.person (pk=5)>, <SearchResult: people.person (pk=218)>, <SearchResult: people.person (pk=192)>, None, None, None, None, None],

Those `None`s at the end of each of those result lists are super weird. Can't imagine a circumstance where a queryset of search results should have those in there at all. Will have to go spelunking in the docs.

Off the top of my head, I could fix this by filtering `None`s from the list back in the view itself. But it could also be that the search index needs to be dropped and rebuilt to get bad results out of it.

**Comment by jbuck** [comment]
@ryanpitts what command am I looking to run to drop the index and re-create it?

**Comment by ryanpitts** [comment]
Should be `python manage.py rebuild_index`

See: https://django-haystack.readthedocs.org/en/v2.4.0/management_commands.html#rebuild-index

**Comment by jbuck** [comment]
@ryanpitts That did the trick! Logs:

```
(source)ubuntu@i-4ed38db3:/var/www/source$ python manage.py rebuild_index --remove --verbosity 1

WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y

Removing all documents from your index because you said so.
Failed to clear Elasticsearch index: Non-OK status code returned (404) containing u'IndexMissingException[[haystack] missing]'.
All documents removed.
Indexing 413 articles.
Indexing 124 codes.
Indexing 508 People.
Indexing 143 organizations.
```

**Comment by ryanpitts** [comment]
Yessssss. I wonder what those corrupted index entries *were*. Regardless, glad they're gone. Thanks!
