### ISSUE TITLE
Allow discourse.webmaker.org to use https-only

### ISSUE THREAD

**Issue by toolness** [MozillaFoundation/mofo-devops#116]
Right now when discourse digest emails are sent out, they include hard links to http://discourse.webmakerprototypes.org.

Currently that domain is set up to forward all requests, along with the appropriate path, to discourse.webmaker.org, which is great.

However, I'd really like to enable https-only for the discourse. It's especially important for users with administrative privileges and stuff, but even normal users probably wouldn't like to have their cookies stolen, especially with respect to private messages and such.

Currently enabling https-only (via the admin panel on the site) doesn't work well, however, because it means those digest emails point to https://discourse.webmakerprototypes.org, which appears to have an invalid security certificate. So one solution to this problem is simply to put a valid security certificate on that domain.

However, another solution, which I suspect is more robust in the long-term, is to change Discourse's configuration settings so it actually thinks it's hosted at discourse.webmaker.org. I don't believe this is a setting I can configure through the admin panel, so it's almost certainly something that one will have to SSH into the Discourse server for.

**Comment by jbuck** [comment]
Yeah, looks like this requires downtime & rebuilding the docker container it's running in: https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098

**Comment by flamingspaz** [comment]
fwiw this instance has the same issues as #37 (also running an extremely out of date version of Discourse)

@jbuck do you want me to take this? Just need the correct ssl cert in AWS.

**Comment by jbuck** [comment]
@flamingspaz arg. We really need a better strategy for managing our Discourse instances...

**Comment by flamingspaz** [comment]
We do, the rest of them are kept in good shape, these two fell under the radar. I can get them all set up today or tomorrow on new infra, just need admin access to this Discourse instance, the ssl cert in aws and we'd need to verify the email address for use with SES.
