### ISSUE TITLE
Instance retirement warning

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#119]
> Running instances will be stopped or terminated after 12:00AM UTC on 2015-08-04. The affected instances are listed below:
> * i-5e2a5322

This is a source-staging node.

@ryanpitts I swear, it's like AWS *knows* we're running stateful web services. Should I preserve the images on this box, or is it okay to just recycle the node?

**Comment by ryanpitts** [comment]
I think to be safe, preserving images sounds smart. Glad it's just the staging node though!

**Comment by jbuck** [comment]
Done!
