### ISSUE TITLE
Fix failing build.webmaker.org monitor

### ISSUE THREAD

**Issue by jdotpz** [MozillaFoundation/mofo-devops#12]
http://opsview.mofoprod.net:3000/cgi-bin/extinfo.cgi?type=2&service=healthcheck&host=Build.Webmaker-Production is suddenly giving a 404.

**Comment by ThomasFarrow** [comment]
done :)

**Comment by davidascher** [comment]
I changed the dev side of build.w.o last night so possible the healtheck
URL is gone. What did you use?

**Comment by jdotpz** [comment]
It was a random URL, and I can't even remember which, but it went away last night. :)
Do you recall what we changed it from @ThomasFarrow ?
