### ISSUE TITLE
Spam on discourse.webmaker.org

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#121]
We've been receiving A LOT of spam over the past few days at http://discourse.webmaker.org/. I've been deleting posts individually and deactivating spam users in the admin, but not sure if that's the best approach. Is there a different filter we can apply, or other solution you know of? Screenshot below. Let me know if this is something you can help with. Thanks!
![screen shot 2015-07-21 at 9 13 34 am](https://cloud.githubusercontent.com/assets/4885898/8801487/1033e0e6-2f89-11e5-8243-877cb12562a9.png)

**Comment by ldecoursy** [comment]
cc @simonwex :)

**Comment by jbuck** [comment]
It sounds like the generally recommended solution here is adding an Akismet Discourse plugin: https://github.com/mozilla/build.webmaker.org/commit/61d76cf3122db7a4656c26595359f1c7a24a7f04

You'll still need to clean-up the existing spam, but it sounds like it should prevent spam going forward.

**Comment by ldecoursy** [comment]
@jbuck Is this something you can help with? It's getting increasingly worse.

**Comment by jbuck** [comment]
@ldecoursy and I went on a spam flagging and deletion spree to clean up most of the spam. I'll add the Akismet plugin when I get a chance too.

**Comment by ldecoursy** [comment]
@jbuck @simonwex Any chance we can prioritize getting the Akismet plugin installed or figuring out another solution to block incoming spam? Another wave just came through - I just deleted a bunch of posts...

**Comment by ldecoursy** [comment]
I also just found a setting under "login" that staff needs to approve new user accounts before they can access the site. I don't think this is a good long-term solution but hoping it helps until we get this figured out.

**Comment by ldecoursy** [comment]
Checking back on this - apparently I blocked out some spammers, but now even existing accounts can't login - when clicking "log in" button, page refreshes but nothing happens.

**Comment by jbuck** [comment]
Okay, I've disabled that setting so people can login again

**Comment by jbuck** [comment]
@simonwex is going to fix this up!

* discourse.webmaker.org points at
* discourse-wm-production ELB in the mofo account points at
* instance i-a6b7e2f6 points at
* ec2-54-224-60-146.compute-1.amazonaws.com

**Comment by simonwex** [comment]
Hey @ldecoursy I ran out of time to work on it today. I'll try to get to it tomorrow (Friday)

**Comment by ldecoursy** [comment]
Thanks. Unfortunately more spam came through last night - I just deleted it.

**Comment by simonwex** [comment]
Akismet API key for me for later:

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.20
Comment: https://keybase.io/crypto

wcFMA6Qx+rumjg5vAQ/+IuRTlOlZ3bvJVtzydCKp4HBAKKEvvgnnrEV26Sr+iOVp
/8qQaLL7pvfux3nYOqmishvpOcklUL8p5Ih6QGBOxBghMOjrAsYuuPa/MQ33oL4N
l4zeD2oQcf/blQciIskaM4+peRzk04v7pfnPIrSbI6hi3U1fKuO0/uuKDMKInm0i
9WQ0oIdLRSoK0Y0bCl6oQMBmsnBe/DKTnqgSt/KjTv7MFNGLFrKvGNdQ+npHnOQw
kw1UZCZRDAyG5YUfDyoNY1eKaYe4GMSZLFPLv82Ya6fUAH9dGytueoXsGVFIol7H
TFKsjHMUZBg2OY/orujdlifwlOdNpGyEEjbCWyemQURvVK4OSaiFUfMNUzzAUvrQ
2wpYA0Vgww9YZlVTJiMDKhi3K0K2ePP7C1EQ3dz9sjdAXUqvnBMx2b1LfRL9mAQ7
0ys9BI3UNQnbpxIQ8UN4DOna1C37sPZ9PhxW426SilmCbrKyP24u+s0P80lR35lk
xcqGCvqpUBAJLFzz9F6VJGzdDOW6IRLcFSepJ9wtIqKQG8AsbqsyhRgm6vQLlwNy
W1e/BOvbjXimJC1WZLefTRS3Df71r+zuyctnnTeJgxM2GFQcaJtB3C7Z2vCq5Lu1
0R28phoiTxeu1PHqtL+SocMnhZ+Cfv8pFHyVccfuMIu+GwV6tIoiF49MsrlbQkTB
wUwDpDH6u6aODm8BD/9r1wVsyk5uGHTcLwQ7bnQcxhssX82gYSapACIeokLwSClC
+I1htYquFEJ+fbBaTbMBsVsyTyP25Pw2asu/JF6JQctjy47hMyUl5sbERtnP4ws1
R2XZGbWHQSbGx8drZbiT5yZp/gSAK5Qq0/oH82EzJhhzX6uv3BvC/dNvG8HQm3YZ
svzrtD4v5VQR+b9ygJJS1rZlzUnkPFT4frwl6S/fy16UtpFY072E+jwtoOgBxfGe
rXWTLAZow6sl4apHdDGfenqYyZmAeP7hki1KzpMMWLFwo2y55kl+xjshEmvSSF6F
wsHJna9tjr8PoJsExL31b6HZAIMbq3xLoIxB2l0iMmiJnYlQ9Bae7lOauIUfAs6s
ZXwwThtY2US/mP+J6k2EB4rR9xPHD/8sFx1L/vTI/GoilLYFzl5MCTP18Uo/fquh
WAP8yQ4ZNYkeAengVep7EasX2zM/LGAhFPjZ+3wYAxXbJBFx8mSFF8LI6qQSlnHw
YfDE/lnzzcVYOrEGxyYeP3MTS71hrP//OVbpdK4HUAKKobTHKtLqLIyJLaVAEbAx
lpGqtaWEhDuftLbx6XH5MkOImeo9tLrKfQETlJox9eF/cud2FjNOR79o2ssPi8Wz
9PXoqTW2iJNMMhJxQNtoc/nowCnSoykTfGrs0499wNJ7oFiFtnAHGTXlb0TULNJZ
AZGTpsba9kgJ69HP6ZDCj/JIDbWBZJBSB3DdmfjbkyKcXyKyQbDyYvdnhNbwZWQl
WnP3iP0J0W7EiG4mHtdma1fo3O25hPwWVr+ZI+Ks3khNJCBEuo60k9s=
=Fpmd
-----END PGP MESSAGE-----

**Comment by ldecoursy** [comment]
Few more snuck in over the weekend - I just deleted 5 spam accounts -each with about 5-6 posts.

**Comment by simonwex** [comment]
Still working on this, should have it buttoned up tonight.

**Comment by jbuck** [comment]
Once discourse.webmaker.org has been restored to working order, we'll add the Akismet anti-plugin

**Comment by simonwex** [comment]
Update: I have the old posts recovered, this is most of what we think of as content. They are in categories, but we don't have the category names. I think this is a minor issue that we could solve by naming them based on discussion content. 

The real issue still outstanding is that we don't have all of the user accounts. We have ~200 out of around 670 and none of the profile data. I don't think we have any way of recovering this.

@ldecoursy, @hkane could we chat about this tomorrow?

**Comment by ldecoursy** [comment]
Yes please - let me know when works for you. I'm available until 5:15pm ET

**Comment by hannahkane** [comment]
+1. What time works for you, @simonwex? (btw, I'm @hannahkane on here.)

**Comment by ldecoursy** [comment]
Cleaning some old tickets - closing this one.
