### ISSUE TITLE
Travis deploys failing

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/mofo-devops#122]
Travis is failing when deploying id.webmaker.org and build.webmaker.org. It suggests that we might have the wrong API key.

@jbuck halp?

cc @alicoding @vazquez

**Comment by vazquez** [comment]
Thanks for filing this Bobby.

**Comment by secretrobotron** [comment]
@vazquez 
<img width="150" alt="screenshot 2015-07-21 14 55 16" src="https://cloud.githubusercontent.com/assets/403231/8809757/9213351a-2fb8-11e5-8ed5-85008f7c6aa1.png">

**Comment by vazquez** [comment]
@jbuck More details on build failing.

https://travis-ci.org/mozilla/build.webmaker.org/builds/71802146

**Comment by vazquez** [comment]
@secretrobotron 

![depositphotos_13134443-funny-yellow-robot-cartoon](https://cloud.githubusercontent.com/assets/1119821/8810666/86f534fc-2fbe-11e5-9ebf-c170c3267f87.jpg)

**Comment by jbuck** [comment]
Fixed in https://github.com/mozilla/build.webmaker.org/commit/61d76cf3122db7a4656c26595359f1c7a24a7f04
