### ISSUE TITLE
Re-enable Mavis' SSH access to Hive Learning Networks servers

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#123]
It's been about a month or two since I last SSH'ed to 

- production: ec2-23-22-235-240.compute-1.amazonaws.com (https://hivelearningnetworks.org/)
- staging: ec2-54-82-160-100.compute-1.amazonaws.com (http://hive.mofostaging.net/)

I tried just now but got a `port 22: Operation timed out` error.  Could you help look into the issue?  :wink:

**Comment by jbuck** [comment]
@mmmavis You'll need to enable security group access to whatever IP you're using. Do you know how to do that?

**Comment by mmmavis** [comment]
@jbuck i'm afraid not. show me? :grin:

**Comment by jbuck** [comment]
@mmmavis Do you have credentials to the mofo AWS account?

**Comment by mmmavis** [comment]
@jbuck I save my credentials in Cyberbuck to access S3 and that's probably the only interaction I have had with MoFo's AWS.  Is it the same pair of username/password?

**Comment by jbuck** [comment]
Don!

**Comment by mmmavis** [comment]
d(d＇∀＇) thannnnnks @jbuck
