### ISSUE TITLE
Load testing results collection

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#128]
We'll collect the results of the load testing we're doing in this thread

**Comment by jbuck** [comment]
**Login.webmaker.org account creations**
Load Impact test results: https://app.loadimpact.com/load-test/f65cb3f6-44f1-4e20-aa8c-75403cff7ea5

**Comment by jbuck** [comment]
**api.webmaker.org read /discover**

This test is set to simulate the Android application starting up and configured at 1000 VU's in 10 minutes:

![screenshot 2015-07-22 16 59 39](https://cloud.githubusercontent.com/assets/578466/8837189/13971162-3093-11e5-8f9e-95767b1476b7.png)

Load Impact test results: https://app.loadimpact.com/load-test/ff5e69fe-ee75-4347-aad5-0407a61285d5

Finally some good news!

**Comment by ashleygwilliams** [comment]
`POST id.webmaker.org/login/oauth/access_token`

This test is set to simulate the Android application starting up and configured at 600 VU's in 10 minutes:

<img width="943" alt="screen shot 2015-07-23 at 12 07 47 pm" src="https://cloud.githubusercontent.com/assets/1163554/8855491/665dc396-3133-11e5-9381-544f08e97bb7.png">

We flatline(30s response time) at a little under 7 r/s.

Load Impact test results: https://app.loadimpact.com/load-test/dc87bf6f-e90d-4caf-b5bc-cda33246dbbe
