### ISSUE TITLE
Make a metrics app for Adam

### ISSUE THREAD

**Issue by jdotpz** [MozillaFoundation/mofo-devops#13]
cc @adamlofting

- [ ]   Have devs/product owners fill out:  https://docs.google.com/a/mozillafoundation.org/spreadsheet/viewform?formkey=dFBONmhPUXcxVVp5TFBiS0I4OWZ1RFE6MQ#gid=0
- [x]  create ec2 security group, allow elb sg on port 80(see other apps for examples)
- [x]  create keypair, share on lastpass
- [x]  app iam creds, share on lastpass
- [x]  build scripts written
- [x]  Cloud init scripts written for 64bit
- [x]  create staging elb
- [x]  create staging launch config
- [x]  create staging autoscale group
- [x]  update fab file with new autoscale group staging
- [x]  create RDS security group, allow access for app ec2 security group
- [x]  create staging db root creds, share on lastpass?
- [x]  create staging db app creds, share on lastpass?
- [x]  create staging db?
- [x]  create DNS entry for staging db?
- [ ]  create DNS entry for elb endpoint
- [x]  create S3 folder for s3://mofo-techops/deployment/apps/staging/appname
- [x]  create S3 folder for s3://mofo-techops/deployment/apps/production/appname
- [x]  grant respective app AWS keys access to  s3://mofo-techops/deployment/apps/staging/appname and s3://mofo-techops/deployment/apps/production/appname
- [x]  Add iam user to s3-creds-staging (or production) iam group
- [x]  Add app-env specific user policy to each user, look at other app-appname-env user policies for a template
- [x]  Upload an allowed ssh file to each envs creds folder, created above.
- [x]  Create configs for app/env, upload to S3 creds env buckets created above
- [x]  update fab file with new autoscale group staging
- [x]  update fab file on builder under /home/ubuntu/.aws/fabfile.py
- [x]  puppet modules written
- [x]  as-update-auto-scaling-group --min-size 1 --max-size 1 --desired-capacity 1
- [x]  create first github tagged version of app
- [x]  Create staging jenkins job
- [x]  Test Jenkins staging job
- [x]  Create staging status jenkins job
- [x]  test!
- [x]  create prod elb
- [x]  create prod launch config
- [x]  create prod autoscale group, multi-AZ
- [x]  create prod db?
- [x]  create DNS entry for prod db
- [x]  create DNS entry for prod elb
- [x]  create monitoring for prod db
- [x]  create monitoring for elb nodes
- [x]  create monitoring for main endpoint
- [x]  create PRODPUSH Jenkins job
- [x]  create PRODBACKOUT Jenkins job
- [x]  create loggins stream for new app
- [x]  create custom DETAIL-appname dashboard in newrelic
- [x]  setup contextual loggins links, newrelic links, monitoring links in Jenkins
- [ ] Secreview?

https://github.com/MozillaFoundation/plan/issues/237

**Comment by jdotpz** [comment]
@adamlofting here's what i'm getting, verified write access to the metricsstaging db.

end scriptroot@i-241cc8cb:/var/www/mofometrics# NODE_ENV="staging" /usr/bin/node /var/www/mofometrics/app.js
Unable to connect to the database: [Error: SequelizeConnectionRefusedError: connect ECONNREFUSED]
An error occurred while creating the table: { [SequelizeConnectionRefusedError: connect ECONNREFUSED]
  name: 'SequelizeConnectionRefusedError',
  message: 'connect ECONNREFUSED',
  parent: 
   { [Error: connect ECONNREFUSED]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     fatal: true },
  original: 
   { [Error: connect ECONNREFUSED]
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     fatal: true } }

I've verified grants and perms for metrics database, so I'm assuming it's trying to write to integration?  I'm making a dump of integration to make a staging version to test.  Any input would be rad. :)

**Comment by adamlofting** [comment]
Hmm... app.js shouldn't be dependent on `mofointegration` or write to it. The demo version at http://webmaker-metrics.herokuapp.com/ is running without any integration creds in the environment at all.

Sequelize is only used for the snapshot models, which talk to the metrics database
https://github.com/mozilla/webmaker-metrics/blob/master/lib/models.js

**Comment by jdotpz** [comment]
Figured it out, it needs to have export in front of var definitions!
That bit is fixed now, so we're creating the db, but then we see it exit.

https://www.irccloud.com/pastebin/NFurYlW6

**Comment by jdotpz** [comment]
Running as foreman, we still see it exit:

http://pastebin.mozilla.org/8638985

**Comment by jdotpz** [comment]
All set!  https://metrics.webmaker.org is up and running.

**Comment by adamlofting** [comment]
This is amazing. I just have a few snagging issues to work through:

- [ ] I can't access integration-db.mofoprod with the admin creds I have (might be an IP restriction)
- [ ] The database in integration-db.mofoprod (which I can see with integration_ro user) hasn't updated since 20 Jan.
- [ ] The database in integration-staging looks like it has crashed halfway through the import as we only have a few tables and they've not been renamed.
- [ ] https://metrics.mofostaging.net/ has been dead today, but http://metrics.webmaker.org/ has been working
- [ ] Persona login isn't working for me on prod at the moment, but I can debug this once I learn how to access the server. (Adam todo)

**Comment by jdotpz** [comment]
The integration db is the same for staging and for prod, and that hadn't been updated in some time.  I've repointed it back to the existing db, and am running the integration.sh script now.  Will check off once I see it has completed.

**Comment by jdotpz** [comment]
The integrationdb is all fixed up and has fresh data.
![screen shot 2015-02-10 at 11 35 27 am](https://cloud.githubusercontent.com/assets/1373628/6132606/2f9c0146-b119-11e4-9315-bd17769d7ab7.JPG)

**Comment by adamlofting** [comment]
Thanks again! I've been able to fix the persona thing by removing the :80 from the host var. I'll do that at source soon and then I think we're in good shape.
