### ISSUE TITLE
Make inventory of all things using Persona

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#131]
Persona's clock is ticking, let's start doing the homework to make sure we don't get loose functionality.

**Comment by jbuck** [comment]
##### Webmaker:
* Webmaker login v3 still supports it, but we're not using it in id.webmaker.org

##### Openbadges:
* Like, everything requiring sign-in here

**Comment by ryanpitts** [comment]
**Source:**
* I use Persona to allow verified people to log in and change information about their organization, as well as post job listings

**Comment by jbuck** [comment]
We should put together a list from https://github.com/search?p=2&q=org%3Amozilla+%22https%3A%2F%2Flogin.persona.org%2Finclude.js%22&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by cadecairos** [comment]
We shouldn't have anything still using persona. Closing!
