### ISSUE TITLE
Deploy the MVP version of thimble-beta and publish.wm.o to production

### ISSUE THREAD

**Issue by sedge** [MozillaFoundation/mofo-devops#133]
We're very close (within a week) to having the MVP version of thimble-beta ready for production, and we'll need it deployed to allow @hannahkane to create starter content. 

**Publish.wm.o:**

* A prod deployment of publish.wm.o
* An s3 bucket/static website set up
* A postgres DB set up 

Do we need a security audit for this server? It will be responsible for lots of direct interactions with S3.

**Thimble-beta**

* Deploy of the latest code
* Proper env config

cc: @jbuck

**Comment by jbuck** [comment]
we'll need to figure out where published content lives, right? like the domain name. Can I just punt on that for now and we can solve later?

**Comment by sedge** [comment]
On staging we're just using the S3 static domain. A prod version of that should be okay for now I think.

**Comment by jbuck** [comment]
Okay, I've deployed publish.webmaker.org/master on a new Heroku app. Need to polish up thimble-beta.webmaker.org tomorrow, hopefully it's not too much trouble

**Comment by sedge** [comment]
Awesome.

Also! There's a piece that was left out of my original estimate, which is a place to host a production version of the brackets (bramble) static editor resources. Staging is pointing at https://mozillathimblelivepreview.net/bramble/ which contains a dist build of the brackets repo.

We use the [`build-browser-compressed`](https://github.com/humphd/brackets/blob/bramble/Gruntfile.js#L602) task to create the built and gzipped files.

**Comment by sedge** [comment]
As a followup, thimble's external dependencies are:

1. id.wm.o
2. publish.wm.o
3. bramble.wm.o

**Comment by jbuck** [comment]
We're good to go! https://d157rqmxrxj6ey.cloudfront.net/jon/2/
