### ISSUE TITLE
Ensure http://weblitmapper.webmakerprototypes.org/ is properly backed up

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#134]

**Comment by jbuck** [comment]
@simonwex I can't find this app in our mozilla Heroku account, the only reference I have to it is kochi-6282.herokussl.com . I suspect it's in a personal account somewhere.

**Comment by jbuck** [comment]
@simonwex okay, we're currently using the sandbox version of compose mongodb: https://dashboard.heroku.com/apps/weblitmapper/resources

If we upgrade to a paid version, we get daily backups included. Or should we have our own backups living somewhere else?

**Comment by jbuck** [comment]
Upgraded to the paid version which has daily backups:

> Automatic backups occur each day. We retain 7 daily backups, 4 weekly backups and 3 monthly backups.
