### ISSUE TITLE
Audit discourse.hivelearningnetworks.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#138]
* [ ] Repo is in mozilla org
 * [ ] Current deployed version is in current repo
 * [ ] User-generated assets live on S3
 * [ ] Regular database backups are being persisted 
 * [ ] Instance is rebuildable if corruption occurs
 * [ ] We have a plan for updating system software

**Comment by jbuck** [comment]
What do you want to audit? Backups, database on RDS, ???

**Comment by simonwex** [comment]
Added some tick boxes, any more to suggest?

**Comment by jbuck** [comment]
I wonder what we should do about the login system used by this discourse instance...

**Comment by jbuck** [comment]
@flamingspaz Interested in taking this discourse instance under your wings?

**Comment by alicoding** [comment]
Apparently we don't have https://discourse.hivelearningnetworks.org/ and in https://hivelearningnetworks.org/connect/ they're linking it to https://discourse.webmaker.org/c/hive-learning-networks

@simonwex do you think we still need more work on this ticket? should we maybe redirect that subdomain to the webmaker discourse or maybe to the homepage?

**Comment by simonwex** [comment]
It's always nice to clean things out. :)
