### ISSUE TITLE
Add Cloudfront cache invalidation to OpenNews deploy script

### ISSUE THREAD

**Issue by ryanpitts** [MozillaFoundation/mofo-devops#139]
We've been having some issues in the last week or so: After we deploy changes to the site, users in some (but not all!) regions do not see updated content for long periods of time. It's required a manual cache invalidation to fix the issue (thanks @jbuck!).

Is it possible to add Cloudfront cache invalidation to the standard Jenkins deploy script?

**Comment by jbuck** [comment]
I've modified the default TTL for objects in Cloudfront to be 10 minutes. So if you want 10 minutes it'll pull down a fresh copy of whatever you're requesting.

**Comment by ryanpitts** [comment]
:+1:
