### ISSUE TITLE
Ensure log purges daily on callcongress app

### ISSUE THREAD

**Issue by jdotpz** [MozillaFoundation/mofo-devops#14]
Per https://github.com/mozilla/call-congress-net-neutrality/issues/3#issuecomment-73213689 I need to ensure daily log removals of the callcongress call logs.

**Comment by jdotpz** [comment]
This is completed.  https://github.com/mozilla/mofo_system_configurations/commit/3c473065eefa614c4be5c71ece098a6e6e458cc2
and
https://github.com/mozilla/mofo_system_configurations/commit/84652968c58a22c7e2a9ac4c449ef409a82c49de

**Comment by davidascher** [comment]
Thanks all.
