### ISSUE TITLE
Point 404s on OpenNews site to custom 404 page

### ISSUE THREAD

**Issue by ryanpitts** [MozillaFoundation/mofo-devops#140]
So this was working as of yesterday (I think?), but we noticed this morning that 404s on opennews.org are no longer pointing to the existing 404.html page. I'm thinking this probably has something to do with Cloudfront config, right?

Currently, we get a `Code: NoSuchKey` generic error page. See this link, for example: https://opennews.org/what/fellowship/foo/

We previously were pointing 404s to _site/404.html, which looks like:

![pasted_image_at_2015_08_05_03_57_pm](https://cloud.githubusercontent.com/assets/56477/9099197/b01621a4-3b83-11e5-956a-a17574e1b37a.png)

**Comment by jbuck** [comment]
@ryanpitts Fixed on my end!

**Comment by ryanpitts** [comment]
Awesome! Could you point me to the docs page that says where to adjust this for Cloudfront, just in case I run into something similar in the future?

**Comment by jbuck** [comment]
@ryanpitts :boom: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesDefaultTTL
