### ISSUE TITLE
How should we handle scaling up or down API.wmo and ID.wmo

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#141]
Before Thursday, August 13, we want to be ready to handle snippet traffic to these apps.

Heroku doesn't provide a way to scale apps dynamically, but it can be provided as an addon: https://addons.heroku.com/adept-scale (at a cost)

Alternatively we can statically scale up to 3 or 4 apps (or more) and see how that works for us.

discuss.

@jbuck @ashleygwilliams @simonwex

**Comment by cadecairos** [comment]
Not sure if adept-scale can handle node apps - it doesn't explicitly state it does. Says it reads the syslog drain to determine load, and I'm not sure how depended that is on the app being run. 

https://devcenter.heroku.com/articles/adept-scale

**Comment by cadecairos** [comment]
I've reached out to adept-scale asking if their product works well with node.js web dynos

**Comment by cadecairos** [comment]
I found this page: https://elements.heroku.com/addons/adept-scale where it does indicate support for dynos running node.js

**Comment by jbuck** [comment]
@cadecairos I bet it works on response times spit out by the Heroku logs. That should work fine with Heroku. Lets add it to our load testing tomorrow and see how it responds to load!

**Comment by cadecairos** [comment]
```
Chris,

At this point we have several apps on non Rails stacks, including PHP, Sinatra, Node and some more fringe stuff.

One thing I will say to people considering the addon is that AdeptScale is designed to work on production/enterprise apps. So if you want to load test or benchmark, be sure to let the app run with at least 150 req/min of simulated traffic for about 30 min. Also, keep traffic changes to realistic patterns.

If you do fire it up, we always love to hear feedback on what your stack is and how it performs in the wild. (Personally I'm interested in seeing it run on someone serving apps built on EmberCLI or Meteor, cause thats what I'd experiment with if I had the time ^_^)

Please let us know if you have any further questions,
Thanks, and happy scaling,
Alex
```

**Comment by cadecairos** [comment]
After adding adept-scale to loadtesting and running some tests from loadimpact, I can't say I recommend going with adept scale.

It appeared to successfully scale up when average requests hit a configured amount (500 ms) but once traffic died down, it failed to scale the dynos back down to the minimum.

**Comment by simonwex** [comment]
In addition to figuring out some notification for you, @jbuck and myself when it would scale us up, let's ask Adept Scale about the scaling down issue.

**Comment by simonwex** [comment]
@jbuck do you know the cost difference between doing this on Heroku with Adept Scale v.s. EC2 with autoscaling groups?

**Comment by jbuck** [comment]
@simonwex I don't think the cost difference is huge between the two, the big difference will be the time investment to get api.webmaker.org running on EC2 with all of the jazzy things it can do.

**Comment by jbuck** [comment]
We ended up rolling with Adept Scale

**Comment by Genkilabs** [comment]
Hi guys, I just ran across this thread randomly. I do a lot (most <_<) of the tech support for AdeptScale, and if you need more help with tuning and benchmarking be sure to open a ticket from the app dashboard and mention me and this thread.
Supporting open source devs like the Mozilla Foundation is something that is important and if I can help you I'd be glad to.

**Comment by simonwex** [comment]
Thanks, @Genkilabs!
