### ISSUE TITLE
Set up a pipeline to deploy new versions of thimble-beta

### ISSUE THREAD

**Issue by sedge** [MozillaFoundation/mofo-devops#142]
Our rapid development means that we need a way to rapidly deploy to production, preferably without having to interrupt the devops team every time.

cc: @jbuck

**Comment by jbuck** [comment]
It's just hosted on Heroku so it's easy enough to deploy to. Do you just want collaborator access to the Heroku app so that it's easy for anyone to push to prod?

**Comment by sedge** [comment]
Sure! How about publish and brackets?

**Comment by jbuck** [comment]
Added you to both
