### ISSUE TITLE
Restart the aggregator under planet.opennews.org

### ISSUE THREAD

**Issue by ryanpitts** [MozillaFoundation/mofo-devops#143]
I'm not sure if this is running on a cron or as a Heroku scheduled task, but it looks like http://planet.opennews.org/ is stuck at the end of June. (There are quite a few posts from member feeds since then.)

I know that the aggregator is running on Atul's app: https://github.com/toolness/planet-badges. I don't know where, though! (Would be happy to dig into this myself if someone could point me in the right direction.)

**Comment by jbuck** [comment]
@ryanpitts You have an invite from Heroku in your email! Have at it: https://dashboard.heroku.com/apps/planet-opennews/resources

**Comment by jbuck** [comment]
@ryanpitts okay, fixed. The problem was S3 credentials

**Comment by ryanpitts** [comment]
AHHHHHHHH! OK thanks, I got set up with the Heroku org yesterday and started looking at how the app is set up, but hadn't gotten further than that.
