### ISSUE TITLE
Create production and staging instances of ttw discourse with DBs on RDS.

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#146]

**Comment by jbuck** [comment]
@flamingspaz What Discourse instances do you have running? Are they all on RDS?

**Comment by flamingspaz** [comment]
community/advocacy ones are on pgshared-production-c and pgshared-staging-c

**Comment by flamingspaz** [comment]
Production is live at http://discourse-ttw-new.mofoprod.net/

- Domain/SSL will need to be done after we've got the old data imported
- Seems like very recently the ability to CDN just S3 uploads was added - I'll look into this when we're a bit more stable.

**Comment by simonwex** [comment]
@flamingspaz, thanks! Could you make my user an admin? (simonwex)

We had an integration with the webmaker login system. I'm going to see if I can find where that code is hosted and if it's still compatible with the new version. Do you know of it?

**Comment by flamingspaz** [comment]
Granted.

I _think_ it's id.webmaker.org on heroku, but I'm not 100%.

**Comment by simonwex** [comment]
@flamingspaz it is, but I'm not sure what module enabled that

**Comment by simonwex** [comment]
@jbuck any ideas?

**Comment by jbuck** [comment]
@simonwex it used the discourse-sso option with https://directory.hivelearningnetworks.org/, it didn't use oauth 2 with id.webmaker.org

**Comment by simonwex** [comment]
@jbuck do you see any problems with us just using the oauth2 plugin with id.wm.o instead of the previous setup?

**Comment by jbuck** [comment]
No, I think that's a pretty good idea

**Comment by simonwex** [comment]
@jbuck did you have a chance to create those OAuth keys?

@flamingspaz do you know how to enable oauth on that discourse instance?

**Comment by flamingspaz** [comment]
Staging is up at https://discourse-ttw.mofostaging.net/. Apologies this took so long, a lot of it was getting the groundwork done on Ansible so these are easier to manage in the future. Just to note, this doesn't have S3 uploads enabled as we only have two buckets left in the account - not sure if we want to use it on this.

As for oauth, seems like it needs to be done via a plugin, see https://meta.discourse.org/t/login-to-discourse-with-custom-oauth2-provider/14717/3

**Comment by simonwex** [comment]
@flamingspaz do you have a pub key/keybase account for sending you credentials?

**Comment by jbuck** [comment]
@flamingspaz Do you know what the callback URL for the discourse instance would be? id.wm.o requires that the callback URL be defined when registering the client. I couldn't see anything obvious in the plugin.

As for the bucket limit, go ahead and create an S3 bucket. I can now [increase](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) the limit.

**Comment by jbuck** [comment]
@flamingspaz 

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMAyLAhGIDGcDqAQ//XTCfdJcmxUh2VpZQTH2jZyVO/PMxMVCSW/A9NRWwRP6v
IjToEkX2lSi1go4bMiqXCQZrkJQQhOeV1uQ1bI09EejVBgTFMYnHyUAuRv5gDsoB
m4moYji5v1SscuhHBcIxCvUn8FuEtiV0l19bbsVDcWPfUhdL+1pj15F0LQ5YnH9X
4+VCjF74m1+i4xf6vJNlZUcZjYRizDB6/J4iDlWeNekAhseXrgvxzu2wRuujVEoS
Cn214ANnBLWzLk20ZhRVPS+2WDpefQVd1AD4fjOU0Gc/ALdL43wl+rJRtfMeajnx
ANVdbwFmSvCLzqrr3ZQxyXw2VDBY5I9/kbQri8THdjaa8MwVMKsB27niti5sjGdk
XvqZQ6E+dO0L6ZBUH9xmgRf6gRZ7+az/mxNMtaQ+X3MWgjBm2ShHrfU41ve9YpYZ
sj/UWLtBdAM2sVT20LOKV/A8CjX2nxJHNHOKl8Kyf5BlVf2DlQx3MCpK8mC+8iyI
UYk7Z7lBdluBVnUK94bgsmibnWRLVx2MB8JMtUwLiN3bJc35f9t6mR2mI+GsjcJG
k6lIecx2HVAMU/0zZPLlol0pz4+AMT0sJ4+lCPraspw64Q6hc2qRsifcKel7V2iB
dWlhdOOdRRYFR0azf1PrLXIYM5k4/fBh1o4c1JMKTx5QhgE+TWIwYoXEThzxS1zS
wH8BDPrAb+Y5AgnwRpaGZPOAeA8/Z947EGmxZH0YP7HY5MoFgLJ1e/p6Y8lO/B/C
sGr1qM0cM9X6wj76WVVzRLCBS7NUd9Bhjpws2yiOXUfbMv+8hix0UWGDmguWTN4b
KoMPxu661BBYfohcBCYpLXas7mJNy0IH6nGNbZcAQF9vYOXWLhNfO1CTLmrZDQB1
w5HYA/RahDgEFLxYUTFIGN7k2U1hi1XlLoBfA2AuEMcNBxMIXGttUH97BsFRfQhk
+S1MxpNPY3vcm/hCyl0w1V1RohWTnODzzAKJkQKpzks2998PmLd1BgCDh1xYpx3g
6Z5Ly722BcsmoJemFxUJv1cShfhgqN1LBPlzQjSwQUzDSo9gwqzJN6URfMvnEeRo
GU5czOzPrzQnLOMp3IOJz1hiv9h89o1fHxzqzOGZfIpy
=FJJN
-----END PGP MESSAGE-----
```

**Comment by flamingspaz** [comment]
it would be https://discourse-ttw.mofostaging.net/auth/webmaker/callback for staging

**Comment by jbuck** [comment]
Okay, updated!

**Comment by LeoMcA** [comment]
The credentials (which yousef forwarded to me) don't seem to be working:

![screenshot from 2015-08-26 11-27-47](https://cloud.githubusercontent.com/assets/755354/9491388/734e4864-4be6-11e5-9b31-474abdb76877.png)

Here's an example url which my plugin is redirecting to (which seems to be well formed, according to [the docs](https://github.com/mozilla/id.webmaker.org/blob/develop/docs/oauth.md#1-redirect-users-to-request-access): `https://id.webmaker.org/login/oauth/authorize?client_id=wm_id_LoF7p72gmD6GZazhS7iO&response_type=code&scopes=user&state=447a4a86a8d58f3122a7aa94ec38b10ef02acbf556959f2d`

And the repo, if that helps: https://github.com/LeoMcA/discourse-webmaker-id

(Once this is fixed, I'm not completely sure the plugin will work, because I don't think it'll be sending the right parameters at the access_token step, and even then if I'm correctly giving Discourse the data - but I can't test that until this is fixed)

**Comment by jbuck** [comment]
Ah crap, sorry. I created those credentials on id.w.o staging (so the URL
is https://id.mofostaging.net )

Want me to create credentials on production?

**Comment by LeoMcA** [comment]
No worries - for staging (and development) I'm more than happy to use the staging server, but it would probably be an idea to generate the production creds for the production Discourse instance at some point.

**Comment by simonwex** [comment]
@flamingspaz did you get the production keys?

**Comment by jbuck** [comment]
@flamingspaz 

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMAyLAhGIDGcDqAQ/8DvKGQmgXPTOrrPJ8zYi6xSXl9qVrYzShRgn2uF/MnlVZ
q347Mo+v2SBpjEEC+2EtZ+GBJWN6swXyJ1TuJLipogLYUdWLOgeyy9Fi0DhBwOyg
G7z1eOZwuiRHTDpwJhXWHhMDrAqq0G4vgGnwDS5pUJL0QdeY26je0v9D54kPNeKK
de1PFyAlQEUl7+Uw1fGG0iLEdhWL0HNy6cqennq8JmfIrerdy6W5vqhJas1cV7cn
SuLX04EM1o0KX2yHwJ5atjdOtmpNen2SEDwYwfGUvdW0yaTOxnqo3I1UfSTmJLMp
8DR3iuXiEZwNgzCUeekLUwfoe5SP6A87b9Uhf37pOIfyAb/OS4GgyWVCeJ8NKfKC
v4S/yIDS5L3hPVtfsym9XaPdd+X+jVQSN2E3QlXVecX/YVxHXvre1WK8Wxxagbwi
9gLJqr7p5lBrCPNIttW+73kWDx9y1YVeZ8zDAG+Mug9CYsvAhhl/JVYRwYRuj+Ui
o2G0bkr1RNnRrj2PrVKvcDsXXbF0CPl3lxyr1CX4f/keRtJ5owLdY+dqAfvzTT0X
p+j7V7S6hfYXQS3qRmm1oBlx4GiHHTHOKdb4ootnFz6nDm1MH3NiluLE+gCA6J2k
Pg85HDZxM3VzDBNDImegGFRe3rezTTCU1QHrI6/HVEmx3lFx5p8dwwCmyyIasGDS
wIABiBowre8em+XTViKUn5qTqX6gHBIBRmeuBUhsXzG9fo5hyYzBXYtsvxVkpLB2
RauuhasOmlFnGbTkWieixhmx/Uz1/JPCj95eULJ0oFuroxZVhy/aZM18a9fMvYlO
Tz6DB7I/vwK2u297U6x9kj5mYv02fzslkEWgj8u52uuMbRR3k+M6GPIgpVshmFVe
BUv2a6NczqDy0iPZsgSmoLHrM/FkgWZuCjqQhdFtLYF2I8HWjaiMhyBAVlpSH2a5
9ZwiCrg2Ujs6y3UBsXk4DfYHaLSQcsmjlxPh8MYQX6Hn7uED6LryUG/XK0lmZMMv
mciHav98E905iy5GqIZDOsHHw2/M2eoaB11n45XtIH3mTRuwKJ2PhgsgBFYRvBt7
MEN9F6TQfTIwlLMrefC1Ki63eqPV/BLMgn6TmeFKlLWhdg==
=0k1Y
-----END PGP MESSAGE-----
```

**Comment by LeoMcA** [comment]
The plugin is up and working on https://discourse-ttw.mofostaging.net/

The repo is here, if you want to look over it: https://github.com/LeoMcA/discourse-webmaker-id

**Comment by flamingspaz** [comment]
Also now live on production, but apparently my username/email is taken and I'm not getting a password reset email.

Once I verify it's working I'll disable Persona and local logins.

**Comment by flamingspaz** [comment]
nevermind, i was being stupid.

@jbuck, could you change the callback url on the prod instance from discourse-ttw to discourse-ttw-new?

**Comment by jbuck** [comment]
@flamingspaz So `https://discourse-ttw-new.mofoprod.net/auth/webmaker/callback` ?

**Comment by flamingspaz** [comment]
yup!

**Comment by jbuck** [comment]
Done!

**Comment by flamingspaz** [comment]
Webmaker login is working for me, though a second try from someone else wouldn't hurt. I've disabled local login, added SSL (will force it on when we move DNS) and set up weekly backups to s3.

I'm also guessing people need to start customizing the site before we move ahead with #168?

**Comment by jbuck** [comment]
@flamingspaz https://www.dropbox.com/s/lo7g1jyn11ykkmf/Screenshot%202015-09-08%2013.53.05.png?dl=0 looks like they're missing a logo?

**Comment by LeoMcA** [comment]
Yeah - I'm currently fixing that... and probably about to have my ass sued by Mars
![screenshot from 2015-09-08 18-35-50](https://cloud.githubusercontent.com/assets/755354/9747628/b4812294-5676-11e5-9825-33db50196f9f.png)

I'll change the logo and then commit the changes.

**Comment by jbuck** [comment]
@LeoMcA funny story, that. Changing the logo to the new one will definitely be required :)

**Comment by LeoMcA** [comment]
Ok - should be landing on prod soon enough.
![screenshot from 2015-09-08 22-32-34](https://cloud.githubusercontent.com/assets/755354/9748031/acce938a-5679-11e5-9a60-6b5ff0a7a911.png)

**Comment by flamingspaz** [comment]
it's in prod now.

**Comment by jbuck** [comment]
@flamingspaz I'm not sure what the next steps are, but it looks good to me. @simonwex do you have the old theme? or will this be using the default theme?

**Comment by flamingspaz** [comment]
Just the theming, moving the DNS over and forcing ssl.

**Comment by simonwex** [comment]
I haven't had a chance to modify the recovered theme yet, it's going to be some work. Let's not let that block getting discourse back.

**Comment by flamingspaz** [comment]
Cool, @simonwex just need the r+ to move the DNS over.

(Also, add a second instance for HA)

**Comment by jbuck** [comment]
@flamingspaz :shipit:

**Comment by simonwex** [comment]
R+! :shipit:

**Comment by flamingspaz** [comment]
almost forgot! need the callback changed to https://discourse.webmaker.org/auth/webmaker/callback

**Comment by jbuck** [comment]
@flamingspaz done!

**Comment by flamingspaz** [comment]
after some ssl fiddling we should be live \o/

**Comment by jbuck** [comment]
lgtm :tada:
