### ISSUE TITLE
Clean up Webmaker product on bugzilla

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#147]
At some point we need to get a bunch of brave souls to dive into bugzilla and clean things out.

There are 600+ open bugs, 24 components and no-one taking care of any of it!

https://bugzilla.mozilla.org/page.cgi?id=productdashboard.html&product=Webmaker&bug_status=open&tab=components

**Comment by cadecairos** [comment]
cc @simonwex

**Comment by Pomax** [comment]
bumping so we don't lose this: there were some bugzilla issues filed that were meant for learning.mozilla.org recently, so it feels like it's worth finally just turning the whole bugzilla part of our product issue tracking off.

**Comment by simonwex** [comment]
Agreed we should remove our product from Bugzilla. Let's make sure first, that we include links to github on our sites/tools.

**Comment by Pomax** [comment]
Which direction are you thinking? Replace any mention of bugzilla with github (I don't thiink we mention bugzilla anywhere in new tools/sites) or make it explicit where to go for "feedback" (rather than "bugs" or "issues" so as not to scare people) on the landing pages/footers for our tool and site offerings?

(this'll probably require some issues getting filed)

**Comment by Pomax** [comment]
All our things have github links at this point, can we file for the removal of the webmaker component? (with Thimble on GSOC, the last thing we want is an influx of people who mistakenly assume they should use bugzilla)

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1347718

**Comment by Pomax** [comment]
I'm cool with that course of action. Let's INCOMPLETE them all and walk with progress.

**Comment by cadecairos** [comment]
THIS DONE.

Webmaker component has been (or will be shortly) put in the component graveyard.
