### ISSUE TITLE
Pingdom access for Community Ops

### ISSUE THREAD

**Issue by flamingspaz** [MozillaFoundation/mofo-devops#151]
Since we've already paid for the year for our current account, we'd only need checks for the new Discourse instances going up. We'd also probably only need just an account for myself to manage them for now.

**Comment by jbuck** [comment]
@flamingspaz what email would you prefer to use? I'll send an invite

**Comment by flamingspaz** [comment]
yousef at mozilla.org.uk

**Comment by jbuck** [comment]
Done!
