### ISSUE TITLE
build.webmaker.org Github creds issue?

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-devops#152]
Not sure what's up, but I don't see any Github hosted content on build.w.o any more:

http://build.webmaker.org/now

<img width="741" alt="screenshot 2015-08-19 11 44 29" src="https://cloud.githubusercontent.com/assets/1901816/9354349/ab68c26c-4667-11e5-8628-eb1557875c51.png">

(this might not be a devops issue though)

**Comment by jbuck** [comment]
This is a code bug in build.w.o, so I've filed a PR to fix it

**Comment by adamlofting** [comment]
I think this is actually an issue with something else in the code. I filed a bug against the build repo. For some reason, the API endpoints where we get the github content are not responding. 

https://github.com/mozilla/build.webmaker.org/issues/91
