### ISSUE TITLE
Hive NYC Directory showing "untrusted connection"

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#153]
cc @juliavallera

Unable to access the Hive NYC Directory at https://directory.hivenyc.org/ Apparently it was working for Julia yesterday. 

I just tried it on Firefox and Chrome

![screen shot 2015-08-20 at 12 31 42 pm](https://cloud.githubusercontent.com/assets/4885898/9389148/7eca3fa8-4737-11e5-922d-6dad732875f3.png)

![screen shot 2015-08-20 at 12 32 49 pm](https://cloud.githubusercontent.com/assets/4885898/9389167/9ac562b4-4737-11e5-87d3-f55c7dc5fe39.png)

**Comment by simonwex** [comment]
I sent an email to webmaster@hivenyc.org unsure who currently owns the cert.

@jbuck, I say we just pull the trigger on purchasing a new one and updating.

**Comment by jbuck** [comment]
From #34

I've updated the Heroku app to use SSL. DNS/SSL should go live in a few minutes, up to 30 minutes from now.
