### ISSUE TITLE
upgrade science lab's discourse

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#158]
Can you upgrade the Science Lab's Discourse instance? Following the directions in the email below doesn't work for us:

*** 

A new version of Discourse is available.

Your version: 1.3.0.beta9
New version: 1.4.0.beta10

You may want to:

    See what's new in the GitHub changelog.

    Upgrade by visiting http://forum.mozillascience.org/admin/upgrade and pressing the "Upgrade" button.

    Visit meta.discourse.org for news, discussion, and support for Discourse.

**Comment by jbuck** [comment]
@flamingspaz Want to take this one?

**Comment by flamingspaz** [comment]
Sure, could I get admin access on it (yousef)? This is the one without RDS I think so I want to img it before I touch it.

**Comment by jbuck** [comment]
@acabunoc Can you give admin to @flamingspaz and myself (jbuck)

**Comment by acabunoc** [comment]
granted admin to both of you through the discourse interface! @jbuck @flamingspaz

**Comment by flamingspaz** [comment]
@jbuck @simonwex Is this instance still ok using Mandrill or would you prefer to move it over to SES?

@acabunoc Since, it's currently on an old version, the theme will most likely be broken once it's been upgraded. Would you like me to spin up a staging server for you to test it out?

**Comment by acabunoc** [comment]
@flamingspaz - thanks, yes a staging server would be helpful!

**Comment by flamingspaz** [comment]
https://discourse-science.mofostaging.net/

Make an account there and I'll bump you to admin.

**Comment by flamingspaz** [comment]
@acabunoc, noticed you haven't signed up yet, anything blocking?

**Comment by acabunoc** [comment]
Completely forgot (sorry, it's been busy). Thanks for flagging!

**Comment by acabunoc** [comment]
@flamingspaz finally signed in (really sorry about the delay!) let me know when I can mess around with the theme :smile:

**Comment by flamingspaz** [comment]
Bumped you up to admin and upgraded discourse. Head over [here](https://discourse-science.mofostaging.net/admin/customize/colors) to start theming!

**Comment by acabunoc** [comment]
Hey @flamingspaz! I finally added the header/footer here: https://discourse-science.mofostaging.net/  Thanks for your patience :)

**Comment by cadecairos** [comment]
@flamingspaz Do you think having this in this heartbeat is reasonable?

**Comment by flamingspaz** [comment]
:+1:  There will be downtime for this through as the database needs to be moved. I've added a notice to the forum that service will be intermittent tomorrow.

**Comment by acabunoc** [comment]
Thanks @flamingspaz & @cadecairos :smile:

**Comment by flamingspaz** [comment]
So I managed to image and upgrade it on a different server but migrating the DB is proving to be a bit of a challenge - I don't think I'll be able to finish it off this week.

**Comment by cadecairos** [comment]
@flamingspaz How are things going here? Anything I can do to help out?

**Comment by flamingspaz** [comment]
Finally finished up all of my assignments so I have time to deal with this. I still have no idea about the database issue so I'm going to deal with the Mandrill/upgrade first and run backups until I figure out why the database migration never works.

@cadecairos we need to verify the email account for SES. Any chance we can get incoming email for that email account going to me or you?

**Comment by cadecairos** [comment]
I'll inquire about verifying the email tomorrow

Glad to have you back around! :D

**Comment by acabunoc** [comment]
Hey,

We recently decided we're going to retire the forum in the new science website. So, not sure if it's worth it to keep moving forward on this!

Thanks for all the work done here! Sorry for the change of plans

**Comment by simonwex** [comment]
That makes sense, @acabunoc. I think it's the same story for #37.

Sorry if you dug into this, @flamingspaz.
