### ISSUE TITLE
http://paperbadger.herokuapp.com/ -> badges.mozillascience.org

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#159]
Can we have the site currently being served at http://paperbadger.herokuapp.com/ (owned by Mozilla) on https://badges.mozillascience.org/ ?

With this move, will it be using the CDN? We're expecting a jump in traffic mid-next week.

- [x] Obtain SSL certificate for badges.mozillascience.org
- [x] Create Cloudfront distribution for badges.mozillascience.org
- [x] Create DNS entry for badges.mozillascience.org and point it at Cloudfront

**Comment by jbuck** [comment]
@acabunoc mind if I change the name of the heroku app to something more descriptive?

**Comment by acabunoc** [comment]
@jbuck - go ahead! but I'll give a heads up to our collaborators (preferably before the change)

**Comment by jbuck** [comment]
@acabunoc I'd like to change it to `badges-mozillascience-org`

**Comment by acabunoc** [comment]
makes sense! When are you making the change? I'll let the others know

**Comment by jbuck** [comment]
@acabunoc I'll make it now

**Comment by acabunoc** [comment]
Can you also add badges.mozillascience.org around the same time?

This way I can just say we're changing from paperbadger.herokuapp -> badges.mozillascience

**Comment by jbuck** [comment]
Hahhhhhh no sadly the domain isn't ready yet, I need to finish some SSL
approval bits first

**Comment by acabunoc** [comment]
Ah, no worries!

**Comment by jbuck** [comment]
@acabunoc All done! Domain should be working in 30 minutes

**Comment by acabunoc** [comment]
Woooo! you rock @jbuck :star2:
