### ISSUE TITLE
Deploy webmaker-firehose to production

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#16]
- [x] Decide where to put it
- [ ] Get it login server credentials
- [ ] Get it admin MakeAPI Hawk credentials
- [ ] Set & verify environment settings
- [x] SSL?

This app doesn't handle any PII, it just reads and writes to the Makeapi. It also has Login.

anything else, @simonwex  @jdotpz ?

**Comment by jdotpz** [comment]
Most of the following will be done if you fill this out so I get this properly built:  https://docs.google.com/a/mozillafoundation.org/spreadsheet/viewform?formkey=dFBONmhPUXcxVVp5TFBiS0I4OWZ1RFE6MQ#gid=0

- [ ] Choose a domain name ( @cadecairos @wex ) and let JP know for SSL purposes. (firehose.webmaker.org?  Is this even going to be visible to the user?  If not, we can use mofoprod.net)
- [ ] Where does it live on github?
- [ ] Any recurring tasks (ala cron) required?  (aka, does JP have to install this on controller)

**Comment by cadecairos** [comment]
> Is this even going to be visible to the user?

internal only, mofoprod should be fine I think. SSO isn't really necessary either.

**Comment by jdotpz** [comment]
Name:  wmfirehose.mofoprod.net

**Comment by cadecairos** [comment]
@jdotpz any opposition to hosting this on mofo heroku?

**Comment by jdotpz** [comment]
Depends what it's doing and what it connects to.

**Comment by jdotpz** [comment]
This is going to Heroku.
