### ISSUE TITLE
Deploy petitions.mozilla.org

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#169]
https://github.com/ScottDowne/petition-template should be deployed somewhere with staging & production setup. Also need to start work on the domain, I'm going to start with petitions.mozilla.org for now since it's a safe default.

- [x] Decide on a domain: `petitions.mozilla.org`
- [x] Obtain SSL certificate
- [x] Create staging Heroku app
- [x] Create staging CDN
- [x] Create staging DNS https://petitions.mofostaging.net
- [x] Create production Heroku app
- [x] Create production CDN
- [x] Create production DNS [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1204141) https://petitions.mozilla.org

**Comment by ScottDowne** [comment]
petitions.mozilla.org to work a lot like call.mozilla.org

**Comment by jbuck** [comment]
This has been completed
