### ISSUE TITLE
SES for the science lab

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#174]
Hello @jbuck!

I got nodemailer working well with my gmail address. Could you help me get setup with Amazon SES to send emails from the science lab?

It [looks straight forward](http://adilapapaya.com/docs/nodemailer/#settingupses) on this end.

Thanks!

**Comment by jbuck** [comment]
@acabunoc I've verified the mozillascience.org domain with AWS SES, and I've filed a support ticket to enable non-sandbox usage. I need to generate credentials for you, and send them to you. By any chance is this you on [Keybase](https://keybase.io/abbycabs)? Could you verify your account? It'll make it much easier to send you credentials securely.

**Comment by acabunoc** [comment]
That's IS me on keybase! Thanks Jon :)

**Comment by acabunoc** [comment]
Aaaannnd, I think it's all verified!

**Comment by jbuck** [comment]
@acabunoc Use keybase to decrypt this blob of text, which has AWS credentials to send email as mozillascience.org.

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMA67QCPWLdzUeAQf/QXWvx6rJbRuF65ZFRcotmqu5JKQA5xsE5bIH0UvFp9u8
SeeKgPPvjs3BF06wVnSaNUfiNWb97rkcF/Fg1kpRPrkIfgZnEoAMgujJ5DrLCEee
QRJ2dqjX0KB5DLJKSvUzKUMRGg/IyLhUWVfNu50xXswDdaEVSJtjMy5eHAjijG/Z
gSFu9+ZtuNnYQXf1v+//PNwQLTlTJw5bZZPcmna58YCl3flO9vgrTl0qyMDv/K8o
BUDVqYX90bP7CI+UdgcJEnYqlq/mwMenVewnGFFGVgAomnZixMyy6NaYf+HibvT2
O7HswoiqAghxUgObtGqmdbBcg38e0HT7VW1Dfjf+uNLAGAGsluklSTq2HfRKKNA8
W2wXlx9XsbHtkKHmswDI8auhns8SiGqxulz+jr712HT9djLoWwhJCUnYm7nCjNq1
t48n2cL8VGRVT3UiZgsk+L6wfGwLD3nE85SywLEx5eQ/aBPz1SelJew8P4k6Gp3R
YKSdZs7qaO2qKqKiOp5fzrXgWoZlMMfBXwbC8mNJWgUR7E+b8840UUi8841tXiNt
7u/99e0HHrd6T5nUbLXOBH8L/AfWA+lUgKiiJRZSQIZY/S/et0GflrjJ6tA+GeQM
TO6hBoGaWyqtMg==
=Yepn
-----END PGP MESSAGE-----

```

**Comment by acabunoc** [comment]
Thanks @jbuck! This works for me :)

However, the emails are all landing in spam. Is there any way to help prevent that?

**Comment by acabunoc** [comment]
Also, Happy Birthday!! :birthday: :cake: :balloon: :star:

**Comment by jbuck** [comment]
I've enabled DKIM message signing, maybe that'll improve it? Do you have
any indication for why it's getting caught in the spam filters?

**Comment by acabunoc** [comment]
This is all I see:

![screen shot 2015-09-03 at 12 41 24](https://cloud.githubusercontent.com/assets/617994/9664623/1e8a8820-5239-11e5-98eb-cf84f0f3350f.png)

With a link to https://support.google.com/mail/answer/1366858?hl=en&expand=5

I tried again, it looks like it *sometimes* go through. Not sure why...

**Comment by jbuck** [comment]
@acabunoc Can you award me a badge? I'd like to look at the email headers, see if there's anything useful in there

**Comment by acabunoc** [comment]
sent!

**Comment by jbuck** [comment]
Okay, it appears as spam for me too. Maybe try changing the text/formatting of your email so it's less spam-like to Google?

**Comment by acabunoc** [comment]
Thanks @jbuck - yeah, I'm looking into that this week: https://github.com/mozillascience/PaperBadger/issues/119#issuecomment-137867507
