### ISSUE TITLE
Transfer TogetherJS Hub to Heroku

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#176]

**Comment by jbuck** [comment]
@simonwex I did a quick test on Heroku today, and it appears to be working: https://dashboard.heroku.com/apps/togetherjs-hub-prod/resources

Can you think of a reason I shouldn't deploy it on Heroku?

**Comment by jbuck** [comment]
@simonwex says because Heroku has a router timeout of 55 seconds and there's no echo/ping to keep the connection alive

**Comment by jbuck** [comment]
I did a patch: https://github.com/mozilla/togetherjs/pull/1089

**Comment by jbuck** [comment]
Instead of writing a patch, I should've tested first. Both Chrome and Firefox work fine without my patch and with Heroku. I was able to idle for 15 minutes, which is long enough for me to say :shipit:

**Comment by jbuck** [comment]
All working now, hooray.

**Comment by simonwex** [comment]
Just an FYI - we can only run this on one dyno. If we scale it, users will end up disconnected from their sessions. This is less computing resources than an EC2 instance, I think we'll have more problems with it here than on EC2.

**Comment by jbuck** [comment]
It's looking pretty slim on memory usage: https://dashboard.heroku.com/apps/togetherjs-hub-prod/metrics/web but I'll keep monitoring it!
