### ISSUE TITLE
Write up decommissioning plan for webmaker.org sites

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#182]
If you'd like to render this, use anything capable of rendering [DOT files](https://en.wikipedia.org/wiki/DOT_%28graph_description_language%29)

```
digraph webmaker {
  api [label="api.wm.o"];
  api -> id;

  appmaker [label="apps.wm.o"];
  appmaker -> login;
  appmaker -> makeapi;
  appmaker -> s3makes;

  beta [label="beta.wm.o"];
  beta -> api;

  bramble [label="thimble.m.o"];
  bramble -> id;

  events [label="events.wm.o"];
  events -> eventsapi;
  events -> login;

  eventsapi [label="events-api.wm.o"];
  eventsapi -> login;

  goggles [label="goggles.wm.o"];
  goggles -> login;
  goggles -> makeapi;
  goggles -> s3makes;

  id [label="id.wm.o"];
  id -> login;

  makeapi [label="makeapi.wm.o"];
  makeapi -> login;

  makevalet [label="makes.org"];
  makevalet -> makeapi;
  makevalet -> s3makes;
  makevalet -> webmaker;

  popcorn [label="popcorn.wm.o"];
  popcorn -> login;
  popcorn -> makeapi;
  popcorn -> s3makes;

  profile [label="wm.org/user/jon"];
  profile -> badges;
  profile -> eventsapi;
  profile -> login;
  profile -> makeapi;
  publish -> id;

  s3makes [label="Make storage"];

  teach [label="teach.m.o"];
  teach -> id;

  thimble [label="thimble.wm.o"];
  thimble -> login;
  thimble -> makeapi;
  thimble -> s3makes;

  webmaker [label="webmaker.org"];
  webmaker -> badges;
  webmaker -> login;
  webmaker -> makeapi;

  welcome [label="welcome.wm.o"];
  welcome -> login;
  welcome -> makeapi;
}
```

cc @ashleygwilliams @simonwex

**Comment by jbuck** [comment]
@simonwex easy peasy:

## The easy stuff (shut down unused stuff)
- Shut down profile
- Shut down events.webmaker.org
- Shut down events-api.webmaker.org
- Shut down welcome.webmaker.org

## The harder stuff (content tools)
The key question here is how much functionality we need to preserve for end users. I'm working off the assumption that we simply want to preserve and view content that they've published to makes.org. If this assumption is wrong, we'll need to do more work

### Appmaker
- Disable saving new content
- The saved makes link directly to apps.webmaker.org so we should upload the static content of apps.webmaker.org to makes.org and modify the `<base>` tag

### Goggles
- Pomax is currently working on implementing support for publish.wm.o and id.wm.o,
- We'll need to modify the script living on goggles.webmaker.org to redirect to a page instructing people how to install the "new" goggles bookmarklet. 

### Popcorn
- Disable saving new content
- The saved makes link directly to popcorn.webmaker.org so we should upload the static content of popcorn.webmaker.org to makes.org and modify the `<base>` tag

### Thimble
- Disable saving new content
- Figure out a way of importing thimble content into bramble. I'm personally a fan of running a bulk import with redirects *or* have redirects run the import step within the users browser.

### makes.org / make-valet
- Convert all of the make metadata within makeapi to static data that the make-valet can use somehow
- Convert the "make details" iframe to be rendered within the make-valet, or remove it entirely
- webmaker.org/me will simply be a static listing of all of a users content in the root of username.makes.org

## webmaker.org
- We should simply not save/re-use anything on here. Just make it a clean break! Change the dns for beta.webmaker.org to webmaker.org and call it a day.

## backend services
- Shut down the makeapi
- Write a patch for id.wm.o to store webmaker users
- Shut down the loginapi

:tada:

**Comment by cadecairos** [comment]
> Shut down profile
> Shut down events.webmaker.org
> Shut down events-api.webmaker.org
> Shut down welcome.webmaker.org

We should discuss how much we (as an org) care about links to sites like profile/events/welcome - should we put in place permanent redirects in Route53 or just let the links break

> The saved makes link directly to apps.webmaker.org so we should upload the static content of apps.webmaker.org to makes.org and modify the <base> tag

I'm seeing a handful of absolute urls in appmaker apps to apps.webmaker.org for styles and JavaScript that will also have to be rewritten - this could be true for more that appmaker apps


> Convert the "make details" iframe to be rendered within the make-valet, or remove it entirely

we can probably remove it entirely if we added all the metadata to og and meta tags  in the make HTML... right? one less piece of complexity.

**Comment by simonwex** [comment]
We should clean our Github portfolio, too: #189

**Comment by simonwex** [comment]
"/me" needs to be moved to the teach site where we already have auth. 
We need to add a 301 to webmaker.org/me to teach.mozilla.org/me

**Comment by xmatthewx** [comment]
Let's move "/me" up the list. This would unblock the relaunch of Webmaker.org. That relaunch will unblock a bunch of communications, marketing, and community work. Some items on the harder stuff list seems less critical.

**Comment by simonwex** [comment]
It's all about "/me" with you, isn't it, @xmatthewx?

Seriously, though: :+1:

**Comment by jbuck** [comment]
This lives in https://github.com/MozillaFoundation/plan/issues/569 now
