### ISSUE TITLE
Shut Down Profile

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#184]
This will shut down the Webmaker user profile service: https://github.com/mozilla/webmaker-profile-2
 
@jbuck suggested we can begin by redirecting traffic by changing DNS

It would then just be necessary to:
* shut down any Github webhooks and service integrations
* disable the profile deployments from Jenkins
* cleanup AWS (turn off AS groups, kill EC2 instances, cleanup security groups)
* Disable any monitoring

Are there any external dependencies on this that we're not considering?

@jbuck @ashleygwilliams @simonwex @Pomax @gvn @k88hudson @xmatthewx

+any one else you all might think have some input here

**Comment by jbuck** [comment]
My preferred option would be to simply shut it down by disabling the configuration option in webmaker.org: `export PROFILE_URL=https://profile2.mofoprod.net/user` because the profile service is exposed as https://webmaker.org/user/jon .

**Comment by cadecairos** [comment]
:+1:

**Comment by gvn** [comment]
AFAIK nothing else is using the profile service...

**Comment by k88hudson** [comment]
Sounds good to me!

**Comment by cadecairos** [comment]
I've disabled profile on staging and production.

Proceeding with removing AWS resources.

**Comment by cadecairos** [comment]
Turns out, we're running profile on a combined EC2 instance with (at least) thimble, goggles and popcorn, on both staging and production.

**Comment by cadecairos** [comment]
This is basically stalled until we can deprecate everything that's in the wmappcluster instances.

Unless we remove it from the cluster - worth it? @jbuck

**Comment by jbuck** [comment]
Nah, not worth it. It'd be more effort to try and slice it out now than just wait until we can kill everything

**Comment by jbuck** [comment]
ALTHOUGH if you wanted to put in the work to get the other things running on Heroku.... well now, you have my attention

**Comment by cadecairos** [comment]
I can certainly try.

**Comment by cadecairos** [comment]
Decomissioning this infra will take place in #215
