### ISSUE TITLE
Shut Down Webmaker Events

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#185]
This will cover the events frontend and events service

Service: https://github.com/mozilla/webmaker-events-service
Client: https://github.com/mozilla/events.webmaker.org

Todos (non-exhaustive):
- [x] DNS redirects from events.webmaker.org to ??? (and events.mofostaging.net)
- [ ] Shut down the front end and service (disable AWS AS groups, kill instances, disable monitoring)
- [ ] Disable github hooks and service integrations
- [ ] Disable events and events-api on jenkins

Questions: 
* Where do we redirect events.wmo to?
* Do we bother modifying site headers and maps to reflect the events service has shutdown

@jbuck @ashleygwilliams @simonwex @Pomax @gvn @k88hudson @xmatthewx

**Comment by jbuck** [comment]
I don't think we should redirects events because we have like 5 people that use it. I don't know what you mean about site headers and maps though

**Comment by cadecairos** [comment]
as in all the header links everywhere else on webmaker.org that links to events

![screenshot from 2015-09-14 14-59-41](https://cloud.githubusercontent.com/assets/438003/9858891/41fc82f2-5af1-11e5-91cb-f242edbe89d7.png)

For w/e reason I thought there was a sitemap page. but it's just some useless xml file thing

**Comment by jbuck** [comment]
Oh yeah, good point. Yeah, we should probably nuke the link to Events

**Comment by cadecairos** [comment]
Official deprecation notice online at https://events.webmaker.org

**Comment by cadecairos** [comment]
## Launch Configurations

### Production

* wmapp2cluster-production-64
 * Deleted
* Staging
  * wmapp2cluster-staging-64

    Deleted

### Autoscale Groups

* Production
  * wmapp2cluster-production-as
Deleted

    Staging

    wmapp2cluster-staging-as

    Deleted


Load Balancers

    Production

    events-api-production

    Deleted

    events-production

    Deleted

    wmpublisher-production

    Deleted

    wmscreenshot-production

    Deleted

    Staging

    events-api-staging

    Deleted

    events-staging

    Deleted

    wmpublisher-staging

    Deleted

    wmscreenshot-staging

    Deleted


RDS Instances

    Production

    events-production-a

    Snapshotted: events-production-a-final-snapshot

    deleted

    Staging

    events-staging-b

    Snapshotted: events-production-a-final-snapshot

    deleted

**Comment by cadecairos** [comment]
Calling this completed.
