### ISSUE TITLE
blog.workopen.org is not available

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#186]
@OpenMatt reported that blog.workopen.org is not available. If it's like the other times it's been down, it's probably because mysql has to be (re)started.

**Comment by jbuck** [comment]
Restarted MySQL

**Comment by OpenMatt** [comment]
blog.workopen.org is down again. 
"Error establishing a database connection"
http://blog.workopen.org/

@jbuck: I'm going to start housing more content and curriculum here moving forward. Can we set it up in a way that it doesn't break monthly?

**Comment by cadecairos** [comment]
I rebooted mysql to bring it back up again.

**Comment by cadecairos** [comment]
(did not mean to close)

**Comment by jbuck** [comment]
@OpenMatt yeah we'll need to do something about this...

**Comment by simonwex** [comment]
Hey @OpenMatt I'm wanting us to get away from hosting wordpress things ourselves. How would you feel about us moving this to a hosted wordpress service?

**Comment by OpenMatt** [comment]
@simonwex sure. can we have a quick discussion about it first? ping me in IRC when you have a sec?
