### ISSUE TITLE
Create a generic "This is deprecated" landing page

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#187]
Lets create a generic this is deprecated page to redirect all the things to as we take down services.

What we need:
* some copy
* a place for it to live
* basic design
* sign-off from people who might care how this is communicated to people

cc/ @jbuck @ashleygwilliams

**Comment by ashleygwilliams** [comment]
here's a start. thoughts?

Hi! You were looking for something- but unfortunately, it's no longer here.

In an effort to keep our open web tools and curriculum as up-to-date and relevant as possible, the Webmaker team has deprecated some services. Most of these services are being replaced by new and improved ones- but a few of them are not. [You can read more about this on our blog.]()

Send us some feedback [here](mailto:???)!

Looking for something to do? Why not checkout some [makes] from our new [Webmaker Android app]()?

**Comment by cadecairos** [comment]
sounds great to me!

> some [makes] from
maybe "projects" is the right term?

> Send us some feedback here!
`help@webmaker.org` perhaps?

**Comment by ashleygwilliams** [comment]
+1 to both @cadecairos

**Comment by cadecairos** [comment]
> a place for it to live

So we probably want to drop this deprecation notice on S3 and serve it up for domains we shut off?

**Comment by ashleygwilliams** [comment]
oh that sounds like a good idea. +1. shall i start a repo and write some html/css?

**Comment by jbuck** [comment]
yeah, we'll host this on S3

**Comment by jbuck** [comment]
@ashleygwilliams yeah, go for it; we can easily get it running on Travis if we want to make tweaks to it too

**Comment by secretrobotron** [comment]
cc @kevzawacki @hpauljohnson

**Comment by secretrobotron** [comment]
:+1: love it. A few tweaks:

Hello there! You were looking for something, but, unfortunately, it's no longer here.

To keep our tools and curriculum as relevant as possible, the Webmaker team has deprecated some services. Most of these services are being replaced by new and improved ones, but a few of them are not. [You can read more about this on our blog.]() (@kevzawacki: what's the right blog post?)

Need help, or have questions or comments about our processes? Send us some feedback [here](mailto:help@webmaker.org)!

Looking for something to do? Why not checkout some [makes] from our new [Webmaker Android app]()?

**Comment by ashleygwilliams** [comment]
wfm @secretrobotron

**Comment by KevZawacki** [comment]
Thanks, all -- this looks great. 

Here's the appropriate blog post: https://blog.webmaker.org/product-update-for-appmaker-and-popcorn-maker

**Comment by ashleygwilliams** [comment]
https://github.com/mozilla/mofo-deprecation <- repo here. adding links and we should be ready to :ship:

**Comment by cadecairos** [comment]
I used @jbucks cloudformation template to set up an S3 bucket and point a Cloudfront distribution at it.

We just need to upload the site.

**Comment by cadecairos** [comment]
FYI: s3 bucket name is `webmaker-deprecated-sites-s3bucket-15kz0pphzvcaz`

**Comment by jbuck** [comment]
@ashleygwilliams has :ship:'d it: d2ib1sypv3hys6.cloudfront.net
