### ISSUE TITLE
Clean up webmakerorg-staging on AWS

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#188]
I've migrated webmaker-staging to heroku, and will be cleaning up things on AWS.

**Comment by cadecairos** [comment]
#### Deleted resources

* Auto Scaling Group: webmakerorg-staging-as
* Launch Configuration: webmakerorg-staging-64-1bCopy (AMI ami-d9d6a6b0)
* Load balancer: webmakerorg-staging
* DNS A record in Route 53 for `webmaker.mofostaging.net.`

**Comment by cadecairos** [comment]
@jbuck can you think of anything else?

**Comment by jbuck** [comment]
@cadecairos I think we're good!
