### ISSUE TITLE
Clean up Github repos as part of decomisison

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#189]
https://github.com/mozilla/thimble.webmaker.org:
 * Move `master` to `archive` branch
 * Rename `bramble` as `master`

https://github.com/mozilla/teach.webmaker.org
 * Rename to teach.mozilla.org

https://github.com/mozilla/popcorn.webmaker.org (Kevin for messaging)
 * add bold deprecation message 
 * how to get involved with other projects
 * "would you like to adopt popcorn?"

https://github.com/mozilla/webmaker.org – Not entirely sure what to do here
 * Possibly redirect to webmaker-desktop
 * Archive master on archive branch somewhere

https://github.com/mozilla/events.webmaker.org
 * add bold deprecation message

**Comment by jbuck** [comment]
ashley is including this feedback as part of the overall decommissioning plan in #182

**Comment by jbuck** [comment]
This worked is listed in https://github.com/MozillaFoundation/plan/issues/569
