### ISSUE TITLE
Thimble published projects aren't being indexed by Google

### ISSUE THREAD

**Issue by humphd** [MozillaFoundation/mofo-devops#191]
If you try a Google search for `site:https://d157rqmxrxj6ey.cloudfront.net` it only returns a very small number of things that look like projects made in the early weeks of turning the site on.  Is there something we need to do in order to get Google to do the right thing here?  Have we been blacklisted?

I ask because there is a desire from the learning team to be able to see what people are making, and being able to do this via a standard Google query would be ideal.

cc @hannahkane

**Comment by hannahkane** [comment]
cc @ldecoursy @chadsansing

**Comment by jbuck** [comment]
I bet those projects exist in the Google search index because they were linked from somewhere that Google already indexes.

I suspect the solution would be to [add a sitemap](https://blog.kissmetrics.com/get-google-to-index/) so that Google knows what URLs to index. @adamlofting confirm/deny?

**Comment by adamlofting** [comment]
Confirmed. Google will need something to point at the sites so it knows they exist.

This could be an autogenerated XML sitemap, and/or some navigatable directory with links that get to the end content.

**Comment by jbuck** [comment]
@adamlofting Great, thanks!

@humphd I filed https://github.com/mozilla/publish.webmaker.org/issues/168 to implement this feature
