### ISSUE TITLE
MozFest Schedule App

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#193]
@jbuck 

Just wanted to get this on your radar.  I don't have much details yet but will fill in more info here gradually.

This year's MozFest app will be built based on Ryan's [SRCCON Schedule App](https://github.com/OpenNews/srccon-schedule).  Everything is build in front end and I guess we can just load the data from a locally hosted .json file (vs storing things in Google Speadsheet etc)?

Would like to hear your suggestion on where this app should live. As part of the MozFest site? or a separate app that we serve? :bowtie:

**Comment by mmmavis** [comment]
FYI, from Ryan
> As for where it should live, when we've used this app with SRCCON, we've always gone with a schedule.srccon.org sudomain pointed at the gh-pages site. No deployment required, updating sessions.json in the repo means that the app automatically gets new data. If that approach works for MozFest, it sure gets rid of some headaches.

**Comment by jbuck** [comment]
@mmmavis Yeah, gh-pages or Heroku seems fine for this. subdomain also seems ideal from a maintenance perspective

**Comment by simonwex** [comment]
Thanks for helping with this, @flamingspaz!

**Comment by mmmavis** [comment]
Hellooo @flamingspaz :bowtie: 

Thanks for helping!

This is Mavis and I've been helping to build the front end bits of the [MLN site(aka Teach site)](https://github.com/mozilla/teach.mozilla.org) and the [MozFest site](https://github.com/mozilla/2015.mozillafestival.org) these days. I haven't had a chance to check out the [MozFest Schedule App code](https://github.com/mozilla/mozfest-schedule-app/)(which pretty much is a clone of the [SRCCON Schedule App](https://github.com/OpenNews/srccon-schedule)) thoroughly yet but am planning to do that next week.  

Let me know if you have any questions! :smile: You can find me via email/GitHub mentions/IRC #teach #webmaker :dancers:

**Comment by flamingspaz** [comment]
Hey Mavis!

I've taken a look at the repo and it seems pretty straightforward. jbuck and myself had a chat a while ago and we decided sticking this up on S3 would be the best option. I'm gonna play about with it over the weekend and I'll let you know if I have any q's.

**Comment by flamingspaz** [comment]
@mmmavis I'm thinking we should have master push to S3 as our production branch and leave gh-pages as a dev/staging. If that sounds good to you I'll shoot a PR.

**Comment by mmmavis** [comment]
Uh I failed at catching all my Github mentions again.  Sorry folks!  I just saw the updates here now.

@ryanpitts and I were discussing about adding CNAME to the app in this [ticket](https://github.com/mozilla/mozfest-schedule-app/issues/1).  It looks like we are gonna use `schedule.mozillafestival.org` for that.  Can you guys suggest what to do next?

**Comment by mmmavis** [comment]
@flamingspaz 
> @mmmavis I'm thinking we should have master push to S3 as our production branch and leave gh-pages as a dev/staging. If that sounds good to you I'll shoot a PR.

Yea that sounds cool with me.

@ryanpitts, will this change affect how your Python script work?

**Comment by ryanpitts** [comment]
@mmmavis @jbuck @flamingspaz Python script don't care :) In fact, it would be plenty easy to add a method that also pushes to S3 if that's preferable.

Sounds like the current plan is to push to GitHub gh-pages branch, and then have merge to master perform a deploy to S3 though?

**Comment by flamingspaz** [comment]
Travis will handle deploying to S3, no need to edit the script :+1: 

> Sounds like the current plan is to push to GitHub gh-pages branch, and then have merge to master perform a deploy to S3 though?

Yep, my thinking is we can cache some of the assets (maybe even everything except for sessions.json?), but that'd be pain for actively developing on. If you want to go gh-pages directly to S3 I can do that too.

**Comment by ryanpitts** [comment]
OK, the Python script that makes the JSON and commits to GitHub is here: https://github.com/mozilla/mozfest-schedule-loader. Tried to document as extensively as possible. Maybe overkill for such a small thing, but explicit is better than implicit!

Not sure where this should be run, but if there is a manual step required to push from gh-pages staging to S3 for prod, it seems like it *could* run on cron. If there's no manual intervention between cron and prod, though, that feels a little risky.

**Comment by ryanpitts** [comment]
For reference, we used a version of this script for SRCCON, and triggered manually via Slackbot command (so, basically, firing a POST request at a specific URL that knew to trigger the job).

**Comment by flamingspaz** [comment]
If we can get the script to grab the secrets from env vars, travis should be able to do that fairly easily using a similar POST method.

(cc @jbuck to make sure that's not a stupid idea)

**Comment by ryanpitts** [comment]
Would it be worth a quick call on Tuesday just to talk about setup here? I'm happy to help however I can, but you all might also have this already handled!

**Comment by flamingspaz** [comment]
Yeah, I think a call would be useful. Are you available ~9PM UTC (and anyone else interested)?

**Comment by ryanpitts** [comment]
Yep, that time works for me.

**Comment by mmmavis** [comment]
works for me too! how should we meet? :)

**Comment by ryanpitts** [comment]
unless anyone prefers a different venue, how about my Vidyo room?

**Comment by mmmavis** [comment]
works for me @ryanpitts 

@flamingspaz will you be able to join Ryan's Vidyo room or you need us to generate a special url? (I actually don't know how :wink: but will find that out)

**Comment by flamingspaz** [comment]
Yeah, I'd need the guest link. I'm running about 10 minutes late so if you
can't grab it by then we can jump into the community it room.

**Comment by ryanpitts** [comment]
https://v.mozilla.com/flex.html?roomdirect.html&key=ps6eD9VZ9tv3

**Comment by mmmavis** [comment]
lovely, see u both in 8 mins!

**Comment by mmmavis** [comment]
nice meeting you @flamingspaz :tada: :dancers: 

If it doesn't take you too much time, would you mind summarizing the stuff that we just talked in the Vidyo call?  Documentation FTW! :bowtie:

**Comment by ryanpitts** [comment]
@flamingspaz what's a good email address for you?

**Comment by flamingspaz** [comment]
(sorry for the late response)

@ryanpitts here's my [mozillians profile](https://mozillians.org/u/yalam96/) so I don't have to post it here :smile: 

As for a recap:
- We're going to use the master branch as production and gh-pages as dev. Merging to master will automatically deploy to S3.
- The python script can be triggered via webhook (slack bot etc) to push a commit to master, which will automatically deploy to S3.
- We won't fully cache the site because last minute changes will happen
- Ryan will shoot over the info I need to play about with getting the script going, tomorrow I'll submit a PR on both repos with the Travis files

**Comment by simonwex** [comment]
Looks like this is cranking along. Thanks so much for al your hard work, @flamingspaz, @mmmavis and @ryanpitts!

**Comment by mmmavis** [comment]
@flamingspaz thanks for the recap :+1: 

@flamingspaz @ryanpitts 
Question: if the Python script pushes to `master` branch of the `mozfest-schedule-app` directly, how does `develop` gets the latest `sessions.json`?

**Comment by flamingspaz** [comment]
@ryanpitts, should be easy enough to make it push to both branches right?

**Comment by ryanpitts** [comment]
Sure, the Python script can push to whichever branches we want, and as many as we want. Right now it is set up to _only_ push to the `gh-pages` branch, which means we get a "staging" version of the schedule app at the github.io site.

**Comment by ryanpitts** [comment]
@flamingspaz OK, just emailed you the env vars you should need. They're all freshly generated and only used for this project, so if you want to just keep using them as-is, that should be fine.

**Comment by mmmavis** [comment]
@flamingspaz 

> The python script can be triggered via webhook (slack bot etc) to push a commit to master, which will automatically deploy to S3.

Could you remind me how we can trigger the Python script?

**Comment by flamingspaz** [comment]
I'm trying to figure out a small snag with Travis on the mozfest-schedule-loader repo so it's not quite there yet, but should be very soon.

Also, master deploy is now working correctly (https://d1hjdf62ddb1ot.cloudfront.net), I've filed an [issue](https://github.com/MozillaFoundation/mofo-devops/issues/225) for an SSL certificate and I'll add the CNAME as soon as I get it.

**Comment by ryanpitts** [comment]
Ooh, nice! What triggers the master deploy?

**Comment by flamingspaz** [comment]
15 minute cron is set up to push to gh-pages, discussion about how we want to do updates on the weekend is [here](https://github.com/mozilla/mozfest-schedule-app/issues/19)

**Comment by mmmavis** [comment]
@flamingspaz staging site is looking good! thanks for setting up the cron job! just wanted to check with you - once we have the SSL certificate and CNAME set up we will be able to check out https://d1hjdf62ddb1ot.cloudfront.net on https://schedule.mozillafestival.org/ ?

**Comment by jbuck** [comment]
Yep!

**Comment by jbuck** [comment]
@mmmavis @flamingspaz This is waiting on https://github.com/mozilla/mozfest-schedule-app/pull/77 and a merge to master to ship schedule.mozillafestival.org (I did the DNS already). Feel free to ship it tomorrow when you're awake!

**Comment by flamingspaz** [comment]
I jumped the gun a bit with merging to master so I can play about with caching images/fonts for speedy refreshes.
