### ISSUE TITLE
Upgrade apps using MongoLab

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#194]
> MongoDB 3.0 is now generally available on MongoLab, so we are in the process of making it the default release version for all new MongoLab deployments. We are also taking steps to discontinue our support for MongoDB 2.4.
> To this end, on Wednesday, September 30, we will upgrade all free Sandbox databases running MongoDB 2.6 to MongoDB 3.0. In addition, we will upgrade all for-pay Shared databases running MongoDB 2.4 to MongoDB 2.6.

We should ensure there are no service disruptions when this upgrade happens

- [x] Get a list of apps that use MongoLab

- List of applications for @jbuck to upgrade
  - [x] [appmaker-integration](https://dashboard.heroku.com/apps/appmaker-integration/resources)
    - This is staging for Appmaker, so I'll just decommission this now.
  - [x] [arcane-dawn-3642](https://dashboard.heroku.com/apps/arcane-dawn-3642/resources)
    - This is something for Appmaker, so I'll just decommission this now.
  - [x] [build-webmaker-org-production](https://dashboard.heroku.com/apps/build-webmaker-org-production/resources)
    - This used to be used for storing sessions, but someone switched this over to storing session data in cookies, so this add-on can be removed.

- List of applications for @acabunoc to upgrade
  - [x] [mozscilab](https://dashboard.heroku.com/apps/mozscilab/resources)
  - [x] [abby-contrib](https://dashboard.heroku.com/apps/abby-contrib/resources)
    - to be decommissioned
  - [x] [badges-mozillascience-org](https://dashboard.heroku.com/apps/badges-mozillascience-org/resources)

**Comment by acabunoc** [comment]
@jbuck - we can delete abby-contrib. I don't seem to have permissions to do this

**Comment by acabunoc** [comment]
As per these instructions:

>You must ensure that your free Sandbox databases running 2.6 meet the upgrade requirements for 3.0 which includes a list of MongoDB 3.0-compatible drivers. If you do not upgrade your app to a 3.0-compatible driver before this upgrade, you may be unable to connect to your deployment.

I made sure mozscilab and badges-mozillascience-org were using the latest version of mongoose which should have a 3.0-compatible driver. I think we're good!

**Comment by jbuck** [comment]
We're all good :tada:
