### ISSUE TITLE
badgekit-api-sciencelab stops responding sometimes - can we heroku restart automatically?

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#196]
Occasionally, [badgekit-api-sciencelab](https://dashboard.heroku.com/apps/badgekit-api-sciencelab/resources) keeps running, but stops responding to api requests. I have to manually `heroku restart`, then everything is fine again. Is there anything we can do to automate this?

The [main page](http://badgekit-api-sciencelab.herokuapp.com/) responds with the same thing even after the api stops working.

This breaks badges.mozillascience.org when that happens. Then, it breaks the badges that embed our widget.

**Comment by jbuck** [comment]
Heroku automatically restarts dynos every 24 hours already :/

Unfortunately this is a known issue with badgekit...

**Comment by acabunoc** [comment]
so sad :( How do you deal with this on other badgekit instances?

**Comment by jbuck** [comment]
> How do you deal with this on other badgekit instances?

:wine_glass:
