### ISSUE TITLE
Run them queries on Backpack

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#199]
Number of badges validated in the past 60 days
SELECT COUNT(*) FROM badge WHERE badge.validated_on > DATE_SUB(NOW(), INTERVAL 60 DAY);

Number of users that have validated badges in the past 60 days
SELECT COUNT(DISTINCT user_id) FROM badge WHERE badge.validated_on > DATE_SUB(NOW(), INTERVAL 60 DAY);

**Comment by jbuck** [comment]
28754 & 6390, respectively

**Comment by ottonomy** [comment]
@jbuck can you run these queries again?

**Comment by ottonomy** [comment]
@jbuck can you run these queries again?

**Comment by jbuck** [comment]
@ottonomy 2016-01-25: 108315 & 15869

**Comment by ottonomy** [comment]
Thanks, @jbuck. We'll socialize these around. I'd like to have a chat soon about setting up a regular stats-reporting system. I'm collecting info right now on what additional statistics would be useful. I'll be in touch about that.
