### ISSUE TITLE
Please help redirect explorecreateshare.org links to hivenyc.org (old domain expired)

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#200]
Hi - 

The old Hive NYC blog was on the explorecreateshare.org domain, which recently expired. Therefore, there are lots of busted links. Is there an easy way to redirect to hivenyc where the content now lives?

For example:
http://explorecreateshare.org/2013/03/18/can-digital-media-move-teens-off-the-couch/ is broken
http://hivenyc.org/2013/03/18/can-digital-media-move-teens-off-the-couch/ works

Thanks!
Lainie

**Comment by ldecoursy** [comment]
Hi - checking back to see if someone can help with this?

**Comment by jbuck** [comment]
The domain name registration has lapsed so we'll need to wait for it to expire before we can register and redirect it

**Comment by ldecoursy** [comment]
Do you know how long that generally takes? Or anything I can do in the meantime? I just tried to renew it but not sure it was during the expiration grace period.

**Comment by jbuck** [comment]
It looks like whatever you did got it working again!
