### ISSUE TITLE
Transfer makes.org to Heroku and decommission AWS infrastructure

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#204]
@cadecairos already did the work to get make-valet working on staging, so we just gotta get production working and then decommission the AWS infra!

**Comment by cadecairos** [comment]
makes.org and mywebmaker.org are both on Heroku now. Staging is on the free teir, production is on a single 1x dyno ($25), and both are running heroku SSL ($20x2)

I've scaled down the staging and production autoscale groups to zero.

We'll wait 24 hours just in case any problems surface, then take destroy all the AWS resources associated with make-valet.

**Comment by jbuck** [comment]
Thanks @cadecairos !

**Comment by cadecairos** [comment]
#### Decommissioned Infrastructure

##### Auto Scale Groups

* [x] makevalet-production-as
* [x] makevalet-staging-as

##### Load Balancers

* [x] makevalet-staging
* [x] makevalet-production

##### Launch Configurations

* [x] makevalet-production-64-newrepo
* [x] makevalet-staging-64-1b
* [x] makevalet-production-64-newpuppet

##### Security groups

* [x] makevalet-ec2-sg
* [x] makevalet-ec2-sg-v

##### Keypairs

* [x] makevalet-130704
