### ISSUE TITLE
Decommission Appmaker

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#205]
We need to do the Appmaker decommissioning:

- [x] Change apps.webmaker.org to point at deprecation page
- [x] Shut down Appmaker infrastructure
- [x] Modify Github repo and readme to note that it's been decommissioned

**Comment by simonwex** [comment]
@jbuck instead of modifying the `<base>` tag in each of the makes. What do you think of us making apps.webmaker.org a static site?

**Comment by jbuck** [comment]
Yeah, we'll probably end up doing that... it's the same thing we did with Popcorn. It's just easier to get it done

**Comment by jbuck** [comment]
https://github.com/mozillafoundation/plan/issues/569

**Comment by cadecairos** [comment]
@alicoding when you're ready to get started on this, come find me and I'll get you all you need
