### ISSUE TITLE
Heroku keys for Travis

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#207]
Hey @jbuck  σ`∀´)σ

I recently hooked up https://github.com/mozilla/2015.mozillafestival.org with Travis and I used my own key(under my MoFo email account) in `.travis.yml`.  Is this how I'm supposed to do it? I guess I'm wondering if there's a standard way / the best way to do things like this across all of our projects. :grin:

**Comment by jbuck** [comment]
I think that's perfectly reasonable!

I'm also a big fan of setting up [Heroku Flow](https://blog.heroku.com/archives/2015/9/3/heroku_flow_pipelines_review_apps_and_github_sync)
