### ISSUE TITLE
blog.webmaker.org won't load

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#208]
@kevzawacki

http://blog.webmaker.org won't load - just tried on FF and Chrome.

**Comment by jbuck** [comment]
503 Service Unavailable means nobody can load it. Lets find out why!

**Comment by ldecoursy** [comment]
Thanks! I wasn't even seeing that on either browser - just blank screen...

**Comment by jbuck** [comment]
I restarted services on the box and we're back in working order :tada:

**Comment by ldecoursy** [comment]
Thank you!
