### ISSUE TITLE
Obtain domain for thimble published projects

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#209]
We've decided on a domain for published Thimble projects, so now we need to purchase it.

**Comment by jbuck** [comment]
IT is currently undergoing a change freeze until november 12, so pushing to next milestone

**Comment by jbuck** [comment]
@cadecairos I spoke to webops and they said the preferred method was to continue to register domains through them. They also suggested that we request a mark monitor account so we could register our own domains. But that's for future us!

I filed the registration bug, since I don't think you were on the thread with the domain decision: https://bugzilla.mozilla.org/show_bug.cgi?id=1229591

**Comment by jbuck** [comment]
@cadecairos also, can you create a new s3+cloudfront cloudformation for this new domain?

**Comment by cadecairos** [comment]
* Cloudfront stack created: published-mln-content-production
* A Route53 Zone was set up for thimbleprojects.org, and is configured to point and the CF dist in the cloudformation stack.
* Digicert is processing our CSR

**Comment by cadecairos** [comment]
@jbuck can we call this done?

**Comment by jbuck** [comment]
Yep, this is done
