### ISSUE TITLE
Authorize thimble.moz.o to invalidate cloudfront on deploy

### ISSUE THREAD

**Issue by sedge** [MozillaFoundation/mofo-devops#211]
Thimble needs AWS keys for [this patch](https://github.com/mozilla/thimble.webmaker.org/pull/1152) in order to allow invalidating CloudFront's edge cache. 

We'll be including them in an encrypted form using travis-ci, so if someone could PM/email/keybase me the creds I'll get right on it!

**Comment by jbuck** [comment]
@sedge and I did this today!
