### ISSUE TITLE
Host GSMA whitepaper on webmaker.org

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/mofo-devops#214]
We need to host a whitepaper written by us and the GSMA on our site so that we can link to it via our blog and in other comms. 

Tried to attach the PDF but github can't process. Will send  via email.

Suggested URL is webmaker.org/localcontent

cc: @simonwex @benrito @kevzawacki

**Comment by jbuck** [comment]
@HPaulJohnson Do you just need a place to host files? Or will there be some sort of landing page that links to the file?

**Comment by jbuck** [comment]
@HPaulJohnson As-in: if it's just a place to host the PDF, I can upload the pdf to https://stuff.webmaker.org/localcontent.pdf as soon as you email it to me

**Comment by HPaulJohnson** [comment]
Just need a place to host the PDF. I will email you the pdf.

**Comment by jbuck** [comment]
@HPaulJohnson is https://stuff.webmaker.org/whitepapers/smartphones_content_skills.pdf okay by you?

**Comment by jbuck** [comment]
@HPaulJohnson If you'd like me to rename the file, let me know somehow! Otherwise I think we're good...

**Comment by HPaulJohnson** [comment]
good to go @jbuck. we'll use a mzl.la link for sharing and blog anyway so it doesn't have to be too pretty. thanks!
