### ISSUE TITLE
Decommission Shared Webmaker Infrastructure on AWS

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#215]
Thimble, Goggles, Popcorn and Profile all shared the same instance and load balancer

Now that we've got Thimble, Goggles, and Popcorn on Heroku, and profile has been shut down, we can get rid of all the resources related to them on heroku.

##### Load balancers
- [x] butter-production
- [x] goggles-production
- [x] thimble-production
- [x] webmaker-profile2-production
- [x] butter-staging
- [x] goggles-staging
- [x] thimble-staging
- [x] webmaker-profile2-staging

##### Auto Scale Groups
- [x] wmappcluster-staging-as 
- [x] wmappcluster-production-as

##### EC2 Security Groups
- [x] wmappcluster

##### Key Pairs
- [x] wmappcluster-03-17-2015

##### Launch Configurations
- [x] wmappcluster-staging-64
- [x] wmappcluster-production-64

###### **Don't touch these yet**
- [x] butter-production-a
  - [x] Snapshotted
- [ ] thimble-production-a
  - [ ] Snapshotted
- [x] goggles-production-a
  - [x] Snapshotted
- [x] shared-staging-a
  - [x] Snapshotted

**Comment by jbuck** [comment]
Be careful with the RDS instances, you *probably* don't want to shut those
down yet...

**Comment by cadecairos** [comment]
Indeed, I hit enter on this too soon. I'm currently editing the list in the issue description, and I'll make a note of that.

**Comment by simonwex** [comment]
Related to: https://github.com/MozillaFoundation/plan/issues/569

**Comment by cadecairos** [comment]
All that's left here is thimble, so I'm going to add that to the issue to decommission old thimble.
