### ISSUE TITLE
webmaker.org SSL certificate expires on October 28 2015

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#216]
Need to renew this and apply it everywhere it's being used

**Comment by cadecairos** [comment]
this seems important :P

**Comment by jbuck** [comment]
Current domains listed in DNS:

* webmaker.org
* api.webmaker.org
* apps.webmaker.org
* beta.webmaker.org
* blog.webmaker.org
* build.webmaker.org
* discourse.webmaker.org
* events.webmaker.org
* goggles.webmaker.org
* id.webmaker.org
* login.webmaker.org
* makeapi.webmaker.org
* popcorn.webmaker.org
* stuff.webmaker.org
* thimble.webmaker.org
* www.webmaker.org

**Comment by jbuck** [comment]
Cert has been renewed

**Comment by jbuck** [comment]
Rotated certs:

**AWS**
- [x] mofo-everything
- [x] mofo-projects

**Heroku**
- [ ]
