### ISSUE TITLE
Move fundraising.mozilla.org to Heroku

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#217]
Inspired by [this article](http://substrakt.co.uk/scaling-wordpress-with-hhvm-on-heroku/) I think we'd all be significantly happier if we ran Wordpress on Heroku instead of EC2. What would it take to do this?

**Comment by jbuck** [comment]
And specifically, I think we'll use [heroku-wp](https://github.com/xyu/heroku-wp)

**Comment by simonwex** [comment]
`/subscribe`

**Comment by jbuck** [comment]
@simonwex ![screenshot 2015-11-18 13 07 06](https://cloud.githubusercontent.com/assets/578466/11249547/7c220fd8-8df5-11e5-8b72-f4ae9ee034a4.png)

**Comment by mmmavis** [comment]
can't wait to see this happen :joy:

**Comment by jbuck** [comment]
I moved this to WPEngine instead.
