### ISSUE TITLE
Mozillascience.org is down

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#219]
Works on the heroku side: http://mozscilab.herokuapp.com/

So I'm very confused. Help, @jbuck?

http://mozillascience.org/

**Comment by acabunoc** [comment]
oh! I think http://mozillascience.org stopped redirecting to www.mozillascience.org (which is *not* down)

**Comment by jbuck** [comment]
Ah, it seems the http-helper is not being very helpful right now. I've setup the DNS for mozillascience.org to point at the CDN directly instead of a redirect.
