### ISSUE TITLE
Too Many Heroku Apps

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#22]
we can't create anymore apps because we've hit an artificial cap of 100.

we should either:
a) kill old apps or 
b) contact Heroku and ask for the cap to be removed (maybe they'll do it at no charge since many of our apps generate revenue for them in some way)

**Comment by jdotpz** [comment]
Since I have very little visibility into what everyone is doing on Heroku, I'm opting for b.  I've opened https://help.heroku.com/tickets/214567 for this issue.

**Comment by davidascher** [comment]
We can actually easily trim that list, so we can and should do a) as well.
/cc @simonwex.

**Comment by jdotpz** [comment]
That would be great @davidascher .  Moving forward, it might be beneficial to remind devs that with great power comes great responsibility and all that. :)  (aka, clean up what you host and don't need any longer).

Perhaps a quick spreadsheet which documents owners/appnames could be useful?

In the meantime, our limit is up to 200 apps.

**Comment by cadecairos** [comment]
:+1: nice.
