### ISSUE TITLE
SSL certificate for schedule.mozillafestival.org

### ISSUE THREAD

**Issue by flamingspaz** [MozillaFoundation/mofo-devops#225]
We need an SSL certificate for schedule.mozillafestival.org, if possible added to AWS for me!

**Comment by jbuck** [comment]
@flamingspaz I've uploaded the certificate to AWS, in the mofo-projects account. I know this is not the account you created the CloudFormation distribution in. Would you mind recreating it in the mofo-projects account?

**Comment by flamingspaz** [comment]
Sure, but I don't think I have access to that account. Mind shooting some creds my way?

https://keybase.io/yousefalam

**Comment by jbuck** [comment]
@flamingspaz Do you think you'll be able to get to this today? If not, let me know!

**Comment by flamingspaz** [comment]
Should have it up in the next hour
