### ISSUE TITLE
Get DNS, SSL, etc for X-Ray Goggles relaunch

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#228]
- [x] Obtain SSL certificate
- [x] Make sure Heroku is configured correctly (dynos, app name, etc)
- [x] Obtain DNS
  - @cadecairos file a bug like https://bugzilla.mozilla.org/show_bug.cgi?id=1221736 once everything is ready in terms of Heroku using the [IT Request form](https://bugzilla.mozilla.org/enter_bug.cgi?product=mozilla.org&format=itrequest)
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1230632

**Comment by Pomax** [comment]
namewise: goggles.mozilla.org = yey. We don't have any metrics on usage so I don't know if setting up CDN immediately makes sense. Let's assume we don't need it for now?

**Comment by xmatthewx** [comment]
What's the status on this? Seems like the last blocker to removing beta from beta.webmaker.org. Thanks!

**Comment by jbuck** [comment]
No progress, been busy with EOY work. I'll get @cadecairos to tackle this next week

**Comment by jbuck** [comment]
Okay, SSL certificate generated

**Comment by Pomax** [comment]
I thought we had the first and third points already, too: it'll be goggles.mozilla.org, and the heroku instances are in the [goggles pipeline](https://dashboard.heroku.com/pipelines/72072a67-e727-44d2-ba82-893c34ebce4a)

**Comment by Pomax** [comment]
also crosslinking to https://github.com/mozilla/goggles.webmaker.org/issues/251 so that can close when this closes

**Comment by jbuck** [comment]
Need to complete an [RRA](https://bugzilla.mozilla.org/show_bug.cgi?id=1230666) first

**Comment by Pomax** [comment]
can we add a few more checkboxes to tick off? Right now the only thing that this issue claims is still pending is DNS clearance, which is not quite right =)

**Comment by cadecairos** [comment]
All done!

**Comment by Pomax** [comment]
\o/
