### ISSUE TITLE
Refresh http://schedule.mozillafestival.org/

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#229]
schedule.mozillafestival.org on https (https://schedule.mozillafestival.org/) is looking great! Thanks for your help @flamingspaz @jbuck :tada: :bowtie: 

http://schedule.mozillafestival.org/ (http) still has last year's schedule. I wonder if we can have that refreshed as well?

**Comment by flamingspaz** [comment]
On my end it's redirecting me to https. Try force refreshing?

**Comment by jbuck** [comment]
Yeah, I think it's just your browser cache

**Comment by mmmavis** [comment]
Darn the browser cache! I have force refreshed many many times. Duh. But on private window it's working fine!
