### ISSUE TITLE
webmaker-metrics died on build

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-devops#23]
I made a [small change](https://github.com/mozilla/webmaker-metrics/commit/357cf0f47a015486f0d9b628d06ee890b741f4c6) to webmaker-metrics this morning

The [build](https://jenkins.mofoprod.net/job/mofometrics/13/) ran, but the [staging app](http://metrics.mofostaging.net/) died and I'm no longer able to SSH into staging or prod to try and kick it manually (terminal just sits with the wheel spinning and gives no output).

I tried [re-running the build via Jenkins](https://jenkins.mofoprod.net/job/mofometrics/14/) to see if that would kick it, which gave less errors in the console output, but didn't bring the app back to life.

**Comment by jdotpz** [comment]
I got Adam into the app, and it required a quick kick to restart.  It's back up.
The Jenkins logs looked A-ok, the bits failing were ok to fail (the fabric kick/version check).
