### ISSUE TITLE
Get cloudfront invalidation credentials for bramble staging

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#230]
sez @sedge

**Comment by sedge** [comment]
This will allow us to set up the ability to invalidate staging thimble with one command.

**Comment by sedge** [comment]
Blocking https://github.com/mozilla/thimble.webmaker.org/issues/1132

**Comment by jbuck** [comment]
Doing this will require temporarily disabling the staging thimble CDN. Just gonna do this now~

**Comment by jbuck** [comment]
@sedge do you have keybase so I can send the credentials to you?

**Comment by sedge** [comment]
@jbuck Yup: https://keybase.io/sedge

I'm happy to do it. Alternatively, you could fill in [these three env vars](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/env.dist#L131-L138) on the staging app with those values. Whichever is easier for you!

**Comment by jbuck** [comment]
@sedge 

-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQIMAy/xV9/90sR1AQ//XBnfSrMtcTE0vcXh95le3IrsXSYxwf6UaYaahGJYhVEO
KK3Ps9psUDEobBi7aeTSomR19sRJ3GWJ+ZNUhUBZPxjKmaVIF1A06WsaE1Q2FIEX
HNDH3HHYZKiZfyioiiCeEC1uQJFfBNIRR5O2Q9DR4HnZ2XanS0+lmzHP2Zz6Mpag
EeVCsU4+bYoo1SUaDT0VMlUrwp+ky1yUVSFG7iMdSg5c7fBDVBDaW0mtQ5D8nq85
ovIFPzXal6qgLev1bzlD85q05h1b7ut1Efn0IG33TVPVNYKmuKkJuiCASp1Ej7Bu
poZWGSRTb19waPWg56vyKkqgmMubS6DxmUh0hmhgRicDILGeW3cWBA4xRgclqXkG
noJOcdcXJY5iCaRAgV+jEE+UJkWVCcDiMQqWICIxP1FB+PBwRD/s8rfRYwxHnA2a
+1hLNy5ZHEeSk0MrEzsVJl4snmEvkpsw5pw2Nd02RkOMH9FC5VTD135o5URcM9Ra
dLQaXgs0gKfG5pfEi+XKcaYS7QZ/IAJujkAFEPZgo7j7D7qjkPd1E6nfjmMAoBrF
RCaT02nhoPCLto7BXau0ZsQLjUjnAauSMEDoHl39yYL6w1CffRM1t8EVnUkrlQ74
5Ty1Yti5ouF7eS/KC1rldv/tAJ8OX1ik42GVj1hCuqLlPULZqWyKqF5So7wpFcHS
swGZLU0C9n2+FIDoj3F8ejglkrgR9m7BY+TdaWe5WdsZdtmi4XTHbZhL/09fX4S8
JCQdU534QElzsyyKdItUn/8HNciF7d/+7fVT7B97GioqKO873QcKxsER/FD8uW+t
p3ZE98jKxrjy3dwOovP0Mrkkld1UTlIbldQ9g3ITYHlSdMhNGdInB2ZZjWikbMZr
luwvwonI4kkAygIXrGYaWuwuZLkllbUfOqrGuYr2RGosOs4r
=cwvy
-----END PGP MESSAGE-----
