### ISSUE TITLE
Migrate blog.webmaker.org to WPEngine

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#234]
Looks like https://blog.webmaker.org is down again!

cc @kevzawacki @omnignorant

**Comment by simonwex** [comment]
@jbuck can we add monitoring to this? Do you know what's causing it?

**Comment by jbuck** [comment]
I have monitoring on the site so I know when it goes down, but it restores itself after a few minutes. I haven't investigated the cause of this issue.

**Comment by jbuck** [comment]
Much like #217 we should look at migrating this over to Heroku

**Comment by simonwex** [comment]
:+1:

**Comment by simonwex** [comment]
@jbuck is there any special customization that would stop us from using a hosted service for this blog?

**Comment by ldecoursy** [comment]
Checking back on this - anything else we need to do here?
