### ISSUE TITLE
Metrics SSL error

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#236]
https://metrics.webmaker.org/dashboard/product-kpis

<img width="832" alt="screenshot 2015-12-01 16 41 50" src="https://cloud.githubusercontent.com/assets/53411/11515447/fa114dc2-984b-11e5-8403-ecd9bc03f661.png">

**Comment by jbuck** [comment]
This is a known issue - when we re-issued the certificate for *.webmaker.org I asked @adamlofting about metrics.webmaker.org and he said it wouldn't likely be used going forward so we didn't need to keep the certificate. If you want, you can click through the certificate warning to see the metrics content.
