### ISSUE TITLE
Add redirect fro /me to teach site.

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#238]
301 
http(s)://webmaker.org/me -> https://teach.mozilla.org/me/

**Comment by simonwex** [comment]
Hey, @cadecairos do you have time to do this?

**Comment by simonwex** [comment]
https://github.com/MozillaFoundation/plan/issues/561

**Comment by cadecairos** [comment]
I though I had already - did we not :ship: it? 

https://github.com/mozilla/webmaker-browser/pull/228/files

**Comment by simonwex** [comment]
I suppose not. Mind making it happen?

**Comment by cadecairos** [comment]
not at all!
