### ISSUE TITLE
Switch beta.webmaker.org to webmaker.org

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#239]
To wrap Webmaker in 2015 as we shift focus in 2016, it'd be great to fully retire the old website and pull beta out of the URL on the new site. 

 - Blocked by Goggles launch https://github.com/MozillaFoundation/plan/issues/554
 - Blocked by /me redirect https://github.com/MozillaFoundation/mofo-devops/issues/238

To things to watch out for: 
 - Make sure that existing Webmaker project links redirect. ex: https://beta.webmaker.org/#/project?user=421495&project=44682 
 - Avoid an infinite redirect loop on Legal link in footer. Currently goes from https://webmaker.org/#/legal to https://beta.webmaker.org/#/legal
 - Make sure rendering for Thumbnail service doesn't break. 

Thanks!

**Comment by xmatthewx** [comment]
This should be unblocked and ready to go now. See planning ticket https://github.com/MozillaFoundation/plan/issues/631

**Comment by Pomax** [comment]
goggles launched, but currently users will still be using the library as it lives goggles.webmaker.org, so we'll need to keep that alive for a while, to give people time to transition to goggles.mozilla.org -- that shouldn't interfere with any other switchovers though

**Comment by jbuck** [comment]
https://github.com/mozillafoundation/plan/issues/569

**Comment by Pomax** [comment]
@jbuck why does that seem to suggest goggles is getting completely turned off? Or am I misinterpreting the "deprecated" notes?

**Comment by jbuck** [comment]
@Pomax I suppose it could be interpreted in multiple ways!

**Comment by jbuck** [comment]
https://webmaker.org is now pointed at beta. Unfortunately I don't think I can setup a redirect from beta.wm.o -> webmaker.org because of all the redirects we had in the previous direction...

**Comment by xmatthewx** [comment]
:open_mouth: Lookin good. Site works as expected. Link to legal is fine. Projects rendering is hunky dory. Nothing seems broken with or without beta in the URL. 

While a redirect away from beta would be nice, we can probably survive without if beta continues to mirror things. Did we remove the wm -> beta redirects? Curious why the reverse is a problem.

**Comment by jbuck** [comment]
@xmatthewx Many of the wm -> beta redirects were 301 Permanent redirects which are cached by users browsers forever. If I setup a beta -> wm redirect then the browser would detect that it can't complete the redirect, and the only fix is the clear the browser cache: https://support.apple.com/en-ca/HT203370

**Comment by jbuck** [comment]
I've modified api.wm.o to point at webmaker.org for thumbnail generation

**Comment by jbuck** [comment]
I think this is as far as we should go for now.
