### ISSUE TITLE
Add logrotate to cron on EC2 instances for all log files

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#240]
1. Rotate the log file when file size reaches a specific size
2. Continue to write the log information to the newly created file after rotating the old log file
3. Compress the rotated log files
4. Specify compression option for the rotated log files
5. Rotate the old log files with the date in the filename
6. Remove older rotated log files

**Comment by simonwex** [comment]
Related to #110

**Comment by cadecairos** [comment]
All mofoprod/mofostaging and openbadges servers I touched in #285 either had logrotate enabled, were S3 sites or were on Heroku.

**Comment by simonwex** [comment]
You're absolutely killing it this week, @cadecairos. Nice work!

**Comment by cadecairos** [comment]
Closing this, based on my comment above
