### ISSUE TITLE
Update InfoSec AWS auditing role

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#242]
https://bugzilla.mozilla.org/show_bug.cgi?id=1232126

**Comment by jbuck** [comment]
I tried to do this, but both stacks failed to create.

**Comment by gene1wood** [comment]
I've enabled all the accounts in our systems (them not being enable is what caused the previous failure). Go ahead and try deploying the stacks again in each account and it should work fine.

**Comment by cadecairos** [comment]
Audit and Incident response roles + Cloudformation stacks have been successfully created in: 
 
 - [x]  mofo-ops
 - [x]  mofo-community
 - [x]  mofo-projects
 - [x]  mofo-everything
 - [x]  mofo-sandbox
 - [x]  mofo-secure
 - [x] mozilla-labs
