### ISSUE TITLE
Figure out when Thimble content is moving

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#243]

**Comment by simonwex** [comment]
I think we should schedule this for early in the new-year.

**Comment by gideonthomas** [comment]
The goal is to have it done by Jan 29th per https://github.com/mozilla/thimble.webmaker.org/milestones/Jan%2029%20Heartbeat%20-%20Erase%20Technical%20Debt

**Comment by simonwex** [comment]
Closing this out, as we have a technical debt milestone to track this. When we have an actionable devops ticket, will recreate.
