### ISSUE TITLE
Obtain a SANS cert for mozillafoundation.org

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#246]
cc/ @simonwex @OpenMatt 

We will probably want to transfer ownership of the domain to Mozilla, I think.

A wildcard cert will let us host apps on subdomains of build.mofo using the same cert.

EDIT:

We're going to host the new things at:
* build.mozillafoundation.org
* book.mozillafoundation.org
* chat.mozillafoundation.org

**Comment by simonwex** [comment]
We *must* transfer ownership in order to purchase the cert.

**Comment by OpenMatt** [comment]
@cadecairos ok. how do we transfer ownership? You have my credentials, I believe -- so please push ahead with whatever's required.

**Comment by cadecairos** [comment]
@OpenMatt Okay, I'll initiate the transfer process.

@simonwex Do you know if there's a formal process for transferring ownership to Mozilla?

**Comment by jbuck** [comment]
We can't transfer a domain that's less than 60 days old

**Comment by cadecairos** [comment]
Certs acquired, deployed to Heroku.

DNS updated, waiting on SSL endpoints to be set up on Heroku's side.

**Comment by jbuck** [comment]
@cadecairos did this!
