### ISSUE TITLE
Recover Blitline credentials

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#248]
MoFo tools utilize Blitline for its thumbnail screenshot service. It appears to be down, but @cadecairos does not have credentials to the account. It's critical that we recover these. cc @simonwex

**Comment by cadecairos** [comment]
I've made contact w/ Jon and gotten access.

**Comment by simonwex** [comment]
@cadecairos could you make sure the details are in the vault?
