### ISSUE TITLE
create a new heroku instance with an id.wmo for external contractor use

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#249]
In order to have one of our external contracts put their work on heroku for live testing, a new copy of id.wmo running on a heroku instance that they can be granted access to is needed.

If we can just copy the staging instance with new env vars so we don't expose any of our own staging cookie secrets etc, this should be a relatively quick job

**Comment by simonwex** [comment]
@cadecairos I'll just heroku fork the staging app. Is there anything I should be careful about scrubbing?

**Comment by cadecairos** [comment]
We should truncate the tables and insert new credentials for the contractors.

**Comment by jbuck** [comment]
@cadecairos and @Pomax did this!
