### ISSUE TITLE
Ship new advocacy.mozilla.org site

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#252]
I have been working on this here: https://github.com/ScottDowne/advocacy.mozilla.org

Looks like we'll want to ship this via Heroku, and not gh-pages.

**Comment by jbuck** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1244778 is needed for the DNS change, and I think that's it.

**Comment by jbuck** [comment]
DNS has been updated!
