### ISSUE TITLE
Need access to customize welcome/start guide for teach.mozilla.org Discourse forum

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#254]
In admin settings under "Other," there is currently an option selected to email all new users a welcome note and start guide, however we can't seem to find the copy to edit/customize it. 

@simonwex offered to help!

cc @kgorr

**Comment by ldecoursy** [comment]
Also per Abigail, we should check what email address this comes from (Mozilla vs. Discourse)

**Comment by flamingspaz** [comment]
You can change that text in Admin > Customize tab > Text Content > New User guidance. The email comes from discourse (teachtheweb@) but the name that comes up is the one listed as "site contact username" (currently @ldecoursy )

**Comment by ldecoursy** [comment]
Thanks @flamingspaz!  @kgorr Can you see if you can access this in Discourse and make recommendations on if/how we can customize this further? I'll close this ticket here and can open another one in our repo to update the copy there.

**Comment by ldecoursy** [comment]
@simonwex OK for me to close?

**Comment by KGorr** [comment]
@ldecoursy, just checked and I can access as @flamingspaz directed (thank you!). Will put the copy and suggested edits onto the new ticket once it's live. Thanks!
