### ISSUE TITLE
Add TOS and Privacy Policy to Discourse footer

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#255]
The link to the TOS is buried at http://discourse.webmaker.org

Can we add a footer that links to the current Webmaker/Mozilla Learning TOS https://beta.webmaker.org/#/legal?_k=8svxtt and Mozilla Privacy Policy https://www.mozilla.org/en-US/privacy/websites/  (These are the same links that live on the teach.mozilla.org footer)

@simonwex to assign

cc @hannahkane @kgorr

**Comment by simonwex** [comment]
@flamingspaz what's the best way for us to make updates to the template for things like this?

**Comment by flamingspaz** [comment]
There's an option to add custom HTML headers/footers which would be what you'd want. As long as you make it a simple layout you shouldn't break other parts of the theme (mobile).

You can find it in Admin > Customize > CSS/HTML. I'd recommend playing about on https://discourse-ttw.mofostaging.net/ before adding into prod.

**Comment by ldecoursy** [comment]
Thanks @flamingspaz!
@simonwex Is this something someone on your team can still help with?

**Comment by ldecoursy** [comment]
Per legal, since there is little Mozilla branding on the site, we need to include “Mozilla” in the footer-- e.g., “Mozilla Privacy Notice” and “Mozilla Learning Terms of Use.”

**Comment by ldecoursy** [comment]
Ping @simonwex

**Comment by simonwex** [comment]
Hey @ldecoursy we're a bit behind because of PTO & illness. I'll make sure we prioritize it next week.

**Comment by ldecoursy** [comment]
@simonwex checking back, noticed the new name of this milestone. Is this doable?

**Comment by flamingspaz** [comment]
@simonwex if this is just adding HTML to the footer do you want me to take it?

**Comment by flamingspaz** [comment]
@ldecoursy I've added the links to the bottom of https://discourse-ttw.mofostaging.net/, are they big enough? Also, do you want to drop the "beta" from the ToS URL as I think they should be the same now?

**Comment by ldecoursy** [comment]
Thanks @flamingspaz !

Those links work for me - also the beta should be gone and just link here: https://webmaker.org/#/legal?_k=8svxtt

**Comment by flamingspaz** [comment]
cool, I got rid of it. Do you want me to move it on to the main website? We can always change the way it looks after the website has a custom theme/branding.

**Comment by ldecoursy** [comment]
Yes @flamingspaz thank you! :)

**Comment by flamingspaz** [comment]
Okay, I made some small changes and put them on the main website.
You can edit the "tos url" and "privacy policy url" Discourse settings to change the links and it'll automatically update the footer.

**Comment by simonwex** [comment]
\o/!!!

Thanks, @flamingspaz!
