### ISSUE TITLE
Transfer hivenyc.org blog hosting to Mozilla

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#256]
Currently hosted on Go Daddy and it expires on Feb. 8

@jbuck, hoping you can help!

**Comment by jvallera** [comment]
Let us know how @jazoulai and I can help

**Comment by jbuck** [comment]
@ldecoursy One thing I'd do right now is cancel the renewal, because I think the notice said that they process it on the week before it expires

**Comment by jbuck** [comment]
@ldecoursy could you create an wordpress admin account for me on hivenyc.org ? I'll need to export all of the data on the site. I'll probably also need file access if that's easy for you to setup?

**Comment by jbuck** [comment]
@simonwex I'd like to use a wordpress hosting provider for this. I was thinking a professional plan from WPEngine. Thoughts?

**Comment by ldecoursy** [comment]
@jbuck Just created an admin account for you, let me know if you don't receive the password via email. Not sure how to give file access - @jazoulai can you help with that?

**Comment by ldecoursy** [comment]
Also just cancelled the renewal - please let me know if for any reason this won't be done before the expiration.

**Comment by jbuck** [comment]
@ldecoursy okay, I got my sign-in working

**Comment by jbuck** [comment]
@jazoulai The reason I need file access is to download all of the pictures from http://hivenyc.org/wp-admin/upload.php

**Comment by jbuck** [comment]
Ah nice, WPEngine has a built-in migration checklist: https://wpengine.com/support/migration-process/

**Comment by jazoulai** [comment]
@jbuck what's the username your using on Wordpress? I can't seem to find your user.

**Comment by jbuck** [comment]
@jazoulai it's jbuck

**Comment by jazoulai** [comment]
sorry yes, don't know why it wasn't coming up before. You have full admin privileges. Are you being denied access to something?

**Comment by jbuck** [comment]
@jazoulai there are two things I need to backup: the database, and the files. It's possible to backup the database from the wp-admin console, but the files need to be backed up by copying them somewhere else.

Looking at [Godaddy's documentation](https://ca.godaddy.com/help/managed-wordpress-sftp-ssh-and-phpmyadmin-credentials-8940), you'll need to get the sFTP credentials and then email them to me.

**Comment by jbuck** [comment]
@ldecoursy actually, I think you might be the only person who can send me the sftp credentials. Let me know if you want to vidyo it!

**Comment by ldecoursy** [comment]
@jbuck Can you do anytime within the next hour, or sometime tomorrow?

**Comment by jbuck** [comment]
@ldecoursy had a quick chat just now. She was able to generate FTP credentials for me, so I've currently backing up the Wordpress data. We also decided to change the renewal to a monthly option, giving us more time if we're not able to complete the migration this week. 

@simonwex and I will figure out what our options for Wordpress hosting are tomorrow on our standup and report back here.

**Comment by jbuck** [comment]
@ldecoursy Okay, we filed https://github.com/MozillaFoundation/mofo-devops/issues/257 to investigate suitable Wordpress hosts. We're looking for one that would suit hivenyc.org as well as our CMS project.

**Comment by ldecoursy** [comment]
@jbuck I see #257 is now closed. Any word on this one before we pay for another month with GoDaddy?

**Comment by jbuck** [comment]
I think I have a decent migration strategy here. Let me see what I can do!

**Comment by jbuck** [comment]
I've started a migration to http://hivenyc.wpengine.com . I'll update this thread when it's done!

**Comment by jbuck** [comment]
@ldecoursy wanna take a quick peek around http://hivenyc.wpengine.com/ and make sure everything looks good?

**Comment by jazoulai** [comment]
@jbuck @ldecoursy should I wait to post new content until the migration is
complete?

Joey
____________________
Community Coordinator, Hive NYC Learning Network, Mozilla
*Follow HIVE NYC * Twitter <https://twitter.com/hivelearningnyc>  |
Instagram <https://www.instagram.com/hivelearningnyc/>  |  Facebook
<https://www.facebook.com/HiveLearningNYC/>  |  Website
<http://hivenyc.org/>

**Comment by jbuck** [comment]
@jazoulai I can run another migration (and it'll be much quicker) so feel free to post content! I'll let you know when I'm transitioning the DNS.

**Comment by ldecoursy** [comment]
Looks good to me at quick glance. @jazoulai can you also poke around the link above and see if everything seems like it's working?

**Comment by jazoulai** [comment]
Everything looks good on my end @ldecoursy <https://github.com/ldecoursy>
 @jbuck!

Joey
____________________
Community Coordinator, Hive NYC Learning Network, Mozilla
*Follow HIVE NYC * Twitter <https://twitter.com/hivelearningnyc>  |
Instagram <https://www.instagram.com/hivelearningnyc/>  |  Facebook
<https://www.facebook.com/HiveLearningNYC/>  |  Website
<http://hivenyc.org/>

**Comment by jbuck** [comment]
old IP is 54.83.28.74
