### ISSUE TITLE
Research Wordpress hosting

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#257]
* Must support REST API (This isn't necessarily WP-API extension, but the API that Calypso uses)
  *  http://v2.wp-api.org/changes-beta-1.html
 * Must support custom content types
 * Must be able to install custom plugins

**Comment by jbuck** [comment]
* WPEngine
  * They love the REST API, they even [wrote a book](http://hs.wpengine.com/torque-wordpress-rest-api-ebook-blog) about it.
  * They support custom content types
  * They have a [list of disallowed plugins](https://wpengine.com/support/disallowed-plugins/)
