### ISSUE TITLE
Force advocacy.mozilla.org to SSL

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#261]
https://advocacy.mozilla.org/ has an active cert, but hosting over http is still allowed. Especially considering our work around encryption campaign, we shouldn't allow non-secure connections.

**Comment by simonwex** [comment]
https://github.com/mozilla/advocacy.mozilla.org/pull/52

**Comment by simonwex** [comment]
Patch landed, need to set config var on staging + production

**Comment by HPaulJohnson** [comment]
@simonwex just confirming this will happen in time for the new /encrypt landing page to go live tomorrow a.m. (2/10 @ 10 am)

**Comment by alicoding** [comment]
done :)

http://advocacy.mozilla.org should now redirect you to https://advocacy.mozilla.org

**Comment by simonwex** [comment]
And FYI @HPaulJohnson we should always be taking the care to share `https://...` links, so the above fix isn't required.

**Comment by HPaulJohnson** [comment]
yep, good reminder @simonwex 

thanks, all!

**Comment by simonwex** [comment]
Confirmed:

```
curl -v http://advocacy.mozilla.org
* Rebuilt URL to: http://advocacy.mozilla.org/
*   Trying 50.16.187.95...
* Connected to advocacy.mozilla.org (50.16.187.95) port 80 (#0)
> GET / HTTP/1.1
> Host: advocacy.mozilla.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
...
```
