### ISSUE TITLE
Counter doesn't load on http://fundraising.mozilla.org/ anymore

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#262]
It's because I shut down the transaction service in #250 and didn't setup a static replacement.

**Comment by jbuck** [comment]
Right now we have a our fundraising blog and Firefox add-on that poll this arbitrary cloudfront distribution for data. I propose we:

1) purchase a new domain that we can change what it's pointing at more easily
2) setup static files there
3) change blog and add-on to point at new url

@cadecairos thoughts?

**Comment by cadecairos** [comment]
Could we skip the new domain name and just set up a static s3 website to serve the properly formatted JSON?

**Comment by jbuck** [comment]
Waiting for CF distribution to update now
