### ISSUE TITLE
Look into Mattermost + LDAP

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#263]
How hard would this be? What do we need from MozIT?

**Comment by jbuck** [comment]
We can file a service now request for this:  Infra Services -> Operations -> SSO Federation Request

**Comment by cadecairos** [comment]
Looks like the LDAP login implementation here supports Gitlab specifically, and Github and Github Enterprise ([only because the API is similar](http://docs.mattermost.com/deployment/sso-gitlab.html#single-sign-on-configuration))

Do you know if our Mozilla LDAP is also similar?

**Comment by jbuck** [comment]
I suspect you'll get access through Okta, but I'd file a Service Now
request to find out

**Comment by cadecairos** [comment]
I suspect this is not possible without code changes, since the mattermost Single Sign On configuration happens within the gitlab configuration settings.

@simonwex What do you suggest we do with this issue?

**Comment by simonwex** [comment]
Closing, we can revisit if it becomes important.
