### ISSUE TITLE
Rehost netgainpartnership.org site on our own kit

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#265]
Repo here:
https://github.com/4site-interactive-studios/netgain

**Comment by jbuck** [comment]
We've exceeded our bandwidth limit, so even more critical now.

**Comment by jbuck** [comment]
http://netgainpartner.wpengine.com/ needs some manual QA by Sam B

**Comment by jbuck** [comment]
DNS has been switched, just waiting for WPE to add the SSL certificate

**Comment by jbuck** [comment]
SSL has been enabled
