### ISSUE TITLE
Turn off or redirect welcome.webmaker.org

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/mofo-devops#268]
Currently https://welcome.webmaker.org doesn't have cert and you have to allow/add exception to view the page. As part of this ticket https://github.com/MozillaFoundation/plan/issues/668 can we remove this subdomain or redirect it somewhere?

**Comment by jbuck** [comment]
I agree, thanks for pointing this out Ali!

**Comment by jbuck** [comment]
Deleted from DNS
