### ISSUE TITLE
Create hosted zone for netgainchallenge.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#269]
- [x] Provide Simon the nameserver addresses
 - [x] CNAME www.NetGainChallenge.org to netgainpartnership.org
 - [x] Add redirects to WPEngine

**Comment by jbuck** [comment]
Nameservers:

* ns-1114.awsdns-11.org
* ns-608.awsdns-12.net
* ns-1972.awsdns-54.co.uk
* ns-327.awsdns-40.com.
