### ISSUE TITLE
Discourse login not working

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#271]
Login at discourse.webmaker.org is not working - a pop-up shows up but it's blank - just tried in Chrome and Safari. 

We have a training tomorrow and need participants to have access to Discourse.

**Comment by ldecoursy** [comment]
Also someone just tweeted us about it https://twitter.com/_Coragem/status/701992105607110657

**Comment by cadecairos** [comment]
I'm seeing this error in the JS console

`TypeError: Discourse.LoginView is undefined`

**Comment by flamingspaz** [comment]
I know what's up with this, I'll fix it when I get home.

**Comment by cadecairos** [comment]
@flamingspaz Awesome, thanks!

**Comment by flamingspaz** [comment]
This should be fixed now. There was a bug in the persona plugin which was fixed a while ago but I didn't think this Discourse instance was using it.
