### ISSUE TITLE
Get our version of Calypso live

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#275]
https://github.com/mozilla/wp-calypso is our fork of Calypso (a WordPress editing interface written in React). It's totally on early WIP state but let's get it live somewhere first so we can share it to the stateholders!

No URL preference though. Maybe `editor` or `content-editor` will work? (on `heroku` or `mofostaging`?)

/cc @wex

**Comment by mmmavis** [comment]
Actually, let me see if I just push it to heroku myself first :smile:

**Comment by cadecairos** [comment]
I've got a DockerFile that is Heroku compatible, and builds+runs Calypso. I'm working on getting the config working right now.

I'm going to file a bug on wp-calypso to see if the Automattic team can provide an example or guide to a production config that doesn't rely on wordpress.com

**Comment by cadecairos** [comment]
TODO: edit my wp-calypso bug https://github.com/Automattic/wp-calypso/issues/4049

**Comment by cadecairos** [comment]
bumping to next heartbeat, due to deployment restrictions in Calypso and the WP API

**Comment by cadecairos** [comment]
I've just successfully logged into Calypso locally using plain old OAuth.

I now need to drop some things into configuration vars... and then.. profit?
