### ISSUE TITLE
Run openbadges backpack usage queries

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#276]
This is a follow-up to #199, but slightly different:

> The queries we had previously defined gave us 2 figures for the last 60 days. Could we run a query on these two items (number of badges and number of accounts) for 30 day intervals all the way back to the beginning to put into a table?

The queries will need to be tweaked, but this should be doable.

Once we've done this, email them to Doug, Nate, and Oren.

**Comment by jbuck** [comment]
I suggested that we run a daily roll-up, that way Doug can easily change the interval as necessary.

**Comment by cadecairos** [comment]
Do we run these against the badgekit or badgekit-api DB?

**Comment by jbuck** [comment]
Neither! We run it against the openbadges-db. And we'll need to tweak the query too.

**Comment by cadecairos** [comment]
I think this query does the trick:

``` sql
SELECT 
    CAST(badge.validated_on AS DATE) AS date,
    COUNT(*) AS validate_badge_count,
    COUNT(DISTINCT user_id) as active_users_count
FROM
    badge
GROUP BY date;
```
