### ISSUE TITLE
Make a note to not shutdown the beta webmaker subdomain

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#277]
Add a note in your tracking docs to let sleeping dogs lie :sleeping: :dog:  to avoid deletion during a future spring cleaning. 

Given resources, use of `beta` might remain in the app for a while. I've filed a bug to update the use in sharing links. This also impacts old thumbnails. Those are two likely vulnerable areas, though there may be others.

**Comment by simonwex** [comment]
Done! (This won't show up in our spring cleaning lsit)
