### ISSUE TITLE
Redirect webmak.es to apps.webmaker.org

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#278]
i-4ce88260

**Comment by jbuck** [comment]
It'll probably be something like https://github.com/mozilla/mofo_system_configurations/blob/master/modules/apps/templates/makerly/vhost.erb but we'll need to figure out what the actual S3 bucket is.

**Comment by cadecairos** [comment]
```
server {
  listen 80;

  server_name "~^(.+)\.webmak\.es$";
  set $subdomain $1;

  location = / {
    rewrite ^ /app redirect;
  }

  location / {
    rewrite ^ /flathead/$subdomain$request_uri? break;
    proxy_pass http://com.mozillalabs.appmaker.s3.amazonaws.com;
  }
}

```

**Comment by cadecairos** [comment]
This is almost done, but there's an issues redirecting `webmak.es` to `www.webmak.es` that I need to debug.

**Comment by cadecairos** [comment]
This was fixed by adding `webmak.es` to the list of alternate domains in the cloudfront distribution.

Webmak.es is no more.
