### ISSUE TITLE
People can't sign into thimble

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-devops#279]
See https://github.com/mozilla/thimble.mozilla.org/issues/1438#issuecomment-192944321

**Comment by davidascher** [comment]
<img width="1148" alt="screenshot 2016-03-06 12 19 34" src="https://cloud.githubusercontent.com/assets/51278/13556722/ba88cbae-e395-11e5-8575-55c3c684bdae.png">

**Comment by davidascher** [comment]
@jbuck can comment w/ some more details later, but IRC logs:

> <jbuck> none of the login.wm.o instances appear to be healthy
> 12:27 PM <jbuck> that's a problem
> 12:28 PM <davida> (possibly consequence of DNS changes? some cached lookups in those nodes?)
> 12:31 PM <davida> want me to find ali?
> 12:31 PM <jbuck> nah, it's good
> 12:31 PM <davida> (anything i can do to help?)
> 12:31 PM <jbuck> service should be restoring now
> 12:32 PM <jbuck> upon sshing into one of the nodes: => / is using 100.0% of 7.87GB
> 12:32 PM <jbuck> heh. we would've avoided this if we migrated to Heroku earlier in the week....
> 

I've confirmed it's working for me, and have shared the good news w/ the thimble bug.

**Comment by davidascher** [comment]
I closed the bug on thimble, but I suggest we use this bug to log the analysis.

**Comment by cadecairos** [comment]
Lol, I was planning to do the Heroku migration on Monday!

**Comment by cadecairos** [comment]
@jbuck The cause of this was logs using up all the disk space, right?

Now that we're on Heroku, that won't be an issue anymore.

**Comment by jbuck** [comment]
Yerp!
