### ISSUE TITLE
Plan a recurring triage of desk.com issues

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#280]
https://webmaker.desk.com/web/agent/

**Comment by cadecairos** [comment]
Are we looking for a weekly calendar event to triage things on desk.com? or something else?

**Comment by xmatthewx** [comment]
Unsure. Whatever best fits your process with @simonwex. These are mostly account related requests, not specifically about any one tool.

**Comment by cadecairos** [comment]
I added a recurring weekly event to my calendar to remind me to spend some time in desk.com. 

Another option would be creating devops issues that link to the desk.com support threads, that way Account related support can be prioritized, and not checked in on once a week.

**Comment by simonwex** [comment]
@xmatthewx who primarily manages the requests as they come in through desk.com?

**Comment by xmatthewx** [comment]
I am often assigned things by @KevZawacki. He maintains an FAQ, answers when he can, reassigns when he can't. 

I wouldn't worry about this too much. Ops requests are low volume and not often critical issues. Simple to resolve. One per week? They've just previously sat unanswered.

**Comment by cadecairos** [comment]
@xmatthewx I think what I'd love to see is that the folks who frequent desk.com can file a bug on this repo when something is needed. I'm going to be adding an issue template so that filing devops bugs is as simple as possible, in terms of "What information should I give?"

**Comment by xmatthewx** [comment]
Do you get an email when something is assigned to you on Desk.com? Take a peek at a couple of them. Most have personal info that we can't post github. 

I'll let you, @simonwex and @KevZawacki decide how to handle this. I don't think that this is the right approach. I recommend you try Desk.com for a month and then decide if we need a different method. 

You'll need to reply and close the issue via Desk.com even if you have a ticket in devops. If you need more info, you'll have to gather it from desk.com as well. We'll have two tickets, two assignments, two message threads, and two open/closed status to maintain ... all for a single tiny request. It seems like that would add work for Kevin and for you, risk of issues falling out of sync, without really saving anything. 

I'll butt out now. :jeans: :dash:

**Comment by cadecairos** [comment]
We can and should keep the personal data in desk. I'm proposing an issue describing the work requested, and a link to the desk issue for retrieving sensitive details (if required). 

This approach will help myself and others involved in operations work to prioritise tasks. I think might be preferable to having ops integrate a second system into our day to day work, especially when the volume if tasks requiring our attention is fairly low.

**Comment by cadecairos** [comment]
I'm gonna go ahead and say that if any ops work is needed to solve a desk.com issue, please file the bug here with a link to the ticket in desk.com.
