### ISSUE TITLE
Regenerate thumbnails missed while service was down

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#283]
Looks like thumbnails began to fail again on 2/29 around Project ID 61237. Some intermittent success, mostly failures. :game_die: :game_die:   #251

**Comment by mofodevops** [comment]
Blitline isn't showing any API errors in their dashboard.

@jbuck did we update the render url when we swtiched beta.webmaker.org? or does that old url still work?

**Comment by mofodevops** [comment]
oops, I'm in the devops account! (cade)

**Comment by xmatthewx** [comment]
Good question @cadecairos. He It looks like the change didn't work: https://github.com/MozillaFoundation/mofo-devops/issues/239#issuecomment-190424318

**Comment by cadecairos** [comment]
No, I'm pretty sure it's working:

https://beta.webmaker.org/#/thumbnail?user=576822&project=56879&page=169389&_k=314wq1
https://webmaker.org/#/thumbnail?user=576822&project=56879&page=169389&_k=314wq1

Both these links work.

**Comment by xmatthewx** [comment]
Agreed. I tested that when jbuck made the DNS changes. The URLs work. However... 

Looking in the DB, 9 out of 10 have no thumb in March, `{}` in the field. Before March, only 1 out of 20 or so are missing their thumb. 

Even projects with 3+ pages and 5+ elements are missing thumbs. Look at http://xmatthewx.github.io/webmaker-firehose/ and hit MORE a bunch of times. 

Something is fishy, and the timing lines up with the DNS change. Coincidence? 

Maybe blitline needs permission to accept requests from the new domain?

**Comment by cadecairos** [comment]
We've identified the issue. Looks like the screenshot service is refusing to accept screenshot requests for webmaker.org (previously it allowed only beta.webmaker.org)

Jon's pushing up a fix now.

We'll need to run the script to regenerate thumbs beginning from when the break happened ( ~February 29)

**Comment by xmatthewx** [comment]
Thanks for the speedy response.

**Comment by xmatthewx** [comment]
Cool. New projects are working. Let's keep this open as a reminder to run the regeneration script on 61236 < `project id` < 62148

**Comment by cadecairos** [comment]
all done!
