### ISSUE TITLE
Redirect gear.mozilla.org to mozilla.org on March 31.

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#284]
Related plan ticket:
https://github.com/MozillaFoundation/plan/issues/762

**Comment by cadecairos** [comment]
:sob:

**Comment by simonwex** [comment]
What do you think the best way is for us to schedule things like this? Should we have a shared calendar?

**Comment by cadecairos** [comment]
That should be okay, so long as we set up good reminders.

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1260869

**Comment by cadecairos** [comment]
This work has been completed.
