### ISSUE TITLE
email address for the sciencelab forum replies

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#29]
Could the sciencelab have one of the following email addresses to enable reply by email on our discourse instance?

replies@mozillascience.org 
OR
replies.sciencelab@mozillafoundation.org

I'll need to be able to enable POP as per these instructions:
https://meta.discourse.org/t/set-up-reply-via-email-support/14003

https://github.com/mozillascience/site/issues/25

**Comment by jbuck** [comment]
I've filed a bug to get this account created: https://bugzilla.mozilla.org/show_bug.cgi?id=1151556

**Comment by jbuck** [comment]
Sorry this took so long! The account has been created, and it being synced to google apps now. I'll create credentials to share with @acabunoc when that's done.

**Comment by acabunoc** [comment]
YAY! thanks @jbuck

**Comment by jbuck** [comment]
Credentials emailed to @acabunoc! Let me know if things don't work.

**Comment by jbuck** [comment]
There seems to be a problem using plus addressing on the postfix forwarder

**Comment by jbuck** [comment]
All fixed now!
