### ISSUE TITLE
Move teach.mozilla.org onto Heroku

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#290]
We're deploying teach.moz on mofostaging.net at the moment, with production being a plain S3, which means that production teach.moz is actually just loose files, without a server to help us do all kind of generally useful things like routing and selective content serving. We're going to switch this over to heroku, which means the following steps need to be taken, probably in the order listed:

- [x] set up a teach.mozilla.org-staging heroku instance
  - http://teach-mozilla-org-staging.herokuapp.com/
- [x] coffee
- [x] tie this instance to the "develop" branch of teach.mozilla.org for autodeployment (staging ID: Z2FDTNDATAQYW2)
- [x] coffee
- [x] turn off automatic deployment to https://teach.mofostaging.net when merging into `develop`
- [x] coffee
- [x] set up a teach.mozilla.org-production heroky instance (once staging has proven itself)
- [x] coffee
- [x] switch over teach.mozilla.org binding to the heroku production instance
- [x] coffee
- [x] turn off post-travis-S3-pushing
- [x] coffee
- [x] remove documentation on the old build process
- [x] note:we will lose the changelog building that is part of the old process, so: either make a new changelog builder as deploy hook, or require that PRs come with updates to the changelog?
- [x] write new documentation on how the heroku deployment works
- [x] coffee
- [x] remove teach.moz S3 bucket(s) also remove the cloudformation stacks
- [x] victory coffee

**Comment by cadecairos** [comment]
Does coffee have to come last?

**Comment by Pomax** [comment]
no, you're right: it shouldn't.

**Comment by alicoding** [comment]
Do you mind if I take this over?

**Comment by Pomax** [comment]
all I care about is getting it done sooner than later, if you want to help sooner be even sooner: awesome =D

**Comment by alicoding** [comment]
I've created production heroky http://teach-mozilla-org-production.herokuapp.com/

**Comment by Pomax** [comment]
have you been drinking enough coffee, though?

**Comment by Pomax** [comment]
Also, why would this happen? ![screenshot 215](https://cloud.githubusercontent.com/assets/177243/13974814/64572e4a-f06c-11e5-99e2-18d3b23dd5c4.png)

**Comment by alicoding** [comment]
It is possible the permission might not be right. I'll fix it once I get to the office.

**Comment by alicoding** [comment]
I can see your pomax [at] mofo email in the list.

**Comment by alicoding** [comment]
This is now completed except we haven't removed the S3 bucket because we just need to make sure everything works 100% before we do that, so lets leave it for few more days and I will remove the S3 bucket there :)

**Comment by Pomax** [comment]
that's great! nice work @alicoding!

**Comment by alicoding** [comment]
It doesn't seem like there's a way to archive/rename an S3 bucket, so either re remove the S3 bucket for teach site or just leave it as is?

**Comment by alicoding** [comment]
Closing this ticket unless we really want to remove this bucket.

@cadecairos @simonwex

**Comment by Pomax** [comment]
if we're not using it anymore at all, I see no reason to keep it around. Unless someone can make a compelling argument to keep it around, let's delete it.

**Comment by cadecairos** [comment]
I agree, it's a static site, so the contents are saved in git. No need to keep the bucket.

**Comment by alicoding** [comment]
I've removed both staging and prod S3 buckets \o/
