### ISSUE TITLE
Clean up Appmaker Firebase apps

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#291]
Appmaker's been shut down, so we wont need the firebase apps any longer.

We might want to back up the data though!

**Comment by cadecairos** [comment]
@simonwex status?

**Comment by simonwex** [comment]
I just loaded the interface, it seems that the flathead.firebaseio.com db is owned by @davidascher.

@davidascher, could you downgrade the plan to the free tier?

**Comment by simonwex** [comment]
WM-APP-FORM-DATA
WM-APP

**Comment by davidascher** [comment]
done.

**Comment by simonwex** [comment]
Thanks, @davidascher!
