### ISSUE TITLE
Thimble is still publishing to a cloudfront URL

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#292]
I just noticed when publishing a project, it's still using the d157rqmxrxj6ey cloudfront url. We should be using thimbleprojects.org.

thimbleprojects.org is configured, but doesn't load from where projects are currently being published:
 * https://d157rqmxrxj6ey.cloudfront.net/simon/44720/ -- Expected
 * https://thimbleprojects.org/simon/44720/  - Should be showing same as above

Related #209

Once it is loading the correct content, the domain settings on `bramble-production` need to be updated.

* [x] Update thimbleprojects.org CNAME to point to d157rqmxrxj6ey.cloudfront.net
* [x] Update bramble-production configuration
  * PUBLISHED_PROJECTS_HOSTNAME='https://thimbleprojects.org'
  * BACK_TO_SCHOOL_PUBLISHED_URL='https://thimbleprojects.org/mozillalearning/62/'
  * COMIC_STRIP_PUBLISHED_URL='https://thimbleprojects.org/mozillalearning/32/'
  * HOMEWORK_EXCUSE_GENERATOR_KIT_URL='https://thimbleprojects.org/mozillalearning/11701/'
  * KEEP_CALM_PUBLISHED_URL='https://thimbleprojects.org/mozillalearning/171/'
  * SIX_WORD_SUMMER_KIT_URL='https://thimbleprojects.org/mozillalearning/11704/'
  * THREE_THINGS_I_HEART_KIT_URL='https://thimbleprojects.org/mozillalearning/11288/'

**Comment by cadecairos** [comment]
https://thimbleprojects.org/cade/45756

**Comment by simonwex** [comment]
```

     ,;``',
    ;      |
    ;;. ;;,'
     `"-'7'.          REAL URLS!!!!!!   _  /
         |' >.                         .'` |\  -
         | /  >.                   _\ /   /  |  -
         '/  / ,`.  __..----.       .'  .'  /  _
         ;  / /_.-'          \     /_.-`_.-'  \
          ;' .'  '`           |  - `-.-'
          |_/                .'   /   \_\_
          _|  |_    .____.-'`         / __)`\
         ( `  /\`'-...__.'  \        | '\(_.'|
          `-\   \ `-'-'-'|   `.      -.  \(_./
             \   \.-.-.  \     \___ /  >-'\_\
              \   \  \ \  `/\  |_  '` /
           _./\    \  ' | /    /_\ .-`
         .' _.\'.   '.__.'    /`\`'
  .-.---'\_/   `.`'-..____   ;   \
 / / .--. |,     `'-._   /`'.|    |
 `| /-' / / \         `.'    \   _/
  '-'  '-' \ `-._            _,-' |
            \    `'''----''''    /
             >                _.'
            / /`'-.._____..--'\ \
           < \                / /
            \ `.           .'  |___ 
          ___\_ `.        /__.-'   ``--..
   ..--''`     `-.\      (___/`'--.._____)
  (_____...--'`\___) 
```

**Comment by cadecairos** [comment]
Mozilla Networks haven't picked up the change in eight days, filed BZ bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1260602
