### ISSUE TITLE
Block donations from known fraudsters

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#293]
Lots of our fraudulent charges are coming from the same email addresses.

A simple webhook to compare emails we see as fraudulent to incoming donations will go a long way to reducing our chargeback rate.

**Comment by cadecairos** [comment]
mmmm.... this is pretty important, but we're limited in tracking donator emails for checking for fraud because we don't have Heroku Private spaces to keep the database off the public internet.

This will require some discussion before we can solve it. we could just have this webhook live in a simple worker instance on AWS, connected to a db in RDS. 

Or we wait until mozilla has a private spaces contract w/ Heroku.

**Comment by simonwex** [comment]
We could keep salted hashes of fraudulent emails on Heroku and just check against that list.

**Comment by valianttry** [comment]
Stripe customer support has been great, and are super helpful with this stuff -- if you think a 30m call with them to double check assumptions / here what other orgs have done would be useful just say the word and I will set something up :moneybag:

**Comment by cadecairos** [comment]
> just say the word and I will set something up

the word!

I can't say no to helpful advice :+1:

**Comment by ScottDowne** [comment]
What about integrating Kount with Stripe?

It was always an option but we wanted to see where Stripe had issues before pulling the trigger.

**Comment by cadecairos** [comment]
Does Kount integrate with skype? I don't see any information on their (Kounts) website about it.

**Comment by ScottDowne** [comment]
@cadecairos I forget. I'll dig around.

**Comment by ScottDowne** [comment]
@cadecairos really, I would say if we decide to use Kount again, we should just email our contact there and ask how to integrate with stripe.

If they integrate with bsd, I'll be surprised if they don't integrate with stripe.

**Comment by alicoding** [comment]
Just adding some resources from Stripe about Fraud protections:

https://stripe.com/docs/fraud
https://support.stripe.com/questions/avoiding-fraud-and-disputes

**Comment by cadecairos** [comment]
Related: https://github.com/mozilla/donate.mozilla.org/issues/1412

**Comment by cadecairos** [comment]
moving to next hearbeat, meeting with stripe on Wednesday

**Comment by cadecairos** [comment]
We're opting into a beta program that will give us more insight into the risk levels associated with each charge. I'm going to close this for now and we can file follow ups if there's any actionable items.
