### ISSUE TITLE
S3 for Mozilla Science Lab

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#295]
Hey @cadecairos, we have an amazon s3 bucket (owned by me) where we upload and serve images for [mozillascience.org/collaborate](https://mozillascience.org/collaborate) -- mostly the project images uploaded by individual project leads. Can we move to a mozilla owned s3 bucket?

We should be able to create a new bucket, copy the exiting images over and update the access & secret keys.

**Comment by cadecairos** [comment]
Sure thing! 

I'll add it to the next heartbeat.

**Comment by gideonthomas** [comment]
@cadecairos:
I added this CORS rule for it to work:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>Authorization</AllowedHeader>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>https://www.mozillascience.org</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by cadecairos** [comment]
@gideonthomas lgtm

**Comment by gideonthomas** [comment]
cool
