### ISSUE TITLE
remove old makes by people whose account got deleted

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#296]
Based on https://github.com/mozilla/thimble.mozilla.org/issues/1461, it feels like we should finally address the "delete makes for people who deleted their account" issue =)

Given what I remember about our infrastructure here, it feels like this is a thing we should be able to fully automate, with scripts checking all makes.org user dirs to see if that user is still an extant account in our login system. If so, we leave it, if not (i.e. the user doesn't exist or deleted their account) we delete the dir.

**Comment by edriann** [comment]
Thank you!

**Comment by cadecairos** [comment]
There's a great deal of work involved in automating this process, we should handle that in another issue.

In the short term, @gideonthomas will remove the makes associated with your old webmaker account.
@edriann Can you provide your webmaker username?

**Comment by edriann** [comment]
@cadecairos @gideonthomas Thank you! I think it's edriannhao.

**Comment by cadecairos** [comment]
> As a solution to the immediate problem that sounds like a solid plan - what's the issue for solving this long-term?

I'm going to propose a simple script we can run when we recieve a request to remove something.

**Comment by gideonthomas** [comment]
The user's content has been removed. Should we still keep this issue open for the script part?

**Comment by edriann** [comment]
Thank you! I tried using Google search, though a search item still appears (perhaps it just hasn't updated yet), the main makes page is already unavailable. 

However though, the source code is still available/viewable. Is it possible you could help me with this as well?

Again, thank you very much!

**Comment by gideonthomas** [comment]
@edriann, no problem! How are you viewing the source code?

**Comment by edriann** [comment]
@gideonthomas It can be accessed through Google Search. Here is the link: https://thimble.webmaker.org/en-US/project/6594/data (apologies for the really hilarious code though, haha).

**Comment by gideonthomas** [comment]
@cadecairos that ^ is in a database, not in S3 right?

**Comment by cadecairos** [comment]
yeah, we didn't account for the source code stored in the Thimble DB.

**Comment by cadecairos** [comment]
I'll update the db

**Comment by cadecairos** [comment]
The data has been removed.
