### ISSUE TITLE
Where does the Hive Directory live?

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#298]
https://directory.hivelearningnetworks.org/nyc/

If I remember it correctly this was something Atul built for Hive 2 years ago.  We need to update something there now and I can't seem to find the repo anywhere. Is it https://github.com/toolness/hive-directory ??? Also I see `hive-nyc-directory` and `hive-nyc-staging` on Heroku but I'm not sure if they are the right instances I should be looking at. Can someone help me find that out please? Thanks!

**Comment by simonwex** [comment]
Hey @mmmavis the app name is "hive-global" in Heroku. It seems that the latest commit deployed is this one: https://github.com/toolness/hive-django/commit/36622b1427c67ca72ed7cf33e7e07d3045f077dd

I've forked the repo (https://github.com/mozilla/hive-django) and added our mofo teams to it.
