### ISSUE TITLE
Create devops admin account on directory.hivelearningnetworks.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#299]
I've emailed Atul, hoping he can flip a bit for my account as we forgot to hand this app off. If he can't, we can dig into the DB and try to add one.

**Comment by jvallera** [comment]
Let me know if you would like me to reach out to Atul as well. Happy to.

**Comment by cadecairos** [comment]
@simonwex how's this one going?

**Comment by simonwex** [comment]
@jvallera please do!

**Comment by jvallera** [comment]
ok. email sent. Awaiting a reply.

**Comment by simonwex** [comment]
Atul got back to us! He's written up instructions and everything. We're currently blocked on the mandril problem, though. @cadecairos do you have a ticket filed for that?

**Comment by simonwex** [comment]
https://github.com/toolness/hive-django/wiki/Administration

**Comment by cadecairos** [comment]
I haven't filed a ticket yet. We're currently in need of someone with a hivenyc.org email address who can verify that mandrill is allowed to use that domain to send mail.

**Comment by simonwex** [comment]
@jvallera can you help with that? ^

**Comment by jvallera** [comment]
Yes, happy to help @cadecairos @simonwex . We have one hivenyc.org email we all use for general emails...will that work? Let me know how best to proceed.

**Comment by cadecairos** [comment]
@jvallera yeah that should be just fine! 

I'll trigger the confirmation of domain ownership on mailchimp/mandrill - basically, they'll send an emaiul with a link that lets the email account approve sending using that domain name.

What's the email address we should use?

**Comment by jvallera** [comment]
going to pull in @jazoulai to help with this. He is currently handling our communications. Joey, see above. We need to help @cadecairos with an email verification via info@hivenyc.org.

**Comment by cadecairos** [comment]
@jazoulai I've sent the verification email to info@hivenyc.org

**Comment by jazoulai** [comment]
Haven't received it yet. Maybe try again? @jvallera info@hivenyc.org
redirects to hivelearningnyc@gmail.com yes?

On Thursday, May 5, 2016, Christopher De Cairos <notifications@github.com>
wrote:

> @jazoulai <https://github.com/jazoulai> I've sent the verification email
> to info@hivenyc.org <javascript:_e(%7B%7D,'cvml','info@hivenyc.org');>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaFoundation/mofo-devops/issues/299#issuecomment-217213978>
>


-- 
Joey
____________________
Community Coordinator, Hive NYC Learning Network, Mozilla
*Follow HIVE NYC * Twitter <https://twitter.com/hivelearningnyc>  |
Instagram <https://www.instagram.com/hivelearningnyc/>  |  Facebook
<https://www.facebook.com/HiveLearningNYC/>  |  Website
<http://hivenyc.org/>

**Comment by jvallera** [comment]
@jazoulai no, it does not. Have to access hivenyc.org through godaddy I believe.

**Comment by cadecairos** [comment]
I sent a second request, just in case

**Comment by jvallera** [comment]
@cadecairos is there any way you can send to hivelearningnyc@gmail.com ? we thought info at hivenyc would go there, but it seems like it doesn't. Not sure where the disconnect is there or how to acceess info@hivenyc. Sorry for confusion.

**Comment by cadecairos** [comment]
unfortunately, it must be sent to an @hivenyc.org email address

**Comment by jvallera** [comment]
I am so confused. I just sent myself an email to info@hivenyc.org and received it. But your email is no where to be found. I checked spam and trash too. Do you mind sending once more?

**Comment by cadecairos** [comment]
I've just sent the request for verification *fingers crossed*

**Comment by jvallera** [comment]
nothing yet :(

**Comment by cadecairos** [comment]
@jvallera let me try sending a test email from my mofo account...

**Comment by jvallera** [comment]
@cadecairos that worked...came through immediately.

**Comment by cadecairos** [comment]
That's very, very strange! I wonder why it's not working for mandrill? 

@simonwex got any insight here?

**Comment by simonwex** [comment]
Looks like the MX records for hivenyc.org are still routing through SLC3. My bet is that mail from outside orgs is hitting SLC3 and getting tossed in the garbage, while anything sent through google is routing within google infrastructure to our inboxes.

```
hivenyc.org.		300	IN	TXT	"v=spf1 include:spf.mandrillapp.com ?all"
hivenyc.org.		300	IN	MX	10 mx1.scl3.mozilla.com.
hivenyc.org.		300	IN	MX	20 mx2.scl3.mozilla.com.
```

I'd open a ticket with IT to convert hivenyc mail handling to google.

**Comment by cadecairos** [comment]
> I'd open a ticket with IT to convert hivenyc mail handling to google.

We control the DNS records for that domain. I'll update them to match the ones on mozillafoundation.org

**Comment by jvallera** [comment]
Thank you!

**Comment by cadecairos** [comment]
@jvallera I re-sent the confirmation email for mailchimp to info@hivenyc.org, could you take a look?

**Comment by jvallera** [comment]
@cadecairos don't see it.

**Comment by cadecairos** [comment]
might have been too soon for the changes to have propagated. I'll give it a go again in an hour or so.

**Comment by cadecairos** [comment]
@jvallera I sent two emails to info@hivenyc.org, one from my mofo email, one from my personal email - did they arrive?

**Comment by cadecairos** [comment]
Nevermind, the changes I made made things worse. reverted, and filed an IT bug with MoCo

**Comment by jvallera** [comment]
ok. thanks for trying @cadecairos let me know if/how i can help.

**Comment by simonwex** [comment]
@cadecairos link to IT bug?

**Comment by cadecairos** [comment]
IT Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1271693

**Comment by cadecairos** [comment]
@jvallera Can you check once more that emails from mandrill aren't in the `hivelearningnyc@gmail.com` inbox/spam folder

**Comment by jvallera** [comment]
@cadecairos I see an email from you yesterday, May 11 with "Test :)" in the body. Is that it?

**Comment by cadecairos** [comment]
So my personal email came through, but no mailchimp stuff at all?

**Comment by jvallera** [comment]
nothing from Mailchimp. I can do a search to make sure, is the address it will come from @mailchimp.com

**Comment by cadecairos** [comment]
It should actually be from @mandrill.com

**Comment by jvallera** [comment]
cannot locate anything from @mandrill

**Comment by cadecairos** [comment]
I've updated the Bugzilla bug with this information. If the mail isn't even reaching Mozilla's mail servers, we probably will have to talk with Mandrill support.

**Comment by simonwex** [comment]
Just a thought for short-circuiting this for later troubleshooting. @jvallera do you mind sharing the credentials with @cadecairos for that account? That way he can check on inbound mail without having to pester you. He can let you know how to do that safely.

**Comment by jvallera** [comment]
@simonwex @cadecairos happy to. Just let me know what works.

**Comment by cadecairos** [comment]
@jvallera sorry for the delay, I've created a "hive" vault in mofo 1password for teams, I'll send you an invite so you can add the credentials there.

**Comment by jvallera** [comment]
perfect, thanks @cadecairos

**Comment by cadecairos** [comment]
@jvallera did you get the invite?

**Comment by jvallera** [comment]
@cadecairos was it to my mozilla address? or hive address? what address is it coming from?

**Comment by cadecairos** [comment]
I sent it to "julia@mozillafoundation.org", I can only assume it's from a 1password.com email address

**Comment by jvallera** [comment]
Yes, it was in my spam @cadecairos I am in and looking at my home dashboard.  what next?

**Comment by cadecairos** [comment]
@jvallera I've approved the signup and added you to the hive vault, you should be able to see it now.

**Comment by jvallera** [comment]
@cadecairos great. just added. let me know if it works for you

**Comment by cadecairos** [comment]
Thanks!

**Comment by cadecairos** [comment]
Done, +saved in 1password
