### ISSUE TITLE
Deploy webmaker-app-bot to staging

### ISSUE THREAD

**Issue by k88hudson** [MozillaFoundation/mofo-devops#3]
Preferred URL is `webmaker-app-bot.mofostaging.net`

Repo is here: https://github.com/mozilla/webmaker-app-bot, still pending review and configuration.

**Comment by jdotpz** [comment]
Ah, hadn't seen this!  I'll get this going!

**Comment by jdotpz** [comment]
Let me know when we've got some code ready to rock @k88hudson :)

**Comment by k88hudson** [comment]
@jdotpz we're close to merging, ill let you know

**Comment by k88hudson** [comment]
@jdotpz ok, good to go

**Comment by k88hudson** [comment]
note: no additional configuration is needed

**Comment by jdotpz** [comment]
- [ ]  create ec2 security group, allow elb sg on port 80(see other apps for examples)
- [ ]  create keypair, share on lastpass
- [ ]  app iam creds, share on lastpass
- [ ]  build scripts written
- [ ]  Cloud init scripts written for 64bit
- [ ]  create staging launch config
- [ ]  create staging autoscale group
- [ ]  update fab file with new autoscale group staging
- [ ]  create S3 folder for s3://mofo-techops/deployment/apps/staging/appname
- [ ]  create S3 folder for s3://mofo-techops/deployment/apps/production/appname
- [ ]  grant respective app AWS keys access to  s3://mofo-techops/deployment/apps/staging/appname and s3://mofo-techops/deployment/apps/production/appname
- [ ]  Add iam user to s3-creds-staging (or production) iam group
- [ ]  Add app-env specific user policy to each user, look at other app-appname-env user policies for a template
- [ ]  Upload an allowed ssh file to each envs creds folder, created above.
- [ ]  Create configs for app/env, upload to S3 creds env buckets created above
- [ ]  update fab file with new autoscale group staging
- [ ]  update fab file on builder under /home/ubuntu/.aws/fabfile.py
- [ ]  puppet modules written
- [ ]  as-update-auto-scaling-group --min-size 1 --max-size 1 --desired-capacity 1
- [ ]  create first github tagged version of app
- [ ]  Create staging jenkins job
- [ ]  Test Jenkins staging job
- [ ]  test!
- [ ]  create prod launch config
- [ ]  create prod autoscale group, multi-AZ
- [ ]  create monitoring for main endpoint
- [ ]  create PRODPUSH Jenkins job
- [ ]  create PRODBACKOUT Jenkins job
- [ ]  create loggins stream for new app
- [ ]  create custom DETAIL-appname dashboard in newrelic
- [ ]  setup contextual loggins links, newrelic links, monitoring links in Jenkins

I'm betting we don't need an ELB here.  https://github.com/mozilla/webmaker-app/issues/664 is where the main issue is tracked.

**Comment by jdotpz** [comment]
We're actually able to throw this right on Heroku!
