### ISSUE TITLE
Enable Pingdom monitoring for sites we care about

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#30]
We have an account but it's apparently been suspended so first step is to get that unsuspended

**Comment by simonwex** [comment]
Previous support ticket: CYM-143-54436

**Comment by simonwex** [comment]
Credit card has been updated, but unable to pay invoice on site.

**Comment by jbuck** [comment]
Account has been obtained

**Comment by jbuck** [comment]
We also brainstormed all of the sites that should be added to Pingdom:

* id.webmaker.org
* api.webmaker.org
* teach.mozilla.org
* teach-api
* webmaker.org
* webmaker mobile app
* advocacy / fundraising forms (that isn't hosted on BSD)
* sendto.mozilla.org / donate.mozilla.org

**Comment by simonwex** [comment]
togetherjs.com
hub.togetherjs.com/status
