### ISSUE TITLE
Import Gigabit blogs to blog.webmaker.org

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#300]
We're planning to sunset three Gigabit blogs:
- http://hivecha.org/blog/
- http://hivekc.org/blog/
- https://blog.mozilla.org/gigabit/

We'd like to archive and link the content somehow, or import it to https://blog.webmaker.org with a #gigabit hashtag. 

Can you advise on the best way to do this?

cc @LindseyFrost @jenntbeard @hannahkane @KGorr

**Comment by cadecairos** [comment]
We'll investigate the workload involved here in the next heartbeat.

**Comment by cadecairos** [comment]
If we want to be able to access the admin interfaces for these instances, we're going to need to upload our existing SSL certificates to WP Engine. I just concluded a chat with WP Engine support, and learned [how to get existing certs installed](https://wpengine.com/support/add-ssl-site/) (bottom of article).

**Comment by cadecairos** [comment]
olanning for this continues. @gideonthomas will update with information at a later date

**Comment by gideonthomas** [comment]
I literally have no idea where https://blog.mozilla.org/gigabit is hosted. It looks like it is managed by MoCo? @cadecairos can you advise?

There seem to be a bunch of ways to do this (all have some caveats), but @cadecairos if we can chat a bit about the right approach, that would be great!

**Comment by gideonthomas** [comment]
@simonwex do you know who manages https://blog.mozilla.org/gigabit so that we can get credentials for running the migration?

**Comment by gideonthomas** [comment]
Exporting the XML content file and importing it into Wordpress works well with one caveat - adding the Gigabit tag. 
There is no easy way to edit the xml and add it in there. But I thought of a better solution. We create an empty wordpress instance locally. Import all the content we want to add to the final blog. Bulk tag all the content in the local instance using the admin interface. Then export the content again into an XML file. And import that file into the final blog.

Things we still need -
- Credentials for Hive Chattanooga's and blog.mozilla.org/gigabit blogs.

**Comment by jenntbeard** [comment]
Hi - The login for blog.mozilla.org/gigabit is through our SSO credentials - maybe we can add you as an admin? 
Hive CHA blog info is:
Site	Account/Location - HiveCHA (wordpress)	
Login/Username - Katie
Password - gigcity2016
Primary owner - Katie Hendrix
Email address associated w/account - katiem@mozillafoundation.org (i think)

**Comment by hannahkane** [comment]
@gideonthomas - is this blocked on credentials? Can I help get those for you?

**Comment by gideonthomas** [comment]
Just got credentials for all three blogs...we can proceed on this this week.

**Comment by hannahkane** [comment]
As discussed now, I think this is the order of operations:

First:
 * Migrate KC/Cha blog posts to blog.mozilla.org/gigabit -> to handle the de-duping now
 * [Move blog.webmaker.org to new url](https://github.com/mozilla/learning.mozilla.org/issues/1855) that better reflects Learning hub - pending conversation with @mcdermott415, but should be confirmed shortly

Second:
 * Migrate + redirect blog.mozilla.org/gigabit to Learning hub blog
 * [not a devops task, but a dependency] Add non-blog Gigabit content to Learning site

Third:
 * Redirect hivecha.org, hivekc.org, and mozilla.org/gigabit to new destination on Learning site (specific url TBD)

**Comment by gideonthomas** [comment]
The blog content migration is done! Will handle the redirects in: https://github.com/MozillaFoundation/mofo-devops/issues/425
