### ISSUE TITLE
Where should sensitive/security related bugs go?

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#301]
Issues here can't be hidden, and we don't have a product/component that really fits on Bugzilla

* [x] new private repo
* [ ] update Issue Template with email instructions
* [ ] profit

**Comment by cadecairos** [comment]
* new private repo
* update Issue Template with email instructions
* file issues in private repo

**Comment by cadecairos** [comment]
@simonwex ping on this - keep in this milestone or bump?

**Comment by simonwex** [comment]
Bamped!

**Comment by simonwex** [comment]
We can work on private issues here: mofo-devops-private

**Comment by simonwex** [comment]
dceb102f19dffefd90d891c05d2a4f33428d8063
