### ISSUE TITLE
Deprecate thimble.webmaker.org

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#302]
### Details
thimble.webmaker.org is long overdue for a shutdown. I have scripts & a process developed to migrate data into bramble (the scripts may need updates).

- [X] Create a deprecation notice
- [X] Decide on a shutdown date. (JUNE 27)
- [x] Update copy for deprecation notice - mozilla/thimble-takedown#2 (before JUNE 22)
- [x] alter deprecation notice to thimble.webmaker.org (in top bar) mozillafoundation/mofo-devops#352 (JUNE 22)
- [x] Redirect thimble.webmaker.org to deprecation page. (JUNE 27)
- [x] [run migration](https://gist.github.com/cadecairos/44e3d34845d0f438779a) (JUNE 27)
- [x] create final snapshot and delete the thimble RDS database

**Comment by cadecairos** [comment]
related: mozilla/thimble.mozilla.org#509

**Comment by mickfuzz** [comment]
Subscribing, I can volunteer to test my projects after they are migrated.

**Comment by cadecairos** [comment]
The plan has been simplified. We will put together a page explaining that Webmaker Thimble is now shut down, details that projects will shortly be migrated for use in the new Thimble, and provide a link.

**Comment by mickfuzz** [comment]
Hi there, do we have a timescale for the migration. 
I now wish I had done a manual migration with the key projects for the Quacking Javascript course. Is that still possible without remixing being turned on?

**Comment by cadecairos** [comment]
Hi @mickfuzz There's a lot of data to import into the new Thimble, but the whole process shouldn't take more than a few hours once started.

Once traffic to the app is turned off, you will only be able to access the projects through their `makes.org` URLs until the migration into the new publish system is completed. Once they're imported, they'll need to be re-published using the new Thimble so that a new published URL can be generated.

**Comment by hannahkane** [comment]
@cadecairos - can you describe the re-publishing experience from the user's perspective? After the projects are imported, will people be able to access them from the new Thimble (where?) and re-publish them there?

**Comment by cadecairos** [comment]
All the projects will appear in the users projects list. Each migrated project will consist of a single `index.html` file, and will be "unpublished". The user can load the project in the new thimble app, and re-publish it to the web just like they would with any other thimble project.

**Comment by cadecairos** [comment]
There appears to be an event running this weekend that will make use of Webmaker Thimble, so lets push on this work in the next HB

**Comment by hannahkane** [comment]
@flukeout to help with the landing page

**Comment by cadecairos** [comment]
woot! @hannahkane / @flukeout are we tracking the building of the landing page anywhere other than here?

**Comment by flukeout** [comment]
Hey @cadecairos - not yet. Have you thought about where the page will live & be hosted? Should we add something to the new Thimble repo and point at that page? Let me know your thoughts and we'll file an issue in the appropriate place.

**Comment by cadecairos** [comment]
I'd like to deploy the page to an S3 bucket, ideally it's a standalone HTML page that has all it needs in one package.

As for where we keep it revisioned - we could put it in the legacy thimble branch, as the final commit.

**Comment by cadecairos** [comment]
@flukeout ping - think we'll be able to get this done in the next few days? I can help in any way you need.

**Comment by flukeout** [comment]
Working on this today and will provide the HTML & CSS

**Comment by flukeout** [comment]
Okay, here's the page...
http://mozilla.github.io/thimble-takedown/

And the assets are in that repo...
https://github.com/mozilla/thimble-takedown

**Comment by flukeout** [comment]
cc @cadecairos @hannahkane

**Comment by cadecairos** [comment]
I've successfully done several dry runs of the migration (using live data) using my local databases. 

Everything runs great, I'm ready to go!

**Comment by cadecairos** [comment]
Redirect in place, and data exported.

I'm about to begin migrating it into the publish service

**Comment by cadecairos** [comment]
MIGRATION COMPLETED

🎉 💯 🍔 🔥 🐎

**Comment by cadecairos** [comment]
Thimble database snapshotted, and deleted. 

![](https://media.giphy.com/media/msKNSs8rmJ5m/giphy.gif)

**Comment by mickfuzz** [comment]
Fantastic - works for all my projects! 

Logo: ![Alt](/http://i.giphy.com/132xaiItSkgXAs.gif"Title")

**Comment by mickfuzz** [comment]
@hannahkane or anyone with permissions, can you merge my pull request which updates the course?

https://github.com/mozilla/webmaker-curriculum/pull/230

Thnx

**Comment by hannahkane** [comment]
@mickfuzz - looking now. thanks for the reminder.
