### ISSUE TITLE
Receipts for wpengine are not automatically going to Alex

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#305]
It'd also be good to figure out and document an approach for creating new accounts, too. (will file)

- [x] heroku
- [ ] firebase
- [x] redpen
- [x] geckoboard
- [x] github
- [x] pagerduty

all need to have (if possible) invoices sent to alex, and use the right CC.

**Comment by simonwex** [comment]
While we're in this frame, let's make sure heroku, firebase and redpen are all handled the same way, too

**Comment by cadecairos** [comment]
I've invited Alex to the devops Google group. I'll work with him to set up filters, if needed.

"Invoices", "Billing" and "Receipts" seem like good filters to have.

**Comment by davidascher** [comment]
changed the descriptions to keep a list of the vendors we have to make sure are right (they're all in my credit card right now)

**Comment by cadecairos** [comment]
I've updated Heroku so that it will now bill the Mofo Credit card. Receipts go to all admin account emails, including "devops@mozillafoundation.org". Alex should now have filters to get all invoice/billing related emails that go to the devops list.

**Comment by cadecairos** [comment]
@davidascher @simonwex Which Firebase apps are we currently paying for? Does Firebase support orgs? It'd be helpful to move apps we pay for there into one org.

**Comment by cadecairos** [comment]
We need to get credentials for redpen added to 1password, assuming we pay for it.

I'm pretty sure I've got all the credentials I need for everything else.

**Comment by cadecairos** [comment]
Updated Billing and CC info in Geckoboard, invoices going directly to Alex

**Comment by cadecairos** [comment]
redpen account added to the vault, now owned by devops@. CC info updated as well.

**Comment by cadecairos** [comment]
MozillaFoundation Github org Billing info updated, devops@ added as a billing manager. (will receive invoices)

**Comment by davidascher** [comment]
re: firebase, only 'flathead' shows up in my view, which is part of appmaker.

**Comment by cadecairos** [comment]
Lets's switch that to a free plan

**Comment by cadecairos** [comment]
Pager duty Billing info updated, bills going directly to Alex

**Comment by cadecairos** [comment]
Assuming we're switching the firebase app to a free teir, and with all the other work completed (Alex has access to devops list, with relevant filters set up, All above accounts now charge the mofo CC and send mail to devops@) I will close this issue.
