### ISSUE TITLE
Document how to sign up for a new service

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#306]
* [ ] 1password vault
* [ ] how to fwd receipts to alex
* [ ] Approval process
* [ ] Approval process (if user data is involved)

Plop the doc on the mofo-devops readme.

Related to #305

**Comment by simonwex** [comment]
@cadecairos what's the current method for Alex getting the receipts? Did we add him to devops@?

**Comment by cadecairos** [comment]
Yes, he's part of the devops list, and has filters set up. 

The problem with this is that if any of the keywords in his filter are not in a billing invoice we get for a new service, he won't get them. 

Ideally, if the service provides setting up a different billing email than the email associated with the account, we want to go with that. if not, we'll need to use the list, and verify Alex gets the invoices.

**Comment by simonwex** [comment]
Alex's keywords are:

 * billing
 * invoice
 * has:attachment
 * statement
 * receipt

**Comment by simonwex** [comment]
db31471d4684c276a6f48a27051c2c21d032b59d
