### ISSUE TITLE
Investigate API/Cache issue with Webmaker

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#308]
Something is broken in Webmaker land. Not all of the projects that are marked as featured get served to the discover route. The problem can't be reproduced with the staging DB. So, it might be a problem with the cache on production. Something outside the API with AWS.

### Info & links

More info: https://github.com/mozilla/api.webmaker.org/issues/204

**Comment by cadecairos** [comment]
@xmatthewx The discover route cache goes stale after 5 minutes - do the projects appear after that amount of time?

**Comment by xmatthewx** [comment]
Hold the phone :phone:. I might have found something. I will report back.

**Comment by cadecairos** [comment]
@xmatthewx do we know if this is still an issue?

**Comment by xmatthewx** [comment]
Closing. Unless I'm mistaken, the problem is due to a choice made in the early stage of the project. I haven't yet confirmed, but I'm pretty sure that Discover only displays projects that are both Featured AND match your locale. A fine idea in theory, but not ideal for a fledgling platform without any content. I'll follow up elsewhere.
