### ISSUE TITLE
SSL Cert for mozilla science

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#31]
On the following domains:

* mozillascience.org
* www.mozillascience.org
* forum.mozillascience.org

Thanks!

**Comment by jbuck** [comment]
Okay, it looks like we already have a certificate for forum.mozillascience.org but it hasn't been applied yet. It's using the mofoprod cert for some reason? There's also an expired cert for mozillascience.org/www.mozillascience.org that will need renewing.

**Comment by jbuck** [comment]
Okay, I've requested an SSL cert for mozillascience.org and www.mozillascience.org . Waiting for approval in Digicert

**Comment by jbuck** [comment]
Approved! Just need to set both up now.

**Comment by jbuck** [comment]
Cert is now configured for https://forum.mozillascience.org

**Comment by acabunoc** [comment]
Yayyyy

**Comment by acabunoc** [comment]
I'm having trouble logging in to the forum via https. Works fine on http.

**Comment by acabunoc** [comment]
It's probably because of the 'Homepage URL' and 'Authorization callback URL' in our github application settings. Can we force people to use https and just have the app setup for https?


![image](https://cloud.githubusercontent.com/assets/617994/7356055/dd2f53d8-ecf3-11e4-96c6-197ada33dc6f.png)

**Comment by simonwex** [comment]
We should do a redirect to https from http, especially for any auth endpoint. @acabunoc when this is done, can you force a password-reset for your users?

**Comment by acabunoc** [comment]
@simonwex yup. Should the redirect be done on @jbuck's end, or in the app on my end?

**Comment by jbuck** [comment]
Turns out I don't have the keypair to this EC2 instance, but @flamingspaz probably does!

**Comment by flamingspaz** [comment]
@chefscott, could you send either myself or @jbuck the discourse-01302014 keypair?

**Comment by jbuck** [comment]
@flamingspaz @chefscott I have the discourse-01302014 keypair, but that's not the right one for this instance.

forum.mozillascience.org A ALIAS forum-mozillascience-production-1439424411.us-east-1.elb.amazonaws.com. (z3dzxe0q79n41h)
i-f3254018 is the only instance in this elb
it's using the keypair named "docker-discourse-mozsci"

**Comment by chefscott** [comment]
I found it -- I just shared with @jbuck.

**Comment by jbuck** [comment]
Mozilla Science forum is now using HTTPS
Mozilla Science site is now using HTTPS

We're all good here!

@acabunoc if you want to change the oauth config, now is the time

**Comment by acabunoc** [comment]
Thank you @jbuck!

**Comment by acabunoc** [comment]
Hey @jbuck -- How is the SSL stuff setup for mozillascience.org? I'm getting weird session issues now -- things are fine locally / before SSL. It's probably something on my end, discourse is fine.

**Comment by jbuck** [comment]
It's using Cloudfront (CDN), so perhaps there's a header not being allowed through or something along those lines. Would you like me to revert the change and point it directly at the Heroku app, or shall we leave it as-is until Tuesday?

**Comment by acabunoc** [comment]
As-is till Tuesday is fine :)

**Comment by acabunoc** [comment]
Temporarily fixed by adding 

    Cache-Control:	private, no-cache, no-store, must-revalidate

Will revisit and find a better solution. Vary:Cookie wasn't getting set properly.

**Comment by jbuck** [comment]
Yeah, it'd be ideal to not set that on the "logged-out" pages, and only have that set for the "logged-in" pages.
