### ISSUE TITLE
[June 2] Redirect old science properties to science.mozilla.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#311]
@acabunoc could you help fill in blanks here?

**Comment by acabunoc** [comment]
| mozillascience.org | science.mozilla.org
| --- | --- | ---- |
home | / | /
blog all | /blog | /blog
projects | /projects/[projectname] | /projects/[projectname]

### further redirect needed:

 | mozillascience.org | science.mozilla.org
| --- | --- | ---- |
training | /training | /programs
community | /community | /programs/events
collaborate | /collaborate | /projects
about | /about | /members
members | /u/[membername] | /members/[membername]
fellows | /fellows | /programs/fellowships
2015 fellows | /fellows/2015 | /programs/fellowships

### same namespace to two different places (SORRY!):

 | mozillascience.org | science.mozilla.org
| --- | --- | ---- |
events | /[eventname] | /programs/events/[eventname]
blog* | /[postname] | /blog/[postname]

\* please place the priority on blogs if you can't do both events and blogs

**Comment by cadecairos** [comment]
[putting this in next up, based on the june 2 tag in the title]

**Comment by acabunoc** [comment]
I can list out all the individual events we need migrated if that would help with the blog & events dilemma

**Comment by gideonthomas** [comment]
Add an exception as per: https://github.com/mozilla/science.mozilla.org/issues/425#issuecomment-221339156

**Comment by acabunoc** [comment]
I updated the table to list all the events and include the exception @gideonthomas mentions

**Comment by cadecairos** [comment]
fixed by mozilla/science.mozilla.org#475
