### ISSUE TITLE
Versioning HiveNYC.org prior to updates

### ISSUE THREAD

**Issue by jazoulai** [MozillaFoundation/mofo-devops#312]
## Details

We are planning to make wide-ranging updates to the content on [HiveNYC.org](http://hivenyc.org/) and thought it might be a good idea to version the site in case we break something major and want to revert back. Is there already a protocol in place for this? 

## Links

Alternatively, I was considering installing a Wordpress plugin called [VersionPress](https://versionpress.net/) to implement versioning.

Please advise. Thank you!!

cc' ing @jvallera

**Comment by cadecairos** [comment]
Our wordpress hosting provider gives us daily backups, so we can feel free to break things without too much worry! ;)

**Comment by jazoulai** [comment]
Thanks @cadecairos! That's all I needed then :)

**Comment by cadecairos** [comment]
Cool, if you need a rollback you can file an issue in this repo and we'll get right on it!
