### ISSUE TITLE
Give Mavis SSH access to hivelearningnetworks.org

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#315]
Please grant me SSH access so I can update the content (`wp-content`) of this WordPress instance. Thanks! :bowtie: 

Related: 
https://github.com/mozilla/teach.mozilla.org/issues/1690

**Comment by cadecairos** [comment]
@mmmavis Have you tried connecting?

**Comment by mmmavis** [comment]
Working from home today. Will try connecting tomorrow from the office :dancer:

**Comment by mmmavis** [comment]
Hey @cadecairos , I forgot to ask you what's the server destination i'm SSHing to. :grin:

**Comment by mmmavis** [comment]
Confirmed that I'm able to SSH to it! :tada:
