### ISSUE TITLE
Point mozillafestival.org and mozfest.org to a new Heroku instance

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#316]
In https://github.com/MozillaFoundation/mofo-devops/issues/309#issuecomment-207022922 we have decided to stick with top domain URL.  Currently both https://mozillafestival.org and https://mozfest.org points https://2015.mozillafestival.org/.  Can we change them so they go to https://mozillafestival-org-production.herokuapp.com/ instead? 

Note that this new Heroku instance has the 2016 MozFest info that we would like to show the world :smile: Not urgent but would be great if we can have this change in place early. :v: 

/cc @edrushka

**Comment by edrushka** [comment]
Any update on this? Would be great if we could get the changes live on the site ASAP. We're sending an info pack to all the MozRetreat planning participants later this week, so I know they will be checking the website. Thanks.

**Comment by simonwex** [comment]
@cadecairos as you can see from the comment, this is urgent enough to get into this HB.

**Comment by edrushka** [comment]
@cadecairos do you have an update on when we can expect to see the MozFest updates live on the site? Can we uncouple them from this ticket or get this done this week?

**Comment by cadecairos** [comment]
@edrushka I've just updated the CDN to use the new 2016 Mozilla Festival Heroku app URL. We should see it working in 20 minutes or so, I'll watch the progress and check that I didn't mess anything up.

**Comment by edrushka** [comment]
:fireworks: Thanks Chris!

**Comment by cadecairos** [comment]
@edrushka `mozillafestival.org` now serves the 2016 site. 

mozfest.org appears to be controlled by moco, I'll file an IT Request to have it redirect to mozillafestival.org

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1265777 (Employee restricted)

**Comment by edrushka** [comment]
hey @cadecairos - yesterday both @xmatthewx and @vazquez were able to see the site updates but I was not. It's been almost 24 hours and I still can't see them. Do you know why? I've tried refreshing, different browsers etc.

**Comment by mmmavis** [comment]
I believe this has been taken care of. Closing this now. YEAH :tada:

**Comment by cadecairos** [comment]
haha love the enthusiasm, but I'm still waiting for moco IT to direct mozfest.org to our Nameservers - Everything on our side is configured, we just need that to happen.

https://github.com/MozillaFoundation/mofo-devops/issues/316#issuecomment-212002672

**Comment by cadecairos** [comment]
BZ bug closed. DNS changes can take up to 24 hours to propagate.

**Comment by mmmavis** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by cadecairos** [comment]
Okay, HTTP redirect is working (from my location) HTTPS does not, because we don't have a cert..

My question: do we care enough to spend 200 bucks a year on a cert for mozfest.org?

**Comment by xmatthewx** [comment]
It might be worth it given that Mozfest is a flagship event with sessions that talk about privacy and security. No strong opinion here.

**Comment by cadecairos** [comment]
we need to also consider about what mozfest.org *does* which is just redirect to mozillafestival.org (which uses https!).

Do we want to shell out that much money for an https redirect?

**Comment by xmatthewx** [comment]
Oh. Right. I see. That makes it less important.

**Comment by cadecairos** [comment]
I've pointed mozfest.org directly at an s3 website that redirects to mozillafestival.org - this means that attempts to connect to the website with SSL don't present a security error, the browser just says to the user that the server doesn't exist.
