### ISSUE TITLE
Archive 2015 MozFest site

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#317]
As discussed in https://github.com/MozillaFoundation/mofo-devops/issues/309#issuecomment-207022922 ...

I've put 2015 site in the `2015.mozillafestival.org` branch on the mozillafestival.org repo: https://github.com/mozilla/mozillafestival.org/tree/2015.mozillafestival.org

Let me know if I can help with anything! :wink:

**Comment by cadecairos** [comment]
mozillafestival.org and www.mozillafestival.org resolve to the new 2016 site, and 2015 site remains reachable at 2015.mozillafestival.org.
