### ISSUE TITLE
Create bit.ly account for API access

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#318]
Account has been created, but we'll be creating many URLs through the API. We'll need to share details for OAuth and likely add a credit card if there are rate or quantity limits.

If you can add any extra authentication information to the vault and ping me, I can get it to the right people.

https://github.com/MozillaFoundation/encryption_campaign/issues/250

**Comment by cadecairos** [comment]
The email is verified, but if we're making an OAuth app, I need details about the app url and the callback URL, which I can't find in MozillaFoundation/encryption_campaign#250

**Comment by cadecairos** [comment]
@wex shall we close this and file a bug here/somewhere else to handle the bitly service?

**Comment by simonwex** [comment]
Yeah, happy for us to close this once we know the other bug has been filed. @ScottDowne could you link to the new boog?

**Comment by ScottDowne** [comment]
Bitly bug is here: https://github.com/MozillaFoundation/encryption_campaign/issues/236
