### ISSUE TITLE
Set up CI for science front-end

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/mofo-devops#319]
### Details

Repo: https://github.com/mozilla/science.mozilla.org

Currently there is only a `master` branch that requires CI. Eventually, once we're closer to launching we'll switch to `develop` and `master`.

### Info & links

FYI: The `mozillascience.org` branch is for the current site up at https://mozillascience.org/ in case we need to do any hotfixes before we launch the redesign.

**Comment by cadecairos** [comment]
This is simple to set up with heroku and pipelines.

**Comment by alicoding** [comment]
- Review app is enabled
- Staging is setup here: http://science-mozilla-org-staging.herokuapp.com/
- Production is setup here: http://science-mozilla-org-production.herokuapp.com/
- Auto deploy to staging is enabled once the PR is merged with travis passed
- Deploy to production using Pipeline.
