### ISSUE TITLE
Investigate email inboxes for coralproject.net

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#32]
@ryanpitts has requested coralproject.net email inboxes. Some things to figure out first:

- [x] Who owns the domain coralproject.net? It's not Mozilla. It's Dan Sinker!
- [ ] Possibly transfer domain to Mozilla? That'll be necessary for SSL certificates from Digicert.
- [ ] Who can host the inboxes? MoCo Google Apps would be ideal, but maybe our own Google Apps instance or AWS Workmail would be good second choices.

**Comment by ryanpitts** [comment]
I *think* @sinker

**Comment by sinker** [comment]
yes, I bought it and we can definitely transfer.

**Comment by ryanpitts** [comment]
Looping in @losowsky here. His would be the first inbox we'd set up.

**Comment by jbuck** [comment]
From informal conversation, it is not currently possible to have a coralproject.net email address under our MoCo Google Apps account

**Comment by simonwex** [comment]
@davidascher I feel like you have some expertise in this field, could you lend a hand? - coralproject.net wants to have @coralproject.net email addresses for general use. After a convo with @limed (Ed Lim) it seems it wouldn't fall under the same agreement as the MoCo Google Apps account and adds some complexity to LDAP.

Do you have any suggestions for third-party mail providers that are vendor-reviewed and/or do you know if google apps is possible?

**Comment by davidascher** [comment]
@ryanpitts: do you want actual inboxes, or just email forwarding to ppl's
existing accounts?  All project staff will be MoFo staff and so have
mozillafoundation email addresses.

**Comment by ryanpitts** [comment]
@davidascher the thought was that, for organizational purposes, actual inboxes would be the best solution. If that's a thing that's possible.

**Comment by ryanpitts** [comment]
Any current thoughts on this issue? Is it moving too big of a mountain to try for actual inboxes vs. aliases?

**Comment by davidascher** [comment]
It would involve a renegotiation w/ Google on the set of domains covered
under our particular agreement (which pays for opting out of some data
analysis as I understand it).  So, my strong recommendation is to just use
aliases.

Coral project staff are Mozilla staff after all.

**Comment by sinker** [comment]
not all Coral staff are Mozilla staff though. Because of the nature of the
collaboration, there are WaPo and NYT people that are/will be working as a
part of Coral.

**Comment by davidascher** [comment]
Good point, and, alas, I think that's another argument for using aliases.
To the extent that people are paid to work on Coral, these are work emails,
and need to be under the governance & protection of the employer.  So we
should setup fowards to people's work inboxes.  (If volunteers end up
working with coral email addresses then those emails should get forwarded
to whatever inbox those volunteers want).  I realize this will make things
like gdocs sharing a tad harder.

**Comment by ryanpitts** [comment]
Revisiting this now that we have a couple additional Coral folks coming on board in the near future. With separate inboxes not in the cards, @losowsky likes the benefits of making it plain that the team is part of Mozilla Foundation. @jbuck can we go ahead and close this?

**Comment by jbuck** [comment]
@ryanpitts Consider it closed!
