### ISSUE TITLE
Get AWS RDS credentials

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#320]
We're not sure if we have access to all AWS RDS instance credentials since they have gone through several changes in management. We should get them in one place.

This is especially needed for the AWS RDS instance for the discourse prod website.

cc @jbuck, @jdotpz, @cadecairos

**Comment by jbuck** [comment]
You have access to all RDS instances - simply rotate the root password!

**Comment by cadecairos** [comment]
@jbuck would that be the "new master password" textbox in the modify instance menu in RDS?

**Comment by jbuck** [comment]
Yep

**Comment by cadecairos** [comment]
o/
