### ISSUE TITLE
add special handling for goggles projects to allow for 'http://' hosting

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#324]
We want to add "http" support for goggles publications, so that people who remix http websites don't see a Mozilla product doing "the worst thing" by serving that remix up over https, with mixed-content blocking turning their remix into a horrible mess. This requires changes in publish.wmo and on the routing side, as well as an update to the goggles notice bar:

- [x] make publish.wmo publish goggles content, switched on the client_id it sees for a project, to an S3 url with `/HTTP/` prefix - https://github.com/mozilla/publish.webmaker.org/issues/224
- [x] make the routing check whether a requested URL exists as `/HTTP/` prefixed resource. If so, allow serving both over `http` and `https`. If possible, we should hide the `http` prefix in the URL that people visit.
- [ ] make the goggles notice bar look at the protocol of the site it's loaded on, and if it's http, notify the user that there *is* an https version, and that they can click to visit that. If they do, the top bar can explain that things look horrid because of mixed-content, with a link back to http, and a learning/teaching opportunity. - https://github.com/mozilla/goggles.mozilla.org/issues/291

Note that the prefix is `HTTP`, not `http`, so as not to conflict with a possible username "http". id.wmo ensures that usernames are always lowercase, so `HTTP` should be a safe prefix.

**Comment by Pomax** [comment]
[PR for publish](https://github.com/mozilla/publish.webmaker.org/pull/225) landed, [PR for goggles](https://github.com/mozilla/goggles.mozilla.org/pull/292/files) pending.

**Comment by cadecairos** [comment]
> make the goggles notice bar look at the protocol of the site it's loaded on, and if it's http, notify the user that there is an https version, and that they can click to visit that. If they do, the top bar can explain that things look horrid because of mixed-content, with a link back to http, and a learning/teaching opportunity. - mozilla/goggles.mozilla.org#291

@Pomax This appears closed - did we not want to do this anymore?

**Comment by cadecairos** [comment]
I'm going to call this one closed, since all the devopsy things that were needed here have been completed.

**Comment by Pomax** [comment]
yep, there's a followup in goggles around the notice bar, but that's not devops related
