### ISSUE TITLE
Inquiry about setting up a cron job to run a Python script for schedule app

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#325]
Hey awesome people!

I barely know anything about this and am hoping I can get some insights on what it will take (time & resources wise) to set up a cron job to run a Python script :grin: 

**Context:**
For the schedule/event app, we have a Python script that pulls data from Google Spreadsheet, parses & formats the data, generates a .json file, and commits that file to a Github repo.  Data should be modified using Google Spreadsheet only (vs directly changing values in the .json file) so I think we need to provide event wranglers an easy way to publish spreadsheet data to the app.

Last year's MozFest we had 1) a cron job 2) and a IRC bot that triggers the Python script. Are these the preferred approaches as still? I'm not sure how they were set up and would love to know how. Is this something someone with zero devops skill can help set up as well? :wink: 

/cc @xmatthewx

**Comment by xmatthewx** [comment]
We hope to use this for **London all-hands** (meeting with Angela to confirm next Wednesday). We would need to have this running by the middle of May to do that with confidence. 
 - I don't think it matters if the job is scheduled or triggered on demand, as long as coordinators can do this without dev help. 
 - I do think we should find the simplest way to set this up for future events, so it's easier to do for multiple events every year. Any creative ideas? 

Reference: https://github.com/mozilla/schedule-app-data-processor

**Comment by flamingspaz** [comment]
Just to add a little more context, we used Jenkins to run the Python script last year as Travis was unable to encrypt the Google Sheets private key. It ran on cron, IRC bot and whenever an update was pushed to the repo.

I'm not sure who makes the decision but y'all are more than welcome to continue using our Jenkins server, which should make it easier for coodinators to trigger the script whatever way works best for them (Jenkins integrates with pretty much everything) and setting up multiple jobs would be pretty painless.

**Comment by mmmavis** [comment]
Hi @flamingspaz :smiley: thanks for providing context!

We are going to have a schedule app for our London All-hands. (Sorry time might be a little tight) @cadecairos @flamingspaz  Can you advice what the next step should be to set up the cron job (and if we have time, chat bot as well)?. As I mentioned earlier, I would love to pick up the skills if it helps lighten DevOps' workload. Let me know how I can help! :wink:

**Comment by cadecairos** [comment]
I can support  this in whatever way needed, but I have zero experience with Slack/Mattermost integrations, or setting up jenkins integrations. 

@flamingspaz would you be able to idestify all that we need to set up to have this working for the London all-hands?

**Comment by flamingspaz** [comment]
- [ ] Make our Jenkins instance public
- [ ] Get Spreadsheet key
- [ ] Add a Jenkins project to run the schedule update
- [ ] Add webhook to Mattermoz to trigger Jenkins job

From there I can teach the team how to clone the job and make it work for other schedules. @cadecairos I can take this issue if you'd like, just assign it to me.

**Comment by cadecairos** [comment]
@flamingspaz you are the best! Let me know if I can help at any point.

**Comment by mmmavis** [comment]
@flamingspaz wow wow wow RAD U ROCK! Thanks for helping again 😄👍 

I'm working on documentation for https://github.com/mozilla/schedule-app-data-processor. This is pretty much based on the script we had for last year's MozFest except I extracted a few hardcoded configs and made them [env vars](https://github.com/mozilla/schedule-app-data-processor/blob/master/docs/REQUIREMENTS.md#environment-variables). (I can share my sample .env if it helps set up Jenkins)

This is where the all-hands app live: https://github.com/mozilla/mofo-allhands . We will need to update `sessions.json` in the 2016-london` dir.

I *think* this is the spreadsheet we are going to use (currently filled with semi-fake data): https://docs.google.com/spreadsheets/d/1TEn1AYjLUSXagxJGhOiNPbDdPxsqJsSmeI-_4pvS41U/edit#gid=1546802594 (I'll leave it for @xmatthewx to confirm)

One more note, I'm going on 2-week PTO starting this Thursday. Hopefully the docs on the repos aren't too hard to digest. I won't be checking my work inbox until May 30. I don't check Twitter often but you can still reach me via Twitter PM if needed. :wink:

**Comment by mmmavis** [comment]
Hey @flamingspaz 
sample env file for the Mofo London all-hands app is here: https://gist.github.com/mmmavis/96bea5b589c0d75453e86c65d89af754

**Comment by flamingspaz** [comment]
Thank you! the docs are perfect too. I've made a copy of the sheet to play about with. We should have this going pretty soon :thumbsup:

**Comment by mmmavis** [comment]
@flamingspaz thank YOU! 😄 

I need to start packing and head to the airport in a few hours. @xmatthewx is on PTO now - he should be back next week. If you have any question, @xmatthewx would be the person to chat with 😎 

I'll see you folks online in ~2 weeks. VACATION WOOHOOOOO 😉

**Comment by cadecairos** [comment]
I've set up a Hubot on https://chat.mozillafoundation.org. The setup includes a role based auth mechanism and command processing middleware that checks a user has the right role to perform an action.   

With @flamingspaz's help I set up a travis integration that only lets the build happen for users that have the "jenkins" role (only myself or wex have the ability to grant roles right now.)

**Comment by xmatthewx** [comment]
Thanks @flamingspaz and @cadecairos! I'm populating our spreadsheet with real data for the London schedule app. Is the chat bot integration set up and something that I can start using?

**Comment by cadecairos** [comment]
I'll grant you the role needed to trigger the job on jenkins!

**Comment by cadecairos** [comment]
cc/ @flamingspaz about whether the job is set to go

**Comment by mmmavis** [comment]
Hi folks, I'm back from PTO! Anything I can help clarify?

**Comment by flamingspaz** [comment]
As mentioned in chat, everything is good to go, I just need the spreadsheet key/private key etc.

Alternatively we could set up a mtg at some point and I can show y'all how to add a new job for a schedule so you can set them up by yourself in the future.

**Comment by flamingspaz** [comment]
Also, I couldn't get it to work using my forked sheet/creds so it'd be nice to see where I went wrong with creating them and if needed update the docs.

**Comment by cadecairos** [comment]
> Alternatively we could set up a mtg at some point and I can show y'all how to add a new job for a schedule so you can set them up by yourself in the future

+1 to this - I'd love a crash course on setting up jobs w/ jenkins

**Comment by xmatthewx** [comment]
Given our timezones, would 10:30am/3:30pm work on Friday? @flamingspaz, are you GMT+1? If that time doesn't work, don't let me block everyone else. Go ahead and schedule something else.

**Comment by mmmavis** [comment]
Hey @flamingspaz which keys do you need? Did you mean Google Service Account?

**Comment by mmmavis** [comment]
Friday works for me. I'm in Vancouver so anytime after 8am (PDT) works. (though after 9am would be preferred 😉 )

**Comment by cadecairos** [comment]
I'm going to call this done :tada:

**Comment by mmmavis** [comment]
✧*｡٩(ˊᗜˋ*)و✧*｡ 🌟
