### ISSUE TITLE
hapi vs express and pros and cons

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#326]
I'm pretty sure this is just to track the discussion and ultimately figure out which one we want to use, or even if we want to limit to one only. Things like pros and cons, and when to use one over the other.

I'm about as comfortable in both, I don't hold any strong opinions, and would be happy to use both when it makes sense if it ever does make sense to use either or in certain situations.

**Comment by cadecairos** [comment]
I don't have a preference for either. They're both fairly good frameworks that have community support.

I'd rather use Ruby on Rails :P

**Comment by Pomax** [comment]
I'm not a fan of HAPI mostly due to a lack of good tutorials from their side. If you're going to have to invent your own methodology, express feels a lot more accessible to both new devs and contributors.

**Comment by cadecairos** [comment]
There doesn't seem to be much of a need for this to remain open, so I'm closing it.

It seems like we can all agree that Django is best for our API's and content management, and express is probably the best for new apps, even though they'll likely be SPAs using react-router.

**Comment by Pomax** [comment]
SPAs but with server side generated "pages" on genuine URLs for hooking the app back into.
