### ISSUE TITLE
Plan & Push CMS-enabled learning site to production

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#332]
This is a ticket to promote the staging version of the Learning site to production. This is a bit atypical since it relies on a third-party service for content. 

@mmmavis and @cadecairos could you weigh in on what you think the precursors are? Here are a few things I think we need to do first:

 * [ ] Scrub test WP content
 * [ ] Ensure onesie files are being efficiently loaded
 * [ ] Develop QA script
 * [ ] Get some help with QA

What else?

**Comment by mmmavis** [comment]
- [ ] Add "Preview on MLN site" feature to our Calypso ( https://github.com/mozilla/learning.mozilla.org/pull/1844 and https://github.com/mozilla/wp-calypso/pull/43 )

MLN site doesn't use Onesie so the rendered result would be a bit different from what users see within TinyMCE. I think as long as we get Preview working we should be good.

**Comment by hannahkane** [comment]
Let me know if I can help with QA. I've started filing some tickets in https://github.com/mozilla/wp-calypso/issues, but I don't think they are blockers to releasing.

**Comment by mmmavis** [comment]
Note that the CMS enabled MLN site code lives on the [`cms-enabled` branch](https://github.com/mozilla/learning.mozilla.org/tree/cms-enabled). Once everything is ready to go we should
- merge `cms-enabled` into `develop`
- remove all testing WP posts from teachmozillaorg.wordpress.com site
- push things to MLN production

**Comment by cadecairos** [comment]
@wex @mavis Is there a reason we're not creating a new WP site for production post data? i.e. `learningmozillaorg.workdpress.com`?

**Comment by hannahkane** [comment]
With regard to the QA script, I previously tested our version of Calypso on Firefox, making use of the 3-box and Resources partials.

I have filed tickets in the [Calypso repo](https://github.com/mozilla/wp-calypso/issues), but I don't believe any of them are blockers to releasing this on the Learning site.

However, now I can't seem to access the staging site. When I go to https://mofo-calypso-test.herokuapp.com/stats/insights/teachmozillaorg.wordpress.com, nothing loads.

**Comment by cadecairos** [comment]
Is this something we're still hoping to make happen soon? Should we target this for sometime in July, while we focus on shutting down webmaker's Thimble?

**Comment by hannahkane** [comment]
It sounds like we're changing the scope of the Calypso project so that it won't apply to as many use cases as previously thought. I think we can hold on this for a bit.

**Comment by cadecairos** [comment]
I don't think this is happening. closing
