### ISSUE TITLE
Push new science site to production under new domain

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#333]
[More detail needed here, can you fill in @gideonthomas, @acabunoc, @alicoding]

Must be done by May 20.

**Comment by alicoding** [comment]
@acabunoc can we confirm about the domain name here?

**Comment by acabunoc** [comment]
science.mozilla.org !

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/enter_bug.cgi?product=mozilla.org&format=itrequest

**Comment by alicoding** [comment]
I forgot to link the bug here... https://bugzilla.mozilla.org/show_bug.cgi?id=1273987

**Comment by alicoding** [comment]
This is now done :) https://science.mozilla.org/

**Comment by hannahkane** [comment]
yay!
