### ISSUE TITLE
Training for the services team

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/mofo-devops#335]
There are bunch of things that I am not so familiar with yet because I haven't done enough work with it.  We have came up with list of things that would help us get comfortable with and help move the work forward if we know enough about.

https://docs.google.com/document/d/1ztkeCNjOoXZbnJ-tqAIR7S7iMrPpZGW_GreUBBNAjAM/edit

Some of the stuff @cadecairos volunteered to help get me and @gideonthomas comfortable and some we just need to document on how to do them.

**Comment by cadecairos** [comment]
This will have to wait until after all-hands (But it will get done!)

**Comment by cadecairos** [comment]
@gideonthomas I'll be in MoTo On the 31st, so we can go over using digicert then, or I'll schedule a meeting and we can do it over Vidyo - either way I want to close out this task asap.

**Comment by cadecairos** [comment]
This issue isn't relevant right now.
