### ISSUE TITLE
SSL cert for Science Blog

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#337]
Can we get an SSL cert for our wp instance of wp.mozillascience.org? 

Related: https://github.com/mozilla/science.mozilla.org/issues/395

**Comment by acabunoc** [comment]
wp.mozillascience.org redirects to https://mozscienceblog.wpengine.com which has ssl

**Comment by gideonthomas** [comment]
That makes sense! Should have thought to investigate how it was working on the current site. My bad :P
Thanks @acabunoc
