### ISSUE TITLE
upgrading screendoor account for science fellows call 

### ISSUE THREAD

**Issue by kaythaney** [MozillaFoundation/mofo-devops#338]
### Details

Need to upgrade from our free Screendoor account for our Mozilla Science Fellow call. (The $49/month will be more than enough :) ). 

### Info & links
current form: https://mozilla-science-lab.forms.fm/mozilla-fellows-for-science-2015

timing / need: as soon as possible? looking to open the call june 3; getting all necessary pieces staged now. 

also, @auremoser is our lead on this! :100: :+1: :information_desk_person: 

thank you!

cc @simonwex

**Comment by cadecairos** [comment]
@auremoser Do you mind if I send you an invite to our Foundation 1Password for Teams account? I'll create a new Vault for Science credentials and you can add in login details for screendoor there.

If you'd prefer a different way of transferring the screendoor account details securely, I'm open to all avenues.

**Comment by auremoser** [comment]
Surely. We can try that! I have keybase on my home machine but unfortunately they haven't debugged the transfer to my [moz computer](https://github.com/keybase/client/issues/1545). 1Password works, or I can invite you to a pw protected dropbox with the details.

**Comment by cadecairos** [comment]
@auremoser I'll send an ivite to the team account, keep an eye out for it!

**Comment by auremoser** [comment]
Cool, let me know what the best way to share creds is, it seems I don't have access to "shared vaults".

**Comment by cadecairos** [comment]
@auremoser added the credentials to the 1password vault, and I logged in.

I created an account for devops@mozillafoundation.org and transferred ownership to it, added a credit card and selected the $50/month screendoor plan.

**Comment by auremoser** [comment]
Thank you @cadecairos!
