### ISSUE TITLE
Use cloudfront instead of atul-https-proxy 

### ISSUE THREAD

**Issue by toolness** [MozillaFoundation/mofo-devops#34]
I've currently got an EC2 instance called `atul-https-proxy` (instance ID `i-6f2b1a3f`) up that uses the [`https-proxy-with-sni.js`](https://gist.github.com/toolness/10485006#comment-1210038) script to proxy HTTPS connections to the following heroku-hosted apps:

* **directory.hivenyc.org** proxies to https://hive-nyc.herokuapp.com
* **directory.hivelearningnetworks.org** proxies to https://hive-global.herokuapp.com
* **webmakerconnect.org** proxies to https://webmaker-connect.herokuapp.com

This was done because Heroku charges a ridiculous amount of money for SSL on custom domains, and these apps receive only a small amount of traffic.

However, based on what @jbuck told me about CloudFront, I think this proxying situation could potentially be implemented through AWS configuration rather than code, which would probably be both more maintainable and less expensive.

**Comment by jbuck** [comment]
- Get a certificate for:
  - [ ] directory.hivenyc.org
  - [ ] directory.hivelearningnetworks.org
  - [ ] webmakerconnect.org
- [ ] Upload certs to AWS
- Create cloudfront distribution for directory.hivenyc.org
  - [ ] directory.hivenyc.org
  - [ ] directory.hivelearningnetworks.org
  - [ ] webmakerconnect.org
- Point directory.hivenyc.org at cloudfront distro
  - [ ] directory.hivenyc.org
  - [ ] directory.hivelearningnetworks.org
  - [ ] webmakerconnect.org

**Comment by toolness** [comment]
Nice!

The cert for directory.hivenyc.org is expired, so we definitely need a new cert for that, but the other two have certs that I believe I obtained through JP (not StartSSL) and I think they may even be for more than 1 year. They're on the EC2 instance I mentioned so I can retrieve them from there and send them to you.

**Comment by jbuck** [comment]
@toolness I can't generate an SSL certificate for directory.hivenyc.org unless the domain is transferred to Mozilla first. I've filed a bugzilla bug to get that ball rolling, but we'll need @ldecoursy's help to get it done

**Comment by ldecoursy** [comment]
Let me know how I can help!

**Comment by jbuck** [comment]
@ldecoursy You'll need to run through the steps listed in https://support.godaddy.com/help/article/3560/transferring-domain-names-to-another-registrar . When you get the authorization code, you'll need to paste it in the bugzilla bug I filed ( https://bugzilla.mozilla.org/show_bug.cgi?id=1165409 ) so that the MoCo IT folks can complete the transfer process.

**Comment by jbuck** [comment]
Lainie and I went through the transfer steps together, and we're half-way there!

**Comment by jbuck** [comment]
All done
