### ISSUE TITLE
User log-in issue on Webmaker

### ISSUE THREAD

**Issue by KevZawacki** [MozillaFoundation/mofo-devops#340]
@cadecairos 

Hi Chris, flagging that I've assigned a Desk.com ticket to you (case #10165). We have a Webmaker user unable to access their account.

**Comment by cadecairos** [comment]
@KevZawacki thanks for filing! I'll take a look when I get to the office this morning

**Comment by cadecairos** [comment]
@KevZawacki The queue processor responsible for sending transactional webmaker emails was down D:

I've fixed the problem and had it process the backup of events (~7500). I've confirmed that resets/migrations are working now. I'll contact the user to let them know to try again.
