### ISSUE TITLE
greenkeeper is still connected to jbuck somehow

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#345]
@cadecairos not a huge deal, but kinda confusing.

In channel we're seeing "jbuck pushed 1 commit to mozilla/donate.mozilla.org"

Which, is far from true. We should if easy, change that to be "greenkeeper pushed 1 commit to mozilla/donate.mozilla.org"

**Comment by cadecairos** [comment]
I disabled greenkeeper, because we never even pay attention to it.
