### ISSUE TITLE
Write email to all-mofo to describe the 2FA requirements

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#346]
![image](https://cloud.githubusercontent.com/assets/25260/15512323/20bad3c2-2194-11e6-94f4-b0208a9ccf7d.png)

**Comment by cadecairos** [comment]
@simonwex are we going to require this for the MozillaFoundation org as well?

**Comment by cadecairos** [comment]
```text
Hello fellow mofos,

This email can be ignored if you are not a member of the Mozilla or MozillaFoundation GitHub organizations, and if you are not a member of the Mozilla Heroku organization.


On June 20th, the Mozilla organization on GitHub will require Two Factor Authentication (2FA) on all accounts. This change is being made to enhance the base level of security on all accounts, as it provides an extra layer of defense if your password is stolen.


We've decided to follow suit with the Mozilla organization and require 2FA on all MozillaFoundation team member accounts, as well as on all Heroku accounts.


You can learn everything you need to know about GitHub and 2FA here: https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/


For Heroku, you can read the articles provided here: https://devcenter.heroku.com/articles/two-factor-authentication

As always, feel free to get in touch with <the services team?> if you've got any questions about 2FA

```

**Comment by cadecairos** [comment]
@simonwex ^ proofread?

**Comment by simonwex** [comment]
* I'd do a separate email for Heroku and for Github and target the list. I think you have the identities, right?–It'll be difficult for many to understand if they can ignore this.
 * I'd include a one-liner to describe what 2FA is as the intro
 * Offer to walk people through it on a 30 min vidyo session?

**Comment by cadecairos** [comment]
Yeah two emails is probably a good idea. I have the user id's of github accounts without 2FA, but not their emails. might be able to get that out of the github API.

I'll draft a v2

**Comment by Pomax** [comment]
it feels like we're missing an explanation on why this matters for github, other than "2fa is more secure so just do it", which doesn't help people understand why we're making their life harder. For the heroku part it is easy to explain that this can give access to our critical infrastructure, so the extra security is definitely warranted there, but for since we work on a lot of open source, we should explain what people can do if they get their hands on a mofo-staff github account. Obviously a few people can delete repos, but the people who can delete *every* repo are already 2fa'd, so the risk (on paper) for a github account being compromised on the mofo side might feel virtually nonexistent to many people in the org.

**Comment by cadecairos** [comment]
```
Hello fellow mofos,

This email can be ignored if you are not a member of the Mozilla or MozillaFoundation GitHub organizations.

On June 20th, the Mozilla and MozillaFoundation organizations on GitHub will require Two Factor Authentication (2FA) on all accounts.

This change is being made to enhance the base level of security on all accounts, as it provides an extra layer of defense if your password is stolen. As Mozillians, it is important that we all care deeply about the security of our data (practice what you preach!) While the damage that could be done by an attacker could be easily reversed, the damage to Mozilla's reputation would be significant.

You can learn everything you need to know about GitHub and 2FA here: https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/
If you'd like a walk through of setting up and using 2FA with GitHub, let me know and I'll host a Vidyo session to help you get set up.
```
@simonwex @Pomax

**Comment by Pomax** [comment]
+1, that actually works fine for me. Explaining that we're all responsible for how Mozilla acts and is perceived nails it.

**Comment by cadecairos** [comment]
sweet! 

The formatting should be significantly better when prepared in Thunderbird.

**Comment by Pomax** [comment]
:zap::bird:

**Comment by simonwex** [comment]
👍

**Comment by cadecairos** [comment]
Message sent (Github version)

**Comment by cadecairos** [comment]
Message sent to all 2FA disabled Heroku org members (but not to the collaborators of individual apps.)

**Comment by cadecairos** [comment]
done, will follow up later in the month
