### ISSUE TITLE
Spin down mozscilab on heroku after we launch science.mozilla.org

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#347]
### Details

This should happen shortly after #311 (with some buffer). Sometime before June 2

See comments on this doc: https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1FcrJzxJL5JzsSHn4MEpw5Za_-FGVLr8NWKEk0ulDxDI/edit?disco=AAAAAr-EwcE&usp=comment_email_document

**Comment by cadecairos** [comment]
Scaled to Zero :copyright:
