### ISSUE TITLE
Forge a SSL cert for directory.hivenyc.org

### ISSUE THREAD

**Issue by toolness** [MozillaFoundation/mofo-devops#35]
The SSL cert for https://directory.hivenyc.org/ has recently expired!

![2015-04-28_16-15-09](https://cloud.githubusercontent.com/assets/124687/7379276/c71cf2d4-edc1-11e4-8e5b-3ef8e6d404ab.jpg)

I got this cert a year ago from StartSSL, I believe. It's currently being proxied from `atul-https-proxy` (see #34 for details on that). We should probably get a cert for it through mozilla at this point, though.

**Comment by jbuck** [comment]
Solving #34 will also fix this issue, so I'm duping this issue on that
