### ISSUE TITLE
Set up auto confirmation emails for MozFest session proposers

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mofo-devops#350]
Filing a ticket in your repo, @cadecairos!

Deadline to implement emails: EOD Wed June 8.

-------

#### Copy for Plan A (each email is customized with unique GH issue)

Hi < first name >,

Thank you for submitting a session proposal to MozFest!

Our session curation process takes place on Github in the [MozFest 2016 Program repo] (https://github.com/MozillaFoundation/mozfest-program-2016). Curation will begin in August when the Call for Proposals closes. In September, you'll be notified whether your session has been accepted or not.

Your session is documented in this issue: < Github ticket # and title >

If you're new to Github, don't be afraid! Sign yourself up for a free account and check out [this tutorial] (https://www.pluralsight.com/blog/software-development/github-tutorial) to learn how to view and comment on issues.

If you have questions, please reach out to festival@mozilla.org

Best,
The MozFest Team

-------

#### Copy for Plan B (same email goes to everyone - no customization except for name)
Hi < first name >,

Thank you for submitting a session proposal to MozFest!

Our session curation process will begin in August when the Call for Proposals closes. In September, you'll be notified whether your session has been accepted or not.

We curate sessions in the open on Github. Take a look at our [MozFest 2016 Program Repo] (https://github.com/MozillaFoundation/mozfest-program-2016) to follow the action.

If you're new to Github, don't be afraid! Sign yourself up for a free account and check out this tutorial to learn how to view and comment on issues.

If you have questions, please reach out to festival@mozilla.org

Best,
The MozFest Team

**Comment by mmmavis** [comment]
cc myself @mmmavis

**Comment by cadecairos** [comment]
This is done
