### ISSUE TITLE
[June 22] Modify deprecation warning on Thimble  

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#352]
Copy suggestion:

"There's a new Thimble! We'll be shutting down this version and migrating existing projects over on Monday, June 27th. Your projects will be inaccessible from X to Y on June 27th. In the meantime, try the new Thimble"

@KevZawacki @kgorr ^ does that ok to you?

@cadecairos to fill in specific times. :)

**Comment by KGorr** [comment]
+1 @hannahkane

**Comment by KevZawacki** [comment]
👍

**Comment by alicoding** [comment]
Done :)
