### ISSUE TITLE
Renew mozillafestival.org certificate

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#353]
My browser reports that the security certificate for mozillafestival.org expired yesterday. If true, this should block the call for proposals if it hasn't gone out already. cc @edrushka @Saallen @cadecairos

**Comment by cadecairos** [comment]
woops, this fell off my radar somehow! Certs renewed, are in process of deploying to the CDN now

**Comment by edrushka** [comment]
Site works again 😌
