### ISSUE TITLE
fix old thimble's login failing opaquely

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#354]
People are still using old thimble, and are now running into CSRF errors when trying to log in. We've not told people that logins won't work, so we'll either have to change the top bar to say this service is no longer active and give them no choice but to be redirected to the new thimble, or we should see if that CSRF error is easy to solve until we shut down old thimble properly after London.

**Comment by cadecairos** [comment]
thimble.webmaker.org logins should be working still - we've not shut it down yet...

**Comment by cadecairos** [comment]
Found the problem. Since switching to Heroku for old Thimble, we lost the ability to upgrade http connections to https.

Simply typing in "thimble.webmaker.org" will result in an http connection, which causes the browser to refuse to transmit Cookie headers, resulting in a 403 for any POST/PUT requests.

**Comment by cadecairos** [comment]
possible solution (without using a Cloudfront CDN) http://stackoverflow.com/a/29186187

**Comment by Pomax** [comment]
alternatively we can slip in some dumb JS:
```
<script>
  if (window.location.protocol === "http:") {
    window.location = window.location.toString().replace("http:","https:");
  }
</script>
```
Quick hack solution for a service we're turning off soon anyway?

**Comment by cadecairos** [comment]
Yeah a quick hack is definitely the solution, with less than a month before shutdown

**Comment by Pomax** [comment]
fix added, now the question is: how do we get thimble to rebuild...

**Comment by cadecairos** [comment]
Deploy the legacy branch to the old thimble app on heroku. (might be called thimble-old)

**Comment by Pomax** [comment]
not seeing a pipeline... does old thimble still use jenkins? O_o

**Comment by cadecairos** [comment]
no worries. there's definitely a pipeline called thimble-old in the moz org (just checked)

**Comment by Pomax** [comment]
there's a pipeline, but from what I can tell (as far as heroku shows me) there are no deploys bound to any branches for the actual apps in the pipeline.

**Comment by cadecairos** [comment]
Yes, auto deploys were never set up, but we can go to the deploy section on the staging version and manually trigger a build fromg the legacy branch (or just set them up)

**Comment by Pomax** [comment]
ahh, aiight.

**Comment by Pomax** [comment]
apparently I do not have the rights to link heroku into thimble. want to hook it up? (or move me to the github group that'll let me set up deploys)

**Comment by cadecairos** [comment]
Deployed fix to thimble-old-staging and thimble-old-production

**Comment by Pomax** [comment]
hero++
