### ISSUE TITLE
discourse.webmaker.org: email link error

### ISSUE THREAD

**Issue by KGorr** [MozillaFoundation/mofo-devops#355]
Received this message from a discourse.webmaker.org user:

"I just want to inform you that the links in the notification newsletters of your Discourse forum are broken ("forum.learning.mozilla.org’s server DNS address could not be found.)"

I received this message via a notification to my inbox, and I verified that the "visit message" button in that email goes to a server not found page. 

I'm not sure how to fix this, so filing this ticket in hopes of getting some help. Thanks!

**Comment by flamingspaz** [comment]
The migration to the new domain looks like it's going to take longer than expected, so I'm going to revert it back to the original domain for now.

**Comment by KGorr** [comment]
Thank you!

**Comment by flamingspaz** [comment]
I've updated the settings, emails sent from now will have the correct links!
