### ISSUE TITLE
HiveNYC URL seems to have an incorrect domain configured

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#359]
Atter clicking on portfolios, links are going to http://hivenyc.wpengine.com/...

**Comment by cadecairos** [comment]
I need to update the URL settings in WPEngine as well as in wp-admin.

I've asked @jvallera to add the credentials to 1Password so I can get in and make the right adjustments.

**Comment by jvallera** [comment]
Hi @cadecairos, I added the login to 1Password. Let me know if you have problems getting access.

**Comment by cadecairos** [comment]
Thanks a lot Julia! I was able to fix the redirect issue.

Christopher De Cairos
DevOps Engineer
Mozilla Foundation
