### ISSUE TITLE
Elasticsearch not available to Source site search

### ISSUE THREAD

**Issue by ryanpitts** [MozillaFoundation/mofo-devops#361]
Search functionality isn't working on Source at all. For example: https://source.opennews.org/en-US/search/?q=django

I'm guessing this is related to the AWS node rollover that happened recently. Looks like elasticsearch didn't start up on the new instance -- or perhaps it's running on a separate box, somewhere that isn't accessible to the new instance? I'm not sure whether it had been configured to run on the same server or elsewhere, but something's not hooking up :)

**Comment by ryanpitts** [comment]
Happy to help diagnose if I can. Once elasticsearch is running/available, we'll need to run `python manage.py rebuild_index` from the Django app instance to get the search index up.

**Comment by cadecairos** [comment]
It should be trying to connect to `http://ec2-23-21-11-111.compute-1.amazonaws.com:9200` I've verified that the source prod instance's security group is permitted to connect over that port. 

Is that configuration handled using a config in S3 (and updated using puppet?), or directly on the instance? (Sorry, I'm not familiar with how jp/jon set this up initially, just guessing)

**Comment by ryanpitts** [comment]
I suspect that JP would have set it up to use puppet, but I don't know that to be true. Sounds like `127.0.0.1:9200` just needs to be forwarded to that elasticsearch instance.

**Comment by ryanpitts** [comment]
Hmm, I may have spoken too soon on `127.0.0.1:9200`. That's the development setting, which looks like it's being overridden on prod to point to `http://source-es.mofoprod.net:9200`

**Comment by ryanpitts** [comment]
In the `mofo-techops` S3 bucket, there's a `creds/apps/production/source` entry, which I think is what you were asking about earlier.

**Comment by cadecairos** [comment]
Doesn't look like ES is running on the prod ES instance

**Comment by ryanpitts** [comment]
wheeeee

**Comment by cadecairos** [comment]
@ryanpitts ES is running now

**Comment by cadecairos** [comment]
It seems it's been running in a screen session on that instance for some time? lol. It's still doing that now.

**Comment by ryanpitts** [comment]
weeeeeird. I think we might still need to run `python manage.py rebuild_index` on the Source instance to catch any articles that have been added while the connection to elasticsearch was down.

**Comment by cadecairos** [comment]
When I run that command I see `Error: No module named jinja2`

**Comment by ryanpitts** [comment]
hmm, is the virtualenv activated? I've been able to run before with:

    cd /var/www/source
    source ./bin/activate
    manage.py rebuild_index

**Comment by cadecairos** [comment]
ugh, I can't install pip because either the ubuntu version on that instance is too old, or the repositories are invalid.

Either way, I've gotta get sleep now 😞 I'll look into this more in several hours.

**Comment by ryanpitts** [comment]
oh wow, I wasn't looking at the clock -- it's so late there! Thanks for getting es back up and running!

**Comment by cadecairos** [comment]
just saw the virtualenv comment - totally forgot that venv is a thing (Python newb here) I'll ge better at it. 

Also: 
```shell
Indexing 523 articles.
Indexing 128 codes.
Indexing 620 People.
Indexing 179 organizations.
```

Should be back in business! Goodnight!

**Comment by ryanpitts** [comment]
WOOOOOO. That's exactly what I was looking for :) Thanks again.
