### ISSUE TITLE
S3 access for two editors

### ISSUE THREAD

**Issue by ryanpitts** [MozillaFoundation/mofo-devops#362]
We've got a couple editors for Source who need access to the MoFo S3 bucket "assets.opennews.org." Chatted with @cadecairos today, just filing here so it doesn't get lost. Editors are:

* Erin Kissane
* Lindsay Muscato

**Comment by cadecairos** [comment]
@ryanpitts so, we need two IAM users, and two keypairs to provide access to that bucket? How are Erin and Lindsay going to be accessing the bucket?

**Comment by ryanpitts** [comment]
@cadecairos yep, two keypairs. They're planning to just use an FTP client.

**Comment by cadecairos** [comment]
@ryanpitts I've created the IAM users, and generated two keypairs. 

How can we best get these securely in the hands of Erin and Lindsay?

**Comment by ryanpitts** [comment]
Hmm, good question -- I'll let them know in our Slack channel and ask if they have any thoughts.

**Comment by ryanpitts** [comment]
@cadecairos I wonder whether https://crypto.cat/ might be useful for stuff like this.

**Comment by cadecairos** [comment]
That's one option.

There's also Signal (https://whispersystems.org) and Telegram (https://telegram.org/)

**Comment by gideonthomas** [comment]
@ryanpitts has the access been granted to the editors?

**Comment by cadecairos** [comment]
@ryanpitts we should move forward with this, I'm open to any means of getting they keys to Erin and Lindsay, so long as it's end-to-end encrypted.

**Comment by ryanpitts** [comment]
Agreed. Erin and Lindsay are up for any of those methods as well, so I'm recommending Signal. Will ask them to install, and then will connect with you for the handoff.

**Comment by ryanpitts** [comment]
Both editors are planning to install Signal -- I'll ping back once they're ready to go.

**Comment by cadecairos** [comment]
@ryanpitts Awesome, I'm not sure exactly how to link people on signal, but my phone # can be found in https://phonebook.mozilla.org/#search/Christopher%20De%20Cairos

**Comment by ryanpitts** [comment]
👍

**Comment by cadecairos** [comment]
How's this looking?

**Comment by ryanpitts** [comment]
@cadecairos checked in with Erin/Lindsay just now. We'll all be in Portland in person the second half of this week, so sounds like their plan is to install Whisper there and take care of everything. Will open an email thread with you so they can coordinate.

**Comment by cadecairos** [comment]
I've handed off the credentials to Erin and Lindsay using Signal.

**Comment by ryanpitts** [comment]
woo! Thanks!
