### ISSUE TITLE
Access to analytics

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#363]
More staff should leverage analytics to improve our work. 

It'd be great if you could give me access to thimble.mozilla.org, learnig.mozilla.org, and other primary domains. I currently can just view things filed under webmaker.org. 

What's the process for getting current and future staff on board? Is there anyway that we could simplify or decentralize this task?

Thanks!

**Comment by cadecairos** [comment]
Access to Google Analytics is controlled by MoCo, because they manage the account governed by Mozilla's contract with Google. We need to file Bugzilla bugs on a case-by-case basis to add people to various websites and to create new tracking codes

Let me see if I can find a mana article I can link here...

**Comment by xmatthewx** [comment]
Cool. Cool. It would also be helpful to have a list of MoFo properties to request. I'm not sure how they're grouped or named.

**Comment by cadecairos** [comment]
My Google account doesn't have access to all the properties we (mofo) have added to GA over the years. I'm not sure if we even have one canonical list. 

cc/ @simonwex

**Comment by cadecairos** [comment]
@simonwex do you now have access to _all the things_? We could add docs somewhere where we maintain a list of GA properties we have, so people can request access for their mofo accounts.

**Comment by alicoding** [comment]
@simonwex should have access to all things on the analytics account and @cadecairos should have access and edit rights to the analytics.

**Comment by cadecairos** [comment]
@xmatthewx What's the deliverable for this issue?

**Comment by xmatthewx** [comment]
I think many good things have been delivered
 - [ ] Give me access to Learning, Science, and other primary properties. I just have Webmaker site and app. 
 - [ ] Give staff a way to request access
 - [ ] Tell design/dev/program staff how to request access

**Comment by cadecairos** [comment]
So I can now see all the web properties we've got on GA, but I can't add users.

@xmatthewx I think what needs to happen here is:

1. When a staffer needs access to properties on AWS, they file a request here
2. I reach out (via a yet to be discovered mechanism) to someone at MoCo who manages GA and ask them to add so-and-so@mozillafoundation.org to the property.

We can document this in the dev-ops repo

**Comment by xmatthewx** [comment]
Okay. I can be a first test case. I currently only have access to Webmaker and Pulse. I'd like to get on Learning and Thimble and Advocacy and ... anything else important?

**Comment by cadecairos** [comment]
It's really inconsistent, but I did have the ability to add you to learning.mozilla.org

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1290472

**Comment by cadecairos** [comment]
I'm gonna kick the tires on that bug, it's seen no attention.

**Comment by xmatthewx** [comment]
Thanks for the proactive diligence.

**Comment by cadecairos** [comment]
Peter German is back from PTO and will assist me with this.

**Comment by cadecairos** [comment]
Just need-info'd Peter German on the bug.

**Comment by cadecairos** [comment]
@xmatthewx you should have access to all those GA properties now.

**Comment by xmatthewx** [comment]
yay. 🐢 slow and steady wins the race every time!
