### ISSUE TITLE
Migrate sciencelab self-hosted blog to wpengine

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/mofo-devops#364]
https://science.mozilla.org/blog is currently being fetched from self-hosted wordpress blog and should probably migrate to wpengine for maintainability and prevent any vulnerability as well.

@acabunoc can you grant me access to the self-hosted version of the blog?

cc @cadecairos @simonwex

**Comment by acabunoc** [comment]
I believe we *are* on wpengine? cc @cadecairos 

https://mozscienceblog.wpengine.com/

**Comment by cadecairos** [comment]
Yeah, there's definitely a science blog on wpengine. 

@alicoding I don't see a self-hosted mozsci wordpress instance in AWS anywhere..?

**Comment by alicoding** [comment]
In that case... closing this ticket 😃
