### ISSUE TITLE
learning.mozilla.org make thumbs are probably borked

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#365]
Based on the addition of CSP headers, these are probably borked, needs research.

**Comment by alicoding** [comment]
Which page is broken? I see all thumbnails for teaching activities.

**Comment by simonwex** [comment]
@cadecairos have you seen any evidence of this? (I added this ticket based on a convo during our scramble)

**Comment by cadecairos** [comment]
CSP might break it, but right now we're being blocked on CORS

**Comment by cadecairos** [comment]
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cade.makes.org/makes.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by cadecairos** [comment]
Fixed that by updateing the allowed origin in make-valet-prod.

I was right, lots of CSP violations loading thumbs. We will not be able to allow for all possible image thumbs.

perhaps we should just display placeholder images based on make type?

What do you think @simonwex

**Comment by cadecairos** [comment]
@gideonthomas found http://content-security-policy.com/ - which indicates that * can allow all sources for a directive (except filesyste: blob: and data:)

**Comment by cadecairos** [comment]
Fixed by mozilla/learning.mozilla.org#1962
