### ISSUE TITLE
Proposal to move discourse.mozilla-community.org  to community.mozilla.org 

### ISSUE THREAD

**Issue by kskarthik** [MozillaFoundation/mofo-devops#367]
I feel community.mozilla.org is apt for discourse location. Are there any problems to do so ? Also, it is easy to remember too http://community.mozilla.org

**Comment by flamingspaz** [comment]
Hey, thanks for filing an issue.

Moving under mozilla.org is definitely something we want to do in the future, but there are multiple things that may need to happen to be approved to be on mozilla.org (defining policies, security reviews, fixing usability issues, etc). There's no time estimate for this unfortunately.

I'm going to close this issue as the community Discourse is not a MoFo project (though the community instance wouldn't be possible without them :heart:). If you want to discuss more about this or anything related to discourse.mozilla-community.org feel free to open a thread in the [Community Ops/Discourse](https://discourse.mozilla-community.org/c/community-ops/discourse) category.

**Comment by kskarthik** [comment]
@flamingspaz Thanks for informing. I created a topic on discourse to discuss more :smiley:  https://discourse.mozilla-community.org/t/proposal-moving-discourse-to-community-mozilla-org/9643
