### ISSUE TITLE
source-elasticsearch-production going down for maintenance - 2016-07-25

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#368]
> Dear Amazon EC2 Customer,
>
> One or more of your Amazon EC2 instances is scheduled for maintenance on 2016-07-25 > for 2 hours starting at 00:00 UTC. During this time, the following instances in the us-east-1 region will be unavailable and then rebooted:
>
>  i-f8c57387
>
> Your instances will return to normal operations after maintenance is complete and all of your configuration settings will be retained. To continue normal operation and avoid any unavailability or reboots during this time, you can migrate the instances listed above to replacement instances. Replacement instances will not be affected by this scheduled maintenance. Otherwise, no action is generally required on your part (certain underlying system components may change at reboot time, and your operating system may prompt you to install additional software/drivers post-reboot as a result). If your instance is part of an auto-scaling group, then it will automatically be terminated and replaced by a newly launched instance during the maintenance window. 

CC/ @ryanpitts

**Comment by ryanpitts** [comment]
Ah, thanks for the ping! Will set myself a reminder to check search once that window is over.

@cadecairos Just for the sake of completeness, do we have a current snapshot of that instance if we needed to spin up a new one?

**Comment by cadecairos** [comment]
> Just for the sake of completeness, do we have a current snapshot of that instance if we needed to spin up a new one?

Not likely! I'll make one.

**Comment by cadecairos** [comment]
AMI + associated volume snapshots are being made.

**Comment by cadecairos** [comment]
Reminder: this is happening today!

**Comment by cadecairos** [comment]
or already happened? *checks*

**Comment by cadecairos** [comment]
Okay things should be back to normal now. Started up ES on that instance that got rebooted, and had source re-index all it's content into it. 

@ryanpitts can you confirm everything is in order?

**Comment by ryanpitts** [comment]
Everything working totally as expected. Thanks!

**Comment by cadecairos** [comment]
🎉
