### ISSUE TITLE
Access to mozillascience-org-assets S3 bucket

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#369]
### Details

Hi! We used to upload images for the science site to this bucket through a form on the old site (create an event, create a project). Now that the form is gone, can we upload images here directly?

Or - is there somewhere else we should host static images for the science site?

cc: @auremoser

**Comment by gideonthomas** [comment]
@acabunoc would you be able to file an issue in the science repo to allow this (uploading these images) through the admin interface as well?

**Comment by cadecairos** [comment]
If the need for this is immediate, I can generate a pair of keys that can upload to the bucket. Cyberduck is probably best tool to upload files ftp style: https://cyberduck.io/

@acabunoc is this an urgent need, or should we wait until we can add an upload tool on the admin interface?

**Comment by acabunoc** [comment]
Not *urgent* But if it's not done within a couple weeks we should get @auremoser a pair of keys.

@gideonthomas - I'll add this issue to the science repo!

**Comment by auremoser** [comment]
thank you @acabunoc @gideonthomas @cadecairos

**Comment by alicoding** [comment]
I have set this up and forwarded the information to @auremoser :)
