### ISSUE TITLE
Move science forum to RDS

### ISSUE THREAD

**Issue by flamingspaz** [MozillaFoundation/mofo-devops#37]
Currently, the science forum is hosted entirely on one server which isn't ideal. There's more information in #8 but the main issue is that the database is stored inside the container, so if the server dies we lose the data.

My recommendation would be to set up new infra similar to the other Discourse forums. I'm happy to take this since I've set up all the others.

https://wiki.mozilla.org/IT/Community/WG/Discourse

**Comment by simonwex** [comment]
Hey @flamingspaz, @jbuck thinks this might have already been done. Can you confirm?

**Comment by cadecairos** [comment]
@flamingspaz @jbuck What's the story here - has this been done?

**Comment by flamingspaz** [comment]
Not yet - I've been taking images every-so-often but I need to spin up one of the images to get ssh access. I have a fair bit of time over Easter and I'll try to get this done.

Note to self: it also uses mandrill which goes paid-only in mid-April.

**Comment by cadecairos** [comment]
> Note to self: it also uses mandrill which goes paid-only in mid-April.

This sounds rather urgent - Can I assis with this?

**Comment by cadecairos** [comment]
@flamingspaz what's the status of this issue? Any thing I can do to move it along?

Should we file an issue RE: mandrill?

**Comment by simonwex** [comment]
Closing as this is disappearing:
https://github.com/MozillaFoundation/mofo-devops/issues/158#issuecomment-214768857
