### ISSUE TITLE
move mofo.build to build.mozillafoundation.org

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-devops#370]
* Goal: move the WordPress site currently at mofo.build to build.mozillafoundation.org

**Comment by OpenMatt** [comment]
* Hosting. The site is currently hosted through Matt's personal account at NameCheap.com
* This replaces the current content at build.mozillafoundation.org. We can just nuke what's there right now (but archive it / back it up just in case)

**Comment by OpenMatt** [comment]
@cadecairos : can you give me an assessment of how long security review might take for this? is getting a simple WordPress site like this generally straightforward, or problematic?

If sec review is potentially onerous / difficult, we could just leave the site with the current URL and hosting instead. So let me know what you think?

**Comment by cadecairos** [comment]
> Hosting. The site is currently hosted through Matt's personal account at NameCheap.com
So, we'd need to migrate the site content over to wp-engine?

Sec review won't be long. we just need to check for all the best practice headers and whatnot. By running it on wp-engine, we'd already be in pretty good shape.

**Comment by OpenMatt** [comment]
ok great! thanks Chris. let me know if there's anything else you need from me on this.

**Comment by cadecairos** [comment]
What's the timeline for this move?

**Comment by OpenMatt** [comment]
@cadecairos as soon as its convenient for you. we're ready whenever you are.

**Comment by cadecairos** [comment]
@OpenMatt I see in namecheap there's some kind of "hosting" product. It says something about a cpanel - is that the wordpress hosting?

**Comment by cadecairos** [comment]
@OpenMatt Do you have an admin account on the wordpress instance behind mofo.build?

Could you create an admin account for me (using my mofo email)?

**Comment by cadecairos** [comment]
okay, so we've hit our limit for wp instances on wpengine (10)

We can either wait for the hive blog consolidation work to finish (should free up some space) or we can upgrade to the business plan (extra $150/month, 25 instances)

I'd prefer to wait for room to free up, but I'm not sure when the hive blog consolidation will be done.

**Comment by OpenMatt** [comment]
Ok thanks Chris.

Let’s just keep the site at mofo.build then. 
I don’t think we can wait for the hive blog work to be done.

Chris: can you re-direct build.mozillafoundation.org to mofo.build?

**Comment by cadecairos** [comment]
@OpenMatt done!

**Comment by cadecairos** [comment]
@OpenMatt Anything left to do here, now that build.mozillafoundation.org points to mofo.build?

**Comment by OpenMatt** [comment]
nope done! thanks.

**Comment by cadecairos** [comment]
🎉
