### ISSUE TITLE
Backpack statistics

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-devops#371]
I'd love to understand the usage of backpack over the last few months (or years if possible).

Specifically, I'd be interested in:

a) rate of issuance of badges per day/week/month
b) rate of retrieval of badge data per day/week/month
c) distribution of # of badges per user (-> what % of our users just create 1-2 badges, vs. some that actually create a meaningful set of badges)
d) a proxy for age of 'age of active users' -- I don't know how to measure it, but i'd love to find out if anyone comes to the backpack and keeps coming back more than a couple of days later.

/cc @simonwex @cadecairos

**Comment by cadecairos** [comment]
Is this data collected by Google Analytics? If so I'll need someone to get me access to that property.

sidenote: GA as a web app feels pretty broken, people keep saying I'm an admin, but I can't actually *do* anything or *see* anything in the site.

**Comment by davidascher** [comment]
No, the data mentioned above isn't captured by GA, I'm hoping there are SQL metrics that might help.

**Comment by cadecairos** [comment]
@davidascher  can you clarify something for me: Is the date a badge record was created the date it was issued, and if so, what constitutes when a badge is retrieved?

**Comment by cadecairos** [comment]
I've written queries that calculate daily, weekly and monthly counts for badges based on the "validated_on" field.

The openbadges db doesn't seem to have much beyond that. I'll look into the badgekit and badgekit-api databases to see what we can do there.

**Comment by davidascher** [comment]
Yes, date issued is when it was created; re: date retrieval that's probably
not doable w/o careful filtering of HTTP access logs.  Don't spend much
time on that (or any of these metrics).
