### ISSUE TITLE
Need Discourse New Log In Process Information Message

### ISSUE THREAD

**Issue by KGorr** [MozillaFoundation/mofo-devops#372]
Per https://github.com/MozillaFoundation/mofo-devops/issues/253 regarding https://forum.learning.mozilla.org, we need to communicate the new log in process for Discourse to eliminate any possible confusion for users. (No longer using Persona - only WebMaker) 

Old templates for re-purposing appreciated!

**Comment by hannahkane** [comment]
Couple questions for @cadecairos -what are the instructions for people who had been using Persona to log in? Do they need to create a Webmaker account? Will their history be preserved?

Are we able to identify Persona users to email, or do we need to do this as an in-app message for everyone?

**Comment by cadecairos** [comment]
A few scenarios here:

#### The user logged in with Persona, and has Webmaker account with  the same email address
logging in with the Webmaker account will log them into their existing discourse account.

#### The user logged in with Persona, and doesn't have a Webmaker account
As long as the user creates a Webmaker account with the identical email they used with persona, they'll log into their account.

#### The user logged in with Persona, and has a Webmaker account, but they don't have the same email
They're going to have to create a Webmaker account with the email they used with Persona.

**Comment by hannahkane** [comment]
Hmm...probably too complicated for an on-screen message. Can we isolate Discourse users who used Persona and email them specifically?

**Comment by KGorr** [comment]
That sounds like a great plan if it's doable @hannahkane. I'm already getting questions about why log ins aren't working... I would love to chat about a process to have proactive communications in place with projects like this before changes are made. :)

**Comment by cadecairos** [comment]
@KGorr We're going to just turn on Persona again, so that the change can be communicated in the forum.

**Comment by KGorr** [comment]
Sweet - that sounds great. Thank you!

**Comment by xmatthewx** [comment]
I agree with @hannahkane's suggestion. We should count many people `used Persona on Discourse` AND `don't have a matching Webmaker account`. The group is probably small. Sending an email or explaining via the forum is much easier than creating new UI. 

Can we migrate these people into Webmaker? On Login, I believe they will get a request to set a password.

**Comment by hannahkane** [comment]
Looks like we can export a list of all of our Discourse users, so we could email people that way. But it doesn't seem like it will be trivial to isolate people who've used Persona. So maybe best to just post to the Forum with details about why Persona is no longer an option, what to do if they don't have a Webmaker account, and an email address for how they can get help.

If others agree, I can draft something.

**Comment by KGorr** [comment]
cc'ing @ldecoursy, in case she wants to weigh in. 

@hannahkane - are you saying it isn't possible or is too tricky to isolate those who use persona?

**Comment by ldecoursy** [comment]
Given what we've been through with Discourse in the past, I think an email to all users might not be a bad idea either. Maybe we can make it more of an update (bookmark new URL, updates to logins, current most active conversations?)

Best,
Lainie

**Comment by hannahkane** [comment]
@kgorr - I actually don't know. I don't personally know how to isolate Persona-users, but maybe someone else does?

Regardless, I like @ldecoursy's idea about couching it in a general update. @KGorr - do you think that would work?

**Comment by KGorr** [comment]
+1 @hannahkane @ldecoursy!

**Comment by hannahkane** [comment]
Started a draft email and shared with @KGorr and @ldecoursy

**Comment by KGorr** [comment]
Thanks @hannahkane - if we can put a date on when persona will no longer be available, I think that would make it very clear and add urgency for users to start using WebMaker. I added this comment to the email draft too. Is this realistic/doable given the time frame?

**Comment by hannahkane** [comment]
What if we plan to send this email out on Monday, July 25th and say Persona will be removed as a login option on Monday, August 1st.

@cadecairos - would that work for you?

**Comment by KGorr** [comment]
FYI The email draft is ready to go as soon as we nail down a time frame. @cadecairos @hannahkane

**Comment by flamingspaz** [comment]
Persona's shutdown isn't until the end of November so I'd recommend giving people a good chunk of time (maybe a month?) so that if needed we could help them move.

**Comment by hannahkane** [comment]
OK, I can send this out tomorrow. @cadecairos - what date would you like for me to use as the date when Persona will no longer be available to use on Discourse?

**Comment by hannahkane** [comment]
ping @cadecairos ^

**Comment by cadecairos** [comment]
https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers

**Comment by hannahkane** [comment]
picking this up again!

@cadecairos - are you okay with me sending an email to our Discourse users tomorrow and saying that Persona will no longer be available after November 1st? This would mean that we shouldn't remove it from Discourse until at least November 1st, but could do at any convenient time between Nov 1 and Nov 30. Does that work?

**Comment by cadecairos** [comment]
@hannahkane sorry for missing your question, I'm okay for this to go out whenever we're ready.

**Comment by hannahkane** [comment]
OK, messaging is done! (Set up a global message on Discourse.) @cadecairos - After November 1, we can flip the switch on Persona on Discourse. Is there another ticket for that already?

**Comment by flamingspaz** [comment]
I got ya in #422, you'll probably have to remind me closer to the time though!

**Comment by hannahkane** [comment]
OK, will remind you. Thanks!
