### ISSUE TITLE
ensure sendto.mozilla.org redirects to donate post BSD

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#374]
Main issue here is I can see at least one link, shipped in firefox's about menu, for a donate that still uses sendto.

We need to make sure that's something we keep control of. Right now I think it's under moco?

@cadecairos 

and @damiankay for your info.

**Comment by cadecairos** [comment]
When the time is right, I'll file a bugzilla bug to make the change.

We can ask for one of two things - Moco sets up a permanent redirect for us or we set up a Cloudfront CDN that handles redirects for us.

We'd choose option 2 if Moco couldn't preserve Query strings on redirect when using option 1

**Comment by ScottDowne** [comment]
Why wait?

**Comment by cadecairos** [comment]
because isn't that how we access the bsd panel?

**Comment by ScottDowne** [comment]
yup, good call.

**Comment by cadecairos** [comment]
@valianttry @damiankay When do we want to do this?

**Comment by valianttry** [comment]
@cadecairos it should be happening already? I just tested and it appears to be redirecting. I'd double check with Scott, but at this point nothing should point to any sendto link.

**Comment by ScottDowne** [comment]
Yeah, the redirect works fine.

The donate link in the browser's about page links to sento.

**Comment by ScottDowne** [comment]
This is only really blocked because we still needed the BSD dashboard, which was used from the sendto url. Once we're done with the BSD dashboard, we can do a proper redirect from sendto, to keep it alive.

**Comment by cadecairos** [comment]
@valianttry @ScottDowne So, the  page at sendto.mozilla.org does a client side redirect, meaning BSD serves the page, and then it redirects. Once our contract officially ends, we're going to have to keep the redirect working another way. (basically, I'll ask MoCo WebOps to put a permanent redirect in place)

**Comment by cadecairos** [comment]
**Note:** The SSL Certificate for sendto.mozilla.org needs to be renewed in less than thirty days. I would prefer to not share secret key with BSD, so we should settle on a date to have the domain redirect permanently to donate.mozilla.org using our own infrastructure.

This isn't necessarily urgent, but it is important to put together a plan, soon.

cc @valianttry @simonwex

**Comment by cadecairos** [comment]
This is done

**Comment by cadecairos** [comment]
(https://bugzilla.mozilla.org/show_bug.cgi?id=1311146)
