### ISSUE TITLE
make teach-mozilla-org-staging.herokuapp.com a real thing

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#375]
Right now we have the odd situation where teach-mozilla-org-staging.herokuapp.com is an app that "exists", but it's not part of the list of regular mofo apps and we shouldn't use it, needing to use teach.mofostaging.net instead.

It would make a lot of sense to instead set up  learning-mozilla-org-staging.herokuapp.com, and then kill off both the teach--- instances, since the teach name no longer applies to the site that is getting deployed.

**Comment by cadecairos** [comment]
teach.mofostaging.net is teach-mozilla-org-staging

**Comment by Pomax** [comment]
based on MM conversation: these should be `learning[...]` now that we have quite a lot of people all working on the learning.mozilla.org website

**Comment by cadecairos** [comment]
- [ ] Update app name to learning-mozilla-org-staging
- [ ] update app env
- [ ] update teach-api-staging env

**Comment by cadecairos** [comment]
Completed.

https://learning.mofostaging.net
