### ISSUE TITLE
Replace the 2015 site with a redirect

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/mofo-devops#376]
### Details
Please replace MozFest 2015 site with a redirect. We're getting a lot of people hitting the old site, which is problematic. See discussion [here] (https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/69#issuecomment-235290635).

### Info & links
2016 site is www.mozfest.org

cc @Saallen @marcwalsh @mmmavis

**Comment by cadecairos** [comment]
https://2015.mozillafestival.org now redirects to https://mozillafestival.org
