### ISSUE TITLE
give http://mofostaging.net a landing page with all projects on it

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#377]
It would be very helpful to list all apps reachable on `mofostaging.net` for stage test purposes, so that people who forget staging URLs (me included!) can find and navigate to the specific stage test site they need to work with.

(Not sure if whatever takes care of the routing can actually generate that page, but if so: that'd be one less thing to update every time we add/remove mofostaging endpoints)

**Comment by cadecairos** [comment]
This would be super nice to have, but we really don't have the bandwidth to get on it right now.

**Comment by Pomax** [comment]
it doesn't need to be autogenerated, full hosted, awesomecakes - a static index.html with a dumb `<uL><li><a href="/learning.mofostaging.net">learning site</a></li><liL.... </ul>` will do just fine, since we don't exactly update mofostaging apps. I'll write you the html file if it's just a matter of then uploading it to S3 or sticking it in a dir that nginx sees as "root" right now

**Comment by cadecairos** [comment]
There's no nginx server running on mofostaging.net, all the subdomains are handled via DNS in Route53. We'd need to set up something specifically to serve that index file.

**Comment by Pomax** [comment]
ah

**Comment by cadecairos** [comment]
@Pomax Do you still think there's value for the team in this?

**Comment by Pomax** [comment]
absolutely: I would be surprised if anyone except devops and maybe @alanmoo knows the full list of projects we maintain.

**Comment by alanmoo** [comment]
I hate to disappoint, but....

(Agreed, this would be helpful)

**Comment by cadecairos** [comment]
haha, noone knows what's on mofostaging. not really.

I don't think there's any easy way to generate something here.

I could create a script that fetches info from AWS Route 53 about mofostaging.net, filter out all the CNAMES, and generate an HTML file, then upload it to S3. we can then serve this page, and have it run weekly or something (via  https://dashboard.heroku.com/apps/mofo-cron)

**Comment by patjouk** [comment]
#wontfix
It's not a priority for our team and might be revisited in the future if relevant.
