### ISSUE TITLE
teach-api uses "teach-api-prod" instead of "teach-api-production" on heroku

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#378]
somewhat cosmetic, but it breaks the pattern of `[app name]-[staging|production]` we use for everything else.

**Comment by cadecairos** [comment]
Based on the difficulty of making this switch without downtime [1] VS the gains from doing it (not really any) I'm going to suggest leaving this app as is. @Pomax can we agree on this?

1.  rename app, update id database, update CSP on learning, update config on learning site

**Comment by Pomax** [comment]
wfm
