### ISSUE TITLE
Recover an etherpad

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#379]
### Details

An etherpad was used to review schedule app options for Mozfest 2015. If we can recover the pad, we can shorten our current search. If we can't, we will survive. 

### Info & links

https://festival.etherpad.mozilla.org/2015scheltool

**Comment by cadecairos** [comment]
These pads were available for a limited time via the Moz VPN, but I'll attempt to access it anyways to see if I can get the data.

**Comment by cadecairos** [comment]
@xmatthewx I am awesome: **http://etherpad.io/p/2015scheltool-recovered**

**Comment by xmatthewx** [comment]
That was fast. 📈 👍 💯 🔥 🚀
