### ISSUE TITLE
Add ZenHub  badge to repos that use it

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#380]
ZenHub was kind enough to let us use their product under a non-profit license, so lets give them the shout out they deserve by adding a badge to README's that make use of ZenHub. (including this one)

https://github.com/ZenHubIO/support <- badge code available here

**Comment by Pomax** [comment]
updated learning.moz readme: https://github.com/mozilla/learning.mozilla.org/blob/develop/README.md

**Comment by cadecairos** [comment]
haha accidentaly thumbs-downed that. thanks, @Pomax

**Comment by cadecairos** [comment]
Added to this repo, and to Advocacy.

**Comment by Pomax** [comment]
Added to Teach-API

**Comment by cadecairos** [comment]
- [ ] MozillaFoundation/plan
- [ ] MozillaFoundation/Design
- [ ] MozillaFoundation/Mozfest2016_production

**Comment by cadecairos** [comment]
I got many, possibly not all of the repos connected to ZenHub in  the MozillaFoundation org, It's too bad their dashboard doesn't display repos that are using Zenhub.

Closing for now
