### ISSUE TITLE
Create Heroku pipeline for mozillafestival repo

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#381]
### Details

As we move to github flow, the mozfest site is one that would benefit from a pipeline, with automatic review apps. Can we make that happen? (I don't have permission) @cadecairos @mmmavis any issues you can think of with this?

**Comment by cadecairos** [comment]
created the [mozillafestival-org pipeline](https://dashboard.heroku.com/pipelines/3a52c84b-b13c-42b6-8cc2-652b646a8a8c)

staging is mozillafestival-org-staging
production is mozillafestival-org-production

we should convert the repo over to github flow before we set up deployments.

**Comment by cadecairos** [comment]
(which means we should drop deployments via travis, in favour of deploy hooks directly with Heroku)

**Comment by cadecairos** [comment]
To enable review apps we need to commit an app.json file to the repo

**Comment by cadecairos** [comment]
all done. Review apps enabled.
