### ISSUE TITLE
Admin rights for over arching organisational page

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mofo-devops#382]
Need access as an admin to Mozilla Foundation repo for @autonome so he can integrate Waffel.io as a project tool

### Info & links
Repo he wants to work within is 
https://github.com/MozillaFoundation/mozfest-program-2016
However he has admin rights to the repo already so he might need further rights on the organisation page https://github.com/MozillaFoundation if possible

**Comment by cadecairos** [comment]
I'd have to whitelist integrations with waffel.io with the org for this to work.

@Saallen Are there specific features that Waffel has that aren't offered by ZenHub?  They seem very similar (And we have unlimited free usage of the latter)

**Comment by Saallen** [comment]
@autonome would this work for you?

**Comment by cadecairos** [comment]
@autonome just pinging you to see what you think about using [Zenhub](https://zenhub.com) instead of Waffel

**Comment by Saallen** [comment]
Hey @cadecairos I pinged him yesterday and he is alll gravy with Zenhub- thanks 🍇

**Comment by cadecairos** [comment]
That's great! I've added a Zenhub badge to the repo to give Zenhub some love (they are letting us use it for free after all)

**Comment by Saallen** [comment]
Thanks- maybe I could ask you to join a wrangler call to help promote this tool ? 🎤

**Comment by cadecairos** [comment]
Sure! are we trying to promote Zenhub (to encourage people to use it), or give a crash course on how to install the addon and use the tool?

**Comment by Saallen** [comment]
It is a great project management tool so it would be good to give an overview on the tool and how to use it- you can give me the crash course and I can share the knowledge?

**Comment by cadecairos** [comment]
Sure! Can you find a spot in my calendar and send a meeting request?
