### ISSUE TITLE
Renew certificates for mozillascience.org

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#385]
### Expires on August 31, 2016

Current cert also includes:
* www.mozillascience.org
* forum.mozillascience.org
* badges.mozillascience.org

CC @acabunoc - Which, if any of these can/should we drop (Do you think the badges subdomain can be moved to a path on mozillascience.org?)

**Comment by acabunoc** [comment]
We can drop:
* www.mozillascience.org
* forum.mozillascience.org

For badges.mozillascience.org - let's try to move it to a path on `science.mozilla.org/badges` -- flagging @josmas

Question for @cadecairos - if badges.mozillascience.org is currently running on heroku, is it possible to have it running on a path?

**Comment by cadecairos** [comment]
Certificate renewe!

I've installed it on:

* The CDN redirecting `www.mozillascience.org` and `mozillascience.org` to `science.mozilla.org`
* The load balancer serving up forum.mozillascience.org
* I removed the CloudfrontCDN serving up `badges.mozillascience.org` and enabled the free SSL feature on the badges-mozillascience-org app, where the new certificate is now installed.
