### ISSUE TITLE
Renew Certificate for petitions.mozilla.org

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#389]
### Expires on September 15th

**Comment by cadecairos** [comment]
Were we going to redirect this to advocacy.mozilla.org?

@ScottDowne @valianttry

**Comment by ScottDowne** [comment]
That was a proposal, I forget if that was a decision.

**Comment by cadecairos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1298140 

I honestly don't remember filing this, but looks like we did make a decision to redirect.

**Comment by cadecairos** [comment]
Ongoing
