### ISSUE TITLE
Generate list of least active chat users

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#398]
I'd like to talk to the MoFos who aren't using chat to understand why. Can we generate two lists?

1. MozillaFoundation emails that aren't signed up for chat
2. 10-20 Least active @MozillaFoundation.org chat users

**Comment by cadecairos** [comment]
I don't have a canonical list of foundation staff emails to check against, but I can pretty easily craft a query to find the least active accounts

**Comment by alanmoo** [comment]
Alright, let's roll with that, it's probably more useful anyway. Can you also just give me a number of @MoFo accounts?

**Comment by cadecairos** [comment]
https://docs.google.com/a/mozilla.com/spreadsheets/d/1psWPweOgx6LDD_yrztc3DY0GABSMUCvN8i90HuIOSS8/edit?usp=sharing

Data in sheet is as of 3:45 PM EDT August 18, 2016
