### ISSUE TITLE
Set up discourse.mozilla-advocacy.org

### ISSUE THREAD

**Issue by flamingspaz** [MozillaFoundation/mofo-devops#4]
Need a Discourse instance up for discourse.mozilla-advocacy.org.

**Comment by jdotpz** [comment]
So here, we need an inbox.  Did we get an answer on which address to use?

**Comment by flamingspaz** [comment]
Yup! discourse-advocacy@mozilla.com preferred, discourse@mozilla-advocacy.org also acceptable. I'm thinking the former may be easier to get going?

**Comment by jdotpz** [comment]
https://mozilla.service-now.com/nav_to.do?uri=com.glideapp.servicecatalog_checkout_view.do?sysparm_sys_id=2881fddfd84e31001518e7275d0aefeb is opened for discourse-advocacy@mozilla.com address, to point to Yousef, JP, and Dave Steer.
