### ISSUE TITLE
Investigate non-LastPass password managers

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#40]
Right now we're using LastPass to share secrets between MoFos. It's not great from a UI/UX perspective, but it is secure. Are there any alternatives that are better in the UI/UX department but are still secure?

**Comment by davidascher** [comment]
Likely only interesting to devops specifically:
https://hashicorp.com/blog/vault.html

**Comment by simonwex** [comment]
@jbuck, I sent you an invite to https://commonkey.com/ it looks pretty nice. Would need it reviewed.

**Comment by jbuck** [comment]
We actually solved this by using 1Password for Teams!
