### ISSUE TITLE
Redirect URLs for copyright campaign

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#402]

**Comment by KevZawacki** [comment]
http://advocacy.mozilla.org/copyright

and

mzl.la/copyright

**Comment by HPaulJohnson** [comment]
there's a bunch of versions of the above with various URL parameters for GA attached. assume you don't need all those so this is just a note to say that we'll need to maintain those parameters on the redirected domain.

**Comment by cadecairos** [comment]
The redirect maintains params, and is in place on https://advocacy.mozilla.org/copyright
