### ISSUE TITLE
Can we bypass paid content requirement for YouTube Live?

### ISSUE THREAD

**Issue by KGorr** [MozillaFoundation/mofo-devops#404]
Mozilla Learning uses Google Hangouts on Air to broadcast live events for our community embedded here: monthly [Curriculum Workshop](https://learning.mozilla.org/en-US/community/curriculum-workshop) and [Community Call](https://learning.mozilla.org/en-US/community/community-call). 

HOA is merging with YouTube Live effective Sept 12, so we have been trying to migrate over to the new platform.  I've successfully gotten through 2 steps (linking AdSense account, enabling monetization) for us to use YouTube Live. Now, it seems the next hoop is a requirement to have 1000 active subscribers in order to turn on paid content...which must be done in order to embed live streaming. We only have 17 subscribers at the moment.

We don't want to actually utilize the paid content (already talked to legal about this), we are just required to enable it to embed the broadcast. Do we have a google representative that works with Mozilla apps who can help us bypass this requirement? Any other ideas?

Our next event is scheduled for Sept 13, so this is an urgent issue to resolve.

Referencing https://github.com/mozilla/learning.mozilla.org/issues/2094

Cc @ldecoursy @simonwex

**Comment by cadecairos** [comment]
@KGorr It might be worthwhile to file a google apps request on Service-Now to see if they can help out.

**Comment by simonwex** [comment]
You could also ask `soap` on IRC for help.

**Comment by KGorr** [comment]
Thank you @cadecairos @simonwex!
