### ISSUE TITLE
I would like an FTP server please - for the Open IoT Studio 

### ISSUE THREAD

**Issue by ileddigital** [MozillaFoundation/mofo-devops#406]
Hello

Please could we set up an FTP server for the Open IoT studio with @thornet . In the first instance to be able to upload images (max 2MB each) - up to 500MBs. 

Thank you

Jon

**Comment by cadecairos** [comment]
I can set up a server for you, but is it possible at all for you to use something more robust like AWS S3 for image uploading?

**Comment by cadecairos** [comment]
@ileddigital Is this something you're still hoping to get set up/need a solution for?

**Comment by cadecairos** [comment]
@ileddigital ping?

**Comment by cadecairos** [comment]
I haven't heard anything here in a while, so I'm closing it for now.
