### ISSUE TITLE
Set up Network Mapping app on Heroku

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#409]
### Details

- [x] A heroku app to deploy to
- [x] deploy/configure permissions for @liberaliscomputing
- [x] A GA property to track activity on the app
- [ ] ~~A Domain? (we could always just stick with the Heroku domain)~~

@alicoding is driving this.
@liberaliscomputing please correct me if I misinterpreted your needs or missed something. Ali will be able to help you with Heroku if you're unfamiliar.

**Comment by liberaliscomputing** [comment]
Since the app
- has static content (HTMLs, JSs, etc.)
- should listen to participants' current status of following in real-time
- needs to be up and running during Mozfest
AWS may be more proper? I need @cadecairos ' and @alicoding 's opinions!

**Comment by alicoding** [comment]
If there's no server involve in term of serving the files we have two options here. Put them on GitHub pages and create domain point to it. Or put the content on S3 and get the domain for that.

The other option we also have here is create a small node server app which will help put this up on heroku.

**Comment by cadecairos** [comment]
I had a chat with @liberaliscomputing  in Mattermost and we determined that Heroku is indeed the place for this. The server component of the app is written in Python/Flask and should run perfectly fine on Heroku.

**Comment by alicoding** [comment]
I've created the app on heroku and added Meenchul as project collab 👍

**Comment by cadecairos** [comment]
@liberaliscomputing is there anything I can do to help you get the application ready for deployment on Heroku?

**Comment by cadecairos** [comment]
@liberaliscomputing Any update on this? how can I help move it along

**Comment by liberaliscomputing** [comment]
@cadecairos I am working on fixing some issues related to the scalalbility of the app. And I figured we may not be able to use GA for this app: most of the activities with the app would be viewing user profiles and we cannot log twitter handles with GA, right? (We cannot log identifable user information with GA, right?)

**Comment by liberaliscomputing** [comment]
@cadecairos Hey, the app is now running on https://network-mapping-app.herokuapp.com/ ! Thanks for your support and @acabunoc assigned [mzl.la/map](mzl.la/map) to this app!
By the way, I am really sorry to make the last minute request, but could I still get GA code for the network mapping app? We won't track clicked Twitter handles, but still can track which type of visualization is clicked the most, corresponding to the increasing number of users.

**Comment by cadecairos** [comment]
GA was set up. Marking this as resolved.
