### ISSUE TITLE
CORS for Review Apps

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#411]
Review apps are great for testing out a feature. But they become redundant when we enable CORS on dependent services. 

For example, when we open up a review app for the learning site, we use a lot of the functionality because it cannot communicate with the teach-api because of CORS.

It would be nice to figure out a way to regex the review app subdomains and add it to our CORS config so that we don't keep encountering this issue.
Not sure what the security considerations for this are, but it probably needs discussion.

**Comment by cadecairos** [comment]
If we can do this on staging **only** then I'm all in

**Comment by gideonthomas** [comment]
Yeah this should only be for staging since that's often what is linked to in review apps

**Comment by cadecairos** [comment]
@gideonthomas I think this should be re-filed on the project repos that specifically need these changes.
