### ISSUE TITLE
Requesting S3 bucket and appropriate credentials for use with Travis CI

### ISSUE THREAD

**Issue by ryanwarsaw** [MozillaFoundation/mofo-devops#412]
### Details

I'm requesting this bucket for a project called "Jisort", it's a DSO prototype Android app. My goal is to automatically deploy the Travis CI APK binary (as a result of building the app) to S3 that would be referenced using a very short URL, allowing people to download the latest version of the app without having to setup any sort of development environment.
### Info & links

https://github.com/mozilla/Jisort

**Comment by ryanwarsaw** [comment]
@cadecairos is this something you could possibly help me with sometime this week, if you have a free moment? I'm also wondering what process I would need to go through in order to have something like ```mzl.la/jisort``` that could be pointed to that bucket for easy remembrance.

**Comment by cadecairos** [comment]
I'll make sure this gets done in the next day or so

> mzl.la/jisort

I have  access to the Bitly account and can get you this.

**Comment by gideonthomas** [comment]
Credentials given to ryan! Bucket name: `jisort`

Ryan will clarify what the name of the object being put in the bucket will be!
From what I understand, it will only be one file that will be overwritten everytime a new version of the apk is pushed up.

cc @cadecairos

**Comment by cadecairos** [comment]
@ryanwarsaw Have we got an idea of the APK URL?

**Comment by cadecairos** [comment]
@ryanwarsaw Can we consider this closed?

**Comment by ryanwarsaw** [comment]
@cadecairos Yes!

**Comment by ryanwarsaw** [comment]
The credentials I was given for the ```jisort``` S3 bucket don't appear to be valid, when I test them out in Travis CI it gives me an invalid signature error (Signature expected isn't valid).

Is it possible I can get new credentials generated and see if that solves the issue? ⛄️ 

Travis CI Logs: https://travis-ci.org/mozilla/Jisort/builds/185367809

**Comment by gideonthomas** [comment]
@ryanwarsaw would you be able to try triggering a rebuild (I feel like this was a time-based failure)

**Comment by ryanwarsaw** [comment]
@gideonthomas I triggered rebuild, the build still fails for the same reason. 

Travis CI Logs: https://travis-ci.org/mozilla/Jisort/builds/185545923

The credentials are identical to the ones I was given, I'm thinking it could be an issue with the Travis CI integration itself, are the S3 credentials for Travis account-based ones? It could be something as simple as that, I'm unable to verify this due to permissions though.

**Comment by gideonthomas** [comment]
It's weird that it was working before though. But now, I'm also seeing that the bucket is empty.

anayway, @ryanwarsaw I opened up a PR with new credentials and disabled the old ones: https://github.com/mozilla/Jisort/pull/238

**Comment by gideonthomas** [comment]
Looks like the problem still persists. @cadecairos any ideas?

**Comment by ryanwarsaw** [comment]
When I look at the ```Integrations and services``` tab in the repository settings, the Travis CI integration says it's never run (even though clearly I'm doing Travis CI builds).

**Comment by ryanwarsaw** [comment]
It now works! Thanks @gideonthomas 🎉
