### ISSUE TITLE
Set up staging instance for mozfest-event-app

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#414]
### Details

As discussed in https://github.com/mozilla/mozfest-event-app/issues/248#issuecomment-246804138, we should

1. [ ] set up staging instance on S3
2. [ ] make sure pushing to `master` triggers updates to the staging instance. 

### Info & links

- https://github.com/mozilla/mozfest-event-app/issues/248#issuecomment-246804138

**Comment by mmmavis** [comment]
@cadecairos I forgot what the staging URL is 😂 Can you paste it here?

**Comment by cadecairos** [comment]
here it is: https://mozfest-app-2016.mofostaging.net/

Today I learned you can make emojis into links [🎉🍰 🎉🍰 🎉🍰 ](https://mozfest-app-2016.mofostaging.net/)

**Comment by mmmavis** [comment]
hahahahha that's my punctuation for period
😉

**Comment by mmmavis** [comment]
Is this ticket done then, @cadecairos ?

**Comment by cadecairos** [comment]
I think so, when we're ready for production we can file a new issue.

**Comment by mmmavis** [comment]
[New ticket](https://github.com/MozillaFoundation/mofo-devops/issues/415) has already been filed! :smile I just need to connect to program team and update the ticket!
