### ISSUE TITLE
Staging instence heroku app for salesforce to nationbuilder

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#416]
@cadecairos This request was in my inbox from Walter, and I think if it's easy, we should do it.

The idea is so things can be tested without corrupting what's in salesforce.

If you have another way to get the testing ability, I'm open to that too.

**Comment by cadecairos** [comment]
@ScottDowne I've created a Heroku app (moz-nb-salesforce-staging), and a new pipeline to connect staging and production. I've set it to autodeploy master to staging and I disabled autodeploy on production. 

Walter has been added as a collaborator, he just needs to configure it to use the sandbox.

**Comment by cadecairos** [comment]
done
