### ISSUE TITLE
GA token for Study Group Orientation materials

### ISSUE THREAD

**Issue by auremoser** [MozillaFoundation/mofo-devops#418]
cc: 
@cadecairos 
@acabunoc 
@zee-moz 

### Details

I put together a [little site](https://mozillascience.github.io/study-group-onboarding/) for Zannah to build the Study Group Orientation materials. In echo of the [Leadership Training site](https://github.com/zee-moz/leadership-training/) it is a Gitbook stored in [this github repo](https://github.com/mozillascience/study-group-onboarding/), using master and gh-pages branches with Travis for building: from markdown in `master`, to html in `gh-pages`. At present, there's a [book.json](https://github.com/mozillascience/study-group-onboarding/blob/master/book.json#L10) file that has some config information include a Google Analytics Token, which I borrowed from the Leadership curriculum.

![screen shot 2016-10-03 at 11 34 58 am](https://cloud.githubusercontent.com/assets/1559703/19042984/39b8e618-895c-11e6-8763-3917223bf9b7.png)

### Ask

Since I'm cribbing the Leadership Training GA token, I would like to make a new one for the Study Group Onboarding materials, and log it in [book.json](https://github.com/mozillascience/study-group-onboarding/blob/master/book.json#L10). I'm happy to fill out a form if necessary, just let me know what I need to do to get a new token.

![screen shot 2016-10-03 at 11 35 12 am](https://cloud.githubusercontent.com/assets/1559703/19042972/31564dbc-895c-11e6-95ba-68a85217df03.png)

### Info & links

We'll be debuting the curriculum with select community members on Friday, but it's not really a rush, if this has to happen in two weeks, it's o.k., we'll probably still be grooming the content then.

* [Github repo](https://github.com/mozillascience/study-group-onboarding)
* [GH-Pages Site](https://mozillascience.github.io/study-group-onboarding/)
* [Roadmap/Timeline](https://github.com/mozillascience/study-group-onboarding/blob/master/ROADMAP.md) 
* [Travis site](https://travis-ci.org/mozillascience/study-group-onboarding/builds)
* [book.json](https://github.com/mozillascience/study-group-onboarding/blob/master/book.json#L10)

**Comment by cadecairos** [comment]
@auremoser Here's the GA code:  UA-49796218-49 

Be sure to [respect DNT settings with a script like this](https://gist.github.com/cadecairos/416e7abe6aab11b8317833924ed1e45d)

I sent your work email an invite to read/analyze the GA view for that page

**Comment by acabunoc** [comment]
whoa so fast!

**Comment by auremoser** [comment]
Thank you @cadecairos !!! + @acabunoc !

**Comment by cadecairos** [comment]
Marking this as closed
