### ISSUE TITLE
Set up GA for science.mozilla.org

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#420]
### Details

We need to add GA to the new science site. Please set it up and let me know the tracking code.

**Comment by cadecairos** [comment]
@alanmoo We need to make sure we wrap the GA script with this one, to respect DNT headers.

https://gist.github.com/cadecairos/416e7abe6aab11b8317833924ed1e45d

**Comment by cadecairos** [comment]
@alanmoo Here's the tracking ID: UA-49796218-50

Remember to use the script wrapper I linked above.

Who needs access to read and analyze?

**Comment by alanmoo** [comment]
Great question. @stephwright?

**Comment by stephwright** [comment]
Ok... here's where I play stupid (while not really playing)... What is GA?  And DNT?

**Comment by cadecairos** [comment]
GA = Google Analytics
DNT = Do Not Track (the feature that some modern browsers let you enable to ask sites to not track you)

**Comment by stephwright** [comment]
Ahh!  Thanks!  
Read & analyze would be at minimum: me, @arlissc, and @acabunoc as backup.  
In the interest of sharing data and learning from it, is there any reason anyone in MLN couldn't at least read the analytics?  (She asks w/o knowing all that's involved.)
Guess I'm asking what the norm is here.

**Comment by cadecairos** [comment]
There's no reason why any staff member shouldn't be able to read the data, it's just that we need to add people manually to the Google Analytics Property, which would be tedious to do for so many people. It's better to anticipate who needs access in the short term and handle giving out access as it's required.

I'll go ahead and add you, Arliss and Abby to the GA property, you should see an email notification from Google Analytics shortly.

**Comment by stephwright** [comment]
Urg... yes.  that sounds good.  Thanks!

**Comment by alanmoo** [comment]
@cadecairos can you add me too, so I can make sure it works once I implement it?

**Comment by cadecairos** [comment]
@alanmoo done

**Comment by stephwright** [comment]
Thanks both of you!!!
