### ISSUE TITLE
Decommission persona on forum.learning.mozilla.org

### ISSUE THREAD

**Issue by flamingspaz** [MozillaFoundation/mofo-devops#422]
Turn off persona on the learning discourse sometime in November

**Comment by cadecairos** [comment]
> Turn off persona on the learning discourse sometime in November

Actually, we've communicated to the discourse users that we're turning it off on 
November 1st. However, that is the Tuesday after Mozfest, so we can always put it off to the 2nd.

**Comment by flamingspaz** [comment]
the Tuesday after Mozfest it is then!

**Comment by flamingspaz** [comment]
this is done!

**Comment by hannahkane** [comment]
Belated thanks, @flamingspaz!
