### ISSUE TITLE
Enable Google Analytics for Internethealthreport.org 

### ISSUE THREAD

**Issue by Solanasaurus** [MozillaFoundation/mofo-devops#424]
### Details

Hello this is a request for Google Analytics to be enabled on the new website for Internethealthreport.org that will be publicly launched on Monday, November 21 but needs to be ready for testing the week before. So, Thursday, November 17, ideally.

Many thanks!
### Info & links

https://Internethealthreport.org

**Comment by cadecairos** [comment]
This is done
