### ISSUE TITLE
Redirect hivekc.org and hivecha.org to learning.mozilla.org/gigabit

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#425]
All of the necessary Gigabit content from these two Wordpress sites—hivekc.org and hivecha.org—has been added to a new home at learning.mozilla.org/gigabit. We can now retire these sites, by redirecting users to the new home on learning.m.o.

cc @jenntbeard @LindseyInCHA

**Comment by jenntbeard** [comment]
Great, so all the unduplicated CHA/KC posts were migrated to the existing Gigabit blog? I am getting ready to put a new post up - assuming I will still do that through the Gigabit WP site.

**Comment by cadecairos** [comment]
Can this wait for the gigabit blog content to be migrated over to the learning blog? It would simplify setting up the redirect.

**Comment by jenntbeard** [comment]
I was working on it now to go up this week - do you know when the gigabit content is to be migrated over to the learning blog?

**Comment by cadecairos** [comment]
waiting on #300 to be completed

**Comment by cadecairos** [comment]
> I was working on it now to go up this week - do you know when the gigabit content is to be migrated over to the learning blog?

We're going to be doing the migration before All-Hands, but until then you can keep writing for the blogs.

**Comment by cadecairos** [comment]
@gideonthomas does this issue cover what was asked in #440?

**Comment by gideonthomas** [comment]
@cadecairos Probably not! Don't we have to file a bug with MoCo to redirect the traffic from there since it's on the mozilla.org domain?

**Comment by cadecairos** [comment]
This was fixed in #472
