### ISSUE TITLE
Enable Google Analytics for the Open Leadership Training Series

### ISSUE THREAD

**Issue by acabunoc** [MozillaFoundation/mofo-devops#426]
### Details

Could I get a GA token & access for the Open Leadership Training Series? No rush.

### Info & links

https://mozilla.github.io/open-leadership-training-series/

**Comment by cadecairos** [comment]
Waitin on a legal bug that's blocking our mofo GA account. I'll do this when that is completed, unless we need it urgently.

**Comment by acabunoc** [comment]
not super urgent, waiting is cool

**Comment by acabunoc** [comment]
Hey @cadecairos! Any update on this?

**Comment by cadecairos** [comment]
Yeah, the folks at MoCo who run Analytics hit a snag transferring our properties over to the new account, but they're working through it with GA Support as we speak. I'm hopeful that this (the work on GA) might be completed before next week, and I'll be able to add a view for this URL on the analytics account.

**Comment by acabunoc** [comment]
hello again @cadecairos! any update?

**Comment by cadecairos** [comment]
Hey @acabunoc - sorry for the long delay. I'm not seeing much activity in the GA account migration I've been wating on, so I just created a property and view for this.

Here's the ID: UA-87658599-3

You should get an invite by email to read/analyze the view.

**Comment by acabunoc** [comment]
Thank you!

**Comment by cadecairos** [comment]
You're welcome! Calling this one completed - re-open if something doesn't work right!
