### ISSUE TITLE
Setup S3 bucket for Pulse

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#430]
We've got images. Need a place to store 'em. Can we have a bucket? Discussion here: https://github.com/mozilla/network-pulse/issues/228

**Comment by cadecairos** [comment]
- [ ] Create an s3 bucket
- [ ] Create a CloudFront CDN to cache image assets
- [ ] create IAM user for uploading images to {s3 bucket}/network-pulse/{objects}

**Comment by gideonthomas** [comment]
Waiting on the back-end to be implemented after which we can exchange credentials to upload to the bucket.

The current assets have already been uploaded to the bucket and can be accessed using  https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/<asset name>
For e.g.  https://d27v9tuhdmbcr4.cloudfront.net/network-pulse/A-Painter.png

**Comment by xmatthewx** [comment]
Thanks @gideonthomas. Since it'll take time to build the back-end, I'd like to update the current links. Can you or @alanmoo generate a file list? It shouldn't be too tricky to merge that into our current data set.

**Comment by gideonthomas** [comment]
I can do that!

**Comment by gideonthomas** [comment]
http://etherpad.io/network-pulse-asset-links

**Comment by xmatthewx** [comment]
Thanks @gideonthomas !

**Comment by cadecairos** [comment]
@xmatthewx Was this bucket put in use for the v2 version of pulse

**Comment by alanmoo** [comment]
I believe the entries in the API are using links to images in this bucket. I'm not sure how images are being uploaded on the front end. @mmmavis?

**Comment by mmmavis** [comment]
Ah for that I mistakenly assumed we were still doing "include a link to your thumbnail" instead of "upload your thumbnail" for the v2 initial launch. I don't know how the flow works for image uploading. Is it the front end that has to interact with S3 bucket or it's the back end's job? 

/cc @Pomax

**Comment by Pomax** [comment]
I don't think we ever discussed this in relation to the network pulse API server... given that you need API keys to publish to S3, and we don't want to expose those client side, this might require additional work at for the API server to accept forms with images and then rather than storing them internally, sending them on to S3 and instead storing the resulting URL.

(This probably needs a bit of dicussion, perhaps we can talk about that during today's call.)

**Comment by xmatthewx** [comment]
Is this still blocked? I believe @Pomax is ready to put it to use.

**Comment by gideonthomas** [comment]
This has been setup and configured in the API.
