### ISSUE TITLE
Pull some stats 

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#432]
### From login system

 * Total number of users
 * Total number of new users in 2014, 2015, 2016
 * Unique users logged in per month
 * Unique users logged in in the past year

### From teach

 * Unique users logged in per month
 * Unique users logged in in the past year

### From Webmaker app

 * Unique users logged in per month
 * Unique users logged in in the past year

**Comment by cadecairos** [comment]
https://docs.google.com/document/d/1GPvMHrrUR7LY_1QK-n27Vy8GCuL0ZQBocEnN60kHdXk/edit

@simonwex you've been granted access.

**Comment by cadecairos** [comment]
completed!
