### ISSUE TITLE
Remove past event from Gigabit Event Page

### ISSUE THREAD

**Issue by jenntbeard** [MozillaFoundation/mofo-devops#434]
### Details
MozFest has passed, we'd like to remove it from our upcoming events page. (I know eventually we will be able to do this ourselves, but I don't think we can do this yet, correct?)

### Info & links
On https://learning.mozilla.org/en-US/gigabit/events, there is an event that has passed - MozFest. Please remove it. Thanks!

**Comment by gideonthomas** [comment]
Refiled in the learning.mozilla.org repo https://github.com/mozilla/learning.mozilla.org/issues/2393
