### ISSUE TITLE
migrate mofo.build from namecheap

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#435]
### Details

- [x] Transfer domain to Mozilla
- [x] Migrate site to WPEngine
- [x] Install LetEcrypt Certificate

I'll need @OpenMatt's help on this

**Comment by OpenMatt** [comment]
Hey, Chris! Let me know the best way to help. I'll get you my credentials for Namecheap so you can manage whatever needs handling from that side.

**Comment by cadecairos** [comment]
Just waiting on the domain transfer to process now!

**Comment by cadecairos** [comment]
All done!
