### ISSUE TITLE
Create bit.ly link mzl.la/jisort-latest

### ISSUE THREAD

**Issue by ryanwarsaw** [MozillaFoundation/mofo-devops#437]
### Details

Please create a bit.ly link ```mzl.la/jisort-latest``` and point it towards the S3 bucket ```jisort``` and the specific file ```Jisort-latest.apk```. Thanks! ☃️

**Comment by cadecairos** [comment]
@ryanwarsaw What's the full URL?

**Comment by ryanwarsaw** [comment]
@cadecairos I don't know what the full URL is for the S3 bucket, but I do know the name of the bucket and the file within the bucket it needs to point to.

**Comment by cadecairos** [comment]
Done!

https://mzl.la/jisort-latest
