### ISSUE TITLE
Clarify gigabit language on landing page

### ISSUE THREAD

**Issue by jenntbeard** [MozillaFoundation/mofo-devops#438]
### Details
We would like to replace the text under the 'What is Mozilla Gigabit?' header on the landing page in an effort to be more clear about what we mean, why we're doing the work and leave people wanting to know more (not less) about the wonderful world of the gig.

Old copy:
Mozilla Gigabit Community Fund provides catalytic funding in US communities to support pilot tests of gigabit technology and related curricula. We increase the participation in next-generation innovation to help support an Internet where all people are empowered, safe, and independent.

New copy:
The Mozilla Gigabit Community Fund provides grant funding in select U.S. communities to support pilot tests of gigabit technologies such as virtual reality, 4K video, artificial intelligence, and their related curricula. In so doing, our goal is to increase participation in technology innovation in support of a healthy Internet where all people are empowered, safe, and independent online.

### Info & links
The paragraph is on this page: https://learning.mozilla.org/en-US/gigabit 

@LindseyInCHA

**Comment by gideonthomas** [comment]
@jenntbeard I think these issues should be filed in the mozilla/learning.mozilla.org repo instead since it is primarily content related while this repo is mainly for setting up websites/apps and making sure they stay up.

**Comment by gideonthomas** [comment]
Re-filed here: https://github.com/mozilla/learning.mozilla.org/issues/2400
