### ISSUE TITLE
Fix third criteria on Apply page

### ISSUE THREAD

**Issue by jenntbeard** [MozillaFoundation/mofo-devops#439]
### Details
On the Apply page (https://learning.mozilla.org/en-US/gigabit/apply), the third funding requirement criteria should read: "Leverage next-generation technologies like virtual reality, 4K video, artificial intelligence, and their related curricula"

### Info & links
https://learning.mozilla.org/en-US/gigabit/apply

@LindseyInCHA

**Comment by gideonthomas** [comment]
@jenntbeard I think these issues should be filed in the https://github.com/mozilla/learning.mozilla.org repo instead since it is primarily content related while this repo is mainly for setting up websites/apps and making sure they stay up.

**Comment by gideonthomas** [comment]
Re-filed here: https://github.com/mozilla/learning.mozilla.org/issues/2401
