### ISSUE TITLE
Create Pingdom account for Adam

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#44]
@adamlofting needs a Pingdom account so he can get additional information about uptime and such.

**Comment by jbuck** [comment]
We also brainstormed all of the sites that should be added to Pingdom:

* id.webmaker.org
* api.webmaker.org
* teach.mozilla.org
* teach-api
* webmaker.org
* webmaker mobile app
* advocacy / fundraising forms (that isn't hosted on BSD)

**Comment by jbuck** [comment]
Sent an account invitation to @adamlofting

**Comment by davidascher** [comment]
We should probably monitor donate.mozilla.org even if it's not our
responsibility to keep it up (assuming low cost)

**Comment by jbuck** [comment]
@davidascher Copied that into #30
