### ISSUE TITLE
Redirect https://www.mozilla.org/en-US/gigabit/ to https://learning.mozilla.org/en-US/gigabit

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#440]
### Details
Now that we've launched the Gigabit section of the Learning site, we want to direct all traffic there. Can we redirect users who land on https://www.mozilla.org/en-US/gigabit/ to https://learning.mozilla.org/en-US/gigabit?

cc @jenntbeard

**Comment by cadecairos** [comment]
In Progress: https://bugzilla.mozilla.org/show_bug.cgi?id=1335040

**Comment by cadecairos** [comment]
This was completed.
