### ISSUE TITLE
Upload mp4 and WebM Thank You Video Exports to CDN

### ISSUE THREAD

**Issue by beccaklam** [MozillaFoundation/mofo-devops#441]
### Details
Upload mp4 and WebM exports of Donor Thank You videos to cloud front and provide src to @beccaklee after. 

### Info & links
Videos can be found in this folder: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0ay1vaXdUdzRLNEE
You'll need to go into each folder (cute, sincere, hero) for the mp4s and WebMs. 

Thanks in advance!!

**Comment by cadecairos** [comment]
- https://d24kjznqej0s8a.cloudfront.net/2016/eoy/Cute/Cute_Final.mp4
- https://d24kjznqej0s8a.cloudfront.net/2016/eoy/Cute/Cute_Final.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/eoy/Hero/Hero_Final.mp4
- https://d24kjznqej0s8a.cloudfront.net/2016/eoy/Hero/Hero_Final.webm
- https://d24kjznqej0s8a.cloudfront.net/2016/eoy/Sincere/Sincere_Final.mp4
- https://d24kjznqej0s8a.cloudfront.net/2016/eoy/Sincere/Sincere_Final.webm

@beccaklam @natalieworth @lovegushwa
