### ISSUE TITLE
Transfer popcornjs documentation to Github

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/mofo-devops#445]
### Details

If possible, lets transfer the documentation that is at 
http://popcornjs.org/popcorn-docs/

Into a github repo so that we can simply host it as a github page.

**Comment by cadecairos** [comment]
This is technically done already: https://mozilla.github.io/popcorn-docs

**Comment by cadecairos** [comment]
I updated links on the readme to point to the gh-pages site, and removed references to the old site. closing this one out.
