### ISSUE TITLE
Have popcornjs.org resolve to github page

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/mofo-devops#446]
### Details

The popcornjs.org page hasn't been maintained in years, and we should simply have that domain resolve to the github page.  From there, we can let folks know the library is no longer maintained.

**Comment by Pomax** [comment]
Can we figure out some good copy for the github page to explain "we don't maintain this, but if *you* want to become the maintainer, we'll be happy to give you the keys to the popcorn kingdom"?

**Comment by cadecairos** [comment]
How is that site hosted? I don't have any records for it on AWS.

**Comment by cadecairos** [comment]
Based on the name servers (`dig ns popcornjs.org`), I think MoCo manages it with MarkMonitor. I'll be able to file a bug for a redirect to the github project page.

**Comment by brettgaylor** [comment]
@Pomax do it.

**Comment by brettgaylor** [comment]
@cadecairos sounds great and matches my memory of where we landed with this.  Maybe we should grab the content from where its hosted at the same time?

**Comment by floatingatoll** [comment]
Hi from MoCo webops. We (Mozilla) need to urgently implement this redirect. There are easily-discoverable security vulnerabilities with the current site and we'd rather redirect it than take it offline. @brettgaylor, since @cadecairos is PTO, is it okay if we set up this redirect immediately, and leave y'all to the effort of turning down the old instance at vesrv?

**Comment by Pomax** [comment]
@floatingatoll hi from the MoFo production team: hit it. No need to keep security issues alive for a project we no longer even work on or support!

**Comment by floatingatoll** [comment]
Yay, thanks :)

**Comment by floatingatoll** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1334200 filed with a note to update this issue when it's done.

**Comment by Pomax** [comment]
@floatingatoll can you add me to the CC list for that bug? (:pomax should pull up the right address)

**Comment by floatingatoll** [comment]
Done

**Comment by brettgaylor** [comment]
@floatingatoll yes, good on the redirect, though is it possible for us to download some content that was hosted there?

**Comment by floatingatoll** [comment]
Go for it - we're not doing anything to turn off the live site, so you can
grab whatever you want from the IP address:

$ host popcornjs.org
popcornjs.org has address 70.32.92.25
$ host 70.32.92.25
25.92.32.70.in-addr.arpa domain name pointer ve.gjwynspb.vesrv.com.

If you need us to delay the redirect for a couple hours to avoid having to
spoof Host headers or whatever, let me know.

**Comment by Pomax** [comment]
@brettgaylor @floatingatoll is there a tarball for the current site we can grab for archival purposes? (spidering an IP is probably going to miss out on some stuff)

**Comment by floatingatoll** [comment]
No clue, we over in Webops have no visibility into this offsite hosting
y'all are using for it, sorry.

**Comment by Pomax** [comment]
fair point. @brettgaylor @cade do we remember where this is *actually* hosted?

**Comment by jbuck** [comment]
I remember that it was on Media Temple but I have no idea about creds or anything like that

**Comment by brettgaylor** [comment]
Looking back though the mists of time, I had thought we switched this over to our own internal infra....can we test if its on media temple with a whois or something?  I have a feeling it isn't, since we haven't been paying for it for some time...

**Comment by floatingatoll** [comment]
10  vzd026.mediatemple.net (70.32.94.3)  83.383 ms  87.898 ms  85.574 ms
11  ve.gjwynspb.vesrv.com (70.32.92.25)  80.132 ms  127.764 ms  135.935 ms

**Comment by cade** [comment]
So **_this_** is how the sausage is made...

**Comment by Pomax** [comment]
goddamnit @cade, I love your sportsmanship. I owe so you many drinks of your choice... /cc @cadecairos

**Comment by floatingatoll** [comment]
Oh wow, heh. Yes, thank you for always putting up with us, @cade :)

**Comment by cade** [comment]
Today, I learned that `mofo-devops` is a repository that exists, that `mofo` is (presumably) shorthand for Mozilla Foundation, and that there's a MoFo production team. I can now tell my friends that, truly, a bunch of MoFo's keep pinging me on their issues.

It is **I** who owe **you** the thanks.

**Comment by Pomax** [comment]
I am 100% on board with that assessment.

**Comment by floatingatoll** [comment]
Technically I'm MoCo and we're MoFoCo, but that's beside the point.

https://www.youtube.com/watch?v=MtdoPUQimJg

**Comment by ziegeer** [comment]
Timeout, redirect to github is now in place.  Old content should still be available at 70.32.92.25.

**Comment by brettgaylor** [comment]
@Pomax dammit!  You were told not to leak video evidence of MoFos all hands gatherings!

**Comment by brettgaylor** [comment]
@cade just FYI, these mofos are hiring....https://careers.mozilla.org/listings/

**Comment by cade** [comment]
I've already got it planned out: a few more years' worth of trolling your issues until I've got enough content to fill a conference presentation. _Then_ I get hired. Then I work the circuit and get internet famous by giving the talk, "How I Got Hired at Mozilla by Trolling Issue Threads".

I'm pretty sure this plan is foolproof.

P.S. :1st_place_medal: for the Dr. Who video.

**Comment by floatingatoll** [comment]
"Trolling issue threads" can accurately describe bug triage some days, so I think you're already ahead of the game!

**Comment by brettgaylor** [comment]
Indeed.  That's literally what my kids think I do for a living.

**Comment by cadecairos** [comment]
Geez I go on vacay for three days, and look what happens!

Thanks for taking care of this!

@cade 🥇 excellent job trolling the thread

Marking this issue as closed!

**Comment by floatingatoll** [comment]
Did y'all put up whatever you needed to say at the README.md for the target of the redirect?

**Comment by cadecairos** [comment]
Yes,  the readme has been updated.

**Comment by cadecairos** [comment]
@floatingatoll We just had a report come in that the redirect is preserving the path, which results in "https://popcornjs.org/download" resolving to "https://github.com/mozilla/popcorn-js/download"

Can we update the redirect all reqeusts redirect to "https://github.com/mozilla/popcorn-js"

**Comment by cadecairos** [comment]
(reported in https://github.com/mozilla/popcorn-js/issues/476)

**Comment by floatingatoll** [comment]
Yeah - just reopen the bug so we can see and fix it. It's very uncommon to
have us nuke paths, but it does come up once in a while.

**Comment by brettgaylor** [comment]
@cadecairos something this re-opening made me think about - were we hosting production versions of popcornjs at that URL that we should also redirect?  Apologies for not thinking of this in advance!

**Comment by floatingatoll** [comment]
Nope, that's on a CDN URL that goes to a Webops S3 bucket. I have a note here to bring that up soon :)

**Comment by brettgaylor** [comment]
Thanks  - that matches my memory :)  We'll cross that bridge when we come to it in a separate issue :)

**Comment by cadecairos** [comment]
The redirect issue has been resolved.
