### ISSUE TITLE
Make sure network-pulse-api-production is configured properly

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#447]
### Details
I've spun up the [network-pulse-api-production app](https://dashboard.heroku.com/apps/network-pulse-api-production/settings) on heroku,  can you take a look at it and make sure it's configured properly, with SSL and API keys, etc.? Staging server is located [here](https://dashboard.heroku.com/apps/network-pulse-api-staging)

I'd also be interested in what actually has to be done for future reference, if you have a few minutes to explain it in Chat or something.

**Comment by cadecairos** [comment]
I've added OAuth credentials to the production app, and I've added a Hobby dev postgres DB. (10m rows should be fine for now)

Alan, you have access to the apps Oauth settings in the Google developer dashboard (https://console.developers.google.com) just sign in with your Mozilla account to see the apps.

Should I go ahead and configure the app with a mofoprod.net domain? I personally would prefer that over the herokuapp domain

**Comment by alanmoo** [comment]
Sounds good to me

**Comment by cadecairos** [comment]
@alanmoo can we close this one?

**Comment by cadecairos** [comment]
(pressed wrong button)

**Comment by cadecairos** [comment]
this feels like it's complete.
