### ISSUE TITLE
migrate storyengine.io from namecheap 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-devops#448]
### Details

- [x] Transfer domain to Mozilla
- [x] Migrate site to WPEngine
- [x] Install LetEcrypt Certificate

**Comment by OpenMatt** [comment]
@cadecairos we'll need to do the same thing we did with https://github.com/MozillaFoundation/mofo-devops/issues/435

**Comment by cadecairos** [comment]
@OpenMatt I'm migrating the site to wpengine right now, once it's mirrored, I'll update the domains nameservers to use Mozilla's. Once that's done I'll add SSL and open a ticket to transfer the domain to Mozilla.

**Comment by cadecairos** [comment]
OK migration completed & Nameservers updated - @OpenMatt Lets try not to update that site for 24-48 hours. I'll check tomorrow to see if the nameserver changes have propagated, and once I have confirmation I'll install a LetsEncrypt certificate, and shore up the security with some basic security headers. (I'll see how difficult it might be to add a content security policy)

**Comment by OpenMatt** [comment]
Hi @cadecairos -- ok sounds great! Thanks. 

I've been doing quite a few content updates today though. Is that bad? I just exported a back-up to be safe. But we're actively working on the site pretty hard right now. Is it ok to keep going, and just do back-ups regularly?

**Comment by cadecairos** [comment]
update: MoCo will be initiating the transfer soon

I also still need to add in the security headers plugin and start developing a CSP for the site.

**Comment by cadecairos** [comment]
Domain transfer completed!
