### ISSUE TITLE
mofo-staffonly != mofo-staffonly

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#449]
In at least one repo, the mofo-staffonly team has been added as a contributor, but.... a few members in that team don't seem to show up. Their handles don't auto-complete in comments and they don't appear as an option in the Assignees drop-down. 

### Info & links

@arlissc & @zee-moz can't be assigned to this issue: https://github.com/mozilla/network/issues/43

they appear in the team: https://github.com/orgs/MozillaFoundation/teams/mofo-staffonly

mofo-staffonly team is a contributor on the repo: https://github.com/mozilla/network/settings/collaboration

Mystery? Or am I missing something?

**Comment by cadecairos** [comment]
It's a bit confusing, but there are two mofo-staffonly teams. one under "mozilla" the other under "mozillafoundation"

I'll add arlissc and zee-moz to the mozilla team.

**Comment by cadecairos** [comment]
ok, invites away

**Comment by xmatthewx** [comment]
ahhhh. i knew there was an obvious reason hiding in plain sight. thanks for the trouble. closing.
