### ISSUE TITLE
Set up staging and production instance for NSF site

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#450]
Context: https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/2
Production URL: https://wirelesschallenge.mozilla.org
Hosting on: ~~Heroku~~ S3 (and uses Jenkins to deploy)
Production site launch date: Feb 15 ✨ 

Updates on Feb 8:
Staging is on https://wirelesschallenge.mofostaging.net/

/cc @hannahkane @ScottDowne

**Comment by gvn** [comment]
Since NSF does a static build I think we'll need to use the [heroku-buildpack-static](https://github.com/heroku/heroku-buildpack-static), which I haven't completely figured out.

Currently NSF is only set up for staging via gh-pages using this script:

https://github.com/mozilla/nsf-challenge/blob/master/scripts/stage.js

@cadecairos, once you have a chance to get familiar with NSF, let's meet to chat about how we want to do prod pushes to Heroku (or maybe AWS if Heroku is a no-go).

**Comment by mmmavis** [comment]
Please invite me to the meeting. I'm not aware of `heroku-buildpack-static` and I'd like to know more about it. 😃

**Comment by gvn** [comment]
Invite sent!

**Comment by cadecairos** [comment]
That buildpack is intriguing, But I worry it'll fall over under heavy load without proper caching.

**Comment by mmmavis** [comment]
from the meeting we just had:

- [ ] ditch `gh-pages`
- [ ] set up staging and production on S3
- [ ] using Jenkins to deploy

@cadecairos @gvn @ScottDowne

**Comment by cadecairos** [comment]
> using Jenkins to deploy

We can still use travis-ci for automatic deployes to staging, if preferred, otherwise I can set up automatic deploys on Jenkins just as easily.

**Comment by gvn** [comment]
What are the pros/cons of using Jenkins vs. Travis for CI?

**Comment by cadecairos** [comment]
> What are the pros/cons of using Jenkins vs. Travis for CI?

@gvn I'll have to look into how well Jenkins integrates with github, but I believe it's capable of marking testing/builds as passed/failed. Downside there is we need to configure the job. 

Upside of Jenkins VS Travis, is we don't have to wait in a queue for a build machine.

**Comment by cadecairos** [comment]
Here's what I've set up:

## Staging
* [Jenkins Job](https://jenkins.mofoprod.net/view/STAGING/job/wireless%20challenge%20(staging)/)
  * Fully automated, on merges to master, it runs `npm i`, `npm test`, and `npm run build`, and uploads `dest/**` to the Staging folder of the S3 Bucket.

## Production
* [Jenkins Job](https://jenkins.mofoprod.net/view/PROD/job/wireless%20challenge%20(production)/)
* Manual deploy (requires account on Jenkins)
  * Deploys master by default, also accepts a build param to deploy any other branch/commit - in case of needing a rollback.

[![](https://jenkins.mofoprod.net/static/8c24fdb0/images/24x24/clock.png)](https://jenkins.mofoprod.net/view/PROD/job/wireless%20challenge%20(production)/build?delay=0sec) [Deploy To Production](https://jenkins.mofoprod.net/view/PROD/job/wireless%20challenge%20(production)/build?delay=0sec)
^ look, a deploy button/link for the readme!

```Markdown
[![](https://jenkins.mofoprod.net/static/8c24fdb0/images/24x24/clock.png)](https://jenkins.mofoprod.net/view/PROD/job/wireless%20challenge%20(production)/build?delay=0sec) [Deploy To Production](https://jenkins.mofoprod.net/view/PROD/job/wireless%20challenge%20(production)/build?delay=0sec)
```

**Comment by gvn** [comment]
Nice! @mmmavis and @ScottDowne can you give these a shot and let us know how it works out?

Once we're feeling good about this for NSF we can set it up for MLN. 👍

**Comment by cadecairos** [comment]
@mmmavis @ScottDowne Is there anything else we need to do here or can we call this closed?

**Comment by mmmavis** [comment]
@cadecairos is https://wirelesschallenge.mozilla.org ready for us?

**Comment by cadecairos** [comment]
> @cadecairos is https://wirelesschallenge.mozilla.org ready for us?

This domain is being set up in https://bugzilla.mozilla.org/show_bug.cgi?id=1337904

I've requested for it to go-live on Monday/Tuesday

**Comment by cadecairos** [comment]
(I've delayed the bugzilla bug until next Tuesday (Feb 21st)

**Comment by cadecairos** [comment]
This is completed. Project is on hold for the time being, however.
