### ISSUE TITLE
Move blog.workopen.org to workopen.org

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/mofo-devops#451]
I'd like blog.workopen.org to appear at workopen.org instead

This will require a few steps:

1) Move the etherpad instance currently running on workopen.org to workopen.io
   - Before doing this, it would be good to have a look at the admin console / database to ensure there's no important data there that will get lost 
2) Move blog.workopen.org to workopen.org
3) Transfer hosting from Mozilla infrastructure to Matt Thompson's personal namecheap infrastructure  
4) Redirect all old blog.workopen.org links to point at their new workopen.org home 
5) Do whatever we can from the namecheap side to ensure the site maintains a good rating from Mozilla Observatory

**Comment by OpenMatt** [comment]
cc @jllin

**Comment by OpenMatt** [comment]
I'd also like to get "matt@workopen.org" working as my email address. I'll be using a personal G suite business account for that. Once I have control over the home page for workopen.org, I should be able to set this up.

**Comment by jlin** [comment]
Tasks:

1. disable nginx site rules for etherpad on workopen.org (digitalocean droplet) - done.
2. stand up wordpress on workopen.org - partially done
3. export post and file data from mofo version of blog.workopen.org and re-import into workopen standalone instance
4. figure out ssl certificate + setup
5. double check dns rules
6. figure out redirection (probably using nginx webserver redirect rules)


At the same time, Matt will need to get the Gsuite setup started (setup involves setting a dns record on workopen.org to confirm ownership of domain, that can be done on the domain control panel, I can help with that)

**Comment by jlin** [comment]
Matt moved DNS for workopen from AWS (mofo) into namecheap freedns. blog.workopen.org is cnamed for now to workopenblog.wpengine.com for the duration of the transfer.

DNS will take up to 24 h to propagate.

**Comment by OpenMatt** [comment]
@jlin let me know if there's anything more you need me to do here? 

stoked to have matt@workopen.org working already :)

**Comment by OpenMatt** [comment]
@jlin I think our final steps are:
- [ ] set up the re-directs
- [ ] privacy / encryption

**Comment by cadecairos** [comment]
How goes this?

**Comment by jlin** [comment]
got workopen.org to use letsencrypt certificates, and attained a B rating on observatory (same as the old blog). I've modified dns to cname blog.workopen.org to workopen.org so we will be off of mozilla infra entirely. sorry for delay in update.

**Comment by OpenMatt** [comment]
hey @jlin -- anything further needed here before we close? thanks for all your great work!

**Comment by cadecairos** [comment]
I've removed the blog from MoFo's WPengine account

**Comment by jlin** [comment]
no other things needed. i think this is done. thanks!

**Comment by cadecairos** [comment]
Thanks jlin!
