### ISSUE TITLE
Pulse v2+ staging and production instances

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#452]
Related ticket: https://github.com/mozilla/network-pulse/issues/330

### Context

For v1
- jQuery based
~~- Staging is off of the `master` branch. URL: https://network-pulse.mofostaging.net/~~
- Production is off of `gh-pages`. URL: https://mozilla.github.io/network-pulse/

(mavis) updates on Feb 2: `master` is now used for v2 staging. What was on `master` (v1 staging code) has been moved to the `v1` branch.

For v2 (WIP, launching soon)
- React based
- Has server
- will be following GitHub flow for branching and deployment

### Staging URL for v2+

~~I'm currently using http://pulse-react.herokuapp.com/ on my Heroku account off of the WIP `react` branch on [Network Pulse](https://github.com/mozilla/network-pulse/tree/react). At some point when `react` gets merged into `master` I should move that Heroku instance to mozilla and rename it to `pulse-staging.herokuapp.org`~~

(mavis) updates on Feb 2: @alanmoo created a Heroku instance https://network-pulse-staging.herokuapp.com/ that's off of the new `master` branch on Pulse repo.

### Production URL for v2+

From https://github.com/mozilla/network-pulse/issues/330 our preference is `pulse.mozilla.org`. We will probably need to create a new GA property for it as well (some context [here](https://github.com/mozilla/network-pulse/issues/330#issuecomment-277844676)).

### v2 Launch Date

We were aiming for end of January originally but other things came up and now there are still a few things we need to implement / fix. @xmatthewx any set deadline in mind?

**Comment by mmmavis** [comment]
@xmatthewx @cadecairos since we are not updating Pulse v1 anymore I'm thinking maybe we can start using `master` as the dev/staging branch of v2+ code? If a v1 update is absolutely needed we can just push to `gh-pages` directly. I don't think the risk is gonna be anywhere close to high there.

**Comment by mmmavis** [comment]
I got everyone's +1 on https://github.com/mozilla/network-pulse/issues/360. I will update `master` with v2 work today and update this DevOps ticket.

**Comment by alanmoo** [comment]
`master` on the [pulse repo](https://github.com/mozilla/network-pulse) is now home to the React version of the site (v2)

**Comment by mmmavis** [comment]
Updates:

We cleaned up the [Pulse repo](https://github.com/mozilla/network-pulse) a bit and @alanmoo helped set up the staging pipeline on Heroku yesterday. We still need to

1. have a production instance set up (@alanmoo I guess we can just do it on own end, no need DevOps help?) 
2. figure out what domain we wanna use
3. create a new GA property so I can plug in the new UA code

**Comment by alanmoo** [comment]
Production is up. https://network-pulse-production.herokuapp.com. If the name needs to be changed at some point that shouldn't be an issue.

**Comment by mmmavis** [comment]
Hey @cadecairos I believe production domain has been set up now.  What's left in this ticket is

> create a new GA property so I can plug in the new UA code

Please ping me when the new UA code is ready for use. Thanks! 😃

**Comment by cadecairos** [comment]
I'll get you that as soon as I can, thanks for the reminder

**Comment by cadecairos** [comment]
@mmmavis Here's the tracking ID: UA-87658599-4

As always, be sure to wrap the GA script insertion code with the DNT respecting wrapper: https://gist.github.com/cadecairos/416e7abe6aab11b8317833924ed1e45d

**Comment by mmmavis** [comment]
@cadecairos thanks! ✨ Can you grant @xmatthewx and myself access to the dashboard as well?

**Comment by mmmavis** [comment]
> @cadecairos thanks! ✨ Can you grant @xmatthewx and myself access to the dashboard as well?

and @Pomax and @alanmoo as well. Thanks!

**Comment by cadecairos** [comment]
Read+Analyze permissions granted. marking this as resolved.

**Comment by mmmavis** [comment]
thanks for much!!! 🍰 ☕️ 🍾 ✨ ヾ(*´∀ ˋ*)ﾉ
