### ISSUE TITLE
Create web page that explains transition from Mattermost to Slack

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#453]
We'll replace chat.mozillafoundation.org with this after we shut down mattermost.

**Comment by alanmoo** [comment]
Simple page with an intro and a link to the Slack instance?

**Comment by simonwex** [comment]
Yeah, barebones.

**Comment by cadecairos** [comment]
@alanmoo got an update?

Should I move this forward a milestone?

**Comment by alanmoo** [comment]
Move it forward. We haven't heard anything about moving people yet, so I haven't set aside time to do this yet.

**Comment by alanmoo** [comment]
@simonwex So staff will be able to log in to Slack, what guidance do we have for non-staff?

**Comment by cadecairos** [comment]
@alanmoo Is there anything else to do here?

**Comment by alanmoo** [comment]
I believe shutting down Mattermost is still pending a course of action for contributors, no? At that point I'd actually need to build this page.

**Comment by cadecairos** [comment]
@alanmoo can we close this?

**Comment by alanmoo** [comment]
This is something that should still be done, but is pending an actual plan for shutting down Mattermost and migrating users. Should we create a broader ticket and include this as a subtask?

**Comment by cadecairos** [comment]
How many contributors do we interact with on Mattermost still? Where are they going to go?

sidenote: I think the only active channel on Mattermost is Thimble, and since Thimble might one day spin out of Mozilla, do we really want to open up a channel on slack for that? IMO a free Slack or Gitter would be more appropriate.

**Comment by alanmoo** [comment]
Looks like Gitter is restricted from the Mozilla org on GitHub, but you make a good point. @humphd Do you have thoughts on this?

**Comment by humphd** [comment]
Probably moving to a free slack workspace for Thimble is what should happen; but can we wait to see what we're doing with Thimble first?  Doing a migration, only to do yet another one seems frustrating.  How critical is it for you to shut this down now?

**Comment by alanmoo** [comment]
Not critical, definitely worth waiting.

**Comment by humphd** [comment]
I think from a Seneca point-of-view it's fine to turn off Mattermost for Thimble now.  Thanks for keeping it up a while longer.

**Comment by alanmoo** [comment]
Ah, good to know. We're working on getting another way up for contributors to reach us via chat, I'll let you know when that comes to fruition.

**Comment by cadecairos** [comment]
@alanmoo anything need to happen here before I start shuttering Mattermost?

**Comment by alanmoo** [comment]
Let's update the Readme for the github repo to say 'We've moved on to Slack. If you're active in one of our repos, reach out to a member of the team and we can send you an invite', and then redirect chat.mozillafoundation.org to that repo.

**Comment by cadecairos** [comment]
> Readme for the github repo

Which one?

**Comment by alanmoo** [comment]
https://github.com/mozilla/chat.mozillafoundation.org

**Comment by cadecairos** [comment]
That repo's just a fork I worked with before I figured out how to deploy official binaries to Heroku. I'll archive it.

**Comment by cadecairos** [comment]
Closing this as Chat is now redirecting to mozfest slack
