### ISSUE TITLE
Document the technologies MoFo Engineering and Ops will host and maintain

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#454]
We should codify the technologies that we're going to build with and support. This information is for internal use and for external contribution, as well as for contractors.

some initial thoughts:

* PostgreSQL 9.6
* NodeJS LTS
* Django 10.x
* Redis 3.2.x

**Comment by simonwex** [comment]
We should probably expand this a bunch. Maybe "things that exist as supported modules on Heroku"?

**Comment by cadecairos** [comment]
> We should probably expand this a bunch. Maybe "things that exist as supported modules on Heroku"?

Do you mean something like this:

## Platforms/Languages

* NodeJS LTS (JavaScript)
* Django 10.x (Python 3.x)

## Preferred Addons

* Heroku postgres
* Heroku Redis

In most cases, if it's a Heroku Addon and your app needs it, we can use it.

There are a few exceptions:
1. Logging - We have a separate account we can use for log aggregation and monitoring with Logentries. 
2. Pingdom - We have a pingdom account.
3. PagerDuty - We use PagerDuty to manage on-call alerts for applications. 

If your app requires any of the above services, contact Chris De Cairos to have your app configured with our accounts.
