### ISSUE TITLE
Thimble Projects staging did not exist

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#456]
Opening this as a clarification issue.

Apparently we didn't have a CNAME record for thimbleprojects.mofostaging.net, however, the cloudfront distribution refers to it as a CNAME. So, I added the record to our mofostaging set in Route53.

My questions are:
- @cadecairos did you recently add the CNAME binding to the cloudfront distribution? I feel like I don't remember such a thing as thimbleprojects.mofostaging.net
- Did you upload https://github.com/mozilla/thimble.mozilla.org/issues/1711 to the staging S3 bucket or the prod S3 bucket (note that they are named poorly on S3 - the prod bucket has the word staging in it and so does the staging bucket)

**Comment by cadecairos** [comment]
> did you recently add the CNAME binding to the cloudfront distribution? I feel like I don't remember such a thing as thimbleprojects.mofostaging.net

Nope, haven't touched it in ages, if at all.

> Did you upload mozilla/thimble.mozilla.org#1711 to the staging S3 bucket or the prod S3

Prod - I'm aware of the terrible naming of the S3 bucket.

**Comment by gideonthomas** [comment]
Ah ok, sooo weird! Anyway, hope I didn't break anything when I made the change.

I'll update the 404 page to the staging S3 bucket as well.

**Comment by cadecairos** [comment]
Closing in favour of https://github.com/mozilla/thimble.mozilla.org/issues/1716
