### ISSUE TITLE
Set up deployment infra for Network

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/mofo-devops#457]
### Details

We'd like to use the same deployment setup as NSF for [Network](https://github.com/mozilla/network).

**Comment by cadecairos** [comment]
OK!

## Staging
[Jenkins Job](https://jenkins.mofoprod.net/view/STAGING/job/Network%20(staging)/)
It's triggered with a webhook, building on merges to master.
it deploys to the "network-staging" S3 bucket in us-east-1, which is served using a CloudFront CDN.
Staging URL is "network.mofostaging.net" (we can change this as the title evolves)

## Production
[Jenkins Job](https://jenkins.mofoprod.net/view/STAGING/job/Network%20(production)/) 
Triggered Manually. Deploys to "network-production" in us-east-1, served using a CloudFront CDN.
Temporary production URL is "network.mofoprod.net"

**Comment by cadecairos** [comment]
@gvn I've filed https://github.com/mozilla/network/issues/80 to add documentation for this deploy pipeline to the README.

**Comment by gvn** [comment]
Looks like there are some permissions errors:

https://network.mofostaging.net/programs gives me 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A07283D837D27B00</RequestId>
<HostId>
8qyQzjkLoWisZMhxrEz4phoU0Hq70PZU2CIP00nY51f3ItZ787tJaJNdtZNaaHmUMh+gzlxXAiM=
</HostId>
</Error>
```

**Comment by cadecairos** [comment]
that's curious.

**Comment by cadecairos** [comment]
I found the issue, and a fix is rolling out as we speak

**Comment by gvn** [comment]
Yay seems to be working!

**Comment by cadecairos** [comment]
closing once more
