### ISSUE TITLE
Url for stop gap copyright petition

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#458]
We're going to need a url setup for a new petition/signup page.

The page is being designed now. I don't know what the URL is going to be.

Some more context, this page is primarily something we'll use between NB and whatever new platform we land on.

The page stack might be most similar to the advocacy.mozilla.org stack, so the final page might live on Heroku.

cc @hannahkane @cadecairos

**Comment by cadecairos** [comment]
Is this URL something we need to go purchase?

**Comment by hannahkane** [comment]
cc @shaghdoosti who I think will know the answer. I *think* she said we already own it (I don't want to list it here in case we don't), but hopefully she can confirm. She's at a conference today and tomorrow, so maybe not until next week.

**Comment by cadecairos** [comment]
@caltrider asked me to get:

dontbreaktheinternet.org
dontbreaktheinter.net

(Which I already have done - they're ours)

Are these the potential domains we're using?

**Comment by hannahkane** [comment]
Yes, but I believe @shaghdoosti needed to get a final OK from Ashley.

**Comment by shaghdoosti** [comment]
Talked to Ashley - let's keep the original copyright URL for the campaign. No need to switch.

**Comment by cadecairos** [comment]
Sounds good! I think we also already have an SSL certificate for it 💰

**Comment by cadecairos** [comment]
All that's left to do here is update changecopyright.org to use the new app. I'll keep this open to track that task.

**Comment by hannahkane** [comment]
@cadecairos - we're shooting for a Friday, March 10th soft launch, assuming all QA tests pass tomorrow. Would this work for you?

**Comment by cadecairos** [comment]
yes, this shouldn't be a problem

**Comment by cadecairos** [comment]
Closing this out, any new tasks can be handled in new issues.
