### ISSUE TITLE
Renew SSL certificate on commons.ca

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#459]
Please renew certificate for commons.ca.

Next steps:
 * Evaluate WP version
 * Decide if we want to move hosts
 * Add to alerting infrastructure–It shouldn't wake us up, but we should know

### Info & links
https://docs.google.com/document/d/1mGpz36aaD7pqioai6CImZDNn6SPmr57SQCVuZVIEA04/edit?ts=58a362c2

**Comment by cadecairos** [comment]
I think the best course of action for us here is:
1. copy the site to WPEngine (a very simple process)
2. Once copied, update DNS settings to use the new wordpress install.
3. Use WPEngines LetsEncrypt integration to get SSL certificates for all the sites on the wordpress install.

**Comment by cadecairos** [comment]
* [X] Site Migrated
* [X] SSL Installed
* [X] DNS Updated
* [X] Wordpress update
* [X] Plugins updated

**Comment by cadecairos** [comment]
I've just added Pingdom monitoring for commons.ca and marksurman.commons.ca

**Comment by cadecairos** [comment]
I'm calling this resolved!
