### ISSUE TITLE
make mozillapulse.org and www.mozillapulse.org do the same thing

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#462]
It looks like the name bindings for mozillapulse.org are set such that it needs the `www.` prefix to work. We'll want to add a secondary binding so that plain mozillapulse.org serves the same content.

**Comment by cadecairos** [comment]
Route 53 doesn't permit CNAMEs on the apex of a hosted zone, so I'll need to use an S3 (lol) website redirect to `www`

**Comment by Pomax** [comment]
brilliant

**Comment by cadecairos** [comment]
I'm rolling out a redirect from the apex to the www subdomain as I type. I'll close once it's working.

**Comment by cadecairos** [comment]
fixed.
