### ISSUE TITLE
Stats for Thimble Users and Projects from Databases

### ISSUE THREAD

**Issue by humphd** [MozillaFoundation/mofo-devops#463]
I'm working on a report and would like to get some data from the Thimble user and project databases, specifically:

* count of users (all time)
* count of projects (all time)

* count of users (since Jan 1, 2017)
* count of projects (since Jan 1, 2017)

I’m not sure if there are any other compelling queries to add to that list?  If so, please do.

Probably it's best if you can email this to me vs. posting here.

**Comment by humphd** [comment]
@cadecairos I forgot to add a range I care about, also:

* count of users (2016)

* count of projects (2016)

**Comment by cadecairos** [comment]
This data has been emailed over to you.
