### ISSUE TITLE
Move Webmaker research reports to more appropriate home

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/mofo-devops#465]
### Details
Right now, there are a few research reports we did in 2015 linked from https://mozilla-foundation-research.herokuapp.com/globalweb/. They're in a webmaker s3 bucket. I think we're trying to consolidate research under a certain umbrella, so it would make sense for this to live closer to, perhaps, other research we do, like the Internet Health Report.

**Comment by cadecairos** [comment]
I don't think this is necessary anymore, as their current location is working.
