### ISSUE TITLE
fix mozillapulse.org observatory F score

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#466]
Right now we score an F on moz's Observatory test for site integrity and security, which we probably want to fix.

https://observatory.mozilla.org/analyze.html?host=mozillapulse.org

**Comment by cadecairos** [comment]
This has been resolved with https://github.com/mozilla/network-pulse/commit/f530fd1187c50bdbb64ca730982cb64054ba447c
