### ISSUE TITLE
Ensure prod deployments are working as expected for Network

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/mofo-devops#468]
### Details

I pushed a Network build to prod via Jenkins a few hours ago and haven't seen updates reflected on the site. Can we ensure that production builds take effect within at most a few hours?

### Info & links

https://github.com/mozilla/network/issues/119
https://network.mofoprod.net/

**Comment by cadecairos** [comment]
@gvn I've updated the CloudFront CDN's default behaviour so that it caches objects no longer than one hour (3600 second max-age), and modified the production build to add cache-control metadata to the objects we upload to S3.

**Comment by cadecairos** [comment]
I think we can call this closed.
