### ISSUE TITLE
Create GA property for the new Mozilla Network site

### ISSUE THREAD

**Issue by vojtechmzl** [MozillaFoundation/mofo-devops#470]
### Details

The new Network site will be launching in the next few days, so we need a new GA ID. We are still waiting on the final URL, but the current placeholder URL is https://network.mofoprod.net/

Please add vojtech@mozillafoundation.org, mw@mozillafoundation.org and gavin@mozillafoundation.org to the account with admin privileges. 

Thanks!

**Comment by cadecairos** [comment]
UA-87658599-6

As always, please use the [DNT wrapper](https://gist.github.com/cadecairos/416e7abe6aab11b8317833924ed1e45d)
