### ISSUE TITLE
add S3 bucket information to the network-pulse-api staging and production instances

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#473]
Can someone add the S3 bucket information to the staging and production heroku instances for the network-pulse-api, so that we can turn on image uploading?

The code uses the same S3 credential variables as the network-api, so we just need the right AWS key, secret, bucketname, etc.

**Comment by Pomax** [comment]
(specific issue to address the larger issue https://github.com/MozillaFoundation/mofo-devops/issues/430)

**Comment by gideonthomas** [comment]
This is done! You just need to set `USE_S3` to `False` on Heroku (for both staging and production) and it should work.

**Comment by Pomax** [comment]
I assume you meant `True`, because otherwise it won't use S3? =)

**Comment by gideonthomas** [comment]
yep lol sorry, I set it to False on heroku so that you can change it when you're ready to test...it was very late at night :P

**Comment by Pomax** [comment]
haha, no worries. Thanks!
