### ISSUE TITLE
Can't login to Slack

### ISSUE THREAD

**Issue by HPaulJohnson** [MozillaFoundation/mofo-devops#474]
### Details

I have an existing Slack account associated with my foundation email, created to collaborate on Moco marketing slack channels.

When attempting to login into the new mozilla.slack.com instance I get the following error: 

"Your email address is already registered to a disabled account and cannot be reused. Please contact your Team Admins for assistance."

Let me know what I can do to regain access?

**Comment by cadecairos** [comment]
@simonwex I'm not sure who administers Mozilla Slack (I know that there's no servicedesk support set up yet, so that's off the table)

**Comment by cadecairos** [comment]
@HPaulJohnson you're signing in using the SSO flow, right?

I'm not sure if pre-existing slack accounts with passwords can join the mozilla instance.

**Comment by HPaulJohnson** [comment]
Yes, this is the error I get with the SSO flow. 

I can login to slack outside of that flow - using my foundation.org email and a slack password - and still access and old instance we used on the advocacy team for the encryption campaign back in early 2016. 

When I try to login to the mozilla instance, i get prompted to go through SSO login and get the error message above?

**Comment by simonwex** [comment]
My account converted to work with SSO. I'll check in later and if it's not
resolved, will ask Sean.

**Comment by HPaulJohnson** [comment]
Ok, let me know. BTW, I've been getting this error since last week when MoCo Marketing made the transition and I tried to login to chat with my peeps on that team.

**Comment by cadecairos** [comment]
@HPaulJohnson You should now be able to log in - I asked an admin to activate your account on the instance - we're unsure why it was deactivated. either way you should be able to join the fun now.

**Comment by HPaulJohnson** [comment]
that did the trick- thank you!
