### ISSUE TITLE
Setup Ask for Network site

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#475]
Docs: https://docs.coralproject.net/products/ask/ 

Discussion in https://github.com/mozilla/network/issues/217

**Comment by cadecairos** [comment]
based on https://github.com/mozilla/network/issues/217#issuecomment-291954248 Lets close this issue for now.

**Comment by cadecairos** [comment]
@xmatthewx I've set up https://ask.mofoprod.net

Login credentials are in 1Password, and access to them will need to be managed there.

Ask doesn't let you specify the custom domain for surveys, but they're available at `https://survey.mofoprod.net/$UNIQUE_ID_FOR_FORM` - we'll have to sub-in the CDN domain manually, since ask will give us the S3 site URL by default.

**Comment by cadecairos** [comment]
@xmatthewx 

I've been chatting with the folks in the coral project slack channel and I found out how to create users.

I can generate accounts for anyone you ask me to (needs to be done while SSH'ed into the server) and I'll send their credentials over a E2E encrypted channel (such as Signal or Telegram)

**Comment by xmatthewx** [comment]
Excellent. Thanks @cadecairos 

@hannahkane – let's gather a list of people who should be able to create an Ask survey or form. I'm thinking you, me, @charissalaisy from 270, Claw, Sam B, Paul Z. Maybe Abby or someone working on global sprint? Anyone else? 

Any user can create a survey and share it with a link like survey.mofoprod.net/xyz123. 

In addition, we can prep to embed them on a new page created via CMS. Ask makes it easy, but I'm betting CMS doesn't allow script tag by default. Maybe we can use embed tag, but doing that we'll have to go with default styles. Either way, not a blocker to using this for engagement.

**Comment by cadecairos** [comment]
> In addition, we can prep to embed them on a new page created via CMS. Ask makes it easy, but I'm betting CMS doesn't allow script tag by default. Maybe we can use embed tag, but doing that we'll have to go with default styles. Either way, not a blocker to using this for engagement.

We've enabled the iframe tag on the CMS for rich text fields, so embedding forms should not be a problem.

I suggest we write a guide to on-board people using this tool with the CMS.

Also, I just realized this is the closed issue, not the open one. oops!

**Comment by cadecairos** [comment]
@xmatthewx I'm going to close out this issue, when we're ready to onboard users to ask, lets do so in a new issue.
