### ISSUE TITLE
Decomission discourse.mozilla-advocacy.org

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#476]
This site is unused and unmaintained, so we should take it offline.

Melissa has asked that we try to migrate posts into another discourse instance (probably forum.learning.mozilla.org)

This migration will need to be investigated, I'm not sure if it's simple or not.

**Comment by LeoMcA** [comment]
> This migration will need to be investigated, I'm not sure if it's simple or not.

It looks like it's possible with relative ease: https://meta.discourse.org/t/topic-and-category-export-import/38930

I'm not sure how it handles conflicting usernames, emails and the like, so you might want to do a trial run with a copy of the instance you're migrating into.

**Comment by alanmoo** [comment]
Can this be closed since we've got #529?

**Comment by flamingspaz** [comment]
I think these two issues capture two different tasks, this one being decommissioning the infra that runs the advocacy discourse and the other doing the migration of content.

I'd prefer to keep them separate, but my opinion isn't that strong.

**Comment by cadecairos** [comment]
I'm okay with these remaining separate tasks. @flamingspaz would you mind if I assigned this decom task to you?

**Comment by flamingspaz** [comment]
yes that makes sense

**Comment by cadecairos** [comment]
@alanmoo Have you heard anything recently about the migration of data? I'd like to decomission this infra sooner rather than later since no one is maintaining it

**Comment by alanmoo** [comment]
Back up the db for a bit longer, but go ahead and shut it down. Redirect it to the main Mozilla discourse.

**Comment by patjouk** [comment]
It's done!
