### ISSUE TITLE
Purchase fallback domain for Pulse

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#477]
As discussed with @cadecairos

**Comment by ryanwarsaw** [comment]
I wasn't sure if you intentionally made this vague (since it was posted on the public tracker) but if anyone decides to chime in with details domain specific, make sure it's done in: https://github.com/MozillaFoundation/mofo-devops-private rather than here. 👍

**Comment by xmatthewx** [comment]
Intentionally vague 😈.  I once knew about that private repo, but forgot about it. Thanks for the reminder!

**Comment by cadecairos** [comment]
Issue moved to [MozillaFoundation/mofo-devops-private #50](https://github.com/MozillaFoundation/mofo-devops-private/issues/50) via [**ZenHub**](https://www.zenhub.com/)
