### ISSUE TITLE
Review Data Practices

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#479]
Let's review these and:

 * Update where appropriate (BSD refs)
 * Ensure we're following data retention policy
 * Ensure third parties are following this as well

https://mana.mozilla.org/wiki/display/DATAPRACTICES/Foundation+Data+Practices

**Comment by cadecairos** [comment]
I will set up a recurring (quarterly) meeting to do this, beginning early December.

**Comment by cadecairos** [comment]
Meeting scheduled!
