### ISSUE TITLE
Migrate MoFo WPEngine sites to Mozilla WPEngine org

### ISSUE THREAD

**Issue by fox2mike** [MozillaFoundation/mofo-devops#480]
### Details
We'd like to move the MoFo blogs under the MoCo account and step 1 for that is to ensure that all the MoFo blogs are compatible with PHP 7. WPEngine has a Wordpress plugin for the same that you can install and once you've run your blogs past the checker and fixed any outstanding issues, we can figure out how to migrate your installs into the MoCo account. 

### Info & links
https://wordpress.org/plugins/php-compatibility-checker/

**Comment by cadecairos** [comment]
@fox2mike I've run the compatibility wizard on all our WPEngine installs and put the results in this Google Sheet: https://docs.google.com/a/mozilla.com/spreadsheets/d/1DmfC1wLU5bNP9ga2VQQ3lPGLJV6wB9vqOteKR-J7le0/edit?usp=sharing (Mozilla auth req'd to view)

Lots of compatibility issues to address. :(

**Comment by cadecairos** [comment]
I'll start fixing the compatibility issues once I can set aside the time to do so (hopefully in the next few weeks)

**Comment by fox2mike** [comment]
@cadecairos Sure thing. You can maybe reach out to Ryan or Craig to help with some ideas on some of these fixes because they went through the same exercise for the main blog. Thanks!

**Comment by fox2mike** [comment]
@cadecairos Any updates here? Just checking in. Community blogs are moving to our WPEngine account too!

**Comment by cadecairos** [comment]
Beyond my initial scans on compatibility, I haven't had a chance to get the blogs compatible with PHP7.

Is the private WPEngine cloud ready to have sites migrate in? If so, I can take on our migrations one property at a time, to make things a bit more managable for me. 

I'm also in the process of bringing on a new team member to work with me on these kind of things, which should really help move this along.

**Comment by fox2mike** [comment]
Oh totally. We can set you up with an install (which can be a multisite if needed) and you can start moving things over one by one (there's no need to move them all in together) if that makes sense.

**Comment by danielhartnell** [comment]
I'm adding a quick update to keep a record of a conversation that I had with cadecairos. We are not going to setup a WPEngine install right now but my team's available when that's needed. He can reach out to us when it's appropriate.

**Comment by cadecairos** [comment]
@danielhartnell We're planning to try migrating an install over next week. What's the right process to get set up on the private cloud with an install/workspace for MoFo?

**Comment by cadecairos** [comment]
@fox2mike @danielhartnell Hey, just wanted to see if we can work on getting MoFo a workspace/install in the next little while.

**Comment by danielhartnell** [comment]
Hey @cadecairos,

Sorry for missing your messages here. GitHub is a little out of band with what I normally use and I do not check my notifications as often as I should. I do have the following bug assigned to me and it would help if you can need info me there for subsequent requests around this work:

https://bugzilla.mozilla.org/show_bug.cgi?id=1417576

I'm also available on Slack or IRC. I'll be in the office at 9am pacific tomorrow and we can start working on this if you have the time. In order to get the install / workspace for MoFo configured, it would help to get a list of users that need access as well as the name for the new install. If you can send that to me (and anything else you feel might be relevant), I can get started on this.

**Comment by cadecairos** [comment]
Just to update:

We've got 3 sites running perfectly on PHP 7.2, and 3 that are on 7.2 but will be shut down eventually, as well as 3 sites NOT compatible with 7.2 and are going to be shut down eventually.

I'm going to migrate The health report over after all hands, then commons.ca.

**Comment by cadecairos** [comment]
We're going to keep Marks site in the mofo-account. We only needed to transfer over IHR. this is done!
