### ISSUE TITLE
Figure out hosting for Advocacy team's Madlib

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#481]
The advocacy team is building an interactive madlib experience where users get to complete the sentence "A Healthy Internet is..." and their answers are added to a community collection. The madlib will be a step in a workflow that starts with users viewing a video about Internet Health, and then completing the madlib.

Parent ticket is [here](https://github.com/MozillaFoundation/Advocacy/issues/792). @ScottDowne - can you link to the repo where you're building it?

We need to figure out where the madlib will be hosted. @lovegushwa has suggested that there's no particular marketing value in the madlib having its own domain, since it's part of a longer workflow. So, from his perspective, hosting it on advocacy.m.o would be fine. @ScottDowne points out that it might take extra effort to host it there, since it wasn't built there.

Important to note that we may do similar madlibs in the future, so whatever solution we land on should be scalable.

Can folks weigh in on where they think the madlib should live?

**Comment by lovegushwa** [comment]
@hannahkane @ScottDowne also we may want multiple versions of the madlib site:

- a version for folks from our email list
- a version or two for social testing (Alex could weigh in here.)
- a version for snippet traffic.

I'm curious if these 'threads' develop different tones based on the origin of the traffic. 
If we need to shut one of these down for troll reasons we can still link to another version thats less problematic.

**Comment by ScottDowne** [comment]
Current repo is here: https://github.com/beccaklam/internet-health-madlib

It's not super hard to move that into a.m.o. I see a few things to consider, though.

1. Can @cadecairos setup some redirect magic so it lives on a.m.o even if the code is not in the repo, and if so, is that better resource usage than me putting it into a.m.o repo?
2. a.m.o is a localized site that's on pontoon. So if we did that, we would need to be very careful to not expose any new strings we don't want localized, or people are going to spend the time to localize it.
3. The nature of this tool, given that it's a test and could get troll-y, maybe it's prudent to have it on a less mozilla branded domain?
4. If it gets troll-y, we want it on something that's easy to shut down?

**Comment by cadecairos** [comment]
> The nature of this tool, given that it's a test and could get troll-y, maybe it's prudent to have it on a less mozilla branded domain?

unless absolutely necessary, lets keep this off of mozilla.org

**Comment by hannahkane** [comment]
Is our other option to purchase a new domain?

**Comment by hannahkane** [comment]
ok, we have a domain we'd like to purchase. @cadecairos - I'll email you separately.

**Comment by hannahkane** [comment]
Closing as this is now duped in the private repo.
