### ISSUE TITLE
Host "Week in the Web" news matrix

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#482]
@beccaklam or @ScottDowne - could one of you please point to the news matrix landing page repo?

As discussed in Slack, the team would like to host this at weekintheweb.mozilla.org.

Any concerns?

**Comment by hannahkane** [comment]
cc @lovegushwa @caltrider

**Comment by hannahkane** [comment]
ping @cadecairos - seemed like you thought this was going to be more difficult than I'd originally thought. Can you clarify what we need to do to get the Week in the Web page up somewhere, even if it's not at this preferred url?

**Comment by cadecairos** [comment]
@hannahkane was this ticket still relevant or did we finish working on this elsewhere?

**Comment by hannahkane** [comment]
This is on hold for now. I think I'll close it, and will re-open if/when we need to. 
Thanks for the reminder, and sorry to have this clogging up your queue!
