### ISSUE TITLE
Google Analytics access (Mozilla Network Site)

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/mofo-devops#485]
### Details
Could you please give Google Analytics access (Mozilla Network Site) to me, Sabrina and Hannah?

**Comment by cadecairos** [comment]
@taisdesouzalessa @hannahkane @sabrinang You should all recieve emails about your access to the property. let me know if there's any trouble accessing the data.

**Comment by taisdesouzalessa** [comment]
Hey @cadecairos I can't see this property in my dashboard (I just see the learning site, which I already had before). Is there anything I am missing or any other place I should be looking for it? It seems Hannah has the same issue. Reopening the ticket here.

<img width="763" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25206676/67b97d94-2537-11e7-9947-5f70e5a747ab.png">

**Comment by cadecairos** [comment]
Is there a silhouette image on the top right of the screen, as pictured here: https://i.imgur.com/aoyCB5T.png

**Comment by taisdesouzalessa** [comment]
@cadecairos Yes, I clicked on the other account and found it! Didn't see the option at all before. Thanks for your help, Cade. Closing the ticket.
