### ISSUE TITLE
Mapping Global Sprint event to Global Sprint site

### ISSUE THREAD

**Issue by auremoser** [MozillaFoundation/mofo-devops#487]
### Details

I'd like to map the current event posting on Mozilla Science's site to the website for the Global Sprint made by @acabunoc, just so there is some consistency in how we direct our community to resources about the Global Sprint 2017.
Ideally, we would be able to keep the current card/link for the Global Sprint at science.mozilla.org and when a user clicks on the card or visits the link, it would redirect to the [Global Sprint website](https://mozilla.github.io/global-sprint/).

### Info & links

* [Global Sprint Event](https://science.mozilla.org/programs/events/global-sprint-2017) - event on Mozilla Science site
* [Global Sprint Site](https://mozilla.github.io/global-sprint/) - website I'd like the event link to redirect to

I caption the card view below, you can find it [here](https://science.mozilla.org/programs/events/programs/events):
![screen shot 2017-04-14 at 4 47 13 pm](https://cloud.githubusercontent.com/assets/1559703/25055302/f12e2860-212f-11e7-858c-a91f475eb774.png)

Ideally, it would redirect to [this](https://mozilla.github.io/global-sprint/) on click:
![screen shot 2017-04-14 at 4 47 26 pm](https://cloud.githubusercontent.com/assets/1559703/25055308/fb0a8202-212f-11e7-9b48-8abe93d99143.png)

Thank you!

**Comment by auremoser** [comment]
@k88hudson it's o.k. if you'd like to reassign someone else, and feel free to point me to another person/place to post this if it's not appropriate in devops. Thanks!

**Comment by acabunoc** [comment]
Thanks @auremoser!

To summarize, we'd like https://science.mozilla.org/programs/events/global-sprint-2017 to redirect to http://mozilla.github.io/global-sprint/

**Comment by gideonthomas** [comment]
@cadecairos I can do this if you're busy, feel free to assign this to me

**Comment by cadecairos** [comment]
@gideonthomas If you can spare the time to handle this, I'd be in your debt
