### ISSUE TITLE
Set up internethealth.typeoutloud.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#488]
The science madlib worked well, so now we're ready to move forward with the next one, which will be internethealth.typeoutloud.org.

@lovegushwa or @HPaulJohnson - can you clarify if there's a hard deadline for this?

cc @ScottDowne

**Comment by ScottDowne** [comment]
@cadecairos Not sure yet how I'm setting up this repo. So now's a good time to make any suggestions that make it easier for you to setup the subdomain.

**Comment by ScottDowne** [comment]
For the URL, I chatted with @cadecairos and @hannahkane and we think gong forward, we should move the url structures to https://www.typeoutloud.org/science and https://www.typeoutloud.org/internethealth

The advantages here is we can ship things faster with less people involved and maintain them easier in one repo.

The disadvantage is the url is a little different?

**Comment by cadecairos** [comment]
* Heroku App
* Link to repo
* Set up Automatic SSL using LetEncrypt
   * Route53 CNAME "www.typeoutloud.org" to "www.typeoutloud.org.herokudns.com"
   * enable Automatic SSL certificate management in Heroku app settings page

**Comment by ScottDowne** [comment]
@hannahkane I think the only hard blocker to this being something we can
drive traffic to is share? Is that how you see this too?

**Comment by hannahkane** [comment]
@ScottDowne - not sure I understand your question. Can you please rephrase?

**Comment by ScottDowne** [comment]
I was just asking about when we consider this ready. I think there are a
few more enhancement features we want to add but the only blocker is share
progress. Right?

**Comment by hannahkane** [comment]
Ah, yes. For some reason that was hard for me to parse, but yes, agree.
