### ISSUE TITLE
Recover youtube account – with a Vengeance

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#489]
The account: https://www.youtube.com/user/Mozilla

The original account that created the youtube account was:
chelsea@mozillafoundation.org

This was before we transitioned our mozilla accounts to Google/OKTA. 

This account was disabled during leave which was when the migration took place.

**Comment by cadecairos** [comment]
@simonwex 

So we need to get in touch with Service Now folks and re-activate that email/inbox, get a reset link, and recover the account?

**Comment by TomFarrow** [comment]
The channel is no longer associated to chelsea@

After the Google Apps migration, the organisational domain took priority, generating an access conflict. This was resolved by Liz Hull by changing the owner of the YouTube channel to a gmail.com account

I'll send you both an email with the current ownership email address (keeping out of here for security) and let you go from there. I'd suggest reaching out to Liz.

It should then be associated to a Google brand page.

**Comment by alanmoo** [comment]
Hi Tom, I got into the Google account for the current ownership email address you're referring to, but it doesn't seem to have the brand account associated with it. Any suggestion where to go next?

**Comment by jessevondoom** [comment]
I found a friend internally who is trying to investigate the current status of the account. If anyone else has any magical detective powers now would be a good time to use them.

**Comment by MaciekPluta** [comment]
Hey All, just so everyone here is aware, as of 3/12/2018, we regained control of the /Mozilla YouTube channel.

**Comment by alanmoo** [comment]
Holy 💩!
