### ISSUE TITLE
Upcoming EC2 maintenance

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#49]
- [x] i-a09e43c6 on 2015-05-08
  - makeapi-development
  - terminated
- [x] i-9e0aa664 on 2015-05-13
  - opennews source production node, must co-ordinate with @ryanpitts on timing
  - cycled through autoscaling
- [x] i-110855fb on 2015-05-14
  - wmlogin-development
  - terminated
- [x] i-15c2fd44 on 2015-05-16
  - makeapi-production configured, but not in the ELB? weird.
  - cycled through autoscaling
- [x] i-79770329 on 2015-05-16
  - http-helper production
  - cycled through autoscaling

**Comment by jbuck** [comment]
@ryanpitts I guess we need to do the "image AMI and replace it" dance sometime in the next two weeks

@jdotpz Any advice to make this easier/faster/less error-prone?

**Comment by ryanpitts** [comment]
I've been buried in event planning and prep for a while, so haven't had the bandwidth to work on switching Source over to use S3 for media storage. Will definitely want to capture an extra backup of the `media` dir just in case.

**Comment by jbuck** [comment]
@ryanpitts is there a clear path to making that switch? If it's clear enough, perhaps I could take it on.

**Comment by jbuck** [comment]
@ryanpitts something like http://martinbrochhaus.com/s3.html ?

**Comment by ryanpitts** [comment]
I think it's going to be implementing something like https://django-storages.readthedocs.org/en/latest/backends/amazon-S3.html using s3boto

**Comment by ryanpitts** [comment]
yep, which is pretty much what's covered in that link :)

**Comment by ryanpitts** [comment]
covered in the walkthrough in *your* link, I mean!
