### ISSUE TITLE
Create CMS accounts

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#491]
Hi team. Please create accounts for network site CMS for our editors. 
 - [x] me `super admin`
 - [x] @samanthaburton `admin`
 - [x] @chrislarry33 `admin`
 - [x] Kevin (I believe he's on there already) `admin`

Thanks!

cc @cadecairos @gideonthomas @Pomax @simonwex

**Comment by cadecairos** [comment]
@xmatthewx What permissions do you think super admin should have that admin doesn't have?

This will inform how the group permissions for "superadmin" and "admin" are set up.

**Comment by Pomax** [comment]
admins cannot delete users or change user permissions, they are "content" admins.
- user: plain user
- staff: (verified) mozilla staff (not automatically admin)
- admin: content admin (not automatically staff)
- superuser: full cms admin

**Comment by xmatthewx** [comment]
Thanks. If you give me the power, I'll take responsibility for creating user accounts for others.

**Comment by Pomax** [comment]
@xmatthewx you already have an account on network-api.mofostaging.net

**Comment by cadecairos** [comment]
superuser: this is a django thing, implies all permissions by default - I think we should only ever have one su account (devops)
superadmin: user administration + admin + staff
admin: Content removal (delete pages/people/features/news) + staff
staff: Content creation (create/update pages/people/features/news)
user: we don't currently use these

**Comment by Pomax** [comment]
"user" is a thing you get simply by having a login without any special flags set.

**Comment by cadecairos** [comment]
> Is the list you're showing the current permission separation in use in the network-api?

no, this is a proposal.

Current group setup is "admin" and "staff" where admin grants user management.

**Comment by xmatthewx** [comment]
I suggest that we continue the conversation on definitions here: mozilla/network-pulse-api#110

I'd like to just get accounts so I can onboard Chris and Sam. So they can start adding content. Sorry if my initial comment complicated this.

**Comment by xmatthewx** [comment]
done. thanks all.
