### ISSUE TITLE
Subdomain on Internet Health Report

### ISSUE THREAD

**Issue by Solanasaurus** [MozillaFoundation/mofo-devops#492]
### Details
We will soon (early May!) be starting a discussion forum/voting process for the “indicators” that we want to include in the next version of the internet health report using an external tool/vendor called Consider.it.
We need help to:
a) create a subdomain (indicators.internethealthreport.org)
b) add a DNS record pointing indicators.internethealthreport.org to internethealthreport.consider.it. 
c) supply them with an SSL certificate they can use to serve indicators.internethealthreport.org over https.
**Urmika from legal team has reviewed and OK'ed use of the vendor.

**Comment by cadecairos** [comment]
This was completed late last week.
