### ISSUE TITLE
Set up Ask for Network site

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#493]
MoFo is keen to use Coral's Ask tool for engagement with the network. We'd like to set this up soon for use during the member preview period. 
 - Long-term, we can explore migrating to SaaS option with Coral, but it's not viable now. 
 - Short-term, we can look at the instance for Internet Health Report. Unsure, but maybe that can serve our purpose. 
    - I will investigate from an admin perspective. 
    - @cadecairos Is that on our servers?

**Comment by cadecairos** [comment]
> @cadecairos Is that on our servers?

no, we don't run that, I'm pretty sure it was set up by the Coral folks.

**Comment by cadecairos** [comment]
@xmatthewx What's our timeline on this, should I prioritize setting up infrastructure for this tool?

**Comment by xmatthewx** [comment]
I'm not familiar with your other priorities. This is pretty high relative to other network site and pulse things. If you're able to poke at it this week, that'd be great.

**Comment by cadecairos** [comment]
Closing in favour of the issue with all the comments. #475
