### ISSUE TITLE
Set up analytics for Story Engine

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#494]
No rush, but we'd like to add analytics to https://storyengine.io/. Is this hosted with wpengine?

We'll be linking to it from the network site.

**Comment by cadecairos** [comment]
Yes this is WPEngine.

1. [ ] Add GA property
2. [ ] Add GA plugin to wordpress?
3. [ ] Add tracking code

**Comment by gideonthomas** [comment]
This is done and should work as long as the wordpress theme for that site doesn't change
