### ISSUE TITLE
add google auth API keys to network-api staging

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#496]
The Network-API has Google Auth provisioned, and needs a google key and secret value set in order to become live. The only APIs this app will need is Google+, so that user authentication can happen.

The env vars needed are:
```
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=...
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=...
```

Note that the key/secret may end in `.app.google.blahblahblah`: that part should not be used. Only the string data preceding `.app......`

The callback URL will need to be `/soc/complete/google-oauth2/`

**Comment by cadecairos** [comment]
This is complete
