### ISSUE TITLE
add CDN routing for network pulse endpoints on network-dev

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#498]
The following network-dev staging routes need to be resolved to the network api instance in order for pulse clients to work:

- `/nonce`
- `/userstatus`
- `/login`
- `/logout`

And then for the "full API under a namespace" let's clear `/api/pulse` as base route

**Comment by cadecairos** [comment]
This is not needed since the routes are on `/api/` which has the correct behaviour settings.
