### ISSUE TITLE
add publish.wmo to http://status.mozillafoundation.org/

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#500]
Right now there's status information for thimble, and login, but not for the publish server, which is crucial to thimble but can fail independently of it.

**Comment by cadecairos** [comment]
does it have a healthcheck endpoint?

**Comment by Pomax** [comment]
it does. The info is summarily at best (it's just `{"http":"okay"}`) but it should be there.

**Comment by cadecairos** [comment]
Done: http://status.mozillafoundation.org/2968192

Bonus status banner
![publish status banner](https://share.pingdom.com/banners/982521e2)
