### ISSUE TITLE
Create view for localhost analytics on network site

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#502]
While developing, it should be easy to see the analytics from a development build of the site, so we know that our analytics code is doing something. Could be hits from localhost:2017 or 127.0.0.1:2017.

**Comment by cadecairos** [comment]
@alanmoo I created a "Dev" view with include filters for localhost and 127.0.0.1

Can you verify that analytics are going through?

**Comment by cadecairos** [comment]
I loaded up the network site on `localhost` and saw that my session was logged on GA. marking this issue closed.
