### ISSUE TITLE
Inventory production databases and make sure they have backups

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#504]
Let's make sure all our production apps with databases have backups/snapshots working.

**Comment by cadecairos** [comment]
I've verified that our AWS databases are all running daily backups.

**Comment by cadecairos** [comment]
api-mozillascience-production has a hobby-dev database - and no backups.

We'll need to migrate it over to something bigger to get backups.

**Comment by cadecairos** [comment]
teach-api-production is also hobby-dev, needs a migration.

**Comment by cadecairos** [comment]
All other DB's on Heroku (that are production) have daily and weekly backups.

**Comment by alanmoo** [comment]
Does that mean those two also spin down after a period of time?

**Comment by alanmoo** [comment]
Let's migrate them (#524). Aside, what's the teach-api used for?

**Comment by cadecairos** [comment]
> what's the teach-api used for?

It's a Django server that has a couple functions. Its Django admin site is used managing clubs stuff, I think. It also connects learning.mozilla.org to id.webmaker.org.

**Comment by alanmoo** [comment]
Cool. Then I'd say this ticket is closed and the work continues in #524.
