### ISSUE TITLE
New email address & google group: matching@mozillafoundation.org

### ISSUE THREAD

**Issue by WillatMozFdn** [MozillaFoundation/mofo-devops#505]
### Details
We need a new, centralized email point of contact to remind people about, and then support them in, the possibility of getting their employer to match their donations to Mozilla; we're not doing a good job at all of that right now and so we're leaving money on the table.

### Info & links
New email address requested: matching@mozillafoundation.org
Set up as a Google Group with members: Rose-Regina Lawrence, Will Easton, Stephanie McVicker

**Comment by cadecairos** [comment]
List created and invites sent! 

I'm going to consider this closed - we can open new issues if there are any issues getting started.
