### ISSUE TITLE
Turn off caching on MozFest site?

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#506]
I'm wondering what the reason was that we enabled caching on MozFest site. Was it because MozFest site gets lots of traffic? If not, I wonder if we can turn it off so that site changes can appear immediately after we deploy a new build. Otherwise it usually takes about 15-30mins for changes to really go live which is a bit long for a site that is prone to have frequent changes here and there.

**Comment by cadecairos** [comment]
Caching speeds up load times globally. I wouldn't suggest removing the cache entirely, but we can reduce it to five or ten minutes.

**Comment by mmmavis** [comment]
@cadecairos cool that'll be great. In terms of priority - this is not urgent at all. 😉

**Comment by cadecairos** [comment]
I've edited the CDN to only cache for 300 seconds before checking for new content from the origin.
