### ISSUE TITLE
Set Up MoCo Internet Health Marketing Team with temp guest Thinglink access

### ISSUE THREAD

**Issue by caltrider** [MozillaFoundation/mofo-devops#508]
MJ Kelly on MoCo's Internet Health marketing team wants to use our Thinglink accout for a piece of content they are making.  

@cadecairos can you give them access in some way?

**Comment by cadecairos** [comment]
@caltrider What's the email address of the person we're adding?

**Comment by caltrider** [comment]
@cadecairos It's mjkelly@mozilla.com

**Comment by cadecairos** [comment]
I've sent a guest invite.

**Comment by cadecairos** [comment]
This is done!
