### ISSUE TITLE
Enable Appveyor for mozilla/brackets

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#514]

**Comment by cadecairos** [comment]
Hey, got plans to implement this or should I steal it back one day? same q for #513 and #512

**Comment by gideonthomas** [comment]
oh sorry, got side-tracked and forgot. I can do this this week!

**Comment by cadecairos** [comment]
@patjouk feel free to switch context to this issue while working on the Heroku inventory stuff. The network repo has an `appveyor.yml` file that can serve as a template, and I can also meet with you to go over the appveyor config file if you'd like.

I'm also going to assign https://github.com/mozillafoundation/mofo-devops/issues/512 to you, which is also appveyor related.
