### ISSUE TITLE
Please kill a temporary Heroku instance "temp-mozfest-cfp-2017"

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#520]
https://dashboard.heroku.com/apps/temp-mozfest-cfp-2017

I created this instance for the call for proposals feature branch. Now that the branch has been merged and pushed live, we no longer need this Heroku instance. I don't have the rights to remove it from Heroku so please help me do it. Thanks!

**Comment by cadecairos** [comment]
Done!

**Comment by mmmavis** [comment]
wow that was fast 👍 😄
