### ISSUE TITLE
Analytics access for wirelesschallenge.mozilla.org

### ISSUE THREAD

**Issue by hannahkane** [MozillaFoundation/mofo-devops#522]
Can you please provide GA access for @hannahkane and @mehan?

Thank you!

**Comment by cadecairos** [comment]
@hannahkane There doesn't appear to be any GA property for that site in the Mozilla GA accounts.

I searched through all open and closed devops issues, and no request was put in for a property to be created. Was this missed(bad), or did someone create a GA property outside of our GA account(worse)?

**Comment by cadecairos** [comment]
Based on a search of the source code: https://github.com/mozilla/nsf-challenge/search?utf8=%E2%9C%93&q=analytics

Google Analytics is not present at all.

**Comment by hannahkane** [comment]
Thanks, @cadecairos. This is my mistake. I did not ask for it initially, and should have.

I'll file a separate ticket.

@mehan - unfortunately, this means we won't have metrics for your upcoming report, but I'll see if I can find someone to add analytics soon, so that we have some data for the next one. I'm very sorry.

**Comment by cadecairos** [comment]
I can give you a very rough (not de-duped, or filtered for bots) idea of the requests made to the site through CloudFront:

![](https://screenshots.firefoxusercontent.com/images/207c69d8-01ee-473c-8eed-6e7414a44c35.png)

**Comment by mehan** [comment]
@hannahkane No worries, thanks for looking into this. Would be great to get GA added soon, as we'll definitely need these numbers again a year from now.

@cadecairos Thanks for the CloudFront data, very helpful! If I was going to roughly characterize these numbers, could they be considered equivalent to pageviews?

**Comment by cadecairos** [comment]
@mehan no, I wouldn't characterize these as page views. It includes all requests to the CDN for things like JS and Images.

I can see 16,927 requests to `/` between 05/08/17 and 07/06/17 - but I'm not sure if the site has "virtual" pages (via React Router, for example) that would not be counted here

**Comment by mehan** [comment]
@cadecairos It's more or less a single-page site, so that number probably captures what we need. Thanks!

**Comment by cadecairos** [comment]
Awesome, I'll close this out for now, and we can file a new issue when we're ready to create a property for wirelesschallenge.mozilla.org
