### ISSUE TITLE
Migrate teach-api-production and api-mozillascience-production to paid instances

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#524]
As discovered in #504, these should be backed up (and not spin down periodically), so let's move them to paid instances and make sure backups are enabled.

**Comment by cadecairos** [comment]
I double checked the docs, and based on [the docs](https://elements.heroku.com/addons/heroku-postgresql), the free db does let us store backups (just not very many)

**Comment by alanmoo** [comment]
What about uptime?

**Comment by cadecairos** [comment]
The free DBs don't come with any guarantees of uptime, or ability to schedule maintenance windows, so we probably should bump them up to the standard 0 plans.

**Comment by alanmoo** [comment]
Sounds good to me.

**Comment by cadecairos** [comment]
teach api migrated.

**Comment by cadecairos** [comment]
scienceapi migrated.
