### ISSUE TITLE
Renew BrowserStack Subscription

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#526]
Just noticed a banner when I login to BrowserStack that says that "Your subscription ends in 29 days".

**Comment by cadecairos** [comment]
I sent a support request, we appear to be on some kind of special plan that can't be renewed via the dashboard.

**Comment by cadecairos** [comment]
@gideonthomas:

> Hello,
>
> Thank you for writing in.
> 
> I see that your sponsored account is set to expire on 18th of August, 2017.
> 
> If you wish to reactivate this account, please share with me the updated GitHub page/ website wherein BrowserStack is mentioned and the logo has been updated.
> 
> Also, please find the attachments for the concerned BrowserStack files.
> 
> Thanks and have a nice day!

**Comment by gideonthomas** [comment]
Looks like this is done! Thanks @cadecairos!
