### ISSUE TITLE
Investigate teach api's missing clubs

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#528]
As per Julia's email yesterday. In Slack she mentioned July 15 may have been the last time clubs that were created between August 2015 and July 2017 were in the database.

>something else we noticed that might be related? The Club guides on learning.mozilla have disappeared as well. https://learning.mozilla.org/en-US/clubs/running

**Comment by cadecairos** [comment]
I'm not sure what happened here, but here's what I've found out so far:

* on [July 18th we upgraded the database](https://github.com/MozillaFoundation/mofo-devops/issues/524#issuecomment-316108524) from a free version of Heroku Postgres to a $50 plan. I used the standard `pg:copy` method to copy all data to the new DB.
* Heroku Postgres stores up to three weeks of daily backups. I've downloaded and restored (locally) backups from July 11th to 17th
* There's no clubs data from any time after August 12, 2015..... 😕 

Whatever happened, happened outside of the backup retention period, and was not detected until now it seems...

**Comment by alanmoo** [comment]
Do we only have those 3 weeks because we upgraded? (What would we have had today if we hadn't? What would we have had if we'd been upgraded all along?)

**Comment by cadecairos** [comment]
> Do we only have those 3 weeks because we upgraded?

no, Heroku Posgres just keeps three weeks of daily snapshots automatically.



> What would we have had today if we hadn't?

The same data



> What would we have had if we'd been upgraded all along?

the same data

It's my opinion that the database update had nothing to do with this missing information - it's just a coincidence. I believe this because the week of backups that we still have from before the migration do not contain the missing data.

**Comment by jvallera** [comment]
Hiya, just checking back on this. Is there any way to get the data back? we probably have a csv file downloaded from last month if it helps.

**Comment by alanmoo** [comment]
We've been working on this and will have an answer tomorrow.
