### ISSUE TITLE
Migrate paperstorm copyright & enable new domain

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/mofo-devops#530]
Here are the things Moniker needs to set up the new dev environment, and to migrate the previous campaign.

**Duplicating old campaign servers**

We decided on moving the old campaign to a different (sub)domain (copyright.paperstorm.it) and use the top domain for the new campaign. This basically means we would need a duplicate setup: 

2 CMSes, 2 API instances, 2 tile server instances, 2 S3 buckets for tiles, and 2 (different) front-ends. Ideally we would duplicate the current setup and make it work with new *.copyright.paperstorm.it domains and use the originals for the new campaign. But of course we're open for any suggestion to make it easier/better. I can imagine it might be easier to just create new instances of servers/app and just change the DNS records...

Probably we would also need a new Google Analytics key for the new campaign, but maybe I should ask Vojtech about this (he set this up the last time...)

Domains / apps for old campaign (copyright)

- [x] copyright.paperstorm.it

This will run the front-end code that's currently on paperstorm.it (I do need to update the URL reference though)
- [x] api.copyright.paperstorm.it
This points to a copy of the current paper-storm Heroku app
- [x] cms.copyright.paperstorm.it
This points to a copy of the current EC2 instance that's running the CMS
- [x] tiles.copyright.paperstorm.it
This points to the current S3 bucket
- [ ] copy of paper-storm-tiles app
Used the generate new tiles for tiles.copyright.paperstorm.it
Domains / apps for new campaign (net neutrality)

- [ ] paperstorm.it
This will run new front-end code for the new campaign about net neutrality. Probably Jenkins also needs some new configuration
- [ ] api.paperstorm.it
This points to the current paper-storm Heroku app. We will update the API to provide the new functionalities necessary for the new campaign.
- [ ] cms.paperstorm.it
This points to a the current EC2 instance that's running the CMS. We will update the CMS to provide the new functionalities necessary for the new campaign.
- [ ] tiles.paperstorm.it
This points to a new S3 bucket for the net neutrality tiles and should have a similar IAM policy to tiles.copyright.paperstorm.it
- [ ] paper-storm-tiles app
Used the generate new net neutrality tiles for tiles.paperstorm.it

**Learnings from previous setup**

When we were setting up the previous campaign we ran into some problems. We made a short list of those things to make setting up the new campaign a smoother experience

**CMS**
- [x] make sure the following IP addresses have (ssh) access to the EC2 instances of staging and production: 92.111.109.14 (Moniker), 83.86.161.28 (Thomas), 77.250.170.33 (Tjerk)

- [x] sudo rights on EC2 instances for Moniker
- [x] enable mod_rewrite module
- [x] S3 tile buckets
- [x] generate S3_SECRET_ACCESS_KEY without slashes for S3 buckets
- [ ] set Access-Control-Allow-Origin header to correct domain
- [ ] double-check CloudFront headers (hit/miss, cache settings)
- [ ] check IAM policy

**Comment by thomasjonas** [comment]
@brettgaylor @cadecairos hello :) Let me know if there's something me or @woudsma can help with. Any updates are also greatly appreciated!

**Comment by cadecairos** [comment]
Hi @thomasjonas! I'll spin up all the resources we need today/tomorrow.

**Comment by thomasjonas** [comment]
@cadecairos Any update on this?

**Comment by cadecairos** [comment]
I've created two Heroku apps:
1. api-paperstorm-na-production
2. tiles-paperstorm-na-production

You'll have to refresh my memory over how we've been deploying code to these apps (the EU copyright ones)

I've also cloned the CMS instance. I still need to set up a load balancer and Security Groups, and tie it all together with a Cloudfront CDN.

After that's set up, I'll set up an S3 bucket and a Jenkins job.

I will also set up all the necessary CDNs for the tile server, the api server and the frontend.

**Comment by thomasjonas** [comment]
@cadecairos Thanks for setting up the Heroku apps. I don't see them yet in the Heroku dashboard, though. Did you share them with us? And did you also install the Postgres + Redis plugins?

Last time we just pushed our code to Heroku. @woudsma probably has a better memory about this.

@brettgaylor also mentioned creating a separate Slack channel for this new campaign. Would that be easier for this kind of discussion or do you prefer to keep this all in the Github issue?

**Comment by brettgaylor** [comment]
+1 - can we create a #paperstorm slack channel and invite moniker folk?

**Comment by cadecairos** [comment]
@thomasjonas I'll add the addons, and add the team as collaborators.

@brettgaylor I'm not sure what the process for adding non-employees to our Slack instance is. It might just be faster to use Mattermost.

**Comment by cadecairos** [comment]
@thomasjonas I've added you and Tjerk to the two new Heroku apps.

**Comment by cadecairos** [comment]
OK, I've wired up all the AWS bits, excluding custom domains.

I will test this all tomorrow, and report back here with our temporary URLs

**Comment by brettgaylor** [comment]
I've filed an IT request to see if we can't get you guys on Slack.

**Comment by thomasjonas** [comment]
@cadecairos ok, great! Let me know when we can start testing this!

**Comment by cadecairos** [comment]
OK, here's a list of resources we can test out:

* CMS
  * URL 
    * https://dqjqqzo92emvy.cloudfront.net/panel/
  * SSH Hostname
    * ec2-54-205-143-127.compute-1.amazonaws.com
       * Access should be enabled for the IPs above, using your SSH keys for identification.
* Tile server
  *  App
      * tiles-paperstorm-na-production
  * URL
    * https://d1ijblgpmrx3tf.cloudfront.net
* API Server
  * App
    * api-paperstorm-na-production
  * URL
    * https://api-paperstorm-na-production.herokuapp.com/
* Frontend
  * https://d2wtt95elkafnj.cloudfront.net

**Comment by thomasjonas** [comment]
@cadecairos Thanks! I think we only need S3's access key, secret access key and bucket name to get it all up and running. Could you put these in the config vars for tiles app? (like [here](https://dashboard.heroku.com/apps/paper-rain-tiles/settings)) Or send them via e-mail otherwise? Also the S3 secret key can't have a slash in it (some bug in a node library)...

We're also wondering what will be the staging server. Are we going to re-use the old staging server for the new campaign? Will the apps you just set up be used for production? We somehow need to transition the current paperstorm.it to copyright.paperstorm.it. What would be the best way to do that?

@brettgaylor you can already fill in the new texts on the CMS URL that Chris sent. You can login with the credentials you used for the copyright campaign. Is there anybody else who needs to have access to the CMS besides you, Chris and Moniker?

@woudsma will work on the tile server and api tomorrow, he'll let you know if there are any problems. I'm already working on the front-end but we need a Jenkins setup to put it online. Can you set that up Chris? And is there anything else that still needs to happen?

**Comment by cadecairos** [comment]
I've added keys to the tile app.

I think we should use the staging environment we had set up, if we could. Otherwise we can use this as staging and I'll have to set it all up again

When we're ready to go live with the new site, we will need to do the following:

1. Get SSL certs for the new domains
2. Update CMS config with new domains
3. Update the Jenkins job for the frontend with the new URLs and run a build
4. Update the Tile server and API server with new domain configurations
5. Update the custom URLs and Certs on the Cloudfront CDNs
6. Update Route53 config for new domains

^ and then do the same for the new infrastructure going up.

The process will take a couple hours before we can be sure that it's all working properly.

**Comment by thomasjonas** [comment]
Thanks again! Cool, we'll use same the staging environment like last time. Makes sense...

Could it be a good idea to install the apps we have running now for the old copyright campaign on the new environment? So we would have copyright.paperstorm.it (old env) and paperstorm.it (new env) the same, until we push the new campaign to the new environment. That would maybe be a bit more work now, but would make going live a bit faster.

**Comment by cadecairos** [comment]
> Could it be a good idea to install the apps we have running now for the old copyright campaign on the new environment? So we would have copyright.paperstorm.it (old env) and paperstorm.it (new env) the same, until we push the new campaign to the new environment. That would maybe be a bit more work now, but would make going live a bit faster.

I think that's what I'm proposing? I'm planning to keep the existing resources, just update their URLs, configs, and Domain settings, so we can put the new resources where they used to be.

**Comment by thomasjonas** [comment]
Ah ok, good. So the copyright.paperstorm.it will be ready soon? I have to make some adjustments to the code to make it work with the new domain...

**Comment by cadecairos** [comment]
Should we move everything over there now, and put temporary redirect up? Then, once the new campaign is ready, we put it up?

**Comment by thomasjonas** [comment]
Yeah, I guess a redirect is fine. That might be actually be the easiest solution. Another option would be to deploy another copy of the old campaign front-end code on the new environment and have it connect with the cms.copyright.paperstorm.it, api.copyright.paperstorm.it, and tiles.copyright.paperstorm.it. But that might make things a bit overly complicated. 

Let's just temporarily redirect it, so the old campaign is all taken care of.

**Comment by woudsma** [comment]
@cadecairos Could you empty the staging S3 tile bucket? We changed the tile rendering, i think it makes sense to clear the old rendered tiles on staging.

**Comment by cadecairos** [comment]
@woudsma cleared it out!

**Comment by thomasjonas** [comment]
@cadecairos is it possible to get the copyright.paperstorm.it domain up and running? And have paperstorm.it temporarily redirect to it? I would rather do this now, instead of when we're finishing up the new campaign...

**Comment by cadecairos** [comment]
@thomasjonas I can try to get this done tomorrow
 
I'm taking this Friday off, and won't be back at it until the 5th (there's a Canadian holiday on the 4th) - so If it proves to be too much work for a single day's worth of effort, it will have to be completed next week.

**Comment by thomasjonas** [comment]
@cadecairos Hope you had a nice few days off! Sorry I didn't reply earlier. It would be nice if you can start with the redirect. Let me know if you need any help!

**Comment by cadecairos** [comment]
Hi @thomasjonas I worked on this a bit last week but ran into an issue when acquiring SSL certificates for the domains. I'm waiting on hearing back from AWS on the issue.

**Comment by cadecairos** [comment]
OK, I successfully worked around the problem I had issuing SSL certificates using AWS to `paperstorm.it`

I'm going to start setting up temporary redirects from `*.paperstorm.it` to `*.copyright.paperstorm.it`

**Comment by cadecairos** [comment]
`tiles.paperstorm.it` now redirects to `tiles.copyright.paperstorm.it`

**Comment by cadecairos** [comment]
OK all the domains are switched over, but I'm seeing CORS issues loading tiles, because browsers are refusing to complete the tile requests if they redirect.

**Comment by cadecairos** [comment]
I'm going to see if updating the URLs in the jenkins build of the front-end fixes this.

**Comment by cadecairos** [comment]
OK, the copyright campaign now lives at `*.copyright.paperstorm.it` (even the CMS, I updated the kirby config)

`paperstorm.it`, `cms.paperstorm.it`, and `tiles.paperstorm.it` are redirecting temporarily and can be configured with the new production resources when we're ready.

**Comment by thomasjonas** [comment]
That's great! Thanks! I'll have a closer look on monday, but everythings seems to be working fine.

**Comment by thomasjonas** [comment]
@cadecairos I just tried to deploy to the new production server, but something seems to go wrong when the build product needs to be copied to S3. Do you have any idea what's wrong?

Log:
```
ERROR: Failed to upload files
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 080A866E7837F9AF), S3 Extended Request ID: gfslGZI/odffa1brPkOuIW9D4M1v3ifk9nExt4eSgPoha3Hz+gCzNY/b5QWipA4rl4fMI7cKmuk=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4187)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4134)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1720)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Build step 'Publish artifacts to S3 Bucket' changed build result to UNSTABLE
Finished: UNSTABLE
```

**Comment by thomasjonas** [comment]
Also I'm unable to ssh into the staging ec2 instance. But that might be because I'm not sure what the correct host is... What is it again? Thanks!

**Comment by cadecairos** [comment]
@thomasjonas 

You should be able to connect from your IP and with your SSH key at ec2-54-205-143-127.compute-1.amazonaws.com

I'll look into that build failure

**Comment by cadecairos** [comment]
OK, I'm pretty sure it was a configuration issue in the IAM policy attached to the IAM user. It should be resolved now.

**Comment by thomasjonas** [comment]
Great! Just made a few builds and adjustments and almost everything seems to work now. Just need to double check the tile creation with @woudsma tomorrow. Thanks for all your work!

**Comment by woudsma** [comment]
@cadecairos I think i have the same problem as Thomas, i'm getting a `AccessDenied: Access Denied` error when uploading to S3 from the tile production server. Could this also be an IAM policy issue?

**Comment by cadecairos** [comment]
I'll check that out now

**Comment by cadecairos** [comment]
@woudsma Yeah, It looks like it was a policy issue, I've updated it to reflect the new bucket.

**Comment by thomasjonas** [comment]
The last hurdle is to fix the CORS issue for the tiles... Or is this related to not running the website from the paperstorm.it domain?

```
Access to Image at 'https://d1ijblgpmrx3tf.cloudfront.net/19.149959.200588.png' from origin 'https://d2wtt95elkafnj.cloudfront.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://d2wtt95elkafnj.cloudfront.net' is therefore not allowed access. The response had HTTP status code 403.
```

**Comment by cadecairos** [comment]
Yeah, the CORS policy on the S3 bucket allowed for paperstorm.it only.

I added d2wtt95elkafnj.cloudfront.net to the policy for now

**Comment by thomasjonas** [comment]
Great! Thanks! @brettgaylor and @cadecairos any idea when we're going live tomorrow? I think @cadecairos only needs to disable the redirect we setup earlier to launch the campaign. Or am I forgetting something? Would be nice to do the transition end of the day (17:00ish, which would be around 10:00 for you guys?) so we have the chance to troubleshoot incase anything goes wrong...

**Comment by cadecairos** [comment]
heh, didn't know we were going live tomorrow. I'll need to make several DNS changes, install some certificates, and possibly change some config variables.

Note that it can take up to 24 hours for changes to domains to propagate across all networks - meaning "go-live at 10 AM EST" might only affect the networks that pick up those changes immediately.

**Comment by brettgaylor** [comment]
I didn't understand there was more to do here - thought we were good to go!

@thomasjonas I understood that you guys would be making the site live, so crossed wires there.  @cadecairos can you do steps you mention above first thing eastern time, so these folks in Amsterdam can confirm things are working as they should?

Thanks!

**Comment by thomasjonas** [comment]
@brettgaylor @cadecairos o oh, that's sounds like a lot more work then I realised... I'm really sorry I didn't inform you earlier about going live. I hope we can make it on time! Let me know if I can help with anything!

I also checked whether the CORS settings for d2wtt95elkafnj.cloudfront.net are working, but that doesn't seem the case. Maybe double check those for paperstorm.it?

**Comment by woudsma** [comment]
@cadecairos Can you scale the tiles-paperstorm-na-production app to professional dyno's? I think we are still on the hobby plans. It's nearly hitting 100% on 512MB memory.
Also the old paper-storm-tiles-production app is still running on professional dyno's, i'm sure we can scale that one down!

**Comment by cadecairos** [comment]
Good call!  I've scaled the copyright tile app down to hobby and scaled the new one to professional dynos

**Comment by cadecairos** [comment]
this is done now!
