### ISSUE TITLE
Setup postcrimes infrastructure

### ISSUE THREAD

**Issue by brettgaylor** [MozillaFoundation/mofo-devops#531]
Placeholder here, as we don't know quite yet what we'll need.

We won't need to migrate, though, and probably won't keep the name.  So it may be just a matter of registering a new domain, and letting young astros deploy as needed.

**Comment by cadecairos** [comment]
- [ ] staging app on Heroku
- [ ] production app on Heroku
- [ ] Mongo DB addon for staging/production

It'll be easier to create apps if I know what we're calling this, otherwise we can use a code name!

**Comment by cadecairos** [comment]
Heroku Pipeline: https://dashboard.heroku.com/pipelines/09585229-3f7b-4699-970c-4df6ab712d64
Staging: https://dashboard.heroku.com/apps/net-neutrality-staging
Production: https://dashboard.heroku.com/apps/net-neutrality-production

**Comment by cadecairos** [comment]
MongoDB addons set-up.

Now I just need to know where the code is!

**Comment by cadecairos** [comment]
This doesn't appear to be something that's happening. lets re-open if we decide to do this in the future.
