### ISSUE TITLE
Create playbook for database migrations

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#532]
Include "Download the most recent backup and compare it to production" as a step before migrating.

**Comment by cadecairos** [comment]
## Draft

1. Download latest backup and restore it to a local postrges database
2. Verify data integrity of the backup
3. Proceed depending on service (Heroku, AWS RDS)

Heroku PostgreSQL:

[I wrote a bash script that can automate this process: ](https://gist.github.com/cadecairos/4ca05411f1156c2b6303b010d0f74f14)

1. Enable maintenance mode on the app
2. Scale the app's dynos to 0
3. Initiate the automated migration using `heroku pg:copy`
4. Remove the old database plan
5. Set the new Database URL config value to `DATABASE_URL` (or whatever value the app expects)
6. Scale the dynos back up
7. Disable maintenance mode

AWS RDS:
1. Create a read replica of the desired size and wait for it to catch up
2. Promote the read replica to be the master database
3. Update the database connection string of the application

**Comment by alanmoo** [comment]
@gideonthomas maybe you have some thoughts on that?

**Comment by gideonthomas** [comment]
lgtm

**Comment by cadecairos** [comment]
alright, I'll get a PR up.
