### ISSUE TITLE
Restore teach-api club data

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#535]
Let's use Julia's CSV and restore the approved clubs.

**Comment by cadecairos** [comment]
@alanmoo do you have the CSV?

**Comment by alanmoo** [comment]
Sent via slack.

**Comment by cadecairos** [comment]
@alanmoo this is going to require a lot of work, and I'm also not sure if it's technically possible with the data we have in that spreadsheet. With clubs winding down eventually, how important is it we put in an effort to do this?

**Comment by alanmoo** [comment]
@jvallera What are your thoughts?

**Comment by jvallera** [comment]
I think it depends on how we want to archive Clubs. We've been talking to @jessevondoom and @Sydette about including people's Clubs on a Legacy page so they can continue to point to them now and in the future. Adding @ldecoursy who is helping manage Clubs sunset.

**Comment by cadecairos** [comment]
@ldecoursy Do you have any insight into how we're going to archive this data?

**Comment by ldecoursy** [comment]
Per @jvallera's note above, @jessevondoom and @Sydette have a plan for a Learning repository / legacy page linked to the Foundation site. In the short term (at least 4-6 months), we're not shutting down the Learning site - so want to keep the map and list of clubs. That timeframe is in part based on MoCo developing plans for its "clubs" initiative. cc @amirad

**Comment by cadecairos** [comment]
I'm going to look into this again, but I'm fairly sure I don't have enough data in the spreadsheet to restore the data in the tables.

**Comment by cadecairos** [comment]
@alanmoo So this fell off at some point, but I'm still of the opinion that we don't have enough data to restore tables. Is there any actionable tasks left relating to teach-api?
