### ISSUE TITLE
Switch thimbleprojects.org to an Amazon cert

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#540]
### Details
Amazon provides free certificates for Cloudfront/ELB's, but we're using a DigiCert certificate for thimbleprojects.org. Lets verify thimbleprojects.org on AWS Certificate Manager, and replace the DigiCert certificate with a free one. Once installed, lets also revoke the Digicert certificate to get a refund on the balance of the cert.

**Comment by patjouk** [comment]
<img width="581" alt="screen shot 2017-10-06 at 1 22 28 pm" src="https://user-images.githubusercontent.com/481052/31290195-925e20c6-aa99-11e7-8a13-ccfc39a4ce23.png">

It's done :)
