### ISSUE TITLE
PTO tool marks Manager's calendar as blocked

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#541]
This isn't urgent, but it actually makes scheduling across the org a bit difficult. 

Here's the situation: When someone on my team requests PTO and I approve, it lands as an entry on my calendar. That's cool, but it shows me as blocked all day or all week. I have to manually change the entry to show me as available. 

Is this due to my calendar defaults? Is it avoidable? Does the event need to be on my calendar since I can see the org's PTO calendar?

cc @MandyRawls

**Comment by cadecairos** [comment]
I took a look at the Google Apps Script powering that tool, and there's no indication that the busy/free state is being set at all. I then took a look at the docs, and Google doesn't provide a method for having an event show as busy/free by default.

There also seems to be an [ongoing thread](https://productforums.google.com/forum/#!topic/calendar/FGvvgTrhgEs) (3+ years!) about adding the ability to set calendar defaults for events that is not being acted upon by Google.

Unfortunately, from what I can see, there's no way to have the tool specify if the event attendees' calendars should be marked busy or free, and there's no way for attendees to specify a default. It seems there's a magical point in Googles systems where it decides that for us...

**Comment by MandyRawls** [comment]
Ali also looked into this when we launched the tool, and sadly there doesn't seem to be a fix. @cadecairos is there a way for the PTO calendar invites to just go to the requester, and not the approver (manager)?

**Comment by cadecairos** [comment]
@MandyRawls have you had a chance to determine if we were able to remove the event from the manager's calendar?

**Comment by cadecairos** [comment]
@MandyRawls Can you update this issue with any more information?

**Comment by MandyRawls** [comment]
Hi @cadecairos if it's not possible to mark the manager as "available" rather than "busy" on the calendar invite, then we are fine to remove the manager completely and just have the employee on the invite. Please let me know what's possible and what, if any, changes are made to the app. Thanks!

**Comment by cadecairos** [comment]
@MandyRawls I think we'll need to meet to get this updated. If I recall correctly, you need to make the code change and publish, otherwise the App Scripts permissions get all screwed up. When is a good time to sync up to fix this up?

**Comment by MandyRawls** [comment]
@cadecairos sounds good, anytime next Mon-Wed would be ideal!

**Comment by cadecairos** [comment]
@MandyRawls I found something that suggests removing the trigger, publishing a new version, and then adding the trigger again. Lets sync up in a vidyo call sometime soon to try this out.

**Comment by MandyRawls** [comment]
@cadecairos maybe we could find a time at all hands to meet on this, might be helpful to work on it in person? Let me know what you think!

**Comment by cadecairos** [comment]
I'm going to close this issue. We attempted to fix the problem but Google Apps scripting is not a very good dev environment, and we weren't able to fix it. If this is still a huge problem, lets consider alternative PTO tracking tools?
