### ISSUE TITLE
Creation of a playbook for people on call

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#546]
One of our road map goals is to onboard the rest of the dev team on the on-call rotation. To do that, we need docs!

For each alert that could be triggered, we could use a template similar to this one:

```markdown
# Alert name - critical/non critical

## Meaning and impact

Describe which part is broken when this alarm is triggered.
What are the consequences (what is down, is it impacting users, etc).

## Where to investigate

Make a list of places to investigate first:

* _go here_
* _and also here_
* _etc_

List (with links) relevant documentations, logentries queries that could help, service name on Heroku or AWS if it's different, etc.

## Common causes and resolutions

Try to find reasons that could triggered the alarm and things to do to resolve it.
Add a list of commands that could resolve the problem, etc.

## Who to contact

It could be useful to list people to contact in case the issue can't be resolved.
```

Since our services are on multiple repos, we will need to create a new one to host this playbook. We should also think of a way to make it easily readable (maybe read the docs?).

**Comment by cadecairos** [comment]
My gut feeling is to create and maintain our playbooks in a new repo, does that sound good to you?

**Comment by patjouk** [comment]
Yes. This it will concern multiple repos, it's probably easier to create a new one to centralize everything. I'll update the ticket to reflect that.

**Comment by patjouk** [comment]
We [already started](https://github.com/MozillaFoundation/mofo-devops-private/pull/120) 🎉
