### ISSUE TITLE
Stand up Coral Talk instance

### ISSUE THREAD

**Issue by ScottDowne** [MozillaFoundation/mofo-devops#551]
### Details
Stand up an instance of Coral Talk for the buyer's guide. Coral Talk is a comment system to allow conversation on the buyer's guide products. The Coral project has other products, in our case we'll llikely only need Talk. I'm not super familiar with them all yet. The Talk system would be a service we stand up and then can use with our pages on advocacy.mozilla.org. It has an admin dashboard which we'll need to give access to a group of people we still need to determine.

The Buyer's Guide launches early Nov, so if we're going to be doing this it needs to be done and integrated by before end of Oct.

### Info & links
Coral Talk docs here: https://coralproject.github.io/talk/
Coral Talk github: https://github.com/coralproject/talk/
We can have been chatting with Andrew Losowsky for all our Coral Talk questions/advice.
The buyer's guide implementation ticket: https://github.com/MozillaFoundation/Advocacy/issues/1050
That ticket is about enabling a comment system on the Buyer's Guide, it's not specific to Coral Talk.

**Comment by alanmoo** [comment]
@cadecairos Priority guidance: After foundation.mozilla.org, before SEPA integration.

**Comment by ScottDowne** [comment]
There is a plugin for Coral Talk called Jigsaw which is basically a toxic comments filter.

I wanted to drop a few notes here so we don't forget. The Jigsaw plugin sends the comment to something else, so we should take a closer look as to what something else is, and determine if it'll need vendor review or not (if it needs vendor review, it'll be something we don't launch with). It's an open source service, and we'll need to get an api key from them. All I know for now, but like I said I'm putting this here so we don't forget.

**Comment by ScottDowne** [comment]
I'm told Coral Talk has a one press Heroku thing. Sounds easy. I can get more info when you're ready.

**Comment by ScottDowne** [comment]
Ah cool, @cadecairos they have a "deploy to heroku" button right in the topof their readme. https://github.com/coralproject/talk/

**Comment by cadecairos** [comment]
@ScottDowne Is there anything more we need to do here? can you take a look [at the configuration docs](https://coralproject.github.io/talk/advanced-configuration/) and see if there's anything that might need customization? I think we might want to fiddle with the email address settings.

**Comment by ScottDowne** [comment]
yeah, changing the config and adding a few plugins was the plan, but i havn't had the chance to dig in and figure it all out.

**Comment by cadecairos** [comment]
@ScottDowne I'm going to close this out, and we can work out configuration issues in the repo where work is happening.
