### ISSUE TITLE
Setup Pulse bot on MozFest slack

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#552]
In prep for MozFest, we'd like to add a bot to slack that posts latest items from Pulse. 

We have something similar on the Mozilla Slack at #mofo-pulse-latest. We'd like to repeat this, but adding the published_by and creators fields. 

Ideally, we would have to up and running early next week, as pre-festival activity ramps up. Let's discuss!

**Comment by cadecairos** [comment]
Who set up the existing integration with the Mozilla Slack instance? I wonder if we can re-use some part of that?

**Comment by xmatthewx** [comment]
The o.g. pulse bot was kindly set up by @phillipadsmith.

**Comment by cadecairos** [comment]
I've set up a Devops Zapier account (creds in the vault)

@patjouk will take a crack at a recipe for doing this. 

You may need to get an invite to the Mozfest Slack instance if you don't have an account, so you can set up an integration. The API endpoint I think we'll want to read is `https://network-pulse-api-production.herokuapp.com/api/pulse/entries/`

**Comment by xmatthewx** [comment]
👍 

People with mofo email can sign up for MozFest slack without an invite. @patjouk - ping me if you have any questions. I'm just matthew. When ready, let's create a new channel called Pulse. Thanks!

**Comment by cadecairos** [comment]
This appears to be working as expected! pulse entries are dumped into the pulse-latest channel on the MozFest Slack instance
