### ISSUE TITLE
Enable  TLSv1.1_2016 on Cloudfront CDNs

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#553]
CloudFront now lets you select a security policy: https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-cloudfront-now-lets-you-select-a-security-policy-with-minimum-tls-v1_1-1_2-and-security-ciphers-for-viewer-connections/

Existing CDNs default to TLSv1 but lets update our CDNs to TLSv1.1_2016 (which is recommended).

**Comment by patjouk** [comment]
Done :)
