### ISSUE TITLE
Google Analytics access

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/mofo-devops#556]
### Details

I would like to have access to Google Analytics (if it exists) of the following sites:
https://science.mozilla.org/programs/fellowships
https://advocacy.mozilla.org/en-US/open-web-fellows/fellows2017

Thanks.

**Comment by cadecairos** [comment]
@patjouk We'll deal with this tomorrow during our meeting.

**Comment by cadecairos** [comment]
@taisdesouzalessa you should be able to access the analytics for those sites now.
