### ISSUE TITLE
Deleting old apps on Heroku and archiving repos ✂️

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#557]
#Following the Heroku Inventory #545, we made a list of apps we will delete soon (huge list at the bottom) and also archive their repos: they're not running for 99% of them but I would appreciate if you take 5 minutes to review that list and flag ones that should stay. **I will start to delete apps on Thursday 1PM UTC**.

@acabunoc : We're not sure what to do with those apps ([done](https://github.com/MozillaFoundation/mofo-devops/issues/557#issuecomment-344333616))

@alanmoo: Same question, but with those apps (list edited, [cf comment](https://github.com/MozillaFoundation/mofo-devops/issues/557#issuecomment-342970001))
- [togetherjs-hub-prod](https://dashboard.heroku.com/apps/togetherjs-hub-prod)

List of apps to be deleted (more info on the [inventory spreadsheet](https://docs.google.com/spreadsheets/d/1nwionBMKQz90qcxRd03fuWs33Tsfx_WLRA6AghVzL_A/edit#gid=0)):

- [x] adhoctribution
- [x] advocacy
- [x] aestimia
- [x] badge-the-world
- [x] badgekit-issue-staging
- [x] badgekit-staging-site
- [x] bramble-editor
- [x] cem-aestimia
- [x] cem-openbadger
- [x] collusiondb-development
- [x] collusionweb-development
- [x] content-editor
- [x] csol-aestimia
- [x] csol-openbadger
- [x] csol-site
- [x] doctodash
- [x] dso-interview-reader
- [x] fifiback
- [x] gauntletdash
- [x] hive-nyc-directory
- [x] hive-nyc-staging
- [x] hivenyc-summer-2014
- [x] kit-builder
- [x] kit-builder-integration
- [x] leadership-network
- [x] makedrive
- [x] milestones-gh
- [x] mofo-cms
- [x] mofo-counter
- [x] mofo-mentions
- [x] moz-call-power
- [x] mozfest-badges
- [x] mozilla-bsd-cache
- [x] mozilla-foundation-iot
- [x] mozscilab
- [x] network-api-staging
- [x] network-api-unity
- [x] network-pulse-staging-pr-757
- [x] npm-readonly-mirror
- [x] obb-aestimia
- [x] obb-dev
- [x] obb-openbadger
- [x] obb-site (deleted the non working app but kept the static site)
- [x] openbadges-badgekit-production
- [x] openbadges-discovery
- [x] planet-hive
- [x] planet-openbadges-org
- [x] planet-opennews
- [x] planet-webmaker
- [x] popcornbrowser
- [x] stopwatching-us
- [x] swcarpentry
- [x] teach-cms-enabled
- [x] teach-mozilla-org-production
- [x] thunderhug
- [x] towtruck
- [x] towtruck-staging
- [x] transformtogeckoboard
- [x] usertest-login
- [x] usertest-webmaker-handshake
- [x] weblitmapper
- [x] webmaker-app-publisher
- [x] webmaker-archiver
- [x] webmaker-bugzilla-counter
- [x] webmaker-bugzilla-scraper
- [x] webmaker-handshake
- [x] webmaker-hookshot-production
- [x] webmaker-hookshot-staging
- [x] webmaker-kit-builder
- [x] webmaker-moderator
- [x] webmaker-screenshot
- [x] wm-prerender
- [x] petitions-mozilla-org
- [x] badgr-server
- [x] mezzanine-cms-experiment
- [x] collusiondb-development
- [x] collusiondb-webvelopment
- [x] mozsprint-proposals
- [x] nationbuilder-salesforce

Apps that will be turned off:
- [x] hubot-mozbot
- [x] software-citation
- [x] network-mapping-app

Not sure:
- [ ] mozillafestival-org-2015
- [ ] mozillafestival-org-2015-prod

Won't be deleted:
- cem-site (/!\ we don't own the domain)
- badgekit-api-sciencelab
- badges-mozillascience-org
- gitter-irc-bot-msl
- validator-openbadges-org-prod
- bakery-openbadges-org

**11/09 edit**:
- added to the delete list: cem-site, mezzanine-cms-experiment, collusiondb-development, collusiondb-webvelopment
- Since it's now possible to[ archive github repos](https://github.com/blog/2460-archiving-repositories), I'll also do that with apps we removed from Heroku. That way, it will be easier to navigate Heroku and Github but we won't lose content :)

**11/15 edit:**
Updated the list of deleted/won't remove apps. A few apps still have unknown status. 

CC @cadecairos @Pomax @ScottDowne @gvn @mmmavis @gideonthomas

**Comment by cadecairos** [comment]
> nationbuild-salesforce
> 
> Not sure what this is. @ScottDowne or @stephaniemcv?

This is a webhook processor written in Python/Flask by a developer at the company we contracted to build our NationBuilder stuff. It processed hooks from NB and sent them to SFDC. I think.

**Comment by jbuck** [comment]
> togetherjs-hub-prod
> @jbuck do you know if this is dead?

@alanmoo Up to you to decide! Seems to work at https://togetherjs.com/ but I don't know whether you want to support it or not.

**Comment by gideonthomas** [comment]
re: togetherjs, we might want to check what's using it and decide accordingly

**Comment by cadecairos** [comment]
> re: togetherjs, we might want to check what's using it and decide accordingly

Yeah, I think there might be sites depending on this still.

**Comment by Pomax** [comment]
What does the full list represent? I'm pretty sure we don't want to delete advocacy, for instance. Or collusion (which supposedly some moco people work on?). Also deleting past mozfest sites is kind of iffy. You want to be see a conference's past track record =)

**Comment by cadecairos** [comment]
> I'm pretty sure we don't want to delete advocacy

This isn't actually advocacy.mozilla.org - it's a dev/test app somebody made



> Or collusion

These apps are just development apps that @mmmavis made a few years ago, as far as I can tell. I will let her confirm this.

The Mozfest schedule apps aren't even being served anywhere, other than the Heroku domains. If we want these to be always on somewhere lets get it a real URL and have someone update the vulnerable Node dependencies.

**Comment by mmmavis** [comment]
Wow collusion!!! Good old times!!!

`collusiondb-development` and ` collusiondb-webvelopment` should be safe to delete (*sob sob* 😢 ). They were just my working in progress apps - I don't think they ever became "production".

For MozFest related instances `mozillafestival-org-2015` and `mozillafestival-org-2015-prod` I can't recall what the reason was that we had these. Let's check with Sarah/Erika when they are back from vacation next week.

**Comment by patjouk** [comment]
@Pomax You can find link to Heroku dashboard and github repo for every apps listed here [on this spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/1nwionBMKQz90qcxRd03fuWs33Tsfx_WLRA6AghVzL_A/edit?usp=sharing), including info on who touched it last and when, if it's runing or not, etc. I put a link to this spreadsheet in the ticket and just a simple list of apps because copy/pasting all those info in this ticket would have been really painfull.
Like @cadecairos said, most of those apps were experiment that are currently not running but were never removed from Heroku.

**Comment by patjouk** [comment]
I did a first round of unplugging 🔥 
We discover that the domain of cem-site doesn't belong to us: I've turned the dyno off but we gonna have to keep the app for now.

@acabunoc Did you have the opportunity to take a look at the app I flagged for you?

I guess I should open a separate ticket for togetherjs. I'll do that soon.

I'm not sure what I should do with `nationbuild-salesforce`. Any ideas?

**Comment by acabunoc** [comment]
Hey @patjouk thanks for pinging, just got back from PTO

These three need to stay online:
    badgekit-api-sciencelab
    badges-mozillascience-org
    gitter-irc-bot-msl

This one can be spun down:
    mozsprint-proposals

**Comment by patjouk** [comment]
@acabunoc Awesome, thanks for the quick answer :)

**Comment by stephaniemcv** [comment]
Apologies for the delay, I've been traveling :-/
Ok and yay for getting rid of nationbuild-salesforce!

**Comment by patjouk** [comment]
About `mozillafestival-org-2015` and `mozillafestival-org-2015-prod`: I'm wondering if they're still there because they were created before Heroku realized their pipelines feature and simply never got deleted after moving mozfest website into a pipeline.

@edrushka and @Saallen, maybe you have more context about those two apps (they're not running or used)? Also, do you know if it's safe to remove [this website](https://mozfest-schedule-2014.herokuapp.com) containing a schedule of mozfest 2014? It's mostly dead links to etherpards but maybe there's a good reason why it's still up.

**Comment by Saallen** [comment]
Hey it would be great to keep the 2014 website or archive but send the link so I can still access.

I defer to @mmmavis and @edrushka  for the other questions

**Comment by alanmoo** [comment]
@Saallen this is the 2014 schedule app, not the site; I'm not sure that has too much value to it, especially at a somewhat cryptic URL. I don't think the 2014 site is still up anywhere; we've been updating the main mozillafestival.org site and not doing subdomains (20xx.mozillafestival.org)

**Comment by cadecairos** [comment]
We shouldn't need to keep this live. The source code is available here: https://github.com/fuzzyfox/firehug/tree/mozfest2014

**Comment by Saallen** [comment]
Hello- for me its about the content, all the sessions.

**Comment by alanmoo** [comment]
@cadecairos Is the data in that repo? I'm not seeing it. Perhaps if we could extract it into a doc it might be a more useful place to live rather than keeping the entire app up.

**Comment by cadecairos** [comment]
I think it's in a Google Spreadsheet somewhere

**Comment by alanmoo** [comment]
I just emailed @fuzzyfox, as I believe they're the owner of the sheet in question.

**Comment by alanmoo** [comment]
@Saallen The data you're looking for is in [this sheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/1v3Qd1IJlE2lbpcnnKGvGJSm6LNvI3ERePXVse1lQKPQ/edit?usp=sharing). With access to that, can we take the app itself down?

**Comment by Saallen** [comment]
That's perfect. Thanks for finding it

**Comment by patjouk** [comment]
I'm closing this ticket: we deleted was could be and discussed the remaining issues during the all hands.
