### ISSUE TITLE
Inventory of AWS resources

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#558]
Following the Heroku inventory #545, we should do a smiliar one with resources running on AWS services.

**Comment by cadecairos** [comment]
notes: 

Resources to look for: Check Route53 CloudFront for Any S3 hosted websites. list EC2 instances/ASG/ELB for applications.

**Comment by patjouk** [comment]
After the whole SES mess, I'll start this ticket when I'm back from holidays: one AWS product per week!

**Comment by patjouk** [comment]
Closing this issue in favor of MozillaFoundation/mofo-devops-private#158
