### ISSUE TITLE
Grant me SSH access to blog.webmaker.org

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#56]
Man I wish I could escape from this for Webmaker Blog but I guess not... there's **NO** way that I can delete or modify my theme package from the Dashboard.

That said, could you grant me access to the server?  I only need access to `/wp-content` 

rawrrrrrrr :scream:  :scream:  :scream:  :scream:  :scream:

**Comment by jbuck** [comment]
Mavis is now able to login!
