### ISSUE TITLE
Tweak donate cloudwatch alarm

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#560]
The CloudWatch alarm for 5xx errors on donate it very sensitive and needs tweaking.

If I recall correctly, if it detects 5xx request volumes of >5% for >5minutes, we get paged.

This is a bit too sensitive, especially since pages tend to get cancelled almost immediately after triggering.

Maybe we can do 5xx >5% for 10 minutes?

**Comment by patjouk** [comment]
It was >0% for 5 min so I changed it to >5%. Is it okay or would you still prefer for 10min?

**Comment by cadecairos** [comment]
That's perfect, thanks @patjouk! Let's let things run their course for now and see if we stop getting pinged for false alarms/hiccups.
