### ISSUE TITLE
Adding News article in Mezzanine to website down

### ISSUE THREAD

**Issue by Sydette** [MozillaFoundation/mofo-devops#562]
When I go to add a news article to Mezzanine for site publication the form does not show up at all .  All other sections work

**Comment by cadecairos** [comment]
I can confirm this on my browser as well. It doesn't seem to be a problem on staging

**Comment by cadecairos** [comment]
Diff of staging and production right now: https://github.com/mozilla/foundation.mozilla.org/compare/b114a06a...28d2d4fe

Not sure if any of those commits would fix this.

**Comment by cadecairos** [comment]
From slack:

> After a day's worth of debugging, Pomax and I figured out the problem.
> 
> Technical details:
> 
> I was reviewing permissions on our mofo-assets bucket a couple days ago, and noticed it had a global ACL for listing objects (bad). I deleted that ACL. That seems to have been a permission that the news site required for an API call it made to our assets bucket. we were able to identify the error by forking the production environment and enabling Debug mode. Once I knew it was a permissions issue I just needed to apply the right IAM policy to the AWS keys we use on the production app.
