### ISSUE TITLE
Sydette can not moderate in pulse 

### ISSUE THREAD

**Issue by Sydette** [MozillaFoundation/mofo-devops#563]
I can not moderate in pulse. I see the submission queue, I mark things as approved, I go back and they are still there and have been reset to pending.

**Comment by xmatthewx** [comment]
I confirmed the bug with @alanmoo's help. We've elevated @Sydette's permissions as a temp fix, but should look at this at some point.

**Comment by Pomax** [comment]
I've added you to the list of "staff", @Sydette, can you see if you have persistent edit abilities now?

**Comment by Pomax** [comment]
@Sydette rescinded: there are some more odd issues going on so you should be able to moderate at the moment and @cadecairos, @alanmoo and I will have to figure out what's _actually_ going wrong here =D

**Comment by alanmoo** [comment]
Closing this and filing a follow up in mozilla/network-pulse-api
