### ISSUE TITLE
Add banner language to learning.mozilla.org re: sunsetting programs

### ISSUE THREAD

**Issue by Sydette** [MozillaFoundation/mofo-devops#564]
Hello All 

### Details

The language has been approved  but does not include Gigabit.. We are still getting emails to teachtheweb email address and would like to minimize confusion 

The approved language is below : 

Mozilla has made a strategic decision to sunset its local digital literacy programs including Hive and Mozilla Clubs over the course of 2017/2018. You have been, and will continue to be, leaders within this movement for Internet health, and Mozilla will continue to find ways to support you and concrete ways for people from our local communities to plug into this work. We will honor all current commitments to our grantee partners and donors. Content on this site, including curriculum and other resources, will continue to be available and archived here for your use. Visit foundation.mozilla.org for more information or contact mozillaclubs@mozillafoundation.org with any further questions.

**Comment by ldecoursy** [comment]
Hi - just updated the title of this ticket. We need to add the language above to learning.mozilla.org as a formal announcement of the sunsetting programs. 

Please ensure, however, that it does NOT show up on the Gigabit pages, as those are all still active.

**Comment by alanmoo** [comment]
Yes, we just need a little more clarity on where it should appear. Something like 
<img width="1226" alt="screen shot 2017-12-19 at 12 49 11 pm" src="https://user-images.githubusercontent.com/1682681/34171080-1ba4ff70-e4bb-11e7-9b54-4787194caa85.png">

Or at the top of the site? 
<img width="1259" alt="screen shot 2017-12-19 at 12 53 49 pm" src="https://user-images.githubusercontent.com/1682681/34171265-b54f1386-e4bb-11e7-8e6d-8eb38e87eb9a.png">

I'd still want a designer to take a quick pass at it, so right now I'm just trying to understand where it should be. cc @xmatthewx

**Comment by ldecoursy** [comment]
Thanks @alanmoo I like the first option but open to design opinions :)

**Comment by alanmoo** [comment]
If the first one is good (with or without a background color to highlight it?) What pages does it need to be on?

**Comment by ldecoursy** [comment]
I think a color to highlight it is useful as an important call-out. I think it's ok just on the homepage for now. I did put together this audit doc, there are other small changes that would be great at some point (not before Thursday) https://docs.google.com/document/d/1tG9Au4CM17GOM6Op1PIoWEFeQevRY7f5YImgae2kGok/edit

**Comment by cadecairos** [comment]
@alanmoo Can we migrate this issue into https://github.com/mozilla/learning.mozilla.org/?

**Comment by xmatthewx** [comment]
Given the length of this message, it would be great if @sabrinang could do a quick mock up for readability.

**Comment by alanmoo** [comment]
Migrated https://github.com/mozilla/learning.mozilla.org/issues/2539

**Comment by bacharakis** [comment]
Hi all! 
Is there any chance to put this banner in at least the Clubs page as well?
A lot of people are directly [landing to the Clubs page](https://learning.mozilla.org/en-US/clubs/) (through search engines) and they miss the banner. As a result they reach out to different communities trying to learn more about the Clubs program and how to join.

Thank you

**Comment by alanmoo** [comment]
I filed a [ticket](https://github.com/mozilla/learning.mozilla.org/issues/2547)
