### ISSUE TITLE
Set up Ask account

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#565]
@jenntbeard need a Mozilla Ask account to be able to set up a form to embed on the NSF Showcase page of foundation.mozilla.org.

No rush, in the next week or so.

**Comment by cadecairos** [comment]
@jenntbeard I've created an account for you. we need to securely get you your password. Have you ever used Signal?

**Comment by jenntbeard** [comment]
Hi - sorry, just got back. I have not used Signal before. Thanks for creating my account though!

**Comment by cadecairos** [comment]
This is done now!
