### ISSUE TITLE
Admin Access to Mezzanine to designers - Foundation site

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/mofo-devops#566]
### Details
Could we please get admin access to Mezzanine to @kristinashu and @sabrinang? 
Site: https://foundation.mozilla.org/

It would be good if they had admin access to both staging and prod.

Thanks!

**Comment by patjouk** [comment]
Hi Tais :)
They can log using their Mozilla Foundation account. Once it's done, they should send us an email so we can give them access to staging and prod.

**Comment by kristinashu** [comment]
Thanks @patjouk! I went to https://foundation.mofostaging.net/admin/login/?next=/admin/ and clicked Log in with Google. Do I need to do anything else?

<img width="1021" alt="screen shot 2018-01-17 at 10 22 45 am" src="https://user-images.githubusercontent.com/1068783/35059574-7be5b1f6-fb70-11e7-93c8-0b43cd56a3ba.png">

**Comment by kristinashu** [comment]
Never mind, it works when I go to https://foundation.mozilla.org/admin/

**Comment by sabrinang** [comment]
This doesn't work for me @patjouk. When I try logging in with my google account from either the staging link or the main admin link it just goes back to the log in with google button page?

**Comment by patjouk** [comment]
Hi!
This strange loop is probably linked to the fact I need to finish your user profile in admin, which I just did. Can you confirm that it works for you? Thanks.

**Comment by sabrinang** [comment]
I tried again on https://foundation.mozilla.org/admin/ it still takes me back after logging in with google and that button doesn't go anywhere if I click it again
![sign-in-help](https://user-images.githubusercontent.com/2492510/35349169-1121f8d2-00ef-11e8-90cf-72b634daabd0.gif)
 @patjouk

**Comment by patjouk** [comment]
Sorry about that :(
Can you try again? It should be fixed now.

**Comment by patjouk** [comment]
@sabrinang I suppose it works or you would have contacted me. I'll close this ticket now but don't hesitate to open it again if it doesn't work.
