### ISSUE TITLE
What do we think of we increasing character limits and adding links Excerpts

### ISSUE THREAD

**Issue by Sydette** [MozillaFoundation/mofo-devops#568]
-->

### Details
Excerpts currently have a 146 limit . It's hard to give a stylized voice in that amount . Can we expand to  editorialize , as well as allowing for links . 
-->

### Info & links
In recent aadhar update , I used the link in the Mozilla press release  would have liked to be able to link that press release and link to connect it more to IH language

**Comment by xmatthewx** [comment]
Is this for the foundation site? If so, let's file the issue here: https://github.com/mozilla/foundation.mozilla.org/issues/new

Dev Ops just covers Operations Tech (login things, integration with CRM or fundraising, sites slow or crashing).

**Comment by cadecairos** [comment]
Please re-file this if necessary, at https://github.com/mozilla/foundation.mozilla.org/issues/new
