### ISSUE TITLE
Create Ask accounts for team members

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#569]
Please (give)/(make sure the following people have) access to Ask

- [x] @taisdesouzalessa 
- [x] @sabrinang 
- [x] @kristinashu 
- [ ] @xmatthewx 
- [ ] @jessevondoom 
- [x] Jon Lloyd (https://phonebook.mozilla.org/?search/jon%20lloyd)

We will be familiarizing ourselves with it and possibly using it for project briefs in the future.

**Comment by cadecairos** [comment]
I've created accounts for @taisdesouzalessa @sabrinang and @kristinashu (each of you will need to help me figure out a end-to-end encryption channel we can use to transfer your login details)

We already hadhave accounts for @xmatthewx and @jessevondoom  - if you two don't know your passwords, I'll reset them and we can have them transferred (again, using an end-to-end encrypted communication channel)

**Comment by kristinashu** [comment]
Thanks @cadecairos, you've used Telegram with me before.

**Comment by taisdesouzalessa** [comment]
Thanks @cadecairos. I have Telegram too, if it helps.

**Comment by xmatthewx** [comment]
Awesome, thanks. Let's start a doc with basic info for Ask staff users. 

Super basic. Where to access, how to login. No need for extensive documentation until our use expands for realz, but it'd be good to capture basic info for ourselves.

**Comment by sabrinang** [comment]
I can use telegram as well @cadecairos, thanks for setting us up!

**Comment by cadecairos** [comment]
@xmatthewx Do you have the login details for ask that I sent previously?
@jessevondoom I've created credentials for you. How would you like me to get them to you?

**Comment by cadecairos** [comment]
Nothing more to do here. if you got creds created, but never received them, slack me!
