### ISSUE TITLE
SSL certificate for beta.webmaker.org

### ISSUE THREAD

**Issue by thisandagain** [MozillaFoundation/mofo-devops#57]
/cc @jbuck

**Comment by jbuck** [comment]
- [ ] Place request for new SSL cert
- [ ] Upload SSL cert to AWS
- [ ] Create new cloudfront distribution for beta.webmaker.org

**Comment by thisandagain** [comment]
@jbuck Any updates?

**Comment by jbuck** [comment]
All done!
