### ISSUE TITLE
Facilitate transfer of Hive NYC assets to PASE

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#571]
Site and domain need to be transferred. Contacts on the PASE side have been emailed to you @cadecairos

**Comment by cadecairos** [comment]
Update: still emailing back and forth, trying to sort out the details. possible meeting needs to be set up.

**Comment by cadecairos** [comment]
I've instructed The PASE contacts on how to migrate to their new install, waiting on getting information from them to kick it off. I've also sent the hivenyc transfer code to them.

**Comment by cadecairos** [comment]
The transfer is being processed. will close once I can confirm it's done.

**Comment by cadecairos** [comment]
The domain has been transferred, but the name servers continue to point to our Hosted Zone on AWS. I'll email Kay to see what's up.

**Comment by cadecairos** [comment]
This is all done!
