### ISSUE TITLE
Add Carto to CSP whitelist 

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#573]
As discussed on slack, we want to add an embed from https://auremoser.carto.com to a page on foundation.mozilla.org. 

@cadecairos mentioned there are some trackers included in there. we can discuss with @auremoser about whether to use a static image. they have a way to export in the tool, but it would require periodic updates. there's an api to get a static image, but we can't include that on a cms page unless it's possible to just hotlink an image to that. 

let's discuss.

**Comment by auremoser** [comment]
I'm not fluent in hotlinking images to the cms pages, but:

- Static Maps for Carto: https://carto.com/docs/carto-engine/carto-js/static-maps/
- Static Map API for Carto that I mentioned before: https://carto.com/docs/carto-engine/maps-api/static-maps-api/
- A project that might help, it's Kate DeCora's tool, integrates with Carto and other map services: https://staticmapmaker.com/cartodb/

I don't mind doing the periodic updates, if it comes to that, maybe on a once weekly schedule in the lead up to the sprint?

Let me know what works for you both.

**Comment by xmatthewx** [comment]
I tried staticmapmaker, but couldn't get it to work. I wonder if it's for an older version of carto's api. We won't be able to set up our own version of this. So...

We can either:
 - whitelist and accept the trackers
 - or do a weekly image export from carto

I'll leave it to you two to decide.

**Comment by auremoser** [comment]
I have no strong opinions either way. Let me know what you think @cadecairos . Fwiw, we used the same map type in precedent (last year, tracking enabled) and it seemed to work well. 

From what I've gathered, there's no way to turn off the "fav" count feature, which the trackers are assessing.

**Comment by cadecairos** [comment]
I've whitelisted https://auremoser.carto.com as an iframe src. I'm not too concerned about the analytics used withing the iframe at this time.

Can we close close this out?

**Comment by xmatthewx** [comment]
thanks @cadecairos. it works as expected: https://foundation.mofostaging.net/opportunity/map-embed/
