### ISSUE TITLE
Serve Webmaker.org statically

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#576]
We're currently serving webmaker.org and beta.webmaker.org through a heroku app, behind a CloudFront CDN. This is silly. We should make a static  "this is not a thing anymore" page on S3 and serve that instead.

@alanmoo Should we get a designer involved, or just throw up something basic?

**Comment by alanmoo** [comment]
What about the existing projects? Are they on a different domain?

**Comment by cadecairos** [comment]
Are you talking about the app? That data is accessed through api.webmaker.org (which is a whole other beast)

There is a desktop "viewer" on beta.webmaker.org, but TBH, I think we can kill it.

**Comment by alanmoo** [comment]
Ah, yes, the desktop viewer is what I was thinking about.

Kevin and I started working on a decommission plan a year ago, and one of the things we discussed was leaving the viewer up, as it upholds the idea that these projects are 'of the web'.

Of all the stuff we have to decommission though, Webmaker does feel like the lowest hanging fruit. Maybe it's time to revisit this. @jessevondoom thoughts?

**Comment by cadecairos** [comment]
ping @jessevondoom

**Comment by cadecairos** [comment]
@alanmoo how can we get @jessevondoom to respond... 🤔

**Comment by cadecairos** [comment]
> Guessing that should be another ticket though?

Yeah, we'll need to discuss this - it's going to be a challenge.

**Comment by patjouk** [comment]
Let's discuss that during All Hands :)

**Comment by cadecairos** [comment]
closing in favour of #610
