### ISSUE TITLE
Story Engine turn over 

### ISSUE THREAD

**Issue by Sydette** [MozillaFoundation/mofo-devops#578]
Hello All , 

We need to turn over Story Engine to a non Mozilla 

Direct storyengine.io to new story engine website 👍  https://loupdesign.wpengine.com/. 

Export Files : https://drive.google.com/file/d/13VN-IlTzFyywIStbcC6tOn4NZhAx4mgi/view?usp=sharing

The site IP : 35.224.80.37

**Comment by prefontaine** [comment]
@Sydette @jessevondoom Please let me know what you need me to do -- I am not sure what action to take. We have all files set up at https://loupdesign.wpengine.com and now just need (1) the StoryEngine.io URL to point to the new IP address, and (2) to turn over ownership of the domain to Loup.

**Comment by cadecairos** [comment]
@Sydette @prefontaine we don't need to migrate the existing site at all, right?

I can update the domain (storyengine.io) to point to the IP in the top comment (35.224.80.37) today, and file a bug to get a transfer code for storyengine.io. I'll need to know who to send this code to at Loup, so they can complete the domain ownership change with their registrar.

**Comment by prefontaine** [comment]
Hi @cadecairos. You can send the domain transfer code to me at christine@loup.design. The site has been migrated. Did you point to the new IP? Old one still shows up for me.

**Comment by cadecairos** [comment]
@prefontaine I've updated the DNS setting, but the site will be down until storyengine.io is added as a domain using the dashboard for the new WPEngine install. I also recommend you use WPEngine's Lets Encrypt integration to get a free SSL certificate and force SSL on the site. [Here's how to do it](https://wpengine.com/support/add-ssl-site/#letsEncrypt)

**Comment by prefontaine** [comment]
@cadecairos Thanks much. Looks like I need to wait an hour for the systems to update. Then I'll check again if it is working.

**Comment by prefontaine** [comment]
@cadecairos Everything is working great. Thank you for the SSL tip. N00b question: Do I initiate the domain name ownership change from my registrar?

**Comment by cadecairos** [comment]
Glad to hear it's working! 

I'm working on getting a transfer code, and once I have it, I'll forward it over, and you can use it to begin the transfer with your registrar.

**Comment by cadecairos** [comment]
The domain transfer is underway, should take a couple days to process. I'll update when it's done.

**Comment by prefontaine** [comment]
@cadecairos @Sydette @jessevondoom This is officially transferred. Thanks much for all of your help!
