### ISSUE TITLE
clean up heroku wagtail apps

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#582]
We've merged wagtail into the main foundation.moz repo, so we should see which heroku apps we currently have around wagtail testing and clean that list up.

**Comment by cadecairos** [comment]
- [ ] Route 53 CNAME (wagtail.mofostaging.net)
- [ ] foundation-wagtail Heroku app
- [ ] Heroku Postgres
- [ ] IAM user (wagtail-s3-bucket)
- [ ] S3 uploads (mofo-assets-staging/wagtail/*)

**Comment by patjouk** [comment]
done 🚀
