### ISSUE TITLE
Redirect hivelearningnetworks.org to Foundation site

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/mofo-devops#586]
### Details
The hivelearningnetworks.org is outdated and no longer relevant. We should redirect to the Foundation site Get Involved page. 

I don't suspect that site gets much traffic and don't think the Foundation site links to it anymore. 

### Info & links
http://hivelearningnetworks.org
https://foundation.mozilla.org/get-involved/

**Comment by cadecairos** [comment]
I've added the following domains to the redirect app:

- www.hivelearningnetworks.org
- www.hivelearningnetwork.org
- hivelearningnetworks.org
- hivelearningnetwork.org

they're configured to redirect to `/get-involved`

I still need to update the domains to point to the redirect app, and make a final backup of the site before deleting the WPEngine install.

**Comment by cadecairos** [comment]
Domains updated, They're all redirecting properly now.
