### ISSUE TITLE
Set up a whitelist for foundation.mozilla.org for which changes should not trigger CI

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#587]
Not every change in foundation.mozilla.org will impact build status (for instance, changes to the README.md), but will still trigger CI runs despite the result of these runs being a foregone conclusion. It turns out we can create exemption patterns to prevent CI from kicking in, so it's worth looking at which (sets of) file(s) we can exempt to prevent CI from kicking in when it doesn't have to.

Files/sets I would suggest for whitelisting:

- `**/*.md` for obvious reasons =)
- .LICENSE`
- `env.default` (probably?)
- `network-api/**/*.html` (to be removed if we eventually figure out how to lint and/or test templates)
- `network-api/media/**`

**Comment by cadecairos** [comment]
Travis now lets us skip ci using a commit message: https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by cadecairos** [comment]
Lets document that we can skip ci for certain changes.

**Comment by Pomax** [comment]
that's fantastic (if a glass half full, glass half empty kind of situation due to Travis itself of course =D). I wonder if we can get github to add a function that automatically adds the comment "rebased from ui" or something when you click the rebase button, so we can ignore that situation too

**Comment by patjouk** [comment]
Info on skip CI merged in foundation.mozilla.org doc. It won't be possible to not run CI at all on a PR: Github expect an answer from Travis, and if Travis doesn't say anything, it just hangs forever. I'm closing this PR as won't fix :(
