### ISSUE TITLE
Gather github activity data during the global sprint

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#588]
Related to mozilla/network-pulse-api#312

I started looking at github api: they provide a few [statistic](https://developer.github.com/v3/repos/statistics/) entry points, but it's limited and doesn't cover our needs. I think we should use the [repo](https://developer.github.com/v3/repos/) entry points instead, especially the commits ones.

I also found something that could be useful: you can obtain a [community profile](https://developer.github.com/v3/repos/community/) per repo that will tell you if they have a Code of Conduct, a readme, a PR template, etc.

What's our next steps?

- We could talk directly to the API or use a python library to do it([Github3.py](https://github3.readthedocs.io)). They provide a few exemple here: https://github.com/sigmavirus24/github3.py/tree/develop/example-notebooks

- Where should the code live? Do we open a new repo?

**Comment by alanmoo** [comment]
Looping in @acabunoc as she had something she was using previously and can give clear needs about what events need to be captured. I recall the biggest concern is that the github API only exposes 200 or so recent events in the category we want, so we'll need to have a way to capture them longer term for reference later on.

**Comment by acabunoc** [comment]
Hi all, I used the activity endpoint for all the repos in the sprint:
https://developer.github.com/v3/activity/

We're still accepting projects, but I can get you a current list of repos.

I can dig up the script I used last year if that would be helpful. I only ran it once a day during the sprint then manually assembled the data for the 50 hours. We need data from a longer timeframe this year (2 weeks before, 6 weeks after),

**Comment by acabunoc** [comment]
used this endpoint specifically:
https://developer.github.com/v3/activity/events/#list-repository-events

**Comment by patjouk** [comment]
Tasks and todos:
- [ ] collect events for a list of repos,
- [ ] write to a G spreadsheet,
- [ ] run at a certain interval.

**Comment by acabunoc** [comment]
Here is the current list of repos: (2nd tab in the spreadsheet)
https://docs.google.com/spreadsheets/d/1mnxJUe9Fhbh3JC_CDSjnsnq5xBB7ZLU_ITq0BTxt0IE/edit#gid=922604362

This will continue to be updated as projects register till the end of the sprint.
Thanks @patjouk & @cadecairos!

**Comment by patjouk** [comment]
Closing this issue: PR related to it was merged 🎉
