### ISSUE TITLE
Error handling and alerting for Github Activity monitor script

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#590]
Lets monitor for errors fetching and processing data. ideally it will trigger a VictorOps alert.

**Comment by patjouk** [comment]
What I identified so far:
- Paging should occur only if repeated failures: One way to do this is to monitor if the file was updated in the last hour+ (probably a cloudwatch alert going to victorops)
- Automatic response: uploads/downloads to s3 have 5 auto retries before raising an exception. We should add retries to Github API requests.
- If the same repo is failing again and again but the rest works, it means we should investigate that repo. No need to page for that, but a warning on slack would be nice.
- Backups! Everyone loves backup! I activated bucket versioning.
