### ISSUE TITLE
Update Hatchet settings/configs for MozFest 2018

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#591]
@cadecairos for ref, this is the ticket from last year: https://github.com/MozillaFoundation/mofo-devops/issues/501 

Call for Proposals opens on June 1 this year as well. I would like to make sure Hatchet for MozFest site is still working.

**Comment by mmmavis** [comment]
Also - is this still [the place](https://github.com/mozilla/webmaker-mailroom/tree/master/templates) where I put email templates in?

**Comment by cadecairos** [comment]
I think we'll also need a worker task to process the new email template (basically, [we fork this worker](https://github.com/mozilla/sawmill/blob/master/worker/mozfest_session_proposal_2017.js))
> Also - is this still the place where I put email templates in?

yup, that's the spot!

**Comment by mmmavis** [comment]
Hey @patjouk , we are still waiting for copy and content. I will ping people again so hopefully we can get content locked by this week. I should be able to file a PR just like [what I did last year](https://github.com/mozilla/webmaker-mailroom/pull/59/files). Will you be the person I should flag for PR review then? 😉

**Comment by mmmavis** [comment]
@patjouk I just filed a [PR](https://github.com/mozilla/webmaker-mailroom/pull/67) and assigned you as reviewer 😃

**Comment by mmmavis** [comment]
@cadecairos seems like my PR for `webmaker-mailroom` has been merged. I'm currently working on MozFest site call for proposals updates on a feature branch. I'm wondering if we need to add the review app URL to Hatchet config in order for us to test the confirmation email feature there.

Review app for that feature branch: https://mozillafestival-org-sta-pr-894.herokuapp.com

**Comment by mmmavis** [comment]
@patjouk @cadecairos do you mind pinging me when this is ready for testing? 😄 We are aiming to push website updates live on May 31 since June 1 is a Friday.

**Comment by mmmavis** [comment]
Yay just tested this via MozFest site and it worked great. Thanks @cadecairos @patjouk for the help! 🎉
