### ISSUE TITLE
Merging Lumberyard into Sawmill

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#595]
![20180530_093003](https://user-images.githubusercontent.com/481052/40724527-87caf976-6421-11e8-8e7c-c5864838d79a.jpg)

Having Lumberyard is the middle makes the whole SQS messages processing complex to understand. We should revisit this and merge Lumberyard into Sawmill.

Todos:
- [x] Move Lumberyard workers into sawmill (https://github.com/mozilla/sawmill/pull/90)
- [x] IAM user sawmill: add amazon SES policy to it (look at Lumberyard IAM config)
- [x] IAM user sawmill: Add SendMessage permissions for the sawmill queue
- [x] Add QUEUE_URL environment variables
- [x] Push to Prod
- [x] Remove INCOMING/OUTGOING env vars
- [x] Make sure that Lumberyard queue is empty before removing it
- [x] Remove SQS config connected to Lumberyard
- [x] Delete lumberyard Heroku apps

**Comment by cadecairos** [comment]
RIP lumberyard.

The project has been archived too.
