### ISSUE TITLE
Change how we do review apps passwords

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#598]
Each time a review app is created, we automatically generate an admin account: the username stays the same but the password is randomly created and printed in the review apps logs. This is not user-friendly, so we need another solution.

What we could do instead:
- Replace the random password by a fixed one [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/management/commands/review_app_admin.py#L27) and [here](https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/utility/management/commands/review_app_admin.py#L15). It's an easy fix but it's a security issue.
- Post the password on a private slack channel: `Review app 'NAME' was created. Admin password: 'PASSWORD' + 'URL'`.

I would prefer the second solution. Opinions @cadecairos @alanmoo?

**Comment by alanmoo** [comment]
I prefer the second as well

**Comment by patjouk** [comment]
done!
