### ISSUE TITLE
Align pulse staging URLs with foundation site

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#599]
The foundation site has nice patterns for staging and admin. Clean and easy to remember. Pulse is a bit messier. Can we clean these up? Even redirects would be fine. 

Current URL <-- proposed URL or redirects:
 - http://mozillapulse.org/
 - https://api.mozillapulse.org/admin/ <-- mozillapulse.org/admin
 - https://network-pulse-staging.herokuapp.com/ <-- pulse.mofostaging.net
 - https://pulse-api.mofostaging.net/admin/ <-- pulse.mofostaging.net/admin

cc @gideonthomas @alanmoo for opinions on new URLs

**Comment by cadecairos** [comment]
> https://api.mozillapulse.org/admin/ <-- mozillapulse.org/admin

We're running the pulse front end on a separate domain than the back end. The setup to proxy the Django admin interface to the front end domain really isn't worth all the work

Or, is it okay to just have `https://mozillapulse.org/admin` redirect to the backend domain?

**Comment by cadecairos** [comment]
Here's what we need to do:

1. Create pulse.mofostaging.net, wire it up properly to pulse staging front end. Verify that OAuth Works (check allowed hosts on staging api)
2. Redirect `mozillapulse.org/admin` to `api.mozillapulse.org/admin` (same behaviour for staging, but for staging infrastructure)
3. Try to enforce the custom domain on front-end (i.e. force redirect away from heroku domain to the custom domain (pulse.mofostaging.net for staging and www.mozillapulse.org for prod )

**Comment by patjouk** [comment]
@xmatthewx pulse.mofostaging.net is up and running but someone else should probably write those redirect routes: I tried but knowing nothing of React, I failed miserably.

**Comment by alanmoo** [comment]
@mmmavis can you help out with the React routes when you have a chance?

**Comment by mmmavis** [comment]
> Enforce the custom domain on front-end (i.e. force redirect away from heroku domain to the custom domain (pulse.mofostaging.net for staging and www.mozillapulse.org for prod ))

@cadecairos I'm not entirely sure what I need to do on front end. Did you mean redirect `/admin` to `pulse.mofostaging.net/admin` (for staging for example)`?

**Comment by cadecairos** [comment]
@mmmavis yes, on the frontend site, we'd like to have `/admin` redirect to the backend admin interface, on staging and on production.

**Comment by cadecairos** [comment]
I'll take of the rest of this issue

**Comment by mmmavis** [comment]
@cadecairos thanks! Sorry this ticket slipped through the cracks on my end.

**Comment by cadecairos** [comment]
All the codes have been written, I'm going to verify they're deployed and functioning before I close this issue.
