### ISSUE TITLE
Buildout of Screenshot Tool

### ISSUE THREAD

**Issue by jdotpz** [MozillaFoundation/mofo-devops#6]
Buildout for Atul's screenshot service.
https://github.com/MozillaFoundation/plan/issues/76#issuecomment-70561351
@toolness @wex: what url will we want for this?  I can get the SSL moving.
- [x]  create ec2 security group, allow elb sg on port 80(see other apps for examples)
- [x]  create keypair, share on lastpass
- [x]  app iam creds, share on lastpass
- [x]  build scripts written
- [x]  Cloud init scripts written for 64bit
- [x]  create staging elb
- [x]  create staging launch config
- [x]  create staging autoscale group
- [x]  update fab file with new autoscale group staging
- [x]  create RDS security group, allow access for app ec2 security group
- [x]  create staging db root creds, share on lastpass
- [x]  create staging db app creds, share on lastpass
- [x]  create staging db
- [x]  create staging cache servers
- [x]  create DNS entry for staging db
- [x]  create DNS entry for staging cache
- [x]  create DNS entry for elb endpoint
- [x]  create S3 folder for s3://mofo-techops/deployment/apps/staging/appname
- [x]  create S3 folder for s3://mofo-techops/deployment/apps/production/appname
- [x]  grant respective app AWS keys access to  s3://mofo-techops/deployment/apps/staging/appname and s3://mofo-techops/deployment/apps/production/appname
- [x]  Add iam user to s3-creds-staging (or production) iam group
- [x]  Add app-env specific user policy to each user, look at other app-appname-env user policies for a template
- [x]  Upload an allowed ssh file to each envs creds folder, created above.
- [x]  Create configs for app/env, upload to S3 creds env buckets created above
- [x]  update fab file with new autoscale group staging
- [x]  update fab file on builder under /home/ubuntu/.aws/fabfile.py
- [x]  puppet modules written
- [x]  as-update-auto-scaling-group --min-size 1 --max-size 1 --desired-capacity 1
- [x]  create first github tagged version of app
- [x]  Create staging jenkins job
- [x]  Test Jenkins staging job
- [x]  Create staging status jenkins job
- [x]  test!
- [x]  create prod elb
- [x]  create prod launch config
- [x]  create prod autoscale group, multi-AZ
- [x]  create prod db
- [x]  create prod cache servers
- [x]  create DNS entry for prod db
- [x]  create DNS entry for prod cache
- [x]  create DNS entry for prod elb
- [x]  create monitoring for prod db
- [x]  create monitoring for prod caches
- [ ]  create monitoring for elb nodes
- [ ]  create monitoring for main endpoint
- [x]  create PRODPUSH Jenkins job
- [ ]  create PRODBACKOUT Jenkins job
- [ ]  create loggins stream for new app
- [ ]  create custom DETAIL-appname dashboard in newrelic
- [ ]  setup contextual loggins links, newrelic links, monitoring links in Jenkins
- [ ]  Update canonical list of urls/sites/info.

**Comment by toolness** [comment]
Ultra cool, thanks JP!

> @toolness @wex: what url will we want for this? I can get the SSL moving.

I have no idea, but the good thing is that it doesn't particularly need to be user-friendly since end-users will never see the URL. Maybe screenshots.webmaker.org or something?

**Comment by jdotpz** [comment]
We could do wmscreenshot.mofoprod.net and skip the SSL mumbojumbo.

I'll be working with @flamingspaz tomorrow afternoon to step through the remaining items to get staging and prod all setup and ready!

**Comment by toolness** [comment]
Oh heck yeah, just use mofoprod.net man! Whatever's easiest :)

**Comment by jdotpz** [comment]
+1!

**Comment by jdotpz** [comment]
Alrighty, wmscreenshot.mofoprod.net is all ready for you @toolness !
