### ISSUE TITLE
Network Mapping Project - Tranfer Github repo from Calibro to Mozilla

### ISSUE THREAD

**Issue by arlissc** [MozillaFoundation/mofo-devops#603]
### Details

This issue relates to the "Mapping the Movement" project w/ Calibro (part of the 3yr strategy evaluation project, run by the Insights team).  This project will end on June 30.  Currently all deliverables for this project are under the ownership of Calibro who has been contracted to complete this work.
We would like to transfer the ownership of the Github repo containing all of the interactive visuals for this project to an appropriate Github repo within Mozilla or Mozilla Foundation organization on Github.
If possible, **we would like this to be completed by 12pm ET Friday June 29**.

### Info & links

Here is the link for the location of the visuals currently.
https://uf0.github.io/mozilla-network/

Once the repo has been transferred to Mozilla we would need the updated new master link and all the additional links so they can be added to the final report prior to submission to the board.

Thank you for your help with this.
If there is any other information needed pls reach out to arliss@mozillafoundation.org

Best, Arliss

**Comment by cadecairos** [comment]
The transfer is basically instant, but because the repo is private I can't tell if they used absolute or relative links to build the site. If it's coded with relative links, then it will just work, with absolute links, it will require a little bit of manual work.

**Comment by cadecairos** [comment]
Transferred: https://github.com/mozilla/mozilla-network

gh-pages: https://mozilla.github.io/mozilla-network/
