### ISSUE TITLE
Snyk CI builds on foundation fail

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#605]
[Example:](https://travis-ci.org/mozilla/foundation.mozilla.org/builds/399372745?utm_source=github_status&utm_medium=notification)
```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's snyk@1.78.1 does not satisfy snyk@^1.88.0
```

Let's investigate and fix it!

**Comment by patjouk** [comment]
They don't support `package-lock.json` updates yet. What we could do:
- Push a commit with an updated lock file every time snyk bot opens a PR,
- Remove the PR fix feature and integrate the new `npm audit` in our process. 

Opinions @cadecairos ?

**Comment by cadecairos** [comment]
> Remove the PR fix feature and integrate the new npm audit in our process

I think this is our best option for the long term. snyk is nice and all, but now conflicts with npm's built in tooling a bit.

**Comment by patjouk** [comment]
See if we can use `npm audit` on travis: it should fail only for critical issues.

**Comment by patjouk** [comment]
I removed the PR feature. Looking at the setting, I saw that we can activate the `Only fail Snyk Test for high severity vulnerabilities` option. Maybe we could do that (I'll contact you on Slack with more details)
