### ISSUE TITLE
Change Taís' access to Google Analytics

### ISSUE THREAD

**Issue by taisdesouzalessa** [MozillaFoundation/mofo-devops#608]
Summary of the issue: I added an annotation in GA and the only option available to me is to keep it private.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/22157921/42475216-d61d138a-837e-11e8-8c8a-b9687cdf14b3.png">

I would like to be able to make the annotations public since the context is important for all team members who see analytics.

For the little I read about it, it seems I need ‘Collaborate’ access to Google Analytics to be able to share annotations. Would it possible to give me permission for that?

**Comment by cadecairos** [comment]
@taisdesouzalessa is this for `foundation.mozilla.org`?

**Comment by taisdesouzalessa** [comment]
yep! If not possible, I could send the notes to somebody who has the access to make it shared as well.

**Comment by cadecairos** [comment]
It's done - the foundation site is one that I have edit user permissions on.

**Comment by taisdesouzalessa** [comment]
Thanks, Cade!
