### ISSUE TITLE
Redirect webmaker.org homepage

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#610]
Redirect webmaker.org (but not the other pages hosted on that site, like projects) to https://foundation.mozilla.org/artifacts/webmaker/

**Comment by cadecairos** [comment]
This is going to be troublesome: https://github.com/mozilla/webmaker-browser

node 0.12. React 0.14. npm 2.6.

**Comment by alanmoo** [comment]
Can we pull it off at a DNS level somehow?

**Comment by cadecairos** [comment]
I might be able to redirect it using CloudFront behaviours

**Comment by cadecairos** [comment]
- Can't do CloudFront Redirect, Webmaker project view lives as a SPA on the root of the site.
- Will take 3 or more days to update dependencies and fix bugs on the webmaker-browser app

Waiting on @alanmoo and @jessevondoom to advise if we should invest time here or just take it down.

**Comment by cadecairos** [comment]
Closing, until we have a complete shutdown plan
