### ISSUE TITLE
Embed AirTable view into IHR

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#616]
from @kaodro 

>The form is [embeddable as iframe into wordpress](
>https://support.airtable.com/hc/en-us/articles/217846478-Embedding-a-view-or-base) via an iframe and I tried it out but it didn't quite work (the preview didn't show the form). It would be great if somebody from your team could have a look at why it doesn't work and advice me how to fix it. I can give access to wordpress to whoever you tell me I should.
>
>Embedding the standard iframe version is our minimal version we can go with but ideally, we would do something more customized and nicer like these guys ([gallery view via API](
https://glitch.com/~airtable-example)).
>
>It would require playing with the [Airtable API](https://airtable.com/api). I would love advice from your team on whenever we can do something that looks better (e.g. shows more boxes) and if that is doable on your side.
>
>Let me know if you need any more info.
>
>Launch date is August 21.

**Comment by cadecairos** [comment]
This probably didn't show up because of the Content Security Policy. you'll need to whitelist the domain that airtable is trying to embed in an iframe in order for it to display on the site.

I'll take a look at the documentation on embedding airtable content to figure out what domains to allow.

**Comment by cadecairos** [comment]
@alanmoo @kaodro I've whitelisted `https://airtable.com` in the child-src directive of our Content Security Policy for the `/2018` site. You should be able to load it in an `iframe` element now.

**Comment by alanmoo** [comment]
Hard to say- what does it look like now? I understand ideal would be closer to [this](https://glitch.com/%7Eairtable-example) but I'm not sure where we're trying to get there from.

**Comment by cadecairos** [comment]
I'm going to close this, if there's any issues with Airtable going forward, lets create a new one!
