### ISSUE TITLE
Heroku maintance on August 22nd

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#617]
Scheduled:  (US) Dyno manager maintenance on Wednesday, August 22 at 22:00 UTC (18:00 EDT).

On Wednesday, August 22, 2018, starting at 22:00 UTC (18:00 EDT), and continuing until 02:00 UTC (4 hours), Heroku will be performing maintenance to the dyno manager in the US Common Runtime.

During this time, the following services will be impacted:

* Dyno scaling and provisioning (including restarts), configuration variable changes, Heroku Scheduler and one-off dynos, and container registry deployments will be unavailable. Autoscaling will not take place during the maintenance.
* Heroku CI test runs will result in an error.
* Build services for applications in the US Common Runtime will be suspended, including Review Apps.
* Free applications on the US Common Runtime will be unable to wake from sleep during the maintenance.

You may see errors if attempting to use these services from the CLI, Dashboard, or API.

Running paid applications will continue to receive traffic during this maintenance. We advise customers who rely on autoscaling to set a safe minimum number of dynos to handle traffic prior to this maintenance.

We will provide an update when we begin and complete the maintenance.

The most recent information is available at: https://status.heroku.com/incidents/1608

---

Let's scale Foundation, donate and maybe pulse and thimble apps.

**Comment by cadecairos** [comment]
- [ ] let staff in #editorialcalendar (and maybe others) know about this
- [ ] See if we can schedule apps to scale up in advance of this date+time
- [ ] Tell engineers about this in #mofo-production

**Comment by patjouk** [comment]
I added a bunch of reminders on #mo-prod and #mofo-engineering (one on the 20th and the other one on Wednesday 22nd). I also announced that maintenance yesterday at the digital team meeting.

**Comment by patjouk** [comment]
HireFire scheduling override is really badly designed. I'm beta testing something tonight but I'm pretty sure I will have to do it manually because the maintenance is happening during the night and HireFire seems really confused by that idea...

**Comment by patjouk** [comment]
Tests worked \o/ I've scheduled automatic overrides for all services on HireFire.

**Comment by patjouk** [comment]
Manual override removed. Everything went well.

For future reference: for scheduling something overnight on UTC:
- one override from X to 23:59 on day 1,
- another override from 00:00 to X on day 2.
