### ISSUE TITLE
Cloudwatch alerts for publish database disk usage

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#619]
Lets notify ourselves if publish DB freespace drops below 100 GB

**Comment by patjouk** [comment]
Fun stuff: I actually set an alert at the end of July: `FreeStorageSpace <= 419,430,400,000 for 5 datapoints within 25 minutes`.
I'll modify it but to 300G: it will give us more time to act before we actually run out of space.

**Comment by cadecairos** [comment]
This is done!
