### ISSUE TITLE
Create backups for Mozfest schedule data

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#620]
We need two automatic backups:

~Google spreadsheets~ Can't do it because of Google Oauth \o/ It's not possible to run a cron task on user data, at least for spreadsheets.
 
Guidebook:
- [x] Get an API token,
- [x] Write a scheduled task to do the actual backups (+alerts)
- [x] Doc it!
- [x] Write decommission todo list issue

links:
- [Guidebook api](https://developer.guidebook.com)
- [Google spreadsheet api](https://developers.google.com/sheets/api/quickstart/python)

@mmmavis I'll contact you on Slack to get the URL of those two spreadsheets + guidebok API token :)

**Comment by mmmavis** [comment]
Oops! Missed your ping earlier in the ticket. No worries at all. Thanks! 😃
