### ISSUE TITLE
Take down and redirect iheartopendata.org

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#622]
We've got a replacement page up on https://foundation.mozilla.org/campaigns/i-heart-open-data/, let's take down the site currently hosted at iheartopendata.org and permanent redirect the url.

(Super low priority)

**Comment by cadecairos** [comment]
Redirect in place! I've disabled the apps in the iheartopendata-org pipeline. They'll get deleted in the next Heroku app purge we do.
