### ISSUE TITLE
DISCUSSION - Can MozFest website handle tons of traffic

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#623]
Based on https://github.com/mozilla/mozillafestival.org/issues/1029#issuecomment-422904824, we are going to embed live streams to the mozfest events like Dialogues and Debates, etc. Will the Mozfest site be able to handle the traffic coming to it because of this form of engagement? Is there anything we need to do to make sure it can handle the load?

**Comment by cadecairos** [comment]
The site should easily be able to handle that traffic. Everything's going through cloudfront so static assets are being cached. The stream won't have any affect on the availability of the site. As a precaution, we can add autoscaling, but I'm not convinced that is necessary, especially with CloudFront helping out.

**Comment by gideonthomas** [comment]
@mmmavis does that make sense? Can we close this?

**Comment by cadecairos** [comment]
There is room for optimization on the client side still, since I can see we're not telling the browser to cache resources at all:

![screenshot from 2018-09-19 15-39-33](https://user-images.githubusercontent.com/438003/45776879-422dae00-bc22-11e8-8777-782880b9360c.png)

**Comment by cadecairos** [comment]
ouch, ~1000KB of JavaScript with a max-age of 0.

![screenshot from 2018-09-19 15-42-42](https://user-images.githubusercontent.com/438003/45777038-ae101680-bc22-11e8-8fca-b966bc4ba29d.png)

**Comment by gideonthomas** [comment]
We can probably improve cache nearer the festival since content won't change then.

**Comment by cadecairos** [comment]
@gideonthomas A quick and easy solution would be to set cache-control headers on static content so that user's browsers load from cache instead of over the network.

**Comment by cadecairos** [comment]
Answer: yes!
