### ISSUE TITLE
Take down https://fbsurvey.mozillafoundation.org and redirect to repo

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#626]
I got the 👍 from @caltrider to archive the project.

Let's take down the project (https://fbsurvey.mozillafoundation.org) and redirect the URL to the repo- https://github.com/mozilla/shinysurvey/

**Comment by cadecairos** [comment]
1. Create a PR in mofo-redirector for this domain (details in top comment)
2. merge + deploy redirect
3. detatch the domain from current heroku app, attach it to mofo-redirector
4. in Route53 update the Hosted Zone record for fbsurvey to point to the redirector heroku app.

**Comment by patjouk** [comment]
It's done. I had to disable fbsurvey DCN (cloudfront, mofo-project) too.
I turn the fbsurvey Heroku app down and put it in maintenance mode. We can remove it in a few days.
