### ISSUE TITLE
Timeout on password protected wagtail page

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#629]
A funder for CS Challenge reported that they experienced repeated timeouts on a page. It seems like an isolated incident, but maybe worth a quick check. If there is a problem, I think it's more likely wagtail's password feature than the page itself. 

 - On Mac using Chrome and Firefox 
 - Page is published but password protected
 - https://foundation.mozilla.org/en/initiatives/responsible-cs/judges/

Reported via @jenntbeard

**Comment by cadecairos** [comment]
This sounds like a localized connection issue, not a problem with the server, but we'll check the logs for any request timeouts for that page.

**Comment by cadecairos** [comment]
I did look into this and detected nothing out of the ordinary. If it happens again / consistently, lets look closer.
