### ISSUE TITLE
Redirect app.mozillafestival.org

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#630]
Can we redirect app.mozillafestival.org to https://guidebook.com/guide/147793/?

A bunch of people are still using that link and are being taken to the old site.

Hoping this can be done soon.

**Comment by alanmoo** [comment]
This isn’t the url we burned with a 301 right? 😅

**Comment by gideonthomas** [comment]
the original url? Not sure.

**Comment by cadecairos** [comment]
This is done and live: (https://github.com/mozilla/mofo-redirector/commit/cf4851a683ef62219b737484b2873ad6e0c367f4)
