### ISSUE TITLE
VictorOps account migration

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#632]
Things to do:

## For the new VictorOps account:
- [x] Invite Alan, Gideon,
- [x] Set up rotations,
- [x] Set up routing keys,
- [x] Do we still need transmogrifiers?

## For the old VictorOps account:
- [x] Remove our integration,
- [x] Remove our rotations,
- [x] Remove our routing keys,
- [x] Remove our transfmogrifier,
- [x] ~~Delete our accounts.~~ we'll keep them, just in case

## Integrations (remove and setup):
- [x] **Slack:** need the approval from slack admins. [Slack app link](https://mozilla.slack.com/apps/A1K9VAUA1-victorops) and [VictorOps docs](https://help.victorops.com/knowledge-base/victorops-slack2-integration/),
- [x] **Logentries**,
- [x] **Healthcheck**,
- [x] **Pingdom**,
- [x] **Heroku**,
- [x] **Email** (check custom integrations in code too)
- [x] **REST** (check custom integrations in code too)

Let's think of all services we run: are some connected to victorops (AWS, Heroku)?
@cadecairos  I'm probably missing some stuff, feel free to edit that issue.

**Comment by cade** [comment]
I think we're replacing the transmogrifiers with the cerebral enhance-o-tron, right @cadecairos?

**Comment by patjouk** [comment]
Oopsie, sorry >.<

**Comment by patjouk** [comment]
Blocked until we resolve our issue with their billing service >.<

**Comment by patjouk** [comment]
Everything is migrated: I've checked all the alerts we had on VictorOps to be sure I didn't forget anything. We had a Cloudwatch integration for donate: I'm pretty sure it's a duplicate of a Heroku alert but I don't have to check right now.

**What still needs to happen:**
- Add annotation with transmogrifier: It's out of scope of this ticket but a nice to have,
- Create a new rotation for all hands or override the current one,
- Check with folks on-call during nights and weekends if they're happy with the rotations I created or if they need to be modified (at all hands),
- Delete all our stuff in the old account.

**Comment by patjouk** [comment]
The only thing left to do is remove our old account: @cadecairos can you take a look when you have time?

I've added a few transmogrifiers with those annotations:
- One for each playbook we have in devops-private,
- One for all pingdom alerts with a link to pingdom dashboard. Same with healthcheck. We don't need one for Heroku since we're only alerting from there for the foundation site. I didn't add one for logentries but will do it for scalyr (they have an integration).
