### ISSUE TITLE
Pre-Commit git hook that runs flake

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#634]
Lets stop failing CI because of forgotten flake issues!

**Comment by patjouk** [comment]
After reading more on git hook, I found that flake8 already [provides one](http://flake8.pycqa.org/en/latest/user/using-hooks.html#built-in-hook-integration). To activate it: `flake8 --install-hook git`. They recommend to not use it and to use the [pre-commit Framework](https://pre-commit.com/) instead, which feels a bit overkill.

Either way, I think we should tell the others that this exists, but let them make their own choice: I want them to be responsible if something breaks, which won't be the case if we force it on them.

What do you think?
