### ISSUE TITLE
Images optimization

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#636]
I'm opening a new issue to centralize discussions around how we could optimize image processing and delivery.

Right now, we're using Cloudinary for the BuyersGuide. The main issue is that it's costing us a lot of money to use their service: not for the transformation part (we're under 5% of plan usage), but for the bandwidth part (we're on the Advanced Plan, costing 250$ per month and we already used 40% of the plan bandwidth).
We need to fix that issue before extending this solution to pulse or the rest of the foundation site.

What our next steps could be:
- investigate how to reduce cloudinary bandwidth usage. I can't get past the feeling I've missed something there,
- Switch to a service like [kraken.io](https://kraken.io/docs/getting-started) that will do the image transformation and upload them to S3,
- Investigate django libs ([sorl-thumbnail](https://github.com/jazzband/sorl-thumbnail), [django-imagekit](https://github.com/matthewwithanm/django-imagekit), [django-image-cropping](https://github.com/jonasundderwolf/django-image-cropping)) and [wagtail](https://docs.wagtail.io/en/latest/topics/images.html#) to do all the work ourselves (it's definitely worth looking into Celery/RabbitMQ or Django channels if we go for that).

I'll continue to experiment on the BuyersGuide: it will be easier to compare implementations and results that way.

Since we're not in the pre-launch rush of the BuyersGuide, I'll take some time first to read blog posts and investigate how other people are handling this issue. I'll also check cloudinary to see if I could improve our current setting.

CC @gideonthomas @alanmoo @xmatthewx @cadecairos

**Comment by cadecairos** [comment]
We're going to close this out, as most of the work here can be handled by the dev team. If any additional tasks require Ops (third party services, new workers/queue for parallelization) let us know.

**Comment by alanmoo** [comment]
Sorry, what work are you referring to?

**Comment by cadecairos** [comment]
We're referring to this issue: https://github.com/mozilla/network-pulse-api/issues/458
