### ISSUE TITLE
Give Chris credentials to AWS

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#64]
@cadecairos should get some credentials for AWS

**Comment by cadecairos** [comment]
for which account? I thought I had some already

**Comment by jbuck** [comment]
For mofo-ops, which is our new parent account that can login to any of our accounts (mofo, mofosecure, mofo-advocacy, mofo-*)

**Comment by cadecairos** [comment]
Ah, okay, I don't have those.

**Comment by jbuck** [comment]
Done!
