### ISSUE TITLE
Migrate our incoming webhooks to slack apps

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#645]
Simple webhook are a legacy feature. They're easy to setup but suffer a big drawback: you can't have multiple persons managing them. Moving our current webhooks to slack apps will offer us this opportunity, while adding a few interesting features like interactive messages, etc.

Disabled webhooks probably don't need to be migrated, but let's check them to be sure.

@cadecairos apps:
- [x] Posts to #mofo-devops as Logentries
- [x] Posts to #mofo-devops as incoming-webhook 
- [x] Posts to #mofo-network-pulse as incoming-webhook — (disabled)
- [x] A private integration (feb 22): Coral Talk integration for the comments on the 2018 IHR
- [x] A private integration — (disabled) 

@patjouk apps:
- [x] Posts to patjouktest as logentries (test webhook, can be removed)
- [x] Posts to mofo-review-apps as Review app bot
- [x] Posts to mofo-devops-victorops as victorops-alerts (Linked to our previous victorops account: we probably don't need it anymore and can archive that channel @cadecairos )
- [x] Posts to #mofo-engineering as Heroku Pipelines Status

**Comment by patjouk** [comment]
Let's review those webhooks after our 1:1 today @cadecairos. Meanwhile, I've already created a few apps and invited you to them.

**Comment by patjouk** [comment]
Note from the meeting:
To remove: all the disabled webhook + everything related to old victorops stuff.

IHR talk bot: might be difficult to port.

**Comment by cadecairos** [comment]
Lets make sure we get this done before I go on leave this June

**Comment by patjouk** [comment]
@cadecairos do you know what `Posts to #mofo-devops as incoming-webhook` that you own is?

**Comment by patjouk** [comment]
I submitted a request for those 3 apps:
- review app bot,
- pipeline bot,
- logentries alerts.

**Comment by patjouk** [comment]
I've migrated all webhooks that needed to migrated. All the previous webhook can be deleted @cadecairos
