### ISSUE TITLE
Upgrade Django and Wagtail on foundation site

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#648]
Lets upgrade Wagtail to v2.4.x and Django to 2.x.

**Comment by Pomax** [comment]
This might be a bit of a problem because according to https://github.com/torchbox/wagtail-experiments the experiments app is compatible with wagtail 1.7-2.3, with no mention of 2.4

**Comment by cadecairos** [comment]
Blocked on https://github.com/cfpb/wagtail-inventory/pull/18

**Comment by cadecairos** [comment]
This is blocked because wagtail-inventory explicitly forbids wagtail >=2.1, so upgrading to 2.4 in our pipfile causes locking to fail.

**Comment by Pomax** [comment]
Unblocked! The PR for wagtail-inventory landed, making it compatible with Django <2.2 and Wagtail <2.5

**Comment by cadecairos** [comment]
hooray, I'll start testing compatibility even more tomorrow.

**Comment by cadecairos** [comment]
blocked by: https://github.com/infoportugal/wagtail-modeltranslation/issues/191#issuecomment-454439675

(wagtail-modeltranslation does not work with Django 2.x)

**Comment by cadecairos** [comment]
this is no longer blocked

**Comment by cadecairos** [comment]
jumped the gun there. `django-modeltranslation` was released. still waiting on `wagtail-modeltranslation`

**Comment by Pomax** [comment]
There is a v10b for wagtail-modeltranslation that is supposedly "stable, but not marked as release because it's only one person working on it" as far as I can tell. We could switch up to that version if that unblocks the uplift.

**Comment by patjouk** [comment]
They released the 0.10 a few hours ago. Removing the blocked label :)

**Comment by Pomax** [comment]
\o/

**Comment by cadecairos** [comment]
wagtail-modeltranslation 0.10.1 has been released. will attempt to do this upgrade for the tenth time

**Comment by Pomax** [comment]
You know what they say, 10th time is the charm

**Comment by cadecairos** [comment]
Blocked: https://github.com/infoportugal/wagtail-modeltranslation/issues/241

**Comment by cadecairos** [comment]
This work has finally concluded. Thanks for the help @Pomax!

**Comment by Pomax** [comment]
and you!
