### ISSUE TITLE
Figure out how many more AWS accounts we need

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#65]
Talk to Pamela to see what AWS accounts we should add such that we can easily use restricted funding for programs.

**Comment by jbuck** [comment]
Current:
* mofo-ops (master account, payee for consolidated billing)
* mofo-advocacy
* mofosecure (shared for apps using PII)
* mofo (deprecated account, shared for apps)
* mozilla-labs (deprecated account, not in consolidated billing)

Proposed:
* mofo-badges
* mofo-hive/learning (Are these separate or the same?)
* mofo-opennews
* mofo-science
* mofo-webmaker

Waiting to hear back from Pamela and what she says!

**Comment by jbuck** [comment]
We'll hash this out on Wednesday

**Comment by jbuck** [comment]
After hashing it out with Pamela, Ruzanna, and Alex we settled on:

- [ ] mofo-billing (parent account consolidated billing + user accounts. currently called "mofo-ops" so this needs to be renamed)
- [x] mofo-advocacy
- [ ] mofo-badges
- [ ] mofo-festival
- [ ] mofo-fundraising
- [ ] mofo-hive
- [ ] mofo-opennews
- [ ] mofo-operations (basically everything that doesn't fit in somewhere else)
- [ ] mofo-sciencelab
- [ ] mofo-webmaker

Old accounts that need stuff migrated out of them

- mofo
- mofo-secure
- mozilla-labs

**Comment by jbuck** [comment]
JP suggested an alternate scheme, similar to what we're doing currently:

- mofo-billing (parent account for consolidated billing)
- mofo-badges
- mofo-programs (advocacy, festival, fundraising, hive, opennews, operations, sciencelab, webmaker combined)
- mofo-sandbox (sandbox for developer testing)
- mofo-secure (services that store PII)

Less accounts, and use tagging for billing purposes

**Comment by thisandagain** [comment]
Agreed on the second scheme (less accounts, more tags). Using separate accounts for each program sounds like quite a bit to manage. The only thing that I would call out is that we should have separate tags for `Webmaker` and `teach.mozilla.org` cost tracking.

**Comment by jdotpz** [comment]
Historically, I've used three tags:
env <staging/prod>
app <appname/service name, aka elasticsearch, wmlogin, wordpress>
project <the group that should pay if someone besides mofo should pay>

**Comment by jbuck** [comment]
cc @simonwex

**Comment by simonwex** [comment]
+1 on second scheme. Something that we should have a good handle on is what accounts with what permissions exist in IAM. It's easy for this to pile up and be very difficult to audit. @jdotpz do you have any prior art there?

**Comment by jbuck** [comment]
Thanks for your input everyone. Action plan!
* Keep mofo-ops as-is, but enable tagged cost allocation reports
* Rename mofo-advocacy account to mofo-products. This account will be used for all of our applications that **do not** store PII
* Rename mofosecure account to mofo-secure for consistencies sake. This account will be used for all our applications that **do** store PII
* Create mofo-badges account, to migrate badges stuff to. Or maybe look at running it on Heroku?
* Migrate everything out of the mofo account
* Migrate our webmaker stuff out of the mozilla-labs account. Turns out this account is mostly for MoCo stuff now!

There's also might be a future need for:
* mofo-badges, if the badges stuff is big enough to warrant it's own account
* mofo-webmaker, if the webmaker stuff is big enough to warrant it's own account
* mofo-sandbox, for us to play around with AWS services in a destructive manner

In terms of tagging, it's absolutely critical that we add the project/department tag and enable [tagged cost allocation reports](http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html). I've been using the same tags as jp, so I think we're good there.
