### ISSUE TITLE
Decommission Post Crimes

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#651]
I've gotten approval from Sara and Jon to decommission Post Crimes. Let's go ahead and take it down, redirecting the url to foundation.mozilla.org

No rush.

**Comment by patjouk** [comment]
PR open in mofo redirector.

Todos:
- [ ] Finish redirection,
- [ ] remove from logentries,
- [ ] remove from pingdom,
- [ ] Delete the pipeline in Heroku,
- [ ] Clean cloudinary (anything that is not related to the Foundation site can go).
- [ ] Check if there's stuff on AWS (cloudfront, S3 mostly)

**Comment by patjouk** [comment]
Managed to redirect www.postcrimes.org but not postcrimes.org. I'll check with @cadecairos today.

**Comment by patjouk** [comment]
Cleaned Cloudinary prod: buyers guide images are the last things in that account.
