### ISSUE TITLE
Redirect Advocacy site

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#657]
### Details
I've spun up this page: https://foundation.mozilla.org/advocacy/

Let's take down https://advocacy.mozilla.org by setting up a few permanent redirects:
https://advocacy.mozilla.org/open-web-fellows/* -> https://foundation.mozilla.org/fellowships (note that I took out the locale for the first link, you may need to redirect `https://advocacy.mozilla.org/{anyLocale}/open-web-fellows/` or at least `en-US`
All other URLs from the advocacy subdomain should point to https://foundation.mozilla.org/advocacy

**Comment by xmatthewx** [comment]
Excellent. I updated the link on the Initiatives page to go directly to the new page.

**Comment by cadecairos** [comment]
We need to do some work on the redirect tool in #660 in order to support more detailed redirects like those requested here

**Comment by cadecairos** [comment]
We were already using a Cloudfront CDN to route requests, so I added a new S3 origin implementing the redirects requested in the top comment.
