### ISSUE TITLE
Set up hobby dyno for old advocacy repo

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#658]
Once #657 is closed, we should take down the advocacy site. However, let's leave it up on a free hobby dyno for now at a url that will be accessible even after the redirects, in case we need to reference the content.

**Comment by alanmoo** [comment]
cc @brettgaylor

**Comment by cadecairos** [comment]
I've updated the app to use a $7 hobby dyno.

**Comment by alanmoo** [comment]
Got a link to it?

**Comment by cadecairos** [comment]
https://advocacy.mozilla.org ?

**Comment by alanmoo** [comment]
Sorry, I wasn't clear in the original ticket. I've updated the language of it.

**Comment by cadecairos** [comment]
Ahhhh I gotcha. 

Once we remove the domain and attach it to our redirect app, this app will still be accessible at https://advocacy-mozilla-org-prod.herokuapp.com

**Comment by alanmoo** [comment]
This still gets a fair amount of traffic, does the fact that it's now a hobby dyno before the redirects happen risk overage charges?

**Comment by cadecairos** [comment]
no, it should easily handle the traffic it's getting, a hobby dyno has the same RAM/Compute power as a 1X, and doesn't sleep, it just has no metrics/horizontal scaling.
