### ISSUE TITLE
Mozilla Pulse email verification is not always reliable

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#661]
### Details

**NOTE - THIS IS A LOW PRIORITY AND MIGHT END UP BEING A WONTFIX**

We use Mailgun to send email verification emails to those who authenticate with Pulse using GitHub for the first time. I think there have been at least two known instances where Mailgun logs show that the email has been delivered, but we've been pinged by users saying that they haven't received the email (even after trying again).

**Comment by cadecairos** [comment]
and they checked spam?

**Comment by gideonthomas** [comment]
yep

**Comment by patjouk** [comment]
Closing this issue for now. To be reopened if it's an issue again.
