### ISSUE TITLE
Make sure top google links redirect to fellowship pages on foundation site

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#662]
When googling "Mozilla Fellowships", this is one of the linnks: `https://advocacy.mozilla.org/en-us/open-web-fellows/`
It should point to `https://foundation.mozilla.org/fellowships`

Let's do a few more relevant searches (Google, DuckDuckGo) around `mozilla`,`fellows`,`fellowships`, etc and make sure any relevant links from Advocacy are doing the right thing.

**Comment by cadecairos** [comment]
`https://advocacy.mozilla.org/en-us/open-web-fellows/` is redirecting as it should.

**Comment by alanmoo** [comment]
cc @xmatthewx

**Comment by cadecairos** [comment]
@alanmoo @xmatthewx Are we expecting to find more URLs here that need specific redirects? Should I go searching for them?

**Comment by alanmoo** [comment]
I did a few searches, this looks good.
