### ISSUE TITLE
Set up vanity staging url for Mozfest site

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#664]
Let's explore using wagtail to host a second site. We can poke around with the staging server, but to get an idea of how it really feels, we should make sure there aren't any strange issues with secondary domains.

Let's create mozfest.mofostaging.net (or mozillafestival.mofostaging.net?) and point it at the same wagtail instance as foundation.mofostaging.net so we can set up a second site root that resolves as we might want in production.

**Comment by gideonthomas** [comment]
https://mozillafestival.mofostaging.net

**Comment by cadecairos** [comment]
@alanmoo This was technically done, but the site copy on Monday overwrote the page and site settings on staging. Should we close this out or work to make the staging mozfest sub-site more permanent?

**Comment by alanmoo** [comment]
Yeah, let's make sure that it works the same way foundation.mofostaging.net works.

**Comment by cadecairos** [comment]
this is working now
