### ISSUE TITLE
Add a `no-percy` filter based on branch name

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#666]
Same thing I did with dependabot branch name, but with `no-percy` too. It will need docs (I'll add a note about skip-ci too).

**Comment by Pomax** [comment]
We can probably update the PR template for this, e.g. "if you _know_ you don't need percy, rename your branch to have `-no-percy` at the end, and push up that renamed branch for forming this PR" or something?

**Comment by patjouk** [comment]
I thought about this a lot and decided that it's not a good idea. Yes, our CI is a bit slower and it's a bit silly that percy run on certain PR (only docs, etc) but I don't think it's the best approach to solve that issue.
