### ISSUE TITLE
Recover data from Mozilla Science Discourse instance

### ISSUE THREAD

**Issue by LeoMcA** [MozillaFoundation/mofo-devops#671]
_Originally posted by @cadecairos in https://github.com/MozillaFoundation/mofo-devops/issues/529#issuecomment-459007208_:
> Please open a new issue to recover any data from one of these instances.

We have a user [asking for archives from the Mozilla Science Discourse instance](https://discourse.mozilla.org/t/archives-of-the-mozilla-science-lab-forum/38069):

> I’m looking in particular for a long thread I had started about Open Science, something like “Shaping a better scientific conversation”

How do we want to handle this?

It should be relatively straightforward to spin up a local instance which we can then archive as static HTML, and upload to s3. But, once static (and if by that point the database has been deleted), handling deletion requests from users becomes very difficult. We could avoid this by anonymizing all users before creating the static site, which removes all PII and just leaves the contents of posts. (Different users become different anonymized accounts, so there's still the ability to understand a thread between multiple people.)

**Comment by cadecairos** [comment]
Also seeing another data recovery request from Steph Wright: forum.mozillascience.org/t/research-coding-q-a-march-24-2015-3-pm-pdt/214

**Comment by patjouk** [comment]
We tried to recover data, but failed for now. We're gonna try again eventually but it's not a priority right now.

**Comment by patjouk** [comment]
We tried again, without success: it won't be possible to do a restoration of that data.
