### ISSUE TITLE
Setup mozillafestival.org email with GSuite

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#675]
Filing here for posterity!

### Details

I got super admin access to the Mozilla Foundation GSuite account. I have changed the MX record for mozillafestival.org in AWS to point to google.

We will be using mozillafestival.org email addresses for NDA'ed wranglers this year at MozFest. We will be creating an email address for each mozfest space as well as admin@mozillafestival.org which will be managed by me (for now). These accounts have been added to the MozFest 2019 org unit. All email accounts will have 2FA enabled on them.

**Comment by patjouk** [comment]
Thanks for creating that ticket and make sure that future us have all the context we need :)
