### ISSUE TITLE
Build.webmaker.org build failed?

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-devops#68]
Hey @jbuck 

I merged [a PR](https://github.com/mozilla/build.webmaker.org/pull/76) to build.webmaker.org which usually auto builds, but the build failed:

https://travis-ci.org/mozilla/build.webmaker.org/builds/62521668

```
Preparing deploy

No stash found.
Expected(200) <=> Actual(401 Unauthorized)
body: "{\"id\":\"unauthorized\",\"error\":\"Invalid credentials provided.\"}" (wrong API key?)
failed to deploy
```

Would you be able to help fix this?

**Comment by jbuck** [comment]
Yep, can do!

**Comment by jbuck** [comment]
I've updated the API key, lets see if this deploys successfully: https://travis-ci.org/mozilla/build.webmaker.org/builds/64010728

Edit - And it does!

**Comment by adamlofting** [comment]
:sun_with_face:
