### ISSUE TITLE
Set up Pulse DB Metrics

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#680]
Situation: While we have good analytics on pulse visitors, it's difficult to track and report on pulse status and growth. Currently, I query the DB periodically to grab and [chart](https://docs.google.com/spreadsheets/d/1aOxihY-XB88m0KCKCsebF22I1C6GHV7BQv65wR_DXU4/edit#gid=2073846902) numbers on profiles and entries, counting issue areas, tags, etc. 

Goal: Set up a dashboard with view into the data. Could be a datastudio thing or native to pulse. 

Steps:
 - Identify key metrics (e.g. users, new users this month, top tags by year, etc)
 - Decide approach (api vs datastudio)
 - Enhance API if needed (e.g. add created date to profiles)
 - Make it so

cc @gideonthomas @cadecairos @patjouk

**Comment by gideonthomas** [comment]
Unless @patjouk has any suggestions, my experience with django dashboards has not been good (not maintained, complicated to implement, etc.). If we're able to embed datastudio in it (or use some kind of integration), that would be super useful!

Some metrics I personally would be interested in but may not be the most important (obviously defer to you Matthew):
1. Segmented post velocity (rate of content coming out segmented by profile type)
2. Trending topics (by tags or keywords or even help categories)
3. Common channels for get involved (are people using github, etc.)
4. Trending creators
5. Number of posts referencing AI per time period per internet health issue

**Comment by patjouk** [comment]
I never did dashboard in Django, but I saw a talk on that subject in 2016 ([abstract](https://2016.djangocon.us/schedule/presentation/40/), [recording](https://www.youtube.com/watch?v=XXG-ESzB9Q8)).

**Comment by cadecairos** [comment]
I'm not sure that the amount of work we'd need to put into this outweighs the benefits.
