### ISSUE TITLE
Failed review apps should prevent merge

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#689]
Tests that fail prevent merge. Let's find a way to do that with the state of a review app's deployment.

**Comment by patjouk** [comment]
Opened a bugzilla issue to add GtiHub actions to the Mozilla org so we can use this action https://github.com/marketplace/actions/heroku-review-app-deployment-status

**Comment by cadecairos** [comment]
We're blocked on this until we can use GH actions.
