### ISSUE TITLE
Redirect party.webmaker.org to teach.mozilla.org

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mofo-devops#69]
Hey @jbuck :sunglasses: , could you help deal with some page redirects?  We would like to redirect a few webmaker.org pages to the Teach site (farewell old pages! :grimacing: )

We are sending out Save the Date emails (for Maker Party) next week so if you have sometime this week to tackle this, that will be super awesome!!! :dancer: 

 * https://party.webmaker.org should go to https://teach.mozilla.org/events

original ticket on Teach site repo: https://github.com/mozilla/teach.webmaker.org/issues/266

/cc @hannahkane

**Comment by jbuck** [comment]
This is deployed now!
