### ISSUE TITLE
Resolve SSL needs for network.mozilla.org

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#691]
I got pinged on Slack about the SSL cert for network.mozilla.org, which seems to be using LetsEncrypt now. Can the digicert (which expires in the next month anyway) be revoked by MoCo IT at this point?

**Comment by patjouk** [comment]
I went to check on Heroku: network.mozilla.org is on the foundation.mozilla.org prod app, with automatic certificate management. It's safe to remove it from digicert.

**Comment by alanmoo** [comment]
I've let @cshields know. (Twice now 😃)
