### ISSUE TITLE
Coordinate heroku production deploy of id.webmaker.org

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#696]
I noticed that we rolled back the last commit (before my latest one) on heroku on production.

@patjouk do you remember why we had to do that? Wanted to check in before I push the new changes to prod.

**Comment by patjouk** [comment]
Sorry for the delay, I thought I answered yesterday but appear no :(
My guess is that we rollback because something was not working (thanks captain obvious). Do we need to add habitat?

**Comment by patjouk** [comment]
Log in work, create an account don't so I guess that's why we rolled back.

**Comment by patjouk** [comment]
I went and check and only have access to donate recaptcha. @alanmoo do you have access to it?

**Comment by patjouk** [comment]
Where are we on this?

**Comment by gideonthomas** [comment]
I think we were waiting on Chris to give you access to the recaptcha stuff. But, there might not be a point in doing this now. I'll leave it to @cadecairos to decide.

**Comment by cadecairos** [comment]
@gideonthomas is this still something that needs to happen?

**Comment by gideonthomas** [comment]
Nah
