### ISSUE TITLE
Configure SQS for Basket

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#698]
This may be for the Wagtail donate project, but I don't have a ton of details other than what Lucie dropped in Slack.

>Adding SQS is adding env var to wagtail-donate settings + update the app.json to add those too to review app. It's those env (https://github.com/mozilla/donate.mozilla.org/blob/master/sample.env#L40-L44) without the no_log one. Use donate staging env var, it will be the same. The json sent to basket will be different because of the changes in "net_amount". Sync with Pmac for how he wants to do that.

**Comment by gideonthomas** [comment]
why am I assigned to this?

**Comment by patjouk** [comment]
Where are we on that?
- Do we have an answer about the `net_amount` field?
- Is Basket ready to receive a payload that is different?

**Comment by alanmoo** [comment]
The last I heard is the email I got from Braintree on July 29, which I forwarded to you.

>Since your Braintree account will match the same flat-rate pricing model that you are on with PayPal today, fees would be pulled out of the end of each day's disbursement and reflected on your statements and the transaction level fee report.  I do not believe that this report can be queried through our API, but have added [our solutions engineer] with our Solutions team to the thread for visibility. 

I'm not sure what to do with that; should I set up a call with the solutions engineer? (We're still waiting for the legal teams to come to agreement, hopefully we're on the last bit of that conversation.)

I don't think anything's changed in basket yet.

**Comment by alanmoo** [comment]
@patjouk or @cadecairos - I think this is taken care of, right?

**Comment by patjouk** [comment]
Staging IAM user for SQS access was created somewhere in August. We will need a new user for Prod when we're ready.

**Comment by cadecairos** [comment]
- [ ] Create IAM user
- [ ] Grant IAM user write access to prod SQS queue

**Comment by cadecairos** [comment]
Configuration complete.
