### ISSUE TITLE
Grant Anil access to Google Search Console

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#699]
For foundation.mozilla.org

https://search.google.com/u/2/search-console/ownership?resource_id=https%3A%2F%2Ffoundation.mozilla.org%2F&hl=en

**Comment by alanmoo** [comment]
cc @anilkanji

**Comment by patjouk** [comment]
Can you do it? It doesn't seem like I have access.

**Comment by alanmoo** [comment]
Ah yes I forgot I filled this. We figured it out.
