### ISSUE TITLE
HerokuPipelineBot config issue for donate.m.o

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/mofo-devops#701]
Hi,

It looks like the bot is hooked up to the foundation website instead of donate.m.o, and pings me when there’s no actual commit to deploy

![image](https://user-images.githubusercontent.com/1294206/63126576-163cb900-bfa8-11e9-8dc1-9372de8c6504.png)

**Comment by patjouk** [comment]
Hm, weird thing happening there. I'll take a look this week. Thanks for
reporting it.
