### ISSUE TITLE
Setup redirect for MozFest discourse

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mofo-devops#706]
We will be using Discourse for MozFest session facilitators to take down notes for their session and discuss on that platform. MoCo is setting up most of this. The only thing that would be helpful is for us to setup a redirect.

Can we create https://discourse.mozillafestival.org as a domain, and redirect it to https://discourse-mozfest-redirect.netlify.com?

The second one is controlled by a MoCo employee.

Ideally, this is done within the next two-ish weeks.

**Comment by cadecairos** [comment]
Created a PR adding the redirect to the mofo-redirector app. Once that lands we can add a DNS record for it and get it an SSL cert.

**Comment by cadecairos** [comment]
@gideonthomas https://discourse.mozillafestival.org/ is live, but it looks like the proxy isn't set up yet?

**Comment by gideonthomas** [comment]
oh maybe! I'll check with Leo about that. Thanks for setting it up

**Comment by cadecairos** [comment]
This is all good, it was a typo in the redirector configuration file.
