### ISSUE TITLE
Set Up Zapier for Fellow Updates

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#707]
The fellowship will leverage Pulse to gather monthly updates from all the fellows. To spark conversation among them and staff, we'd like to use zapier to post these updates to the fellow slack channel.

Before we can set this up, @sabrinang will work with the fellow team to understand the workflow. Technically, we could either leverage a tag on entries, or possibly the profile type fellow. TBD.

This might seem minor but will potentially be hugely unlocking. It's currently very difficult for staff like Anil and Kevin to understand fellow activity to promote their work and integrate it with our other marketing and advocacy campaigns.

**Comment by gideonthomas** [comment]
I've done this
