### ISSUE TITLE
Issue/Error with watch_static_files after docker command

### ISSUE THREAD

**Issue by youriwims** [MozillaFoundation/mofo-devops#708]
### Details
After running `inv docker-catchup` I received the following error in the screenshot below. This was after a fresh clone and setup. After running `docker exec foundationmozillaorg_watch-static-files_1 ls node_modules/webpack`, I received this error message `ls: cannot access 'node_modules/webpack': No such file or directory`.

The issue was resolved once I ran `docker exec foundationmozillaorg_watch-static-files_1 npm install` and used the `ls` command above to verify that webpack had the intended packages. Afterwards, running `docker-compose up` showed that it was watching with no errors.

### Screenshot
<img width="566" alt="Screen Shot 2019-09-04 at 3 42 38 PM" src="https://user-images.githubusercontent.com/36484608/65188613-d2bceb00-da3c-11e9-9ac6-84721dbd79d4.png">

**Comment by patjouk** [comment]
Did you run `inv docker-setup` before running `inv docker-catchup`?

**Comment by youriwims** [comment]
Yes :/

**Comment by cadecairos** [comment]
@patjouk to follow up with @youriwims

**Comment by patjouk** [comment]
Fixed!
