### ISSUE TITLE
https://donate.mofostaging.net does not deploy the latest changes from master

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/mofo-devops#709]
Hey there,

We’re trying to deploy a change to the current donate website (probably one of the last), but the staging server doesn’t pick up the latest commit from the master branch and I don’t feel like deploying to prod without a last check on staging. Travis seem broken, so this is probably the reason: https://travis-ci.org/mozilla/donate.mozilla.org/builds/587228791?utm_source=github_status&utm_medium=notification
Could you have a look?

See https://github.com/mozilla/donate.mozilla.org/issues/2163 for further details

**Comment by patjouk** [comment]
Our build started to use Xenial instead of Trusty two months ago. We [need to update](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui) our travis.yml because it's not possible to use xvfb directly anymore.

I'll open a PR right away.
