### ISSUE TITLE
Pontoon can’t push to donate-wagtail

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/mofo-devops#712]
Hey team,

It looks like the master branch on https://github.com/mozilla/donate-wagtail is protected, while Pontoon needs to commit directly on master via this user https://github.com/mozilla-pontoon. Could you lift that protection? We could still block force pushes (Pontoon would never force push), to make sure no one rewrites history by mistake.

Localization has started, and people can’t test their translations on staging until this is fixed. This is also prevent us from landing new strings because .po files are not in sync.
Can you help unblock the situation?

Many thanks!

**Comment by alanmoo** [comment]
I'm going to unblock this for the purposes of testing and time constraints, but leave this ticket open as something to find the right long-term solution on. Maybe something to consider around the development branch conversation, @MozillaFoundation/developers?

**Comment by alanmoo** [comment]
Actually, this is all I see...
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1682681/66509144-6fa10000-eaa0-11e9-81e1-9cc9d102a944.png">

**Comment by alanmoo** [comment]
@TheoChevalier i turned rules off for master to unblock you but I’m leaving this open to decide on a long term approach for this.

**Comment by cadecairos** [comment]
let's try to re-enable branch protection and authorize the pontoon user to push to master, but after we launch.
