### ISSUE TITLE
Update Coral Talk domain

### ISSUE THREAD

**Issue by alanmoo** [MozillaFoundation/mofo-devops#714]
Add comments.mozillafoundation.org as a URL for our Coral Talk instance.

Keep in mind that the existing URL shouldn't break the PNI comments, which points to the ugly heroku URL (for now).

See also https://github.com/mozilla/foundation.mozilla.org/issues/3589

**Comment by cadecairos** [comment]
I was able to update the staging/prod talk instances to v4.11.1 (there's currently no migration path for Talk v4 to v5), and migrate the prod app to comments.mozillafoundation.org. Comments on the buyer's guide continue to work. I also renamed the pipline and apps to not be specific to the buyer's guide.
