### ISSUE TITLE
Fix Pontoon Integration

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#715]
* Can't communicate with git repo
* Ensure the django queue is setup to run the task periodically.

https://github.com/mozilla/donate-wagtail/issues/528
https://github.com/mozilla/pontoon/pull/1468

**Comment by cadecairos** [comment]
https://github.com/mozilla/donate-wagtail/issues/528

**Comment by patjouk** [comment]
Ticket is blocked by work that needs to happen on Torchbox side. The infra is ready for donate wagtail, but not thunderbird donate.

Updates on blockers can be found here: https://github.com/mozilla/donate-wagtail/issues/447

**Comment by cadecairos** [comment]
This is being handled in other issues, and doesn't need a meta ticket.
