### ISSUE TITLE
Come up with a plan to use Basket with Exact Target

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#73]
https://github.com/MozillaFoundation/plan/issues/433

**Comment by adamlofting** [comment]
@jbuck - I just wanted to check if any work has happened on this? And/or how much time you think you have to work on this in this heartbeat?

**Comment by jbuck** [comment]
@adamlofting and I just had a chat:

##### Email Use-cases
* Welcome to Webmaker email
* We haven't seen you in a week, come back
* Reset password
* Your friend liked that thing you made

##### Requirements
* localization
* any mofo product should be able to send transactional email (webmaker, teach)
* Email tracking (Opens, clicks, bounces)
* A/B testing
* Email history (who did we send an email to, and when)

##### Wants
* Editing without a developer

**Comment by jbuck** [comment]
@adamlofting and I had a quick chat at Whistler and he started a security review of another transactional email provider

**Comment by awdng** [comment]
@jbuck just curious, where did you guys end up for transactional emails after this ? We are facing similar requirements and issues with ExactTarget

**Comment by jbuck** [comment]
Sadly, nowhere. Most of the dependent use-cases went away a few months later
