### ISSUE TITLE
Sentry issue filtering

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#731]
Sentry is very noisy and catching errors it should not (browser extensions, etc). ~We can whitelist urls, so let's give our emails account a break and do that :D~ 

(cade) update: We were able to filter most things using the Sentry dashboard. But we can still implement rules to ignore certain errors on the backend and frontend that we know we don't want to see, for example, the `DisallowedHost` error we see when someone tries to scan the site with a tool

Docs: https://docs.sentry.io/platforms/javascript/#decluttering-sentry
example of whitelist: https://gist.github.com/impressiver/5092952

# To do

- [x] [Foundation site Bug](mozilla/foundation.mozilla.org#4448)
- [ ] Donate-wagtail

**Comment by cadecairos** [comment]
We're meeting on Tuesday March 17th to do this.
