### ISSUE TITLE
Pontoon workflow for the foundation site

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#735]
After meeting with Chris and Théo during all hands, it was decided to implement this workflow for connecting Pontoon to the Foundation site:

Translations will be separated from the code. A new repo will be created for keeping and syncing translations with pontoon. Every push to master will trigger a test on travis (`compilemessages`, etc) and if green, archive the translations and push them to an s3 repo. This archive will be downloaded as part of the post_deploy step on Heroku staging, just before running `compilemessages`. The translations are moved to prod when staging slug is promoted to prod.

Generating new files to translate and pushing them to the translation repo needs to stay a manual step, as request by Théo.

CC @cadecairos @TheoChevalier

**Comment by patjouk** [comment]
All done. We will do the same thing for donate now.

**Comment by TheoChevalier** [comment]
Happy to report [this string](https://github.com/mozilla-l10n/fomo-l10n/commit/9cd0eba49d5377660fdd246f5f4fd26a9d0b36cc#diff-3054aeda246ef49ac2365cb770b5f366R122) made it to prod as expected 🎉
