### ISSUE TITLE
Making sure translations get deployed even when the code doesn't change

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#740]
As pointed by @TheoChevalier in MozillaFoundation/mofo-devops#739, we need to find a way to make sure that translations don't pile up in the translation repo. This is mostly a problem for donate-wagtail since we're not working on it every day like we do with the foundation site.

*Random ideas:*
- Basic: Set a reminder on slack to deploy donate every two days + manually redeploy master on staging + force promotion of the pipeline
- Automatic verification: we check for signs of deploy in logs (could be as simple as `Deploy`) and alert on slack if the last one was two days ago. We deploy manually.
(Of couse, we would write a script for triggering the whole deply + promote, we're not monsters)
- Fully automatic: after checking that there's no code change, we have a cron task that builds staging + promotes automatically once per day. If there's new code, nothing happens since it will get pushed during one of the two daily deploys.

I'm of course in favor of fully automatic :D
@cadecairos @TheoChevalier opinions?

**Comment by cadecairos** [comment]
Lets do an automated build task using mofo-cron.

**Comment by patjouk** [comment]
As long as we merge dependabot PRs frequently, we don't really need this.

If we ever need to deploy a translation change but don't have any code to ship it, we can manually trigger a redeploy of staging (will trigger a download of the latest translations) + force the pipeline promotion using the Heroku CLI (not possible from the pipeline dashboard).

**Comment by patjouk** [comment]
Reopening because this issue happened today. An easy way to fix it would be to merge at least one dependabot PR per day on repo with less activities (in our case, donate).

**Comment by ayahohner** [comment]
@TheoChevalier does this still happen?

**Comment by TheoChevalier** [comment]
@benhohner Yup, this is still the current behavior, and I need to ping people to rebuild/redeploy master when translations are piling up

**Comment by ayahohner** [comment]
Do we throw a github action at this?

**Comment by tomusher** [comment]
I've created a [task in the mofo-cron repo](https://github.com/MozillaFoundation/mofo-cron/blob/master/tasks/redeploy_site/task.sh) that we can use to trigger an app rebuild.

How often do we want this to run? Daily?

**Comment by TheoChevalier** [comment]
Sooooo cool! Daily would be great, thanks Tom!
Let me know when it’s in place for the donate site, and I can make a dummy change to check if this works :)

**Comment by tomusher** [comment]
I've set that up to run at 9am UTC daily so I can monitor it.

**Comment by TheoChevalier** [comment]
Awesome :) Let’s see if [this change](https://github.com/mozilla-l10n/mozilla-donate-content/commit/c1e288710e78927ac6bb848396342cedf5261080) appears on https://donate.mozilla.org/fr/faq/ tomorrow morning then

**Comment by TheoChevalier** [comment]
Confirming it did work! 🎉

**Comment by tomusher** [comment]
I think that's because pomax deployed last night - the automation hasn't ran yet (will run at 9am UTC).

**Comment by TheoChevalier** [comment]
Wait no, I’m dumb, I’ve made a change to the wagtail-localize repo, so of course it got picked up by wagtail-localize 🙃

I’ll test with this change: https://github.com/mozilla-l10n/donate-l10n/commit/ae391704df5f7782176d8f3105b6abd1163fda31#diff-90db5fafa8176f223d3a808e7508431752219e8b337759c92d10ef9fe97f40afR36

**Comment by tomusher** [comment]
The automated deployment ran as expected - did your change work @TheoChevalier?

**Comment by TheoChevalier** [comment]
I ended up making [another change](https://github.com/mozilla-l10n/donate-l10n/commit/6521138d48283cec627e9079033f6a6c92d54242) easier to spot, and can confirm it’s showing up on https://donate.mozilla.org/fr/ ! :)
