### ISSUE TITLE
Remove pipenv

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#742]
After giving it a good thought, it's happening.

Let's test it on the foundation site. We will use pip-tool instead to pin our dependencies. I'm giving it a 13 in estimate because it will require some prototyping and a few trials and errors :)

Todo:
- [x] Foundation site
- [x] Pulse-api
- [x] Donate
- [x] Mofo-redirector
- [x] Mofo-cron

**Comment by bsieber-mozilla** [comment]
(Randomly saw this issue from Slack, unsure if this might be of any assistance. It was posted in the #python channel. https://medium.com/telnyx-engineering/rip-pipenv-tried-too-hard-do-what-you-need-with-pip-tools-d500edc161d4)

_lurks away_

**Comment by patjouk** [comment]
Done for the foundation site, I'm moving to donate.

**Comment by patjouk** [comment]
I've opened PRs for all the remaining projects that are still running pipenv.

**Comment by patjouk** [comment]
All done!
