### ISSUE TITLE
IHR redirect

### ISSUE THREAD

**Issue by TheoChevalier** [MozillaFoundation/mofo-devops#745]
I’ve noticed `https://internethealthreport.org` redirects me to `https://foundation.mozilla.org/en/internet-health-report/`, while it should redirect me to `https://foundation.mozilla.org/internet-health-report/` and let the website handle the language negotiation.

Can that link be updated please?

Thanks!

**Comment by cadecairos** [comment]
This will require a bit of manual work to update the redirect rules in the WPEngine admin panel.

**Comment by cadecairos** [comment]
I've updated all the WP Engine redirects so that they'll rely on the Foundation site's i18n setup to choose an appropriate language for the reader.
