### ISSUE TITLE
Deliver Story Collection Tool

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#750]
We have gathered requirements for a form tool to gather input from our audience via our website. Background below. 

**Next step**: The next step is to examine 3rd party options to see if they meet the requirements. We will track this in a [google sheet](https://docs.google.com/spreadsheets/d/1hvP0NBavLbbDi2bOqdufy7TRjwKnuN12VaaJ9mhsgks/edit#gid=0). 

**Background:** To inform the Foundation’s campaigns and insights, we sometimes solicit input from partners or the public. Our Youtube campaign demonstrated the value. This proposed tool aims to enable that, making the job easier for staff and more inviting for participants.

**Project Brief**: https://docs.google.com/document/d/1CYRXutd7G_6l9clonn-ogkinwxeebqcIjx-_Wna1YHU/edit#heading=h.x64exxh4xy4w

**Comment by cadecairos** [comment]
Blocked on defining an MVP deliverable for Engineering

**Comment by cadecairos** [comment]
cc/ @anilkanji

**Comment by cadecairos** [comment]
Working on the contract w/ legal and Typeform.

**Comment by kristinashu** [comment]
This was completed a while ago and Typeform is now in use and embedded on our site!
