### ISSUE TITLE
Create typeform account and whitelist on staging

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#751]
We're ready to test the tool. 

 - [ ] create free tier account
 - [ ] whitelist embed on staging
 - [ ] inform designer to test. tracking here: https://github.com/MozillaFoundation/Design/issues/512

**Comment by cadecairos** [comment]
Account created, it's in the team vault.

Whitelisted the typeform domain we got on foundation.mofostaging.net
