### ISSUE TITLE
Help bridge GA between fo'mo and donate

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#752]
In ideal world, Analytics will give us a complete view from referrals to donations. For example, what earned media in 2020 leads to higher donation rates? Should we invest more in certain content partnerships? Currently, we see referrals in fo'mo GA and donate "intent" (button event). In donate GA we total dollars for various segments. But, there's a blackbox in-between. 

There are many good reasons why this doesn't work. But, we need to find a way to work around it. One GA property for both domains? Creative solutions welcome.

**Comment by cadecairos** [comment]
Brain dump:

I don't think we need a single shared GA property.

I have a good feeling the right solution is to have individual pages on fomo specify unique UTM parameters in links to donate.mozilla.org. Then if that donation completes, we know what foundation page the journey started from.

If a FoMo page can specify: `utm_source=foundation.mozilla.org`, `utm_campaign=some_unique_campaign_id`, and maybe even `utm_content=[button,linkbutton,etc]` then we should get a pretty decent amount of insight.

I'm not sure, however, how we'd link referrals, unless we also pass that through to donate in the UTM params.

**Comment by cadecairos** [comment]
Turns out this is already done - There's a GA rollup property for FoMo, Donate, Mozfest, and pulse which can automatically merge sessions.
