### ISSUE TITLE
Delete the `foundation-site-ia-refresh` app

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#758]
Ref: mozilla/foundation.mozilla.org#4671

Todo:
- [ ] Use terraform destroy to delete resources created on Heroku (rm -rf the `.terraform` dir + [init with the new DB credentials](https://devcenter.heroku.com/articles/using-terraform-with-heroku#remote-postgres-backend) because Heroku rotate DBs)
- [ ] Delete the IAM users
- [ ] Delete Google Auth settings (Lucie's account)

I'm not sure when that will be able to take place so I'm putting this ticket in icebox for now.

**Comment by patjouk** [comment]
@cadecairos Can we sync at some point about the Auth0 token? I want to make sure it continues to work when I'm out!

**Comment by jamilasnell** [comment]
WE did it already
