### ISSUE TITLE
Add our "S3-backend" terraform modules to MoCo's repo

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#762]
I met with Alberto on Monday June 8th, and we talked about how we use Terraform at MoCo and MoFo. They don't have a module to create S3 Terraform backend, so I suggested that I could open a PR with ours.

Our module is tailored to our needs, so I need to revisit it a little before I can open a PR [on their repo](https://github.com/mozilla-it/terraform-modules/tree/master/aws).

**Comment by cadecairos** [comment]
@patjouk let's make sure we focus on getting the issues in the milestone that are not labelled unplanned done before spending time on this one.

**Comment by patjouk** [comment]
PR opened https://github.com/mozilla-it/terraform-modules/pull/74

**Comment by patjouk** [comment]
Final step is to migrate our infra to use that module.
