### ISSUE TITLE
Create a page for changecopyright.org on the foundation site

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#769]
We need a landing page on the foundation site to redirect traffic coming from changecopyright.org.

@phildexter Can you check with design and content what they want to do? I gave it the July 20th milestone, but feel free to change it.

**Comment by cadecairos** [comment]
@patjouk I don't think this is going to happen this milestone.

**Comment by patjouk** [comment]
Worst case, I can prepare the infra part and you can finish it after I'm
gone.

**Comment by cadecairos** [comment]
https://foundation.mozilla.org/cms/pages/1035/edit/
