### ISSUE TITLE
Create CF dristributions and mofo/thunderbird domain names for those

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#775]
We need to create 4 new distributions and domains:
- `donate-mofo-assets.mofostaging.net`
- `donate-thunderbird-assets.mofostaging.net`
- `donate-mofo-assets.mofoprod.net`
- `donate-thunderbird-assets.mofoprod.net`

**Comment by tomusher** [comment]
These are all in two buckets (`mofo-assets` and `mofo-assets-staging`) which already have CloudFront distributions.

Do we need these additional domains?

**Comment by Pomax** [comment]
@benhohner  to see if we want higher fidelity in our bucketizations

**Comment by ayahohner** [comment]
@tomusher Would there be a benefit to billing by having separate buckets? I believe we do need to pass the costs for Thunderbird stuff along to that team, and so introspection into the costs of each set of assets would be useful

**Comment by tomusher** [comment]
It wouldn't be cheaper to have separate buckets, but it would let us trace costs-per-bucket easier for passing on to Thunderbird.

For context though, our S3 costs are very small (about $5/m) - so maybe worth considering whether any additional tweaks are worth the time investment.

**Comment by ayahohner** [comment]
@tomusher is there a way to use a separate directory so that if we need to in the future, it's easier to migrate assets to a separate bucket?

**Comment by tomusher** [comment]
@benhohner At the moment every site uses a separate directory inside that bucket - so yes it should be easy enough to migrate assets to another bucket when required.

**Comment by ayahohner** [comment]
@tomusher perfect. Closing this!
