### ISSUE TITLE
Fix whitenoise configuration on donate

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#776]
We need to edit the current whitenoise configuration:

- Make sure `whitenoise.middleware.WhiteNoiseMiddleware` is above the `django.middleware.gzip.GZipMiddleware`.
- `whitenoise.runserver_nostatic` needs to at the top of the `INSTALLED_APPS` so that whitenoise works on local dev (ref: http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development).
- Add `STATIC_HOST` env var. Instructions here: http://whitenoise.evans.io/en/stable/django.html#instructions-for-amazon-cloudfront. This needs to be done for donate mofo and thunderbird (donate and prod).

**Comment by tomusher** [comment]
PR at https://github.com/mozilla/donate-wagtail/pull/1465

**Comment by Pomax** [comment]
assigning an estimate of 0 mostly because it's pending PR review
