### ISSUE TITLE
Transfer AWS LDAP group ownership

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#783]
Access groups managed on people.mozilla.org

- [ ] mofo_aws_admins
- [ ] mofo_aws_everything
- [ ] mofo_aws_projects
- [ ] mofo_aws_secure
- [ ] mofo_aws_community
- [ ] mofo_aws_labs
- [ ] mofo_aws_sandbox

**Comment by cadecairos** [comment]
I think @mmmavis and @Pomax need to accept the invites on people.mozilla.org

**Comment by Pomax** [comment]
That does assume we ever use people.mozilla.org of course.

**Comment by cadecairos** [comment]
IT has already migrated LDAP access groups to it, among other things. It can't be stopped!

**Comment by Pomax** [comment]
where should we see these invites? (I don't see anything that indicates a notification of pending messages or the like)

**Comment by cadecairos** [comment]
That was a bit of an assumption on my part about the invites - maybe it was an email?

**Comment by cadecairos** [comment]
oh, the invites expired

**Comment by Pomax** [comment]
accepted all invites.
