### ISSUE TITLE
Transition from mLab MongoDB to new provider

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/mofo-devops#798]
comments.mozillafoundation.org uses mLab MongoDB on Heroku, which is shutting down on November 10th.

**Comment by cadecairos** [comment]
https://devcenter.heroku.com/changelog-items/1823

**Comment by cadecairos** [comment]
I was able to successfully migrate `mozilla-foundation-talk-ihr` from mLab to ObjectRocket. OR instances are not cheap though, nearly $50/month just for the base plan. Therefore I propose (and have already done so) attaching the one $50 addon instance to all three of our talk apps, creating a new DB on the instance for each app, and migrating all the collections from each app to the new databases.

The process will need to go something like this:

1. Connect to the Object Rocket dashboard

**Comment by cadecairos** [comment]
@tomusher @phildexter ^

**Comment by phildexter** [comment]
Tom aiming to get this done between 2nd and 4th Nov.

**Comment by tomusher** [comment]
`comments-mofo-org-staging` and `comments-mofo-org-production` have been migrated to the shared ObjectRocket instance. Confirmed working and have removed attached mLab instances.
