### ISSUE TITLE
Document Mozilla Science forum

### ISSUE THREAD

**Issue by flamingspaz** [MozillaFoundation/mofo-devops#8]
We should document how this is set up so if any issue arises, someone can look at the documentation and know what they're doing.

**Comment by flamingspaz** [comment]
This was spun up with a Bitnami AMI, ami-c1de96a8, and it looks like there are no other resources related to it. There isn't a database on the shared RDS instance so I'm assuming that's in the docker container too.

@chefscott does that sound about right? Do you know if/how this instance is receiving emails?

In any case, we should get that database onto RDS.

**Comment by chefscott** [comment]
It was a docker container -- not sure about the emails.

**Comment by flamingspaz** [comment]
Okay, it's sending out emails as noreply@mozillascience.org - guessing that means it's not accepting incoming email which is a shame, that's a nice feature.
