### ISSUE TITLE
Migrate our webmaker stuff out of the mozilla-labs account

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#80]
Follow-up from #65. Turns out this account is mostly for MoCo stuff now! And it only has some older webmaker-app stuff in it.
### Services to decommission
- [ ] CloudFront
  - [ ] discourse.cdn.mozilla-community.org
  - [x] webmaker-app.mofodev.net
- [x] EC2
- [x] Elasticache
- [x] Glacier
- [ ] IAM
- [x] RDS
- [ ] Route53
- [x] SQS
- [ ] S3

**Comment by jbuck** [comment]
@flamingspaz I see some csa stuff in this account, do you have access to it to see whether it's safe to decommission or not?

**Comment by flamingspaz** [comment]
It should just be S3 buckets (since there used to be a limit per account). I've opened [an issue](https://jira.mozilla-community.org/browse/DIS-75) on our end to track migrating them. and I'll run through the other services and see what's left.

**Comment by jbuck** [comment]
I did a bunch of decommissioning work today for #201. Still more to go, but the bill is now down to $5/month so it's less important.
