### ISSUE TITLE
Mozilla Donate Disaster Recovery Plan

### ISSUE THREAD

**Issue by tomusher** [MozillaFoundation/mofo-devops#800]
Document and discuss disaster recovery for Mozilla Donate platform.

**Comment by jamilasnell** [comment]
@tomusher can you label and assign this ticket so that the relevant parties can know that this is a plan of attack for the holidays? Thank you

**Comment by benhohner** [comment]
This already exists 
https://docs.google.com/document/d/1YpNo25waIsfOXayY8_1R-nthuAp9MmR8n9NRHqOb2hU/edit

Maybe we should use this ticket to decide where to put it so it's not lost again?

**Comment by tomusher** [comment]
Sorry yes, this ticket was to track the creation of that document - I just forgot to close the ticket!

We should figure out where to put it as part of #807 though.

**Comment by jamilasnell** [comment]
this has been done already
