### ISSUE TITLE
Migrate to Github Actions from Travis

### ISSUE THREAD

**Issue by tomusher** [MozillaFoundation/mofo-devops#801]
As Travis CI is reducing/suspending free minutes for open source repositories, we intend to migrate sites that use Travis CI to Github Actions.

These are:

* https://github.com/mozilla/donate-wagtail
* https://github.com/mozilla/foundation.mozilla.org

**Comment by tomusher** [comment]
@Pomax is there anything left to do on this one?

**Comment by Pomax** [comment]
I had https://github.com/mozilla/foundation.mozilla.org/issues?q=is%3Aissue+is%3Aopen+travis as tracking issue, the only thing left for us there is figuring out the "deploy the maintenance page to S3" task
