### ISSUE TITLE
Upgrade Heroku Stacks

### ISSUE THREAD

**Issue by tomusher** [MozillaFoundation/mofo-devops#803]
Our Heroku apps are using old stack versions (heroku-16 and heroku-18). We should upgrade these to heroku-20 to make sure we're keeping up and make the most of the security changes/optimisations in these new base OSes.

**Comment by tomusher** [comment]
Staging stacks have been upgraded for the foundation and mozilla sites. Next step is to test the stability of these and then do the same for production.

**Comment by benhohner** [comment]
@tom When can we say these are stable enough to move to prod?

**Comment by tomusher** [comment]
Foundation and Donate prod are now on heroku-20 (because the environments got promoted from staging).

For the remaining apps:

- Comments - we plan to remove
- Redirector - is on heroku-18 - I think we can leave this and look in to using Cloudflare to replace it
- Network Pulse/Network Pulse API - I need to take some more time to understand these apps before I make any changes here.

**Comment by Pomax** [comment]
@tomusher for each of these three issues, how do we want to proceed?

1. comments: as long as we can back up the data somewhere, we can probably delete the app afterwards
1. yes, let's leave it at 18
1. I can do a call this week or next to talk you through what they do, network-pulse is a node/express project, network-pulse-api is a Django Rest Framework.

**Comment by benhohner** [comment]
Update: Heroku has let us know that every second build on the Heroku-16 stack will fail until Jun 1st when builds will stop working all together.
