### ISSUE TITLE
Align heroku database versions

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/mofo-devops#811]
We're currently using four different postgresql versions:

- production = 9.6.2
- staging = 10.15
- review apps = 12.5
- local dev = 10.12

Let's get these all on the same version, or we're going to be chasing database ghosts, where one system's failing while everything else shows no indication of failure.

**Comment by tomusher** [comment]
As a first step for this I've added a new Postgres 12.5 addon to `foundation-mofostaging-net` and `donate-wagtail-staging`, copied across the data and made them the primary database.
The old versions remain in case we need to rollback.

@pomax could you check staging on these sites to make sure everything works as you expect?

**Comment by Pomax** [comment]
very nice, as far as I can tell this is working the same as before.

**Comment by tomusher** [comment]
I've removed the old 9.6 staging databases and done the same upgrades to the two production sites, leaving the old databases in place for now.
