### ISSUE TITLE
Investigate provisioning Lambda functions for SQS

### ISSUE THREAD

**Issue by benhohner** [MozillaFoundation/mofo-devops#815]
We need SQS to be able create a PATCH or POST to a RESTful API endpoint. This is required for sending data to a Cinchy API.
In the future we may be moving away from Basket, and sending data directly to Cinchy. We need a solution in AWS to make a RESTful request.

Initial idea:
SQS -> Lambda function

Investigate:
- Possible solutions
- Feasibility
- Rough estimate of how long to implement

**Comment by tomusher** [comment]
Just a few questions on this:

- How time critical are the messages?
- Do we have an example of the sort of messages that this will be processing?
- Is SQS required in this situation vs buffering messages in the source application and sending directly to Cinchy on a cron?

Whatever the case, the two approaches I'd expect to be most suitable are:

* Lambda to process messages, triggering appropriate API calls.
* Processing messages in a separate application running on Heroku.
