### ISSUE TITLE
Help CV team implement SQS -> Cinchy

### ISSUE THREAD

**Issue by benhohner** [MozillaFoundation/mofo-devops#818]
One person work with Jenny Zhang to implement an SQS queue on Common Voice on April 28th @12:30pm-2:30pm EST!

- [x] Work with Jenny Zhang on April 28th @12:30pm-2:30pm EST to give any resources needed to get SQS set up to send events
- [ ] Schedule any additional time required and let Ben/Jam know so we can adjust sprint.

**Comment by KalobTaulien** [comment]
No work is needed for this so I'm going to close this ticket. If something comes up let's create a new ticket to manage the SQS -> Cinchy work
