### ISSUE TITLE
Setting up the Sites mofostaging.net and mofoprojects.net in the Cloudflare Account

### ISSUE THREAD

**Issue by bheasman** [MozillaFoundation/mofo-devops#828]
### Details
Setting up the Sites mofostaging.net and mofoprojects.net in the Cloudflare Account.

Background from @jzinner :

1. Tom, would you please set up a login for Gareth Slaven gareth@mozillafoundation.org next week. (I believe the Super Admin is in the 1password "Infrastructure" Vault).   
Jackie and DJ - this means the Data + CRM Team now has a responsibility to inform the mofo-devops if Gareth leaves, because a DevOps will need to revoke Cloudflare access / delete Gareth's account independently of other account deactivation.  

2.  Tom, would you please try setting up the mofostaging.net and the mofoprojects.net Sites / Zones with Cloudflare Account.  I believe these zones are both hosted off the AWS Account: ‘MofoEverything’ AWS Account.  If you need to work with Gareth on this, just let us know.  
I surveyed the existing DNS records in  the AWS account 'MofoEverything' - it looks like the *.mofostaging and *.mofoprojects are out of Route 53.  The ICAAN lookup shows AWSDNS nameservers and a MarkMonitor registration - so I think the entire Zone is hosted out of Route 53 and not being split out from MoCo's Infoblox system. But, Tom, if you find out differently, or end up havingn to working with Corporate to get DNS for these two changed-over to Cloudflare - Please CC devops@ or or @-Slack-mention me so I can read along to Corporates DNS management as well.

**Comment by bheasman** [comment]
@tomusher - just looping you into this ticket - if you can add any relevant details here and update the status once done, that'd be good - thanks!

**Comment by tomusher** [comment]
This is done.

* Gareth has access to the Cloudflare account.
* mofostaging.net and mofoprod.net have had DNS and NS switched over to Cloudflare

**Comment by bheasman** [comment]
Thanks @tomusher !
