### ISSUE TITLE
Change DNS for advocacy.mozilla.org domain to point to the new cloudfront url

### ISSUE THREAD

**Issue by alicoding** [MozillaFoundation/mofo-devops#83]
We are switching away from the current Wordpress server to the static one which is this URL:

ddbq602zsou8c.cloudfront.net

**Comment by jbuck** [comment]
- [ ] Have webops change DNS: https://bugzilla.mozilla.org/show_bug.cgi?id=1168187
- [ ] Decommission Wordpress server
