### ISSUE TITLE
DNS record review & cleanup *.mofostaging.net

### ISSUE THREAD

**Issue by jencohoon** [MozillaFoundation/mofo-devops#832]
### Review & cleanup *.mofostaging.net DNS 
Two changes in Q2|Q3 2022 appear to have caused cruft to accumulate in our `*.mofostaging.net` DNS records: 1) the disabling of the Heroku Review-App pipeline, and 2) the migration of the `*.mofostaging.net` DNS hosting from AWS Route 53 to Cloudflare, [Issue #828](https://github.com/MozillaFoundation/mofo-devops/issues/828). 

Tracking the DNS record review & cleanup in this Google sheet: [mofostaging.net DNS migration to Cloudflare](https://docs.google.com/spreadsheets/d/1iTfmqSZRkPiQZ4Krjer8Dpt85NKZYnfyzQTXI3s4vaU/edit#gid=0)

**Comment by jzinner** [comment]
Hi @marcwalsh - wondering if you could review the items in the `Record Name` column of [this spreadsheet](https://docs.google.com/spreadsheets/d/1iTfmqSZRkPiQZ4Krjer8Dpt85NKZYnfyzQTXI3s4vaU/edit#gid=0) that start with `mozfest`?

My view of our Heroku account does not show a `mozfest` app - though the record values point to a `*.herokudns.com`?  Do you have access to a separate Heroku account that hosts a `mozfest` app? 

Thank you,

**Comment by jencohoon** [comment]
Ok - it turns out that the foundation app actually builds multiple sites.  And per [the "OPS and Heroku Settings" doc in the foundation repo](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/ops_heroku_settings.md) - mozillafestival is built when foundation is built. 

So looks like mozillafestival and foundation are two "Django apps" that hang off the foundation filesystem at: "networkapi <- Django apps live within this directory",  per the ["Stack" doc in foundation Github repo](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/stack.md)

**Comment by jencohoon** [comment]
Outcome: 
25 unused (un-resolving) records removed from Cloudflare
23 unused (un-resolving) records removed from Route53
