### ISSUE TITLE
Github Auth broken on build.webmaker.org (secure connection failed)

### ISSUE THREAD

**Issue by adamlofting** [MozillaFoundation/mofo-devops#84]
It looks like an issue with the cert for build.w.o

![screenshot 2015-05-26 10 07 08](https://cloud.githubusercontent.com/assets/1901816/7809052/5ceb18ee-038f-11e5-9e76-5c9f1942cb67.png)

**Comment by jbuck** [comment]
Updated the cert, should propagate in 30 mins or so
