### ISSUE TITLE
Pass the "referrer" header to origin server for directory.hivelearningnetworks.org

### ISSUE THREAD

**Issue by toolness** [MozillaFoundation/mofo-devops#85]
Someone reported that sign-in to directory.hivelearningnetworks.org fails with the following error:

> Forbidden (403)
>
> CSRF verification failed. Request aborted.
>
> You are seeing this message because this HTTPS site requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.
>
> If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests.

Looks like this is fallout from #34. Can we enable the forwarding of that header from cloudfront to the origin server?

**Comment by jbuck** [comment]
Done!

**Comment by toolness** [comment]
Awesome, thanks jbuck--I just logged into the site and verified that it works now!
