### ISSUE TITLE
Create S3 credentials for OpenNews editor

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#89]
@ryanpitts Who am I giving these credentials to (email/github) and what S3 bucket does she need access to?

**Comment by ryanpitts** [comment]
GitHub: @tsl-lindsay
Email: lmuscato@gmail.com
Bucket: assets.opennews.org

Thanks!

**Comment by jbuck** [comment]
Done! @tsl-lindsay check your gmail.

**Comment by tsl-lindsay** [comment]
Got 'em, thank you!
