### ISSUE TITLE
What error is happening here?

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#92]
https://badgekit.org/directory

**Comment by jbuck** [comment]
Can you show me a screenshot and/or steps to reproduce this error? I just see a redirect to the root

**Comment by simonwex** [comment]
Ah, sorry. 

STR:
 1. *Log in*
 2. Visit https://badgekit.org/directory

**Comment by jbuck** [comment]
Okay, finally some headway here:

`Error: template not found: signup.html`

**Comment by jbuck** [comment]
Which is this bug: https://github.com/mozilla/openbadges-badgekit/pull/455

**Comment by jbuck** [comment]
Which is this commit fixing it: https://github.com/mozilla/openbadges-badgekit/commit/499810b79ffc595a97f62f96310f6ef745b9d08e

**Comment by jbuck** [comment]
You only got this message if you signed-in with a non-mofo address

**Comment by jbuck** [comment]
And I didn't break anything, hooray~
