### ISSUE TITLE
Move thimble-beta from webmaker.org to mozilla.org

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#93]
Discussed evolving tools and domains with @adamlofting this morning before seeing the note about thimble-beta.

We might want to run with thimble-beta.mozilla.org rather than dot webmaker.org given the shifting relationship between Teach, webmaker, and other tools.

cc @simonwex

**Comment by jbuck** [comment]
I don't think we should do this for thimble-beta. Maybe for thimble, once it is not beta.

**Comment by xmatthewx** [comment]
That sounds reasonable. I flagged this because when we transition the Webmaker site, there are two challenges:

 1. creating clean redirects from old localized links to not-yet-localized content on Teach
 2. avoiding confusion with users (and staff) as Webmaker shifts from a program to an app

Adding new things under the Webmaker umbrella complicates things a wee bit.

**Comment by jbuck** [comment]
This was done awhile back!
