### ISSUE TITLE
Ensure our active projects use modern Travis infrastructure

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#94]
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by simonwex** [comment]
tl;dr: In order for us to take advandage of our dedicated instances running at TravisCI, we can't use `sudo`

**Comment by jbuck** [comment]
We're all good to go here

**Comment by simonwex** [comment]
:clap: !
