### ISSUE TITLE
Decide what to do with mozillaignite.org

### ISSUE THREAD

**Issue by jbuck** [MozillaFoundation/mofo-devops#95]
The SSL certificate will expire in 12 days. The site hasn't been updated in 2 years. Can we decommission it?

https://bugzilla.mozilla.org/show_bug.cgi?id=1170866#c1

cc @simonwex @davidascher

**Comment by davidascher** [comment]
I'll ask ops.

**Comment by jbuck** [comment]
We're doing stuff in #97
