### ISSUE TITLE
Archive and Deactivate mozillaignite.org

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#97]
* [x] Archive main website on S3 `wget -m -p https://mozillaignite.org/`
* [x] Archive blog on S3 `wget -m -p http://blog.mozillaignite.org/`
* [x] Obtain SSL certificates for mozillaignite.org, www.mozillaignite.org, and blog.mozillaignite.org
* [x] Dupe mozillaignite.org site in S3
* [x] Decommission any outstanding mozillaignite.org infra
* [x] Update https://bugzilla.mozilla.org/show_bug.cgi?id=1170866

**Comment by benrito** [comment]
Main concern is archiving the blog and the content here: https://mozillaignite.org/resources/ 

Could we host the latter on S3 as well?

Can we create a redirect so mozillaignite.org sends folks to us-ignite.org?

**Comment by simonwex** [comment]
Redirect is easy - yes. 

We'll archive the entire mozillaignite.org and blog.mozillaignite.org site content. Archiving implies saving a copy, but not hosting it for public consumption. 

When you say host the resources section, at what domain would you like it hosted? If we're transitioning off of mozillaignite.org, continuing to host content there leaves us in the same position as now when the new SSL certs expire.

**Comment by benrito** [comment]
Don’t know what our cert policy is, but the content at that link is not an application, so would be fine to just serve it off S3.

Specifically looking at these tutorials, which are not hosted elsewhere:

https://mozillaignite.org/resources/labs/lab4-websockets-unlocking-web-full-duplex-1-gbps/ <https://mozillaignite.org/resources/labs/lab4-websockets-unlocking-web-full-duplex-1-gbps/>
https://mozillaignite.org/resources/labs/web-rtc-data-and-webapps-of-the-future/ <https://mozillaignite.org/resources/labs/web-rtc-data-and-webapps-of-the-future/>
https://mozillaignite.org/resources/labs/future-uses-of-webrtc-video/ <https://mozillaignite.org/resources/labs/future-uses-of-webrtc-video/>
https://mozillaignite.org/resources/labs/future-uses-of-webgl/
https://mozillaignite.org/resources/labs/lab-5-spdy-eliminating-web-bottlenecks-and-taking-full-advantage-1-gbs/

**Comment by simonwex** [comment]
People who have visited the site with a modern browser will automatically request the site over SSL. If we don't have a cert, they won't get a response (even a redirect)

**Comment by simonwex** [comment]
Also, it seems that the page rank of us-ignite.org is already above mozillaignite.org:

http://bfy.tw/JF6

![image](https://cloud.githubusercontent.com/assets/25260/8136567/f0c6817e-10f1-11e5-9a7f-4f8fb4c21f9f.png)

**Comment by benrito** [comment]
Do we have any domain where we can host this content? webmakerprototypes?

That US Ignite site is probably where people would find, but those pages are just linking back to our stuff.

Alternately;

1 would gh-pages work?

2 i can try to get them to host our content going forward

**Comment by simonwex** [comment]
Hey @benrito, let's chat about this on vidyo. I want to understand your goals with both the content and the domain strategy overall. It feels like we could resolve this in 10 mins instead of a dozen back-and-forths.

I've emailed you some options for meeting times.

**Comment by jbuck** [comment]
I've just duplicated the site in S3 for now. If there's any redirects to be made, just let me know and I can make it happen!
