### ISSUE TITLE
Point demo@webmaker.org at demo@mozillafoundation.org google group

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#98]
Please set up the aliases `demo` and `demos` on webmaker.org to point to the google group `demo` on mozillafoundation.org.

**Comment by xmatthewx** [comment]
To clarify: We want a user account using demo@webmaker.org. Google group makes it easy for a bunch of us to use the account and replace passwords as our shared memory fails us.

**Comment by jbuck** [comment]
@xmatthewx says it's not needed anymore
